git-lcl: ENH: Allow accumulation of commit logs across multiple lcl invocations via --into
Passing the temp dir into it instead of creating one, and skipping the paged display at the end; instead, this has to be explicitly requested through a separate call with the --show option.
csplit would still (at least partially) overwrite existing separated commits from a previous invocation; we need to "save" those by renaming them with a monotonically ascending timestamp.

diff --git a/bin/git-lcl b/bin/git-lcl
--- a/bin/git-lcl
+++ b/bin/git-lcl
@@ -13,7 +13,14 @@ HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" '[LOG-ARGS ...] [<revision range>] [[--] <path>...] [-?|-h|--help]'
 }
 
+showPagedLogs()
+{
+    [ "$PAGER" = smartless ] && PAGER=less	# smartless does not page small outputs that fit the terminal, but we explicitly want to page through each date range separately.
+    "${PAGER:-less}" --RAW-CONTROL-CHARS "${tempDirspec}"/*
+}
+
 isColor=; [ -t 1 ] && isColor=t
+isInto=
 typeset -a logArgs=()
 while [ $# -ne 0 ]
 do
@@ -37,6 +44,14 @@ do
 			shift; shift
 			;;
 
+	--into)		shift; tempDirspec="${1:?}"; shift; isInto=t;;
+	--show)		shift
+			if [ -z "$tempDirspec" ]; then
+			    echo >&2 'ERROR: Need --into TEMPDIR before --show.'
+			    exit 2
+			fi
+			showPagedLogs; exit $?
+			;;
 	--)		logArgs+=("$1"); shift; break;;
 	*)		logArgs+=("$1"); shift;;
     esac
@@ -64,8 +79,10 @@ containsGlob()
     return 1
 }
 
-tempDirspec="$(mktemp --directory --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || { dirspec="${TMPDIR:-/tmp}/$(basename -- "$0").$$$RANDOM"; mkdir -p -- "$dirspec" && printf %s "$dirspec"; })" || exit $?
-[ "$DEBUG" ] || trap 'rm -rf "$tempDirspec" 2>/dev/null' EXIT
+if [ -z "$tempDirspec" ]; then
+    tempDirspec="$(mktemp --directory --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || { dirspec="${TMPDIR:-/tmp}/$(basename -- "$0").$$$RANDOM"; mkdir -p -- "$dirspec" && printf %s "$dirspec"; })" || exit $?
+    [ "$DEBUG" ] || trap 'rm -rf "$tempDirspec" 2>/dev/null' EXIT
+fi
 
 typeset -a limitRevisionsArgs=()
 if ! containsGlob '-+([0-9])' "$@" && ! contains '-n' "$@" && ! contains '--max-count' "$@"; then
@@ -81,6 +98,17 @@ fi
 if [ "$isColor" ]; then
     pipethrough --piped -- colordiff --color=yes -- "${tempDirspec}"/log* 2>/dev/null
 fi
+if [ "$isInto" ]; then
+    # Rename the newly added logs so that subsequent invocations don't overwrite
+    # them.
+    prefix="$(date +%s%N)"  # Use Epoch + nanoseconds to get a monotonically increasing prefix.
+    for filespec in "${tempDirspec}"/log*
+    do
+	filename="${filespec##*/}"
+	mv -- "$filespec" "${tempDirspec}/${prefix}${filename}"
+    done
 
-[ "$PAGER" = smartless ] && PAGER=less	# smartless does not page small outputs that fit the terminal, but we explicitly want to page through each date range separately.
-"${PAGER:-less}" --RAW-CONTROL-CHARS "${tempDirspec}"/log*
+    exit 0	# The client has passed the temp dir; it is also responsible for showing the contents (presumably after aggregating multiple "git-lcl --into" calls) via "git-lcl --into TEMPDIR --show.
+fi
+
+showPagedLogs
