ENH: Also print the tag subject with -v|--verbose

diff --git a/bin/git-tagtype b/bin/git-tagtype
--- a/bin/git-tagtype
+++ b/bin/git-tagtype
@@ -6,7 +6,7 @@ printUsage()
     cat <<HELPTEXT
 List only those tags of the passed (annotated or lightweight) type.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" 'all|annotated|lightweight [[-l|--list] <pattern>] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" 'all|annotated|lightweight [-v|--verbose] [[-l|--list] <pattern>] [-?|-h|--help]'
 }
 
 tagType=
@@ -21,14 +21,22 @@ case "$1" in
     *)			printf >&2 'ERROR: Invalid tag type %s; must be either annotated or lightweight.\n' "$1"; exit 2;;
 esac; shift
 
+isVerbose=
 pattern=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-    --list|-l)		shift; pattern="$1"; shift;;
-esac
+	--color)	shift; shift;;
+	--verbose|-v)	shift; isVerbose=t;;
+	--list|-l)	shift; pattern="$1"; shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 case $# in
     0)	;;
     1)	pattern="$1"; shift;;
@@ -37,17 +45,17 @@ esac
 
 patternMatcher()
 {
-    while IFS=$'\n' read -r line
+    while IFS=$'\t' read -r tagName remainder
     do
-	case "$line" in
-	    $pattern) printf '%s\n' "$line";;
+	case "$tagName" in
+	    $pattern) printf '%s%s\n' "$tagName" "${remainder:+$'\t'}${remainder}";;
 	esac
     done
 }
 
 tagList()
 {
-    git for-each-ref --format "${tagType:+%(objecttype)$'\t'}%(refname:strip=2)" --sort=version:refname refs/tags
+    git for-each-ref --format "${tagType:+%(objecttype)$'\t'}%(refname:strip=2)${isVerbose:+$'\t'%(contents:subject)}" --sort=version:refname refs/tags
 }
 
 tagTypeFilter()
