git-timespan-command: ENH: Support --reverse, --with-range ' ' splits into two separate range args, default to HEAD
In order to support a --revision REVISION override in the bisecthere br-variants, we need to:
- support a --reverse flag that swaps the timespan-ago commit and the passed --revision REVISION
- split the range into two arguments if whitespace is passed in --with-range
- default to HEAD (instead of omitting it) if --[with-]range is passed

The bisecthere now pass --reverse and -3 ... TIMESPAN, so appending [--] <pathspec>... now works there, too!

System-info: Ubuntu 24.04.5 LTS, x86_64
Platform-info: git version 2.55.0, hub version 2.14.2, gh version 2.98.0 (2026-08-20), git-lfs/3.8.0 (GitHub; linux amd64; go 1.27.0)

diff --git a/bin/git-timespan-command b/bin/git-timespan-command
--- a/bin/git-timespan-command
+++ b/bin/git-timespan-command
@@ -16,7 +16,7 @@ only the starting revision will be used)
 - replacing TIMESPAN in the following +(N) arguments and appending those
 HELPTEXT
     local requiredEnvironmentVariables; [ -n "$GIT_TIMESPANCOMMAND_TIMESPAN" ] || requiredEnvironmentVariables='GIT_TIMESPANCOMMAND_TIMESPAN=SINCE-ARG'
-    printf "Usage: ${requiredEnvironmentVariables}${requiredEnvironmentVariables:+ }%q %s\\n" "$(basename "$1")" '[-r|--revision REVISION] [--no-range|--range|--with-range RANGE|--inverted] [--one-more] ... [-?|-h|--help]'
+    printf "Usage: ${requiredEnvironmentVariables}${requiredEnvironmentVariables:+ }%q %s\\n" "$(basename "$1")" '[-r|--revision REVISION] [--no-range|--range|--with-range RANGE|--inverted] [--reverse] [--one-more] ... [-?|-h|--help]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... GIT-COMMAND [...] [-?|-h|--help]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... --keep-position GIT-COMMAND [... TIMESPAN ...]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... [-2 GIT-COMMAND ARG1|-3 GIT-COMMAND ARG1 ARG2|...] [...]'
@@ -28,6 +28,7 @@ unset isRange
 isShowOneMore=
 range='..'
 sinceArg=--since
+isReverse=
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -37,6 +38,7 @@ do
 	--range)	shift; isRange=t;;
 	--with-range)	shift; isRange=t; range="${1:?}"; shift;;
 	--one-more)	shift; isShowOneMore=t;;
+	--reverse)	shift; isReverse=t;;
 	--inverted)	shift; sinceArg=--until;;
 	--)		shift; break;;
 	*)		break;;
@@ -58,16 +60,28 @@ getTimespanAgoCommit()
 }
 
 typeset -a rangeArgs=()
-if [ -z "$revision" -a -z "${isRange+t}" ] && [ ! "$isShowOneMore" ]; then
+if [ -z "$revision" -a -z "${isRange+t}" ] && [ ! "$isShowOneMore" ] && [ ! "$isReverse" ]; then
     # For commands that don't require a range and don't require a single commit
     # (i.e. the log variants), we can directly inject the --since argument.
     rangeArgs=("$sinceArg" "$GIT_TIMESPANCOMMAND_TIMESPAN")
 elif [ -z "$isRange" -a -n "${isRange+t}" ]; then
+    # --no-range
     rangeArgs=("$(getTimespanAgoCommit)${isShowOneMore:+^}") || exit $?
-    [ -z "$revision" ] || rangeArgs+=("$revision")
+    if [ -n "$revision" ]; then
+	[ "$isReverse" ] \
+	    && rangeArgs=("$revision" "${rangeArgs[@]}") \
+	    || rangeArgs+=("$revision")
+    fi
 else
     [ -n "$revision" ] && isRange=t
-    rangeArgs=("$(getTimespanAgoCommit)${isShowOneMore:+^}${isRange:+^$range}${revision}") || exit $?
+    startRevision="$(getTimespanAgoCommit)${isShowOneMore:+^}${isRange:+^}"
+    endRevision="${revision:-${isRange:+HEAD}}"
+    if [ "$isReverse" ]; then
+	tmp="$startRevision"
+	startRevision="$endRevision"
+	endRevision="$tmp"
+    fi
+    rangeArgs=("$startRevision"${isRange:+$range}"$endRevision") || exit $?
 fi
 
 isCountedAppend=
