Documentation: Consistency: Use <pathspec>... instead of FILE(s) / FILE [...] / <path>
Git 2.50 seems to use <pathspec> now (though there are also still many instances of <path>); let's unify it to that.
FILE|DIR are still used when individual files are meant or their location may point outside the current repository.
Cosmetics: Style: Add empty lines

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.87.3 (2026-02-23), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-diffY b/bin/git-diffY
--- a/bin/git-diffY
+++ b/bin/git-diffY
@@ -1,8 +1,8 @@
 #!/bin/bash
 set -o pipefail
 
-: ${GIT_DIFFY_FILE_PREFIX=[01;47m}
-: ${GIT_DIFFY_FILE_SUFFIX=[0m}
+: ${GIT_DIFFY_FILE_PREFIX='[01;47m'}
+: ${GIT_DIFFY_FILE_SUFFIX='[0m'}
 
 printUsage()
 {
@@ -13,7 +13,7 @@ printUsage()
 Show changes between commits as a side-by-side diff ${suppressNote}.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[<diff-options>] [<commit> [<commit>]] [--] [<path>...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[<diff-options>] [<commit> [<commit>]] [--] [<pathspec>...] [-?|-h|--help]'
 }
 
 # Highlight diff output if available.
@@ -59,7 +59,7 @@ set -- "${allargs[@]}"
 
 if [ "$isAsDiffTool" ]; then
     if [ $# -eq 0 ]; then
-	echo >&2 'ERROR: No FILEs passed.'
+	echo >&2 'ERROR: No <pathspec>... passed.'
 	exit 2
     fi
 
diff --git a/bin/git-diffc b/bin/git-diffc
--- a/bin/git-diffc
+++ b/bin/git-diffc
@@ -7,7 +7,7 @@ printUsage()
 Show changes between commits as a context diff.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[<diff-options>] [<commit> [<commit>]] [--] [<path>...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[<diff-options>] [<commit> [<commit>]] [--] [<pathspec>...] [-?|-h|--help]'
 }
 
 # Highlight diff output if available.
@@ -40,7 +40,7 @@ set -- "${allargs[@]}"
 
 if [ "$isAsDiffTool" ]; then
     if [ $# -eq 0 ]; then
-	echo >&2 'ERROR: No FILEs passed.'
+	echo >&2 'ERROR: No <pathspec>... passed.'
 	exit 2
     fi
 
diff --git a/bin/git-diffe b/bin/git-diffe
--- a/bin/git-diffe
+++ b/bin/git-diffe
@@ -7,7 +7,7 @@ printUsage()
 Show effective diff that just shows net lines added / removed.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[<diff-options>] [<commit> [<commit>]] [--] [<path>...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[<diff-options>] [<commit> [<commit>]] [--] [<pathspec>...] [-?|-h|--help]'
 }
 
 case "$1" in
@@ -51,7 +51,7 @@ set -- "${allargs[@]}"
 
 if [ "$isAsDiffTool" ]; then
     if [ $# -eq 0 ]; then
-	echo >&2 'ERROR: No FILEs passed.'
+	echo >&2 'ERROR: No <pathspec>... passed.'
 	exit 2
     fi
 
diff --git a/bin/git-editstage b/bin/git-editstage
--- a/bin/git-editstage
+++ b/bin/git-editstage
@@ -7,9 +7,11 @@ Directly edit file(s) in the index (or the HEAD revision if the file hasn't been
 staged yet or --head is given) without modifying the corresponding files in the
 working copy. You can re-edit the same set of files again with --continue.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--head] [EDITOR-ARGS ... [--]] [<path> ...] [-?|-h|--help]'
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--head] [EDITOR-ARGS ... [--]] [<pathspec>...] [-?|-h|--help]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '--continue [--head] [EDITOR-ARGS ... [--]]'
 }
+
 sourceRev=
 isContinue=
 while [ $# -ne 0 ]
@@ -67,7 +69,7 @@ if [ ! "$isContinue" ] && [ ${#paths[@]} -eq 0 ]; then
 	exit 1
     fi
 elif [ "$isContinue" ] && [ ${#paths[@]} -gt 0 ]; then
-    echo >&2 "ERROR: --continue uses the original <path>s, don't add new ones."
+    echo >&2 "ERROR: --continue uses the original <pathspec>..., don't add new ones."
     exit 2
 fi
 
@@ -87,10 +89,10 @@ if [ "$isContinue" ]; then
     readarray -t paths < "$indexEditPathsFilespec"
     readarray -t editFilespecs < "$indexEditFilesFilespec"
     if [ ${#editFilespecs[@]} -eq 0 ]; then
-	printf >&2 'ERROR: No <path> given but also no edited files found under %s/!\n' "$indexEditDirspec"
+	printf >&2 'ERROR: No <pathspec> given but also no edited files found under %s/!\n' "$indexEditDirspec"
 	exit 2
     elif [ ${#paths[@]} -ne ${#editFilespecs[@]} ]; then
-	echo >&2 "ERROR: Inconsistent numbers of <path> and edited files found. Aborting."
+	echo >&2 "ERROR: Inconsistent numbers of <pathspec> and edited files found. Aborting."
 	exit 2
     fi
 
diff --git a/bin/git-logoffiles b/bin/git-logoffiles
--- a/bin/git-logoffiles
+++ b/bin/git-logoffiles
@@ -4,11 +4,11 @@ set -o pipefail
 printUsage()
 {
     cat <<HELPTEXT
-Show a log of commits that cover (at least partially) the files in <path> / the
-files affected by <commit>.
+Show a log of commits that cover (at least partially) the files in <pathspec> /
+the files affected by <commit>.
 Arguments are as to git log (e.g. --since="1 month ago" SUBDIR; but nothing that
 affects the output formatting) and only apply to the shown log; plus at least
-one mandatory <path> or <commit>.
+one mandatory <pathspec> or <commit>.
 
 RELATED COMMANDS:
 - git-logofrelatedfiles also includes any commits that modify related files
@@ -16,7 +16,7 @@ RELATED COMMANDS:
   modify the passed files.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--only-list-expanded-paths|<log-options>] [<revision range>] [--] <path>|<commit> [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--only-list-expanded-paths|<log-options>] [<revision range>] [--] <pathspec>|<commit> [...] [-?|-h|--help]'
 }
 
 typeset -a gitLogArgs=()
@@ -57,14 +57,14 @@ if [ $# -eq 0 ]; then
 	gitLogArgs=("${gitLogArgs[@]:0:${#gitLogArgs[@]}-1}")
     done
     if [ ${#files[@]} -eq 0 ]; then
-	echo >&2 'ERROR: No <path>|<commit> passed.'
+	echo >&2 'ERROR: No <pathspec>|<commit> passed.'
 	exit 2
     fi
 else
     for arg
     do
 	if ! addPathOrCommit "$arg"; then
-	    printf >&2 'ERROR: Not a <path> or <commit>: %s\n' "$arg"
+	    printf >&2 'ERROR: Not a <pathspec> or <commit>: %s\n' "$arg"
 	    exit 2
 	fi
     done
diff --git a/bin/git-logofrelatedfiles b/bin/git-logofrelatedfiles
--- a/bin/git-logofrelatedfiles
+++ b/bin/git-logofrelatedfiles
@@ -4,7 +4,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-%|--percentage-threshold PCT] [<log-options>] [<revision range>] [--] <path>|<commit> [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-%|--percentage-threshold PCT] [<log-options>] [<revision range>] [--] <pathspec>|<commit> [...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -19,10 +19,10 @@ printLongUsage()
     # It is printed to stdout to allow paging with 'more'.
     cat <<HELPDESCRIPTION
 Show log of commits that modify files that often get changed in commits that
-modify files in <path> / the files affected by <commit>. So it doesn't just show
-commits that modify the passed files, but also any commits that modify files
-that are often modified together with the passed files, even if those commits
-don't directly modify the passed files.
+modify files in <pathspec> / the files affected by <commit>. So it doesn't just
+show commits that modify the passed files, but also any commits that modify
+files that are often modified together with the passed files, even if those
+commits don't directly modify the passed files.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
@@ -76,14 +76,14 @@ if [ $# -eq 0 ]; then
 	gitLogArgs=("${gitLogArgs[@]:0:${#gitLogArgs[@]}-1}")
     done
     if [ ${#files[@]} -eq 0 ]; then
-	echo >&2 'ERROR: No <path>|<commit> passed.'
+	echo >&2 'ERROR: No <pathspec>|<commit> passed.'
 	exit 2
     fi
 else
     for arg
     do
 	if ! addPathOrCommit "$arg"; then
-	    printf >&2 'ERROR: Not a <path> or <commit>: %s\n' "$arg"
+	    printf >&2 'ERROR: Not a <pathspec> or <commit>: %s\n' "$arg"
 	    exit 2
 	fi
     done
