git-showfiles-command: ENH: Support passing multiple revisions via --revisions REVISION1 [...] ;
For parity with git-logoffiles, which also takes multiple <commit>s.
git-showfiles can handle those (as long as they aren't revision ranges).

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.95.0 (2026-06-17), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-showfiles-command b/bin/git-showfiles-command
--- a/bin/git-showfiles-command
+++ b/bin/git-showfiles-command
@@ -1,28 +1,30 @@
 #!/bin/bash
 set -o noglob
 
+: ${GIT_SHOWFILESCOMMAND_REVISIONS_END=;}
+
 printUsage()
 {
     cat <<HELPTEXT
 Execute GIT-COMMAND with the files (inside <pathspec>) that were modified in the
-last commit / N'th commit / passed -r|--revision REVISION.
+last commit / N'th commit / passed -r|--revision[s] REVISION(s).
 - appended
 - replacing FILES argument(s) anywhere
 - replacing FILES in the following GIT-COMMAND and -(N-1) arguments
 - replacing FILES in the following +(N) arguments and appending those
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-c ...] GIT-COMMAND [-n N|--count N|-r|--revision REVISION] [GIT-COMMAND-ARGS ...] [--] [<pathspec>...] [-?|-h|--help]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '--keep-position GIT-COMMAND [-n N|--count N|-r|--revision REVISION] [... FILES ...] [--] [<pathspec>...]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-2 GIT-COMMAND ARG1|-3 GIT-COMMAND ARG1 ARG2|...] [-n N|--count N|-r|--revision REVISION] [...] [--] [<pathspec>...]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[+1 ARG1|+2 ARG1 ARG2|+3 ARG1 ARG2 ARG3|...] GIT-COMMAND [-n N|--count N|-r|--revision REVISION] [...] [--] [<pathspec>...]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[-c ...] GIT-COMMAND [-n N|--count N|-r|--revision REVISION|--revisions REVISION1 [...] $GIT_SHOWFILESCOMMAND_REVISIONS_END] [GIT-COMMAND-ARGS ...] [--] [<pathspec>...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "--keep-position GIT-COMMAND [-n N|--count N|-r|--revision REVISION|--revisions REVISION1 [...] $GIT_SHOWFILESCOMMAND_REVISIONS_END] [... FILES ...] [--] [<pathspec>...]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[-2 GIT-COMMAND ARG1|-3 GIT-COMMAND ARG1 ARG2|...] [-n N|--count N|-r|--revision REVISION|--revisions REVISION1 [...] $GIT_SHOWFILESCOMMAND_REVISIONS_END] [...] [--] [<pathspec>...]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[+1 ARG1|+2 ARG1 ARG2|+3 ARG1 ARG2 ARG3|...] GIT-COMMAND [-n N|--count N|-r|--revision REVISION|--revisions REVISION1 [...] $GIT_SHOWFILESCOMMAND_REVISIONS_END] [...] [--] [<pathspec>...]"
 }
 
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 esac
 
-revision=
+typeset -a revisions=()
 typeset -a args=()
 unset files
 while [ $# -ne 0 ]
@@ -34,14 +36,25 @@ do
 			    printUsage "$0" >&2
 			    exit 2
 			fi
-			revision="HEAD~$(($1 - 1))"
+			revisions+=("HEAD~$(($1 - 1))")
 			shift
 			;;
-	--revision|-r)	if [ -n "$revision" ]; then
-			    args+=("$1" "$2"); shift; shift
+	--revision|-r)	if [ ${#revisions[@]} -eq 0 ]; then
+			    shift; revisions+=("${1:?}"); shift
 			else
-			    shift; revision="${1:?}"; shift
+			    args+=("$1" "${2:?}"); shift; shift
 			fi
+			;;
+	--revisions)	shift
+			while [ $# -gt 0 -a "$1" != "$GIT_SHOWFILESCOMMAND_REVISIONS_END" ]
+			do
+			    revisions+=("${1:?}"); shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --revisions must be concluded with '${GIT_SHOWFILESCOMMAND_REVISIONS_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
 			;;
 	--)		shift; typeset -a files=("$@"); break;;
 	*)		args+=("$1"); shift;;
@@ -68,7 +81,7 @@ if [ $# -eq 0 ]; then
 fi
 
 readarray -t committedFiles < <(
-    eval "${GIT_SHOWFILES_COMMAND:-git-showfiles}" '"${revision:-HEAD}" -- "${files[@]}"' \
+    eval "${GIT_SHOWFILES_COMMAND:-git-showfiles}" '"${revisions[@]}" -- "${files[@]}"' \
 	| { xargs -n 1 --no-run-if-empty sh -c 'test -r "$1" && printf %s\\n "$1"' sh || :; }
     printf '\n%d\n' ${PIPESTATUS[0]}
 )	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
