WIP: Use commandOnSelected to filter URLs

diff --git a/bin/git-logbrowse b/bin/git-logbrowse
--- a/bin/git-logbrowse
+++ b/bin/git-logbrowse
@@ -12,14 +12,33 @@ Extract URLs from log messages and open (print with -p|--print) them in the
 browser.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-p|--print] [<log-options>] [<revision range>] [[--] <path>...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-p|--print] [--accept-single] [--single-only] [<log-options>] [<revision range>] [[--] <path>...] [-?|-h|--help]'
+}
+openBrowser()
+{
+    if [ -n "$GIT_LOGBROWSE_BROWSER" ]; then
+	exec "$GIT_LOGBROWSE_BROWSER" "$@"
+    elif type -P browse >/dev/null; then
+	exec browse "$@"
+    elif type -P x-www-browser >/dev/null; then
+	exec x-www-browser "$@"
+    elif type -P xdg-open >/dev/null; then
+	exec xdg-open "$@"
+    else
+	echo >&2 'ERROR: Cannot find a web browser; point the GIT_LOGBROWSE_BROWSER environment variable to one.'
+	exit 5
+    fi
 }
 isPrint=
+typeset -a commandOnSelectedArgs=()
 typeset -a logArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--browse)	shift; openBrowser "$@"; exit $?;;
+	--@(accept-single|single-only))
+			commandOnSelectedArgs+=("$1"); shift;;
 	--print|-p)	shift; isPrint=t;;
 
 	# Ignore options that influence commit formatting (we need just the
@@ -40,18 +59,10 @@ unset 'urls[-1]'
 [ -z "${urls[-1]}" ] && unset 'urls[-1]'
 [ ${#urls[@]} -gt 0 ] || exit 99
 
-printf '%s\n' "${urls[@]}"
-[ "$isPrint" ] && exit 0
-
-if [ "$GIT_LOGBROWSE_BROWSER" ]; then
-    exec "$GIT_LOGBROWSE_BROWSER" "${urls[@]}"
-elif type -P browse >/dev/null; then
-    exec browse "${urls[@]}"
-elif type -P x-www-browser >/dev/null; then
-    exec x-www-browser "${urls[@]}"
-elif type -P xdg-open >/dev/null; then
-    exec xdg-open "${urls[@]}"
+if [ "$isPrint" ]; then
+    printf '%s\n' "${urls[@]}"
+    exit 0
 else
-    echo >&2 'ERROR: Cannot find a web browser; point the GIT_LOGBROWSE_BROWSER environment variable to one.'
-    exit 5
+    printf -v quotedScriptFilespec %q "${BASH_SOURCE[0]}"
+    exec commandOnSelected "${commandOnSelectedArgs[@]}" --command "$quotedScriptFilespec --browse" -- "${urls[@]}"
 fi
