git-rcolatest: Refactoring: Reuse git-filter-out-persistent-branches

diff --git a/bin/git-rcolatest b/bin/git-rcolatest
--- a/bin/git-rcolatest
+++ b/bin/git-rcolatest
@@ -34,18 +34,16 @@ do
     esac
 done
 
-currentBranch="$(git-remotebr "$remote" 2>/dev/null || echo "(remote branch not found)")"
-masterBranch="$(git-mbr)"
-baseBranch="$(git-nbr 2>/dev/null)"
 remoteBranch="$(
     ${GIT_RCOLATEST_REMOTE_BRANCH_COMMAND:-git-rbr} "$remote" ${GIT_RCOLATEST_REMOTE_BRANCH_ARGUMENT:---sort=committerdate} "$@" \
-	| grep --invert-match --fixed-strings --line-regexp -e "${remote}/${masterBranch}" ${baseBranch:+-e "${remote}/$baseBranch"} -e "$currentBranch" \
+	| git-filter-out-persistent-branches --remote "$remote" \
 	| tail -n 1
 )" || exit $?
 if [ -z "$remoteBranch" ]; then
     # git branch does not return an error if there are no matches for the passed pattern.
+    baseBranch="$(git-nbr 2>/dev/null)"
     printf >&2 'ERROR: No%s branch (excluding the current %s and %s%s) found in %s.\n' \
-	"${*:+ matching}" "$currentBranch" "$masterBranch" "${baseBranch:+ and ${baseBranch}}" "$remote"
+	"${*:+ matching}" "$(git-remotebr "$remote" 2>/dev/null || echo "(remote branch not found)")" "$(git-mbr)" "${baseBranch:+ and ${baseBranch}}" "$remote"
     exit 1
 fi
 exec git-checkout-remote-branch "${checkoutArgs[@]}" "$remoteBranch"
