FIX: Cannot pass multiple arguments
E.g. "--quiet --"; need full command-line argument parsing.

diff --git a/bin/git-staged b/bin/git-staged
--- a/bin/git-staged
+++ b/bin/git-staged
@@ -10,14 +10,19 @@ HELPTEXT
 }
 isQuiet=
 typeset -a diffArgs=(--name-only)
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-    --quiet|-q)		shift; isQuiet=t; diffArgs=(--quiet --exit-code);;
-    --)			shift;;
-esac
+	--color)	shift; shift;;
+	--quiet|-q)	shift; isQuiet=t; diffArgs=(--quiet --exit-code);;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 
 runDiff()
 {
