git-rblastfixup: ENH: Also handle out-of-order fixups
The previous implementation assumed that the first fixup commit also references the earliest commit target, but that isn't necessarily so; the last fixup can also target the oldest commit.
We need to resolve the target commits individually for each fixup (as it's the most recent with that commit subject, but there could be previous commits with an identical subject).
If there are multiple target commits, git-logrevs puts them into the correct order and we can pick the earliest from them.

diff --git a/bin/git-rblastfixup b/bin/git-rblastfixup
--- a/bin/git-rblastfixup
+++ b/bin/git-rblastfixup
@@ -34,20 +34,26 @@ do
     esac
 done
 
-IFS=$'\t' read -r lastCommit originalMessage < <(
-    git log --pretty='tformat:%H %s' "${gitArgs[@]}" "${rangeArg[@]}" "$@" | \
-	sed -n -e 's/^\([[:xdigit:]]\+\) \(amend\|fixup\|squash\)! \(.*\)$/\1\t\3/p' | \
-	eval "${number:+sed -n -e "1,${number}p" | }" 'sed -n -e \$p'
+typeset -A targetCommits=()
+while IFS=$'\t' read -r lastCommit originalMessage
+do
+    fixupTargetCommit="$(git log --pretty='tformat:%H' --max-count 1 --grep "${originalMessage:?}" --fixed-strings "${rangeStart}${lastCommit:?}^" "${gitArgs[@]}" "$@")"
+    if [ -z "$fixupTargetCommit" ]; then
+	printf >&2 'ERROR: Could not find the original commit prior to %s with message: %s\n' "$lastCommit" "$originalMessage"
+	exit 3
+    fi
+    targetCommits["$fixupTargetCommit"]=t
+done < <(
+    git log --pretty='tformat:%H %s' "${gitArgs[@]}" "${rangeArg[@]}" "$@" \
+	| sed -n -e 's/^\([[:xdigit:]]\+\) \(amend\|fixup\|squash\)! \(.\+\)$/\1\t\3/p'
 )
-if [ -z "$lastCommit" -o -z "$originalMessage" ]; then
-    echo >&2 'No fixup / amend / squash commits found.'
-    exit 1
-fi
 
-lastFixupCommit="$(git log --pretty='tformat:%H' --max-count 1 --grep "$originalMessage" --fixed-strings "${rangeStart}${lastCommit}^" "${gitArgs[@]}" "$@")"
-if [ -z "$lastFixupCommit" ]; then
-    printf >&2 'ERROR: Could not find the original commit prior to %s with message: %s\n' "$lastCommit" "$originalMessage"
-    exit 1
-fi
+case ${#targetCommits[@]} in
+    0)	echo >&2 'No fixup / amend / squash commits found.'
+	exit 1
+	;;
+    1)	targetCommit="${!targetCommits[*]}";;
+    *)	targetCommit="$(git-logrevs --pretty='tformat:%H' --revisions "${!targetCommits[@]}" \; "${gitArgs[@]}" "$@" | tail -n 1)" || exit 3;;
+esac
 
-exec git-rbni "${lastFixupCommit}^"
+exec git-rbni "${targetCommit:?}^"
