ENH: Also support basing the new branch off the current one / <start-point>

diff --git a/bin/git-createbranch b/bin/git-createbranch
--- a/bin/git-createbranch
+++ b/bin/git-createbranch
@@ -8,7 +8,7 @@ Create a new branch [from <start-point>] without switching to it. Enforces that
 such is passed.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-f|--force] -b|-B|--branch <new-branch> [<start-point>] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-f|--force] -b|-B|--branch (<newbranch>|OLD=NEW|^=PREFIX|+=SUFFIX) [...] [<start-point>] [-?|-h|--help]'
 }
 
 isForce=
@@ -26,18 +26,35 @@ do
     esac
 done
 if [ ${#branches[@]} -eq 0 ]; then
-    echo 'ERROR: No -b <new-branch> passed.'
+    echo 'ERROR: No -b|-B|--branch (<newbranch>|OLD=NEW|^=PREFIX|+=SUFFIX) passed.'
     echo
     printUsage "$0"
     exit 2
 fi >&2
-newBranch="${branches[0]}"
+
+oldBranch=
 case $# in
-    0)	commit=;;
-    1)	commit="$1"; shift;;
+    0)	commit=
+	oldBranch="$(git-brname --real-branch-only)" || exit $?
+	;;
+    1)	commit="$1"; shift
+	if git-existsbr "$commit"; then
+	    oldBranch="$commit"
+	elif [ ${#branches[@]} -gt 1 ]; then
+	    echo >&2 'ERROR: Cannot base new branch on a <start-point> that is not a branch.'
+	    exit 2
+	fi
+	;;
     *)	printUsage "$0" >&2
 	exit 2
 esac
+
+if [ -n "$oldBranch" ]; then
+    newBranch="$(replaceWith -- "$oldBranch" "${branches[@]}" 2>/dev/null || printf %s "${branches[0]}")"
+    [ "$oldBranch" != "$newBranch" ] || exit 4
+else
+    newBranch="${branches[0]}"
+fi
 
 oldValue=''	# Note: Empty <oldvalue> ensures that the $newBranch reference doesn't exist yet.
 [ "$isForce" ] && oldValue="$(git rev-parse --verify --quiet "${newBranch:?}" 2>/dev/null)"
