ENH: Allow pruning of remote branches via -R|--reverse
I thought about adding a --except flag to git-odeletebr, but the specification of branches not to delete is difficult and error-prone. Instead (at least in my current situation), the local branch state is correct and we want that to be reflected in the remote as well, so this works like a reverse pruning, and this command is ideal to extend.

diff --git a/bin/git-rprune b/bin/git-rprune
--- a/bin/git-rprune
+++ b/bin/git-rprune
@@ -21,7 +21,16 @@ With --test, only print which local branches would be deleted.
 Note: To do this automatically on each fetch / pull:
     git config --global fetch.prune true
 HELPTEXT
+    echo
     printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [-t|--test|-f|--force] [-?|-h|--help]"
+    echo
+    cat <<HELPTEXT
+Remove old branches in ${remote:-REMOTE} that have no corresponding local branch any
+longer.
+With --test, only print which ${remote:-REMOTE} branches would be deleted.
+HELPTEXT
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} -R|--reverse [-t|--test|-f|--force]"
 }
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
@@ -29,17 +38,19 @@ esac
 
 remote="${1:?}"; shift
 
-action=deleteLocalBranch
+action=
 branchDeleteOption=-d
+isReverse=
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)		shift; printUsage "$0"; exit 0;;
-	-f|--force)		shift; branchDeleteOption=-D;;
-	-t|--test)		shift; action=dryRun;;
-	--)			shift; break;;
-	-*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)			break;;
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--reverse|-R)	shift; isReverse=t;;
+	--force|-f)	shift; branchDeleteOption=-D;;
+	--test|-t)	shift; action=dryRun;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
     esac
 done
 if [ $# -ne 0 ]; then
@@ -52,24 +63,36 @@ deleteLocalBranch()
     local localBranch="${1:?}"; shift
     git branch $branchDeleteOption "$localBranch"
 }
+deleteRemoteBranches()
+{
+    git push "$remote" --delete "${@#${remote}/}"
+}
 dryRun()
 {
-    local localBranch="${1:?}"; shift
-    echo "Prune $localBranch"
+    printf 'Prune %s\n' "$@"
 }
 
 readarray -t remoteBranches < <(git-rbr "$remote")
 readarray -t localBranches < <(git branch | awk '{print $NF}')
 
 status=0
-for localBranch in "${localBranches[@]}"
-do
-    trackedRemote="$(git config "branch.${localBranch}.remote" 2>/dev/null)"
-    if [ "$trackedRemote" = "$remote" ]; then
-	trackedBranch="$(git config "branch.${localBranch}.merge")"
-	if ! contains "${remote}/${trackedBranch##refs/heads/}" "${remoteBranches[@]}"; then
-	    $action "$localBranch" || status=$?
+if [ "$isReverse" ]; then
+    typeset -a oldRemoteBranches=()
+    for remoteBranch in "${remoteBranches[@]}"
+    do
+	contains "${remoteBranch#${remote}/}" "${localBranches[@]}" || \
+	    oldRemoteBranches+=("$remoteBranch")
+    done
+    [ ${#oldRemoteBranches[@]} -eq 0 ] || ${action:-deleteRemoteBranches} "${oldRemoteBranches[@]}" || status=$?
+else
+    for localBranch in "${localBranches[@]}"
+    do
+	trackedRemote="$(git config "branch.${localBranch}.remote" 2>/dev/null)"
+	if [ "$trackedRemote" = "$remote" ]; then
+	    trackedBranch="$(git config "branch.${localBranch}.merge")"
+	    contains "${remote}/${trackedBranch##refs/heads/}" "${remoteBranches[@]}" || \
+		${action:-deleteLocalBranch} "$localBranch" || status=$?
 	fi
-    fi
-done
+    done
+fi
 exit $status
