FIX: Use reset --hard instead of update-ref
As the latter leaves the undone changes in the index.
The tagging is different from the uncommit-to-branch (where I based the implementation on), as we'll stay on the current branch, so "git reset" is the right thing to use here.

diff --git a/bin/git-archivecommit b/bin/git-archivecommit
--- a/bin/git-archivecommit
+++ b/bin/git-archivecommit
@@ -59,9 +59,12 @@ fi
 if [ $# -gt 0 ]; then
     printUsage "$0" >&2
     exit 2
+elif git-dirty; then
+    echo >&2 'ERROR: working copy is still dirty; please clean up first.'
+    git status
+    exit 1
 fi
 
-currentBranchName="$(git-brname --real-branch-only)" || exit $?
 tagCommit="$(git rev-parse HEAD)" || exit $?
 if [ -z "$tagName" ] && [ ! "$isYes" ]; then
     </dev/tty read -r -p "Please enter tag name: " tagName
@@ -86,5 +89,5 @@ else
 fi
 
 git tag ${isForce:+--force} "$fullTagName" "$tagCommit" || exit $?
-git update-ref -m "archivecommit: move $commitNum commit${commitNumPlural} to $fullTagName" "refs/heads/$currentBranchName" "${commit}^" || exit $?
+git reset --hard "${commit}^" || exit $?
 ! git existsremote origin || git push ${isForce:+--force} --tags origin || exit $?
