ENH: Consistency: Add -E|--print-error [--error-message MSG]
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.92.0 (2026-04-28), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-staged b/bin/git-staged
--- a/bin/git-staged
+++ b/bin/git-staged
@@ -6,10 +6,12 @@ printUsage()
 Test whether there are / list staged files in index.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet] [--] [<pathspec>...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet|-E|--print-error [--error-message MSG]] [--] [<pathspec>...] [-?|-h|--help]'
 }
 
 isQuiet=
+errorMessage='ERROR: Index is not empty:'
+isPrintError=
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -18,6 +20,10 @@ do
 			shift;;
 	--color)	shift; shift;;
 	--quiet|-q)	shift; isQuiet=t;;
+	--print-error|-E)
+			shift; isPrintError=t;;
+	--error-message)
+			shift; errorMessage="$1"; shift;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
@@ -28,5 +34,9 @@ if [ "$isQuiet" ]; then
     ! git diff --cached --quiet --exit-code -- "$@"
 else
     paths="$(git-stifiles "$@")"
-    [ -n "$paths" ] && printf '%s\n' "$paths"
+    if [ -n "$paths" ]; then
+	[ ! "$isPrintError" ] || printf >&2 '%s\n' "$errorMessage"
+	printf '%s\n' "$paths"
+	[ ! "$isPrintError" ] || exit 1
+    fi
 fi
diff --git a/bin/git-unstaged b/bin/git-unstaged
--- a/bin/git-unstaged
+++ b/bin/git-unstaged
@@ -7,22 +7,37 @@ Test whether there are / list uncommitted changes to committed files in the
 working copy (ignoring changes in the index and untracked files).
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet] [--] [<pathspec>...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet|-E|--print-error [--error-message MSG]] [--] [<pathspec>...] [-?|-h|--help]'
 }
 
 isQuiet=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
+errorMessage='ERROR: Working copy has unstaged changes:'
+isPrintError=
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-    --quiet|-q)		shift; isQuiet=t;;
-    --)			shift;;
-esac
+	--color)	shift; shift;;
+	--quiet|-q)	shift; isQuiet=t;;
+	--print-error|-E)
+			shift; isPrintError=t;;
+	--error-message)
+			shift; errorMessage="$1"; shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 
 if [ "$isQuiet" ]; then
     ! git diff --quiet --exit-code -- "$@"
 else
     paths="$(git-stIfiles "$@")"
-    [ -n "$paths" ] && printf '%s\n' "$paths"
+    if [ -n "$paths" ]; then
+	[ ! "$isPrintError" ] || printf >&2 '%s\n' "$errorMessage"
+	printf '%s\n' "$paths"
+	[ ! "$isPrintError" ] || exit 1
+    fi
 fi
