git-uptodate: Documentation: Split into long and short usage, long parsing

diff --git a/bin/git-uptodate b/bin/git-uptodate
--- a/bin/git-uptodate
+++ b/bin/git-uptodate
@@ -2,30 +2,56 @@
 # Source: https://stackoverflow.com/a/25109122/813602
 set -o pipefail
 
+printShortUsage()
+{
+    # Note: short followed by long option; if the user knows the short one, she can
+    # skim the long one.
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet] [--] [<remote>[/<branch>]] [-?|-h|--help]'
+}
 printUsage()
 {
-    cat <<HELPTEXT
+    # This is the short help when launched with no or incorrect arguments.
+    # It is printed to stderr to avoid accidental processing.
+    printShortUsage "$1" >&2
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
+}
+printLongUsage()
+{
+    # This is the long "man page" when launched with the help argument.
+    # It is printed to stdout to allow paging with 'more'.
+    cat <<HELPDESCRIPTION
 Check remote whether the current branch is on the same commit as the tracked
 remote branch / passed remote (or whether a fetch / push is needed).
 Check remote whether there are tags with higher version numbers than the
 currently checked out tag.
-HELPTEXT
+HELPDESCRIPTION
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet] [<remote>[/<branch>]] [-?|-h|--help]'
+    printShortUsage "$1"
+    echo
+    cat <<HELPTEXT
+    --quiet|-q		Do not print an up-to-date message or the pending
+			commits.
+HELPTEXT
 }
 
 [ -t 1 ] \
     && typeset colorArg=(--color=always) \
     || typeset -a colorArg=(--no-color)
 isQuiet=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --color=auto)	shift;;
-    --no-color|--color=*)
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--color=auto)	shift;;
+	--no-color|--color=*)
 			colorArg=("$1"); shift;;
-    --color)		[ "$2" = auto ] || colorArg=("$1" "$2"); shift; shift;;
-    --quiet|-q)		shift; isQuiet=t;;
-esac
+	--color)	[ "$2" = auto ] || colorArg=("$1" "$2"); shift; shift;;
+	--quiet|-q)	shift; isQuiet=t;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 
 checkBranch()
 {
