git-r[l]deletebr: Consistency: ENH: Also default to the current branch, like deletebr

diff --git a/bin/git-rdeletebr b/bin/git-rdeletebr
--- a/bin/git-rdeletebr
+++ b/bin/git-rdeletebr
@@ -3,9 +3,9 @@
 printUsage()
 {
     cat <<HELPTEXT
-Delete remote <branch> from ${remote:-REMOTE}.
+Delete the current branch / passed <branch> from ${remote:-REMOTE}.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [-i|--ignore-missing] [-y|--yes] [--] <branch> [...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [-i|--ignore-missing] [-y|--yes] [--] [<branch> ...] [-?|-h|--help]"
 }
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
@@ -32,11 +32,9 @@ do
     esac
 done
 if [ $# -eq 0 ]; then
-    echo 'Need (at least one) remote <branch> to delete!'
-    echo
-    printUsage "$0"
-    exit 2
-fi >&2
+    branch="$(git-brname --real-branch-only)" || exit $?
+    set -- "$branch"
+fi
 
 
 if [ "$isIgnoreMissing" ]; then
diff --git a/bin/git-rldeletebr b/bin/git-rldeletebr
--- a/bin/git-rldeletebr
+++ b/bin/git-rldeletebr
@@ -4,7 +4,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [-f|--force] [-i|--ignore-missing-in-${remote}] [-I|--ignore-missing-local] [-y|--yes] [--] <branch> [...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [-f|--force] [-i|--ignore-missing-in-${remote}] [-I|--ignore-missing-local] [-y|--yes] [--] [<branch> ...] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -18,7 +18,8 @@ printLongUsage()
     # This is the long "man page" when launched with the help argument.
     # It is printed to stdout to allow paging with 'more'.
     cat <<HELPDESCRIPTION
-Delete <branch> from the local repository as well as ${remote:-REMOTE}.
+Delete the current branch (and detach) / passed <branch> from the local
+repository as well as ${remote:-REMOTE}.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
@@ -67,11 +68,10 @@ do
     esac
 done
 if [ $# -eq 0 ]; then
-    echo 'Need (at least one) <branch> to delete!'
-    echo
-    printUsage "$0"
-    exit 2
-fi >&2
+    branch="$(git-brname --real-branch-only)" || exit $?
+    git-detach || exit $?
+    set -- "$branch"
+fi
 
 
 # Need to determine remote branch names before deleting the local branches.
