Robustness: Add sanity check for master branch
Normally, no affected submodules would be found and that error would be shown. However, if --same-branch is passed and some submodule(s) have the master branch checked out, this could indeed happen.

diff --git a/bin/git-supersubreintegratetom b/bin/git-supersubreintegratetom
--- a/bin/git-supersubreintegratetom
+++ b/bin/git-supersubreintegratetom
@@ -389,6 +389,11 @@ reintegrateSuperproject()
 {
     goToSuperproject
 
+    if [ "$(git-brname --real-branch-only 2>/dev/null)" = "$masterBranch" ]; then
+	echo >&2 "ERROR: Already on master branch; nothing to ${integrationType}integrate."
+	exit 4
+    fi
+
     typeset -a integrateArgs=() ffintegratetoArgs=()
     case $(git bomcount) in
 	0)  echo >&2 'ERROR: Expected at least one commit in the superproject on the branch, but none found.'
