Refactoring: Minor: Complete command-line argument parsing
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.92.0 (2026-04-28), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-committemplate b/bin/git-committemplate
--- a/bin/git-committemplate
+++ b/bin/git-committemplate
@@ -37,15 +37,25 @@ HELPTEXT
 
 action=print
 saveOperator='>'
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --get-filespec)	shift; action=getFilespec;;
-    --save)		shift; action=save;;
-    --append)		shift; action=save; saveOperator='>>';;
-    --edit)		shift; action=edit;;
-    --clean)		shift; action=clean;;
-    -*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-esac
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--get-filespec)	shift; action=getFilespec;;
+	--save)		shift; action=save;;
+	--append)	shift; action=save; saveOperator='>>';;
+	--edit)		shift; action=edit;;
+	--clean)	shift; action=clean;;
+	--)		shift; break;;
+	-*)		if [ "$action" = 'edit' ]; then
+			    break
+			else
+			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2
+			fi
+			;;
+	*)		break;;
+    esac
+done
 if [ $# -ne 0 -a "$action" != 'edit' ]; then
     printUsage "$0" >&2
     exit 2
