Robustness: Minor: Mutually exclusive --sort-by-* and -s|--summary
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.47.0, hub version 2.14.2, gh version 2.55.0 (2024-08-20), git-lfs/3.6.0 (GitHub; linux amd64; go 1.23.1)

diff --git a/bin/git-brlifetimes b/bin/git-brlifetimes
--- a/bin/git-brlifetimes
+++ b/bin/git-brlifetimes
@@ -73,6 +73,12 @@ do
 	*)		logArgs+=("$1"); shift;;
     esac
 done
+if [ -n "$sorter" ] && [ "$isSummaryOnly" ]; then
+    echo 'ERROR: Cannot combine --sort-by-* with -s|--summary.'
+    echo
+    printUsage "$0"
+    exit 2
+fi >&2
 [ "$isColor" ] || unset "${!GIT_BRLIFETIMES_COLOR_@}"
 
 summarizer()
