ENH: Allow passing numbers to COMMAND via -c|--command|--exec

diff --git a/bin/git-difflines b/bin/git-difflines
--- a/bin/git-difflines
+++ b/bin/git-difflines
@@ -1,11 +1,16 @@
 #!/bin/bash
 set -o pipefail
 
+: ${GIT_DIFFLINES_FILE_MARKER='{+}'}
+fileMarker="$GIT_DIFFLINES_FILE_MARKER"; unset GIT_DIFFLINES_FILE_MARKER
+: ${GIT_DIFFLINES_NUMBER_MARKER='{}'}
+numberMarker="$GIT_DIFFLINES_NUMBER_MARKER"; unset GIT_DIFFLINES_NUMBER_MARKER
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--only-new|--only-old|--only-removed] [--prefix-numbers PREFIX] [<diff-options>] [<commit> [<commit>]] [--] [<path>...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[--only-new|--only-old|--only-removed] [--prefix-numbers PREFIX] [-c|--command \"COMMANDLINE\" [...] | --exec SIMPLECOMMAND [...] ${numberMarker:+[}${numberMarker}${numberMarker:+] [...]} ; [...]] [<diff-options>] [<commit> [<commit>]] [--] [<path>...] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -32,11 +37,21 @@ HELPDESCRIPTION
 			files (so actual deletions, not changes).
     --prefix-numbers PREFIX
 			Prepend PREFIX before each line number.
+    --command|-c CMD	Execute CMD as a command-line for each diffed file${fileMarker:+; ${fileMarker}
+			is replaced with the filespec}.
+			Line numbers ${numberMarker:+either }are appended${numberMarker:+ or replace any $numberMarker
+			marker} inside COMMANDLINE.
+    --exec COMMAND [...] ;
+			Execute COMMAND for each diffed file${fileMarker:+; ${fileMarker} is replaced
+			with the filespec};
+			all following arguments are taken to be arguments to the
+			COMMAND until an argument consisting of ';' is
+			encountered. Line numbers ${numberMarker:+either }are appended${numberMarker:+ or replace
+			any $numberMarker marker} inside COMMANDLINE.
 HELPTEXT
 }
 
 typeset -a pager=("${PAGER:-less}" --quit-on-intr --RAW-CONTROL-CHARS); [ -t 1 ] || pager=()
-
 oldFormat=$'%dn\n'
 newFormat="$oldFormat"
 algorithm=oldNewDiff
@@ -44,6 +59,7 @@ prefix=
 isAsDiffTool=
 typeset -a allargs=()
 typeset -a forwardedArgs=()
+typeset -a commands=()
 while [ $# -gt 0 ]
 do
     case "$1" in
@@ -57,6 +73,25 @@ do
 	--only-removed)	forwardedArgs+=("$1"); shift; algorithm=removedDiff;;
 	--prefix-numbers)
 			forwardedArgs+=("$1" "${2?}"); shift; prefix="${1?}"; shift;;
+	--command|-c)	forwardedArgs+=("$1" "${2?}"); shift; commands+=(${commands:+;} "$1"); shift;;
+	--exec)		forwardedArgs+=("$1"); shift
+			cmd=
+			printf -v escapedFileMarker %q "$fileMarker"
+			printf -v escapedNumberMarker %q "$numberMarker"
+			while [ $# -gt 0 -a "$1" != ';' ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    quotedArg="${quotedArg//"$escapedFileMarker"/$fileMarker}"	# %q escapes {}, we don't want that to have it interpolated later.
+			    cmd="${cmd}${cmd:+ }${quotedArg//"$escapedNumberMarker"/$numberMarker}"	# %q escapes {}, we don't want that to have it interpolated later.
+			    forwardedArgs+=("$1"); shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo 'ERROR: --exec command must be concluded with ;!'; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			forwardedArgs+=("$1"); shift
+			commands+=(${commands:+;} "$cmd")
+			;;
 	*)		allargs+=("$1"); shift;;
     esac
 done
@@ -92,13 +127,27 @@ END { processHunk(); }
 '
 }
 
+execute()
+{
+    local filespec="${1:?}"; shift
+    typeset -a numbers=(); readarray -t numbers
+    [ ${#numbers[@]} -gt 0 ] || return
+
+    local quotedNumbers; printf -v quotedNumbers '%q ' "${numbers[@]}"; quotedNumbers="${quotedNumbers% }"
+    typeset -a interpolatedCommands=("${commands[@]//"$numberMarker"/$quotedNumbers}")
+    [ "${interpolatedCommands[*]}" = "${commands[*]}" ] && interpolatedCommands+=("$quotedNumbers")
+    interpolatedCommands=("${interpolatedCommands[@]//"$fileMarker"/$filespec}")
+    eval "${interpolatedCommands[@]}"
+}
+
 if [ "$isAsDiffTool" ]; then
     if [ $# -eq 0 ]; then
 	echo >&2 'ERROR: No FILEs passed.'
 	exit 2
     fi
 
-    $algorithm "$@"
+    eval '$algorithm "$@"' \
+	"${commands[*]:+| execute "${!#}"}"
     exit 0	# Need to return success to avoid that Git complains that the "external tool died".
 else
     readonly scriptName="$(basename -- "${BASH_SOURCE[0]}")"
