BUG: Major: Off-by-one with merge base
For the duration, we need to use the date of the first commit of the branch, but the merge base is preceding that! A lot of time could have passed since that branch was created, causing vastly inflated durations!!! (The repos I mainly tested that with were either "hot" ones that saw regular development, or had information so old that the error wasn't easy to recognize. Bummer.)
I basically just need to log all commits on the branch with the common ${firstParent}..${parent} range. The number of records immediately gives me the commit count (saving the separate invocation of git-count), and I can obtain both the (short, saving one more call) hash and author epoch from it. Yay; that should speed up the data collection a fair bit!

System-info: Armbian 24.11.1 noble, aarch64
Platform-info: git version 2.47.0, hub version 2.14.2, gh version 2.62.0 (2024-11-14), git-lfs/3.5.1 (GitHub; linux arm64; go 1.21.8)

diff --git a/bin/git-brlifetimes b/bin/git-brlifetimes
--- a/bin/git-brlifetimes
+++ b/bin/git-brlifetimes
@@ -123,9 +123,6 @@ summarizer()
 
 logLifetimes()
 {
-    local anyCommit="$(git rev-parse --verify --short HEAD)"	# Resolve what core.abbrev resolves to.
-    local abbrevLen="${#anyCommit}"
-
     status=
     while IFS=' ' read -r -a fields
     do
@@ -146,22 +143,28 @@ logLifetimes()
 	for parent in "${otherParents[@]}"
 	do
 	    let parentCount+=1
-	    local mergeBase startDate dateDiff commitCount
-	    mergeBase="$(git merge-base "$firstParent" "$parent")" || { status=$?; printf >&2 'No merge base for %s and %s:\n%s\n' "$firstParent" "$parent" "$logLine"; continue; }
-	    startDate="$(git show --no-patch --pretty=tformat:@%at "$mergeBase")" || { status=$?; printf >&2 'No start date for %s:\n%s\n' "$mergeBase" "$logLine"; continue; }
+	    typeset -a branchRecords=()
+	    readarray -t branchRecords < <(git log --pretty=$'tformat:%h\t@%at' "${firstParent}..${parent}")
+	    if [ ${#branchRecords[@]} -eq 0 ]; then
+		printf >&2 'ERROR: No merge base for %s and %s:\n%s\n' "$firstParent" "$parent" "$logLine"
+		continue
+	    fi
+	    local commitCount=${#branchRecords[@]}
+	    local startRecord="${branchRecords[-1]}"
+	    local startCommit="${startRecord%%$'\t'*}"
+	    local startDate="${startRecord#*$'\t'}"
 	    dateDiff="$(datediff --output "$datediffOutputFormat" "$startDate" "$endDate")" && : ${status:=0} || { status=$?; continue; }
-	    commitCount="$(git-count "${mergeBase}..${parent}")"
 
 	    if [ -n "$picker" ]; then
 		eval "$picker"
 	    else
 		local parentCountSuffix=''; [ ${#otherParents[@]} -gt 1 ] && parentCountSuffix=" ($parentCount)"
 
-		printf '%s%s%15s%s %s%5d%s %s%s%s..%s%s\n' \
+		printf '%s%s%15s%s %s%5d%s %s%s%s %s%s\n' \
 		    "${inserter:+$(eval "$inserter")$'\t'}" \
 		    "$GIT_BRLIFETIMES_COLOR_LIFETIME" "$dateDiff" "$GIT_BRLIFETIMES_COLOR_RESET" \
 		    "$GIT_BRLIFETIMES_COLOR_COMMITCOUNT" "${commitCount:-0}" "$GIT_BRLIFETIMES_COLOR_RESET" \
-		    "$GIT_BRLIFETIMES_COLOR_MERGEBASE" "${mergeBase:0:abbrevLen}" "$GIT_BRLIFETIMES_COLOR_RESET" \
+		    "$GIT_BRLIFETIMES_COLOR_MERGEBASE" "$startCommit" "$GIT_BRLIFETIMES_COLOR_RESET" \
 		    "$logLine" "$parentCountSuffix"
 	    fi
 	done
