Refactoring: Split into long and short usage, full command-line argument parsing
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.96.0 (2026-07-02), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-files-command b/bin/git-files-command
--- a/bin/git-files-command
+++ b/bin/git-files-command
@@ -2,9 +2,28 @@
 
 : ${GIT_FILESCOMMAND_EXEC_END=;}
 
+printShortUsage()
+{
+    # Note: short followed by long option; if the user knows the short one, she can
+    # skim the long one.
+    printf 'Usage: %q %s\n' "$(basename "$1")" "--source-command \"SOURCE-COMMANDLINE\"|--source-exec COMMAND [...] $GIT_FILESCOMMAND_EXEC_END [-?|-h|--help] ..."
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... GIT-COMMAND [GIT-COMMAND-ARGS ...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... --keep-position GIT-COMMAND SOURCE-COMMAND [GIT-COMMAND-ARGS ... FILES ...]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... [-2 GIT-COMMAND ARG1|-3 GIT-COMMAND ARG1 ARG2|...] [...]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... [+1 ARG1|+2 ARG1 ARG2|+3 ARG1 ARG2 ARG3|...] GIT-COMMAND [...]"
+}
 printUsage()
 {
-    cat <<HELPTEXT
+    # This is the short help when launched with no or incorrect arguments.
+    # It is printed to stderr to avoid accidental processing.
+    printShortUsage "$1" >&2
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
+}
+printLongUsage()
+{
+    # This is the long "man page" when launched with the help argument.
+    # It is printed to stdout to allow paging with 'more'.
+    cat <<HELPDESCRIPTION
 Execute GIT-COMMAND with a list of files that is obtained from SOURCE-COMMAND
 (e.g. showfiles)
 - appended
@@ -13,34 +32,36 @@ Execute GIT-COMMAND with a list of files that is obtained from SOURCE-COMMAND
 - replacing FILES in the following +(N) arguments and appending those
 Any appended <pathspec>... are removed off GIT-COMMAND's argument list and
 instead passed to SOURCE-COMMAND.
-HELPTEXT
+HELPDESCRIPTION
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" "--source-command \"SOURCE-COMMANDLINE\"|--source-exec COMMAND [...] $GIT_FILESCOMMAND_EXEC_END GIT-COMMAND [GIT-COMMAND-ARGS ...] [-?|-h|--help]"
-    printf 'Usage: %q %s\n' "$(basename "$1")" "--source-command \"SOURCE-COMMANDLINE\"|--source-exec COMMAND [...] $GIT_FILESCOMMAND_EXEC_END --keep-position GIT-COMMAND SOURCE-COMMAND [GIT-COMMAND-ARGS ... FILES ...]"
-    printf 'Usage: %q %s\n' "$(basename "$1")" "--source-command \"SOURCE-COMMANDLINE\"|--source-exec COMMAND [...] $GIT_FILESCOMMAND_EXEC_END [-2 GIT-COMMAND ARG1|-3 GIT-COMMAND ARG1 ARG2|...] [...]"
-    printf 'Usage: %q %s\n' "$(basename "$1")" "--source-command \"SOURCE-COMMANDLINE\"|--source-exec COMMAND [...] $GIT_FILESCOMMAND_EXEC_END [+1 ARG1|+2 ARG1 ARG2|+3 ARG1 ARG2 ARG3|...] GIT-COMMAND [...]"
+    printShortUsage "$1"
 }
 
 sourceCommand=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --source-command)	shift; sourceCommand+="${sourceCommand:+; }${1:?}"; shift;;
-    --source-exec)	shift
-			cmd=
-			while [ $# -gt 0 -a "$1" != "$GIT_FILESCOMMAND_EXEC_END" ]
-			do
-			    printf -v quotedArg '%q' "$1"
-			    cmd="${cmd}${cmd:+ }${quotedArg}"
-			    shift
-			done
-			if [ $# -eq 0 ]; then
-			    echo "ERROR: --source-exec command must be concluded with '${GIT_FILESCOMMAND_EXEC_END}'"; echo; printUsage "$0"
-			    exit 2
-			fi >&2
-			shift
-			sourceCommand+="${sourceCommand:+; }$cmd"
-			;;
-esac
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--source-command)
+			shift; sourceCommand+="${sourceCommand:+; }${1:?}"; shift;;
+	--source-exec)	shift
+    			cmd=
+    			while [ $# -gt 0 -a "$1" != "$GIT_FILESCOMMAND_EXEC_END" ]
+    			do
+    			    printf -v quotedArg '%q' "$1"
+    			    cmd="${cmd}${cmd:+ }${quotedArg}"
+    			    shift
+    			done
+    			if [ $# -eq 0 ]; then
+    			    echo "ERROR: --source-exec command must be concluded with '${GIT_FILESCOMMAND_EXEC_END}'"; echo; printUsage "$0"
+    			    exit 2
+    			fi >&2
+    			shift
+    			sourceCommand+="${sourceCommand:+; }$cmd"
+    			;;
+	*)		break;;
+    esac
+done
 if [ -z "$sourceCommand" -o $# -lt 1 ]; then
     echo >&2 'ERROR: Need to pass GIT-COMMAND and SOURCE-COMMAND'
     exit 2
