git-unapply-index: BUG: Regression: Explicit check for staged changes failed to consider -- or <commit> (after 6cb39d91)
Do full command-line argument parsing, and for simplicity only accept a custom commit through -r|--revision REVISION; this is a rare use case, anyway.

(This corrects commit 6cb39d917fbdab870de0421914a440b61e14337b)

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.92.0 (2026-04-28), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-unapply-index b/bin/git-unapply-index
--- a/bin/git-unapply-index
+++ b/bin/git-unapply-index
@@ -9,18 +9,25 @@ revert in the working copy those changes that have been added to the index but
 not committed yet.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[<commit>] [--] [<pathspec>...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-r|--revision REVISION] [--] [<pathspec>...] [-?|-h|--help]'
 }
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
-			shift;;
-    --color)		shift; shift;;
-esac
+
+typeset -a revision=()
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--revision|-r)	shift; revision=("${1:?}"); shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
+
 
 if ! git-staged --quiet -- "$@"; then
     echo >&2 'ERROR: Nothing staged.'
     exit 1
 fi
 
-git diff --no-color --cached "$@" | git apply --reverse
+git diff --no-color --cached "${revision[@]}" -- "$@" | git apply --reverse
