FIX: Header with working copy name is printed even though no submodule
If the condition is false, we need to skip the switch statement, as it's status=0 will set didVisitSubmodules to true.

diff --git a/bin/git-ffintegrateto b/bin/git-ffintegrateto
--- a/bin/git-ffintegrateto
+++ b/bin/git-ffintegrateto
@@ -529,25 +529,29 @@ fi || {
 
 status=0
 didVisitSubmodules=
-[ ! "$isPushSubmodules" ] || pushSubmodules || status=$?
-case $status in
-    0)	didVisitSubmodules=t;;
-    99) # Still continue with the submodule branch deletion when there's no
-	# upstream configured.
-	;;
-    *)	# Any real push errors abort; don't continue with branch deletion.
-	exit $status;;
-esac
+if [ "$isPushSubmodules" ]; then
+    pushSubmodules || status=$?
+    case $status in
+	0)  didVisitSubmodules=t;;
+	99) # Still continue with the submodule branch deletion when there's no
+	    # upstream configured.
+	    ;;
+	*)  # Any real push errors abort; don't continue with branch deletion.
+	    exit $status;;
+    esac
+fi
 
-[ ! "$isDeleteMergedSubmoduleBranches" ] || deleteMergedSubmoduleBranches || status=$?
-case $status in
-    0)	didVisitSubmodules=t;;
-    99) # Still continue with the branch push when there's no upstream
-	# configured.
-	;;
-    *)	# Any real deletion errors abort; don't continue with branch push.
-	exit $status;;
-esac
+if [ "$isDeleteMergedSubmoduleBranches" ]; then
+    deleteMergedSubmoduleBranches || status=$?
+    case $status in
+	0)  didVisitSubmodules=t;;
+	99) # Still continue with the branch push when there's no upstream
+	    # configured.
+	    ;;
+	*)  # Any real deletion errors abort; don't continue with branch push.
+	    exit $status;;
+    esac
+fi
 
 [ ! "$isPushBranch" ] || pushBranch || {
     status=$?
