ENH: Also show the additional information on the merge commit that concludes a feature
git-flow doesn't integrate with my git-extensions, but fortunately I use the "git feat finish" alias where I can add my commit extension.

System-info: Ubuntu 24.04.2 LTS, x86_64
Platform-info: git version 2.49.0, hub version 2.14.2, gh version 2.69.0 (2025-03-19), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-feat-finish b/bin/git-feat-finish
--- a/bin/git-feat-finish
+++ b/bin/git-feat-finish
@@ -34,4 +34,8 @@ if targetBranch="$(git config --get gitflow.branch.develop)"; then
     git-mergecheck --merge-to "$targetBranch" || exit $?
 fi
 
-exec git flow feature finish "$@"
+git flow feature finish "$@" || exit $?
+
+[ ! -t 1 ] \
+    || git-commitInfo \
+    || exit 0  # Don't fail when there's a problem with the additional information; the commit is all that counts.
