git-rco: Usability: Detect erroneous -b|-B argument
As this would create a local branch named <remote>/<branch>, which is confusing and also difficult to undo. (Git complains with "fatal: ambiguous argument '...': unknown revision or path not in the working tree."; manual cleanup of .git/{config,branches,logs,refs} is needed.)

diff --git a/bin/git-rco b/bin/git-rco
--- a/bin/git-rco
+++ b/bin/git-rco
@@ -4,12 +4,15 @@ if [ $# -eq 0 ]; then
     echo >&2 "ERROR: Must pass remote and branch name"
     exit 2
 fi
-remote=$1; shift
+remote="$1"; shift
 
 if [ $# -eq 0 ]; then
-    echo >&2 "ERROR: Must pass branch name"
+    echo "ERROR: Must pass branch name"
     exit 2
-fi
+elif [[ "$1" = -[bB] ]]; then
+    echo "ERROR: Don't pass -b|-B; a branch will be created, anyway."
+    exit 2
+fi >&2
 branch=${!#}
 remoteBranch="${remote}/${branch:?}"
 
