Refactoring: Minor: Long parsing

diff --git a/bin/git-brname b/bin/git-brname
--- a/bin/git-brname
+++ b/bin/git-brname
@@ -14,11 +14,18 @@ HELPTEXT
 isRealBranchOnly=
 tagEmbellishment='(tag: %s)'
 detachedEmbellishment='(%s...)'
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --real-branch-only)	shift; isRealBranchOnly=t;;
-    --raw)		shift; tagEmbellishment='%s'; detachedEmbellishment='%s';;
-esac
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--real-branch-only)
+			shift; isRealBranchOnly=t;;
+	--raw)		shift; tagEmbellishment='%s'; detachedEmbellishment='%s';;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -ne 0 ]; then
     printUsage "$0" >&2
     exit 2
