XXX: "git oup" still doesn't update the fetchdate
When invoked through a Git alias, Git's own /usr/lib/git-core/git-fetch eclipses our wrapper.
Invoke with full path to our wrapper if the command might be invoked through a Git alias (i.e. for git-up, but git-ucatchup doesn't need this).
git-rco is only concerned with fetching a single branch, so instead of teaching our git-fetch wrapper to distinguish between full repo fetches and selected branches (possible by checking for <refspec>s after the <repository> arg), just drop the wrapping there for now.

diff --git a/bin/git-up b/bin/git-up
--- a/bin/git-up
+++ b/bin/git-up
@@ -121,7 +121,11 @@ if versionCompare "$GIT_VERSION" -lt 2.18 2>/dev/null; then
 fi
 
 if [ "$GIT_UP_FETCH" ]; then
-    git-fetch "$remote" || exit $?
+    # XXX: When invoked through a Git alias, Git's own
+    # /usr/lib/git-core/git-fetch eclipses our wrapper.
+    readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+    [ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+    "${scriptDir}/git-fetch" "$remote" || exit $?
 fi
 
 # Here, merges typically happen from the master / base branch to pick up
