Robustness: Parse --revision|-r / --branch|-b only once
And pass duplicated args along; there may be other nested git-*-command(s) that also require the argument. By doubling it we can now achieve that.

diff --git a/bin/git-showfiles-command b/bin/git-showfiles-command
--- a/bin/git-showfiles-command
+++ b/bin/git-showfiles-command
@@ -21,13 +21,18 @@ case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 esac
 
-commit='HEAD'
+revision=
 typeset -a args=()
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-	--revision|-r)	shift; commit="$1"; shift;;
+	--revision|-r)	if [ -n "$revision" ]; then
+			    args+=("$1" "$2"); shift; shift
+			else
+			    shift; revision="${1:?}"; shift
+			fi
+			;;
 	--)		args+=("$1"); shift; break;;
 	*)		args+=("$1"); shift;;
     esac
@@ -39,7 +44,7 @@ if [ $# -eq 0 ]; then
     exit 2
 fi
 
-readarray -t files < <(eval "${GIT_LASTFILES_COMMAND:-git-showfiles}" '"$commit"'; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+readarray -t files < <(eval "${GIT_LASTFILES_COMMAND:-git-showfiles}" '"${revision:-HEAD}"'; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
 [ ${files[-1]} -ne 0 ] && exit ${files[-1]}
 unset "files[$((${#files[@]}-1))]"
 [ -z "${files[-1]}" ] && unset "files[$((${#files[@]}-1))]"
