git-rbrurl-compare-to-base: ENH: Allow passing complete range, too
As many of our variants use rev-range-* to pass an existing range. We still need to convert HEAD into a rev and parse the range into the base and commmit constituents.

diff --git a/bin/git-rbrurl-compare-to-base b/bin/git-rbrurl-compare-to-base
--- a/bin/git-rbrurl-compare-to-base
+++ b/bin/git-rbrurl-compare-to-base
@@ -9,6 +9,8 @@ returned by BASE-COMMAND.
 HELPTEXT
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '--remote REMOTE --base BASE-COMMIT|--base-command BASE-COMMAND [--base-to-rev] [--short[=length]] [--commit-to-rev] [COMMIT] [-?|-h|--help]'
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" '--remote REMOTE --range RANGE'
 }
 
 remote=
@@ -28,6 +30,17 @@ do
 	--commit-to-rev)
 			shift; isNormalizeCommitRev=t;;
 	--short*)	revParseArgs+=("$1"); shift;;
+	--range)	shift
+			if ! [[ "$1" =~ ^([^.]*)\.{2,3}([^.]*)$ ]]; then
+			    printf 'ERROR: Not a range: %s\n' "$1"
+			    echo
+			    printUsage "$0"
+			    exit 2
+			fi >&2
+			base="${BASH_REMATCH[1]}"
+			commit="${BASH_REMATCH[2]}"
+			shift
+			;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
