git-localbr: Cosmetics: Move getBranches() to the usual position after the command-line argument parsing

diff --git a/bin/git-localbr b/bin/git-localbr
--- a/bin/git-localbr
+++ b/bin/git-localbr
@@ -11,6 +11,22 @@ current branch and master (and base branch if defined)).
 HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" '[--include-current] [--include-master] [--include-base] [--include-all] [--] [<glob> ...] [-?|-h|--help]'
 }
+
+typeset -a branchFilters=()
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	    shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
+			    shift;;
+	--color)	    shift; shift;;
+	--include-*)	    branchFilters+=("$1"); shift;;
+	--)		    shift; break;;
+	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		    break;;
+    esac
+done
+
 getBranches()
 {
     typeset -a localBranches=()
@@ -41,21 +57,6 @@ getBranches()
 	printf '%s\n' "${localBranches[@]}"
     fi
 }
-
-typeset -a branchFilters=()
-while [ $# -ne 0 ]
-do
-    case "$1" in
-	--help|-h|-\?)	    shift; printUsage "$0"; exit 0;;
-	--no-color|--color=*)
-			    shift;;
-	--color)	    shift; shift;;
-	--include-*)	    branchFilters+=("$1"); shift;;
-	--)		    shift; break;;
-	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)		    break;;
-    esac
-done
 
 getBranches "$@" | \
     git-filter-out-persistent-branches "${branchFilters[@]}"
