git-commitidentical: ENH: Allow referencing a commit in a different working copy
This is super cool for identical changes across submodules, because we can use the superproject / first submodule's commit and apply that to all (dirty) submodule repositories.
The syntax is similar to git-inside, so we can simply take the "git inside lo1 SHA -- PATH" from the git commit wrapper, and turn it into "git commitidentical SHA -- PATH".
git-commitlike inherits this new ability automatically; we still need to separately extend git-correct to get the same for git-commitrelate.

diff --git a/bin/git-commitidentical b/bin/git-commitidentical
--- a/bin/git-commitidentical
+++ b/bin/git-commitidentical
@@ -3,13 +3,20 @@
 printUsage()
 {
     cat <<HELPTEXT
-Commit directly (without further edits) with the same commit message as <commit>.
+Commit directly (without further edits) with the same commit message as <commit>
+[from the working copy that FILE or DIR resides in].
 This is similar to git commit -c|--reedit-message|-C|--reuse-message, but
 doesn't include authorship and timestamp as well.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[<commit-arguments> ...] <ref>|:/<pattern> [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[<commit-arguments> ...] <ref>|:/<pattern> [-- FILE|DIR] [-?|-h|--help]'
 }
+
+gitInWorkingCopy()
+{
+    git ${workingCopyFilespec:+inside} "$@" ${workingCopyFilespec:+-- "$workingCopyFilespec"}
+}
+
 typeset -a commitArgs=()
 while [ $# -ne 0 ]
 do
@@ -24,11 +31,18 @@ do
     esac
 done
 if [ $# -eq 0 ]; then
-    echo >&2 "ERROR: Must pass <commit>!"
+    echo >&2 'ERROR: Must pass <commit>!'
     exit 2
 fi
-ref="${!#}"
-commitId="$(git-commitid "$ref")" || exit $?
+lastArg="${!#}"
+workingCopyFilespec=
+if [ $# -gt 1 -a -e "$lastArg" -a "${*:(-2):1}" = '--' ]; then
+    workingCopyFilespec="$lastArg"
+    set -- "${@:1:$(($#-2))}"
+    lastArg="${!#}"
+fi
+
+commitId="$(gitInWorkingCopy commitid "$lastArg")" || exit $?
 
 commitMessageFilespec="$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || echo "${TEMP:-/tmp}/$(basename -- "$0").$$$RANDOM")"
 cleanup()
@@ -36,7 +50,7 @@ cleanup()
     rm -f "$commitMessageFilespec" 2>/dev/null
 }
 [ "$DEBUG" ] || trap 'cleanup' EXIT
-git lo1 "$commitId" > "$commitMessageFilespec" || exit $?
+gitInWorkingCopy lo1 "$commitId" > "$commitMessageFilespec" || exit $?
 if [ ! -s "$commitMessageFilespec" ]; then
     echo >&2 "ERROR: No commit message"
     exit 1
