FIX: Minor: Typo: $! instead of $?
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.87.3 (2026-02-23), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-reauthor b/bin/git-reauthor
--- a/bin/git-reauthor
+++ b/bin/git-reauthor
@@ -25,10 +25,10 @@ elif [ $# -ge 2 ] && ! [[ "$1" =~ @ ]] && [[ "$2" =~ ^[^\ ]+@[^\ ]+$ ]]; then
 else
     typeset -a candidateArgs=("$1")
 fi; shift
-author="$(git-whois --accept-unknown --select "${candidateArgs[@]}")" || exit $!
+author="$(git-whois --accept-unknown --select "${candidateArgs[@]}")" || exit $?
 
 if [ ! "$author" ]; then
-    echo >&2 "ERROR: No author!"
+    echo >&2 'ERROR: No author.'
     exit 1
 fi
 
