CHG: Renaming: clone[d]br to stack[d]br, pc.../...topc to ps.../tops
I found the "stacked branches" description at https://andrewlock.net/working-with-stacked-branches-in-git-is-easier-with-update-refs/ and like it!
Cloning is the low-level technical term (and I wasn't fully happy with that as there's overlap with the much more prominent "git clone" of repos).
It's better to describe this via the high-level end result: a stack of numbered branches that is supposed to be applied one after the other.

diff --git a/bin/git-stackedbranch-command b/bin/git-stackedbranch-command
--- a/bin/git-stackedbranch-command
+++ b/bin/git-stackedbranch-command
@@ -1,13 +1,13 @@
 #!/bin/bash
 set -o pipefail
 
-: ${GIT_CLONEBR_SEPARATOR=-}
+: ${GIT_STACKBR_SEPARATOR=-}
 
 printUsage()
 {
     cat <<HELPTEXT
 Execute GIT-COMMAND with the branch name where next / previous existing OFFSET
-cloned branch is added to the appended ${GIT_CLONEBR_SEPARATOR}1 suffix
+stacked branch is added to the appended ${GIT_STACKBR_SEPARATOR}1 suffix
 - appended
 - replacing BRANCH argument(s) anywhere
 - replacing BRANCH in the following GIT-COMMAND and -(N-1) arguments
@@ -23,7 +23,7 @@ HELPTEXT
 }
 
 # Need to parse off -o|--offset, --exclude-base and -b|--branch from anywhere first.
-typeset -a clonedbranchesArgs=()
+typeset -a stackedbranchesArgs=()
 typeset -a allargs=()
 offset=
 branch=
@@ -31,7 +31,7 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-	--exclude-base)	clonedbranchesArgs+=("$1"); shift;;
+	--exclude-base)	stackedbranchesArgs+=("$1"); shift;;
 	--offset|-o)	shift; offset=${1:?}; shift;;
 	--branch|-b)	shift; branch="${1:?}"; shift;;
 	--)		allargs+=("$1"); shift; break;;
@@ -41,29 +41,29 @@ done
 set -- "${allargs[@]}"
 [ -n "$branch" ] || branch="$(git-brname --real-branch-only)" || exit $?
 
-clonedBranch=
-readarray -t branches < <(git-clonedbranches "${clonedbranchesArgs[@]}" ${branch:+--branch "$branch"})
+stackedBranch=
+readarray -t branches < <(git-stackedbranches "${stackedbranchesArgs[@]}" ${branch:+--branch "$branch"})
 branchIndex=$(index "$branch" "${branches[@]}") || { echo >&2 "Cannot find branch ${branch}."; exit 3; }
-let clonedBranchIndex=branchIndex+offset
-if [ $clonedBranchIndex -lt 0 ]; then
+let stackedBranchIndex=branchIndex+offset
+if [ $stackedBranchIndex -lt 0 ]; then
     if [ $branchIndex -eq 0 ]; then
-	printf >&2 'ERROR: No previous cloned branches available; cannot go back.\n'
+	printf >&2 'ERROR: No previous stacked branches available; cannot go back.\n'
     else
 	branchPlural=es; [ $branchIndex -eq 1 ] && branchPlural=
-	printf >&2 'ERROR: Only %d previous cloned branch%s available; first is %s; cannot go back %d branches.\n' $branchIndex "$branchPlural" "${branches[0]}" $((-1 * offset))
+	printf >&2 'ERROR: Only %d previous stacked branch%s available; first is %s; cannot go back %d branches.\n' $branchIndex "$branchPlural" "${branches[0]}" $((-1 * offset))
     fi
     exit 2
-elif [ $clonedBranchIndex -ge ${#branches[@]} ]; then
+elif [ $stackedBranchIndex -ge ${#branches[@]} ]; then
     if [ $branchIndex -eq $((${#branches[@]} - 1)) ]; then
-	printf >&2 'ERROR: No next cloned branches available; cannot go forward.\n'
+	printf >&2 'ERROR: No next stacked branches available; cannot go forward.\n'
     else
 	branchCnt=$((${#branches[@]} - branchIndex))
 	branchPlural=es; [ $branchCnt -eq 1 ] && branchPlural=
-	printf >&2 'ERROR: Only %d next cloned branch%s available; last is %s; cannot go forward %d branches.\n' $branchCnt "$branchPlural" "${branches[-1]}" $offset
+	printf >&2 'ERROR: Only %d next stacked branch%s available; last is %s; cannot go forward %d branches.\n' $branchCnt "$branchPlural" "${branches[-1]}" $offset
     fi
     exit 2
 fi
-clonedBranch="${branches[$clonedBranchIndex]}"
+stackedBranch="${branches[$stackedBranchIndex]}"
 
 isCountedAppend=
 case "$1" in
@@ -74,7 +74,7 @@ case "$1" in
 	typeset -a countedArgs=("${@:2:${countedArgNum}}")
 	set -- "${@:$((2 + countedArgNum))}"
 
-	countedArgs=("${countedArgs[@]//BRANCH/${clonedBranch}}")
+	countedArgs=("${countedArgs[@]//BRANCH/${stackedBranch}}")
 
 	[ "$isCountedAppend" ] \
 	    && exec git-wrapper "$@" "${countedArgs[@]}" \
@@ -82,9 +82,9 @@ case "$1" in
 	;;
     --keep-position)
 	shift
-	exec git-wrapper "${@//BRANCH/${clonedBranch}}"
+	exec git-wrapper "${@//BRANCH/${stackedBranch}}"
 	;;
     *)
-	exec git-wrapper "$@" "$clonedBranch"
+	exec git-wrapper "$@" "$stackedBranch"
 	;;
 esac
diff --git a/bin/git-stackedbranches b/bin/git-stackedbranches
--- a/bin/git-stackedbranches
+++ b/bin/git-stackedbranches
@@ -1,7 +1,7 @@
 #!/bin/bash
 set -o pipefail
 
-: ${GIT_CLONEBR_SEPARATOR=-}
+: ${GIT_STACKBR_SEPARATOR=-}
 
 printShortUsage()
 {
@@ -21,15 +21,15 @@ printLongUsage()
     # This is the long "man page" when launched with the help argument.
     # It is printed to stdout to allow paging with 'more'.
     cat <<HELPDESCRIPTION
-List all branches that can be obtained from the current / passed branch by
-appending ${GIT_CLONEBR_SEPARATOR}1 (${GIT_CLONEBR_SEPARATOR}2, etc.) at the end of the branch name.
+List all stacked branches that can be obtained from the current / passed branch
+by appending ${GIT_STACKBR_SEPARATOR}1 (${GIT_STACKBR_SEPARATOR}2, etc.) at the end of the branch name.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
     echo
     cat <<HELPTEXT
     --exlude-base	Do not include the base branch (the branch without the
-			${GIT_CLONEBR_SEPARATOR}1 suffix).
+			${GIT_STACKBR_SEPARATOR}1 suffix).
 HELPTEXT
 }
 
@@ -53,11 +53,11 @@ if [ $# -ne 0 ]; then
 fi
 [ -n "$branch" ] || branch="$(git-brname --real-branch-only)" || exit $?
 
-[[ "$branch" =~ ^(.+)"${GIT_CLONEBR_SEPARATOR}"([[:digit:]]+)$ ]] \
+[[ "$branch" =~ ^(.+)"${GIT_STACKBR_SEPARATOR}"([[:digit:]]+)$ ]] \
     && branchBase="${BASH_REMATCH[1]}" \
     || branchBase="$branch"
 readarray -t branches < <(
-    git-localbr --include-all -- ${isIncludeBase:+"$branchBase"} "${branchBase}${GIT_CLONEBR_SEPARATOR}+([0-9])" \
+    git-localbr --include-all -- ${isIncludeBase:+"$branchBase"} "${branchBase}${GIT_STACKBR_SEPARATOR}+([0-9])" \
 	| sort --numeric-sort
 )
 
@@ -65,7 +65,7 @@ if [ ${#branches[@]} -eq 0 ]; then
     printf >&2 'ERROR: %s branch is no local branch: %s\n' "$branchOrigin" "$branch"
     exit 2
 elif [ ${#branches[@]} -eq 1 -a "${branches[0]}" = "$branchBase" ]; then
-    printf >&2 'ERROR: %s branch has no cloned branches; there is no %s1 suffix: %s\n' "$branchOrigin" "$GIT_CLONEBR_SEPARATOR" "${branches[0]}"
+    printf >&2 'ERROR: %s branch has no stacked branches; there is no %s1 suffix: %s\n' "$branchOrigin" "$GIT_STACKBR_SEPARATOR" "${branches[0]}"
     exit 1
 fi
 printf '%s\n' "${branches[@]}"
diff --git a/bin/git-stackedbrdo b/bin/git-stackedbrdo
--- a/bin/git-stackedbrdo
+++ b/bin/git-stackedbrdo
@@ -2,18 +2,18 @@
 set -o pipefail
 shopt -qs extglob
 
-: ${GIT_CLONEBR_SEPARATOR=-}
+: ${GIT_STACKBR_SEPARATOR=-}
 
 printUsage()
 {
     git-localbrdo --help 2>&1 | sed \
-	-e "1s#^.*\$#Check out all branches that can be obtained from the current / passed branch by appending ${GIT_CLONEBR_SEPARATOR}1 (${GIT_CLONEBR_SEPARATOR}2, etc.) at the end of the branch name one by one and execute \"git SIMPLECOMMAND\" and/or COMMANDLINE on each branch.#" \
+	-e "1s#^.*\$#Check out all stacked branches that can be obtained from the current / passed branch by appending ${GIT_STACKBR_SEPARATOR}1 (${GIT_STACKBR_SEPARATOR}2, etc.) at the end of the branch name one by one and execute \"git SIMPLECOMMAND\" and/or COMMANDLINE on each branch.#" \
 	-e '2b removeFirstParagraphLoop' \
 	-e '/^ *\(--include-current\|--include-master\|--include-base\|--include-all\|--branches BRANCH \[\.\.\.\] ;\)/b removeOptionLoop' \
 	-e '/^ *--no-pager/i\
     --branch|-b BRANCH	Use BRANCH instead of the current branch.\
     --exclude-base	Do not include the base branch (the branch without the\
-			${GIT_CLONEBR_SEPARATOR}1 suffix).\
+			${GIT_STACKBR_SEPARATOR}1 suffix).\
     --reverse		Iterate from highest offset to lowest.\
     --start-branch|-S N	Skip the first N branches.' \
 	-e '/^Usage:$/N' -e '/\(^\|\n\)Usage: */{ s/\(^\|\n\)\(Usage: *\)\?\([^ ]\+ \)*git-localbrdo /\1\2'"$(basename "$1")"' [-b|--branch BRANCH] [--exclude-base] [--reverse] [--start-branch|-S N] /; s/\[--include-current\] \[--include-master\] \[--include-base\] \[--include-all\] \[--branches BRANCH \[\.\.\.\] ;\]//; }' \
@@ -24,14 +24,14 @@ printUsage()
 
 isReverse=
 branchStartNum=
-typeset -a clonedbranchesArgs=()
+typeset -a stackedbranchesArgs=()
 typeset -a localbrdoArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-	--branch|-b)	clonedbranchesArgs+=("$1" "${2:?}"); shift; shift;;
-	--exclude-base) clonedbranchesArgs+=("$1"); shift;;
+	--branch|-b)	stackedbranchesArgs+=("$1" "${2:?}"); shift; shift;;
+	--exclude-base) stackedbranchesArgs+=("$1"); shift;;
 	--reverse)	shift; isReverse=t;;
 	--start-branch|-S)
 			shift; branchStartNum="${1:?}"; shift;;
@@ -40,7 +40,7 @@ do
     esac
 done
 
-readarray -t branches < <(eval 'git-clonedbranches "${clonedbranchesArgs[@]}"' "${isReverse:+| tac}"; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+readarray -t branches < <(eval 'git-stackedbranches "${stackedbranchesArgs[@]}"' "${isReverse:+| tac}"; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
 [ ${branches[-1]} -ne 0 ] && exit ${branches[-1]}
 unset 'branches[-1]'; [ -z "${branches[-1]}" ] && unset 'branches[-1]'
 
@@ -54,7 +54,7 @@ if [ -n "$branchStartNum" ]; then
 	    branchesPlural=es
 	    branchesAuxiliaryVerb=are
 	fi
-	printf >&2 'ERROR: There %s only %d cloned branch%s.\n' "$branchesAuxiliaryVerb" ${#branches[@]} "$branchesPlural"
+	printf >&2 'ERROR: There %s only %d stacked branch%s.\n' "$branchesAuxiliaryVerb" ${#branches[@]} "$branchesPlural"
 	exit 99
     fi
     branches=("${selectedBranches[@]}")
diff --git a/bin/hub-stackedbrpull-requesttops b/bin/hub-stackedbrpull-requesttops
--- a/bin/hub-stackedbrpull-requesttops
+++ b/bin/hub-stackedbrpull-requesttops
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-: ${GIT_CLONEBR_SEPARATOR=-}
+: ${GIT_STACKBR_SEPARATOR=-}
 
 printShortUsage()
 {
@@ -20,9 +20,9 @@ printLongUsage()
     # This is the long "man page" when launched with the help argument.
     # It is printed to stdout to allow paging with 'more'.
     cat <<HELPDESCRIPTION
-Create a series of GitHub pull requests for all branches that can be obtained
-from the current / passed branch by appending ${GIT_CLONEBR_SEPARATOR}1 (${GIT_CLONEBR_SEPARATOR}2, etc.) at the end of the
-branch name.
+Create a series of GitHub pull requests for all stacked branches that can be
+obtained from the current / passed branch by appending ${GIT_STACKBR_SEPARATOR}1 (${GIT_STACKBR_SEPARATOR}2, etc.) at the end
+of the branch name.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
@@ -30,11 +30,11 @@ HELPDESCRIPTION
     cat <<HELPTEXT
     --branch|-b BRANCH	Use BRANCH instead of the current branch.
     --exclude-base	Do not create a pull request for the base branch (the
-			branch without the ${GIT_CLONEBR_SEPARATOR}1 suffix).
+			branch without the ${GIT_STACKBR_SEPARATOR}1 suffix).
     --start-branch|-S N	Skip the first N branches.
 
 The first pull request is made against the default / passed BASE branch, all
-subsequent ones are drafts made against the previous cloned branch.
+subsequent ones are drafts made against the previous stacked branch.
 Branches with existing pull requests are skipped. An unclean exit of the editor
 gives the choice to skip just that branch or to abort the whole operation.
 
@@ -47,25 +47,25 @@ HELPTEXT
 }
 
 branchStartNum=
-typeset -a clonedbranchesArgs=()
+typeset -a stackedbranchesArgs=()
 typeset -a firstPullrequestArgs=()
 typeset -a pullrequestArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-	--branch|-b)	clonedbranchesArgs+=("$1" "${2:?}"); shift; shift;;
-	--exclude-base) clonedbranchesArgs+=("$1"); shift;;
+	--branch|-b)	stackedbranchesArgs+=("$1" "${2:?}"); shift; shift;;
+	--exclude-base) stackedbranchesArgs+=("$1"); shift;;
 	--start-branch|-S)
 			shift; branchStartNum="${1:?}"; shift;;
 	--base)		firstPullrequestArgs+=("$1" "${2:?}"); shift; shift;;
-	--head)		echo >&2 'ERROR: --head HEAD is not supported; use -b|--branch to specify the clone branch.'; exit 2;;
+	--head)		echo >&2 'ERROR: --head HEAD is not supported; use -b|--branch to specify the stacked branch.'; exit 2;;
 	--)		pullrequestArgs+=("$1"); shift; break;;
 	*)		pullrequestArgs+=("$1"); shift;;
     esac
 done
 
-readarray -t branches < <(eval 'git-clonedbranches "${clonedbranchesArgs[@]}"'; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+readarray -t branches < <(eval 'git-stackedbranches "${stackedbranchesArgs[@]}"'; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
 [ ${branches[-1]} -ne 0 ] && exit ${branches[-1]}
 unset 'branches[-1]'; [ -z "${branches[-1]}" ] && unset 'branches[-1]'
 
@@ -79,7 +79,7 @@ if [ -n "$branchStartNum" ]; then
 	    branchesPlural=es
 	    branchesAuxiliaryVerb=are
 	fi
-	printf >&2 'ERROR: There %s only %d cloned branch%s.\n' "$branchesAuxiliaryVerb" ${#branches[@]} "$branchesPlural"
+	printf >&2 'ERROR: There %s only %d stacked branch%s.\n' "$branchesAuxiliaryVerb" ${#branches[@]} "$branchesPlural"
 	exit 99
     fi
     branches=("${selectedBranches[@]}")
@@ -91,9 +91,9 @@ firstPullRequestExists()
     firstPullrequestArgs=()
 
     # Note: We could trivially implement this ourselves here as we have all the
-    # branches, but the hub-pull-requesttopc command already implements the
+    # branches, but the hub-pull-requesttops command already implements the
     # reference to the previous pull request for us.
-    prCommand=(hub-pull-requesttopc --draft --branch)
+    prCommand=(hub-pull-requesttops --draft --branch)
 }
 
 branchesPlural=es; [ ${#branches[@]} -eq 1 ] && branchesPlural=
