Robustness: Detect failure to revert the index changes and show necessary manual changes
This can happen when the changes to index and working copy overlap:
    $ echo first change >> file
    $ git addu
    $ echo second change >> file
    $ git stashi
    ERROR: The following reversals of the index failed and need to be applied manually (in reverse!):
    diff a/file b/file    (rejected hunks)
    @@ -1,3 +1,4 @@ it is good
    +first change

Obtain the changes via "git apply --reject", show them, and remove then already (presumably, only small changes would be applied manually, anyway; in case of huge conflicts the user would rather undo and choose a different approach), so that they don't pollute the working copy.

diff --git a/bin/git-stashi b/bin/git-stashi
--- a/bin/git-stashi
+++ b/bin/git-stashi
@@ -31,7 +31,21 @@ git stash apply 'stash@{1}' || exit $?
 
 # Create a temporary patch to reverse the originally staged changes and apply
 # it.
-git stash show -p | git apply -R
+status=0
+printf '\nRestoring working directory state by removing staged changes...\n'
+git stash show -p | git apply -R --reject || status=$?
 
 # Delete the temporary stash.
-git stash drop stash@{1}
+git stash drop --quiet 'stash@{1}'
+
+if [ $status -ne 0 ]; then
+    readarray -t rejectFilespecs < <(find . -name '*.rej' -mmin -1 -type f -print)
+    [ ${#rejectFilespecs[@]} -gt 0 ] || exit $status
+
+    printf >&2 '\nERROR: The following reversals of the index failed and need to be applied manually (in reverse!):\n'
+    type -t colordiff >/dev/null && [ -t 1 ] && hasColorDiff=t
+    eval 'cat "${rejectFilespecs[@]}"' "${hasColorDiff:+|}colordiff" && \
+	rm --force -- "${rejectFilespecs[@]}"
+
+    exit $status
+fi
