git-segregated-user-command: Consistency: Reimplementation: Explicitly parse known log arguments instead of parsing the git-*-command GIT-COMMAND args (cp. a0b9fe8b)
Right now, "dsta" is the only client, so the flaws of the previous implementation didn't surface here yet.

(This relates to commit a0b9fe8b803c1a3688065cbfc0704e794c76898d)

diff --git a/bin/git-segregated-user-command b/bin/git-segregated-user-command
--- a/bin/git-segregated-user-command
+++ b/bin/git-segregated-user-command
@@ -4,6 +4,12 @@ set -o noglob -o pipefail
 : ${GIT_SEGREGATEDUSERCOMMAND_PREFIX_SEPARATOR:=:}
 authorMarker='{}'   # Note: Internal use only, no need to be configurable.
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+source "${libDir}/logArgParser.sh" || exit 3
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
@@ -41,11 +47,11 @@ filter
     --no-git-color	Do not pass a --color=... to GIT-COMMAND.
     --committer		Use committers and pass --committer instead of --author
 			to GIT-COMMAND.
-    --with-log-args	All GIT-COMMAND arguments should also be used when
+    --with-log-args	All GIT-COMMAND log arguments should also be used when
 			determining the authors.
     --with-log-args-except-last
-			All GIT-COMMAND arguments expect the very last should
-			also be used when determining the authors.
+			All GIT-COMMAND log arguments expect the very last
+			should also be used when determining the authors.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
@@ -60,8 +66,9 @@ typeset -a colorArg=()
 filter=author
 subjectPlaceholder='%a'
 contextCommand=
-isFirstArg=t
 withLogArgs=
+typeset otherArgs=()
+typeset -a logArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -81,9 +88,24 @@ do
 			shift; withLogArgs=all;;
 	--with-log-args-except-last)
 			shift; withLogArgs=except-last;;
-	*)		break;;
+	--)		break;;
+	*)		if { [ "$withLogArgs" = all ] || [ "$withLogArgs" = except-last -a $# -gt 1 ]; } \
+			    && { countLogArgs '' "$1"; argCount=$?; [ $argCount -gt 0 ]; }
+			then
+			    while ((argCount-- > 0))
+			    do
+				logArgs+=("$1")
+				otherArgs+=("$1")
+				shift
+			    done
+			else
+			    otherArgs+=("$1")
+			    shift
+			fi
+			;;
     esac
 done
+set -- "${otherArgs[@]}" "$@"
 if [ $# -eq 0 ]; then
     echo >&2 'ERROR: No GIT-COMMAND passed.'
     exit 2
@@ -126,12 +148,6 @@ case "$1" in
 	;;
 esac
 
-typeset sharedLogArgs=()
-case "$withLogArgs" in
-    all)	    sharedLogArgs+=("$@");;
-    except-last)    [ $# -eq 0 ] || sharedLogArgs+=("${@:1:$(($#-1))}");;
-esac
-
 # With piping into withHeader / pager, we need to explicitly enable color for
 # Git, unless this command's output itself is redirected. Also don't do this if
 # the user explicitly turned off color.
@@ -154,7 +170,7 @@ do
     esac
 done
 
-readarray -t authors < <(git log --pretty="tformat:${subjectPlaceholder}N" "${sharedLogArgs[@]}" | sort --unique)
+readarray -t authors < <(git log --pretty="tformat:${subjectPlaceholder}N" "${logArgs[@]}" | sort --unique)
 [ ${#authors[@]} -gt 0 ] || exit 99
 
 iterateUsers()
@@ -167,4 +183,5 @@ iterateUsers()
     return $status
 }
 
-eval 'iterateUsers "$@"' "${pager:+|}" '"${pager[@]}"'
+eval 'iterateUsers "$@"' \
+    "${pager:+|}" '"${pager[@]}"'
