git-reintegrate: BUG: Cosmetics: Plural not interpolated; echo → printf

diff --git a/bin/git-reintegrate b/bin/git-reintegrate
--- a/bin/git-reintegrate
+++ b/bin/git-reintegrate
@@ -547,7 +547,7 @@ case $status in
 	# configured.
 	;;
     *)	# Any real push errors abort; don't continue with branch deletion.
-	echo >&2 'Push of the merged branch%s failed.' "$branchesPlural"
+	printf >&2 'Push of the merged branch%s failed.\n' "$branchesPlural"
 	if [ ${#branches[@]} -eq 1 ] \
 	    && contains --ff-only "${allArgs[@]}" \
 	    && contains --no-checks "${allArgs[@]}"
