git-addn: Documentation: Highlight that this is about FILEGLOBs
There are subtle differences in the glob that gets evaluated by a switch statement (can wrap in @(...) even if there's no globbing character, works across / boundary) and a real file glob. For the latter, we really need to use eval, and yet special shell characters (that had been properly escaped) are fine.

diff --git a/bin/git-addn b/bin/git-addn
--- a/bin/git-addn
+++ b/bin/git-addn
@@ -5,10 +5,10 @@ printUsage()
 {
     cat <<HELPTEXT
 Add all modified and deleted files except those matching FILE(s) or the escaped
-GLOB(s). Like addu, but with inverted meaning of the file arguments.
+FILE-GLOB(s). Like addu, but with inverted meaning of the file arguments.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" "FILE|'GLOB' [...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "FILE|'FILE-GLOB' [...] [-?|-h|--help]"
 }
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
@@ -33,7 +33,7 @@ noMatchFor()
 }
 
 if [ $# -eq 0 ]; then
-    echo >&2 'ERROR: Must pass at least one FILE / escaped GLOB to not add!'
+    echo >&2 'ERROR: Must pass at least one FILE / escaped FILE-GLOB to not add!'
     exit 2
 fi
 
