Adapt: Replace filterAge invocation and its hard-coded parameters with datediff delegation
The filterAge functionality has been included in datediff, which also supports the understands protocol to have its command-line argument parsing (and usage help) delegated to it.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.92.0 (2026-04-28), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-brage b/bin/git-brage
--- a/bin/git-brage
+++ b/bin/git-brage
@@ -1,11 +1,16 @@
 #!/bin/bash
 set -o pipefail
 
+filterAge()
+{
+    datediff --field-separator $'\t' "$@"
+}
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--bare|-l|--long] [-r|--remote REMOTE|-a] [-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]|DATE] [--] [<branch-glob> ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[--bare|-l|--long] [-r|--remote REMOTE|-a] [$(filterAge --get-short-usage filter 2>/dev/null)] [--] [<branch-glob> ...] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -33,11 +38,8 @@ HELPDESCRIPTION
     -r			List remote-tracking branches.
     --remote REMOTE	List a particular REMOTE.
     -a			List both local and remote-tracking branches.
-    -n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]|DATE
-			Only print those branches that match the age comparison.
-SUFFIX may be 's' for seconds (the default), 'm' for minutes, 'h' for hours, 'd'
-for days, 'w' for weeks, 'mo' for months, 'y' for years, 'g' for generations.
 HELPTEXT
+    filterAge --get-long-usage filter 'branches' 2>/dev/null
 }
 
 typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS)
@@ -71,10 +73,20 @@ do
 			    additionalBranchFilters+=(-e $'\t'"${remote}\$")
 			done < <(git remote)
 			;;
-	-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt)
-			postAction=(filterAge --field-separator $'\t' "$1" "$2"); shift; shift; prefixRefFormat='%(committerdate:unix)';;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	-*)		if argCount=$(filterAge --understand-for filter --understands "$@"); then
+			    [ ${#postAction[@]} -gt 0 ] || postAction=(filterAge --filter)
+			    while ((argCount-- > 0))
+			    do
+				postAction+=("$1"); shift
+			    done
+			    prefixRefFormat='@%(committerdate:unix)'
+			elif [ $? -eq 2 ]; then
+			    exit 2
+			else
+			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2
+			fi
+			;;
 	*)		break;;
     esac
 done
@@ -91,4 +103,7 @@ branchAge()
 	grep --invert-match -e '/HEAD$' "${additionalBranchFilters[@]}"
 }
 
-eval 'branchAge "$@"' "${postAction:+|}" '"${postAction[@]}"' "${formatter:+|}" '"${formatter[@]}"' "${pager:+|}" '"${pager[@]}"'
+eval 'branchAge "$@"' \
+    "${postAction:+|}" '"${postAction[@]}"' \
+    "${formatter:+|}" '"${formatter[@]}"' \
+    "${pager:+|}" '"${pager[@]}"'
diff --git a/bin/git-brc b/bin/git-brc
--- a/bin/git-brc
+++ b/bin/git-brc
@@ -2,11 +2,16 @@
 set -o pipefail
 shopt -qs globstar # ** matches files and/only (as **/) subdirs recursively.
 
+filterAge()
+{
+    datediff --field-separator $'\t' "$@"
+}
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--bare|-l|--long] [-r|-a] [-b|--base <branch>] [-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]|DATE] [--] [<branch-glob> ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[--bare|-l|--long] [-r|-a] [-b|--base <branch>] [$(filterAge --get-short-usage filter 2>/dev/null)] [--] [<branch-glob> ...] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -36,10 +41,9 @@ HELPDESCRIPTION
 			(also by remotes)) is used as the merge base.
     -r			List remote-tracking branches.
     -a			List both local and remote-tracking branches.
-    -n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]|DATE
-			Only print those branches that match the age comparison.
-SUFFIX may be 's' for seconds (the default), 'm' for minutes, 'h' for hours, 'd'
-for days, 'w' for weeks, 'mo' for months, 'y' for years, 'g' for generations.
+HELPTEXT
+    filterAge --get-long-usage filter 'branches' 2>/dev/null
+    cat <<HELPTEXT
     <branch-glob>	Only consider branches that match <branch-glob>.
 HELPTEXT
 }
@@ -47,8 +51,8 @@ HELPTEXT
 locality='local'
 base=
 isBare=
-format='%at	%ai	(%ar)'
-typeset -a filterAction=(sed -e 's/^[^\t]*\t//')
+format='@%at	%ai	(%ar)'
+typeset -a filterAction=()
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -60,14 +64,24 @@ do
 	--all|-a)	shift; locality='all';;
 	--remote|-r)	shift; locality='remote';;
 	--base|-b)	shift; base="$1"; shift;;
-	--bare)		shift; isBare=t; format='%at';;
-	-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt)
-			filterAction=(filterAge --field-separator $'\t' "$1" "$2"); shift; shift;;
+	--bare)		shift; isBare=t; format='@%at';;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	-*)		if argCount=$(filterAge --understand-for filter --understands "$@"); then
+			    [ ${#filterAction[@]} -gt 0 ] || filterAction=(filterAge --filter)
+			    while ((argCount-- > 0))
+			    do
+				filterAction+=("$1"); shift
+			    done
+			elif [ $? -eq 2 ]; then
+			    exit 2
+			else
+			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2
+			fi
+			;;
 	*)		break;;
     esac
 done
+[ ${#filterAction[@]} -gt 0 ] || filterAction=(sed -e 's/^[^\t]*\t//')
 typeset -a what=()
 [ $# -gt 0 ] || set -- ''
 for branchGlob
@@ -108,6 +122,8 @@ fi
 
 # Print the sorted information without the leading Unix timestamp used as the
 # sort key.
-printf '%s\n' "${firstCommits[@]}" | \
-    sort --numeric-sort | \
-    eval '"${filterAction[@]}"' "${formatter:+|}" '"${formatter[@]}"' "${pager:+|}" '"${pager[@]}"'
+printf '%s\n' "${firstCommits[@]}" \
+    | sort --numeric-sort \
+    | eval '"${filterAction[@]}"' \
+	"${formatter:+|}" '"${formatter[@]}"' \
+	"${pager:+|}" '"${pager[@]}"'
diff --git a/bin/git-localbr b/bin/git-localbr
--- a/bin/git-localbr
+++ b/bin/git-localbr
@@ -2,11 +2,16 @@
 set -o pipefail
 shopt -qs extglob
 
+filterAge()
+{
+    datediff --field-separator $'\t' "$@"
+}
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--include-current] [--include-master] [--include-base] [--include-all] [-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]|DATE] [--sort <key> [--sort ...]] [--] [<branch-glob> ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[--include-current] [--include-master] [--include-base] [--include-all] [$(filterAge --get-short-usage filter 2>/dev/null)] [--sort <key> [--sort ...]] [--] [<branch-glob> ...] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -27,18 +32,15 @@ HELPDESCRIPTION
     echo
     printShortUsage "$1"
     echo
+    filterAge --get-long-usage filter 'branches' 2>/dev/null
     cat <<HELPTEXT
-    -n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]|DATE
-			Only print those branches that match the age comparison.
-SUFFIX may be 's' for seconds (the default), 'm' for minutes, 'h' for hours, 'd'
-for days, 'w' for weeks, 'mo' for months, 'y' for years, 'g' for generations.
     <branch-glob>	Only consider branches that match <branch-glob>.
 HELPTEXT
 }
 
 typeset -a sortArgs=()
 typeset -a branchFilters=()
-typeset -a filterAction=(sed -e 's/^[^\t]*\t//')
+typeset -a filterAction=()
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -53,18 +55,28 @@ do
 	--include-*)	branchFilters+=("$1"); shift;;
 	--sort)		sortArgs+=("$1" "$2"); shift; shift;;
 	--sort=*)	sortArgs+=("$1"); shift;;
-	-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt)
-			filterAction=(filterAge --field-separator $'\t' "$1" "$2"); shift; shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	-*)		if argCount=$(filterAge --understand-for filter --understands "$@"); then
+			    [ ${#filterAction[@]} -gt 0 ] || filterAction=(filterAge --filter)
+			    while ((argCount-- > 0))
+			    do
+				filterAction+=("$1"); shift
+			    done
+			elif [ $? -eq 2 ]; then
+			    exit 2
+			else
+			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2
+			fi
+			;;
 	*)		break;;
     esac
 done
+[ ${#filterAction[@]} -gt 0 ] || filterAction=(sed -e 's/^[^\t]*\t//')
 
 getBranchRecords()
 {
     typeset -a localBranchRecords=()
-    readarray -t localBranchRecords < <(git for-each-ref "${sortArgs[@]:---sort=committerdate}" --format=$'%(committerdate:unix)\t%(refname:short)' refs/heads/)
+    readarray -t localBranchRecords < <(git for-each-ref "${sortArgs[@]:---sort=committerdate}" --format=$'@%(committerdate:unix)\t%(refname:short)' refs/heads/)
     [ ${#localBranchRecords[@]} -gt 0 ] || return 1
 
     if [ $# -gt 0 ]; then
diff --git a/bin/git-rbr b/bin/git-rbr
--- a/bin/git-rbr
+++ b/bin/git-rbr
@@ -2,16 +2,42 @@
 set -o pipefail
 shopt -qs extglob
 
+filterAge()
+{
+    datediff --field-separator $'\t' "$@"
+}
+
+printShortUsage()
+{
+    # Note: short followed by long option; if the user knows the short one, she can
+    # skim the long one.
+    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE|''} [$(filterAge --get-short-usage filter 2>/dev/null)] [--sort <key> [--sort ...]] [--] [<branch-glob> ...] [-?|-h|--help]"
+}
 printUsage()
 {
-    cat <<HELPTEXT
-List all branches in ${remote:-REMOTE / all remotes} [matching <branch-glob>].
-HELPTEXT
-    echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE|''} [-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]|DATE] [--sort <key> [--sort ...]] [--] [<branch-glob> ...] [-?|-h|--help]"
+    # This is the short help when launched with no or incorrect arguments.
+    # It is printed to stderr to avoid accidental processing.
+    printShortUsage "$1" >&2
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
+printLongUsage()
+{
+    # This is the long "man page" when launched with the help argument.
+    # It is printed to stdout to allow paging with 'more'.
+    cat <<HELPDESCRIPTION
+List all branches in ${remote:-REMOTE / all remotes} [matching <branch-glob>].
+HELPDESCRIPTION
+    echo
+    printShortUsage "$1"
+    echo
+    filterAge --get-long-usage filter 'branches' 2>/dev/null
+    cat <<HELPTEXT
+    <branch-glob>	Only consider branches that match <branch-glob>.
+HELPTEXT
+}
+
 case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+    --help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
     --no-color|--color=*)
 			shift;;
     --color)		shift; shift;;
@@ -21,14 +47,14 @@ if [ $# -eq 0 ]; then
     echo >&2 'ERROR: Must pass REMOTE.'
     exit 2
 fi
-remote="$1"; shift
+remote="${1:?}"; shift
 
 typeset -a branchArgs=()
 postProcessingAction=
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--no-color|--color=*)
 			shift;;
 	--color)	shift; shift;;
@@ -36,11 +62,20 @@ do
 			branchArgs+=("$1" "$2"); shift; shift;;
 	--@(merged|no-merged|contains|no-contains|points-at|sort)=*)
 			branchArgs+=("$1"); shift;;
-	-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt)
-			printf -v postProcessingAction 'augmentLines --prepend -- git log --max-count 1 --pretty=tformat:%%ct | filterAge --field-separator %q %q %q' $'\t' "$1" "$2"
-			shift; shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	-*)		if argCount=$(filterAge --understand-for filter --understands "$@"); then
+			    [ -n "$postProcessingAction" ] || postProcessingAction='augmentLines --prepend -- git log --max-count 1 --pretty=tformat:@%ct | filterAge --filter'
+			    while ((argCount-- > 0))
+			    do
+				printf -v quotedArg ' %q' "$1"
+				postProcessingAction+="$quotedArg"; shift
+			    done
+			elif [ $? -eq 2 ]; then
+			    exit 2
+			else
+			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2
+			fi
+			;;
 	*)		break;;
     esac
 done
@@ -51,4 +86,5 @@ remoteBranchQuery()
     git branch "${branchArgs[@]}" --remotes --list --format '%(refname:lstrip=2)' "${@/#/${remote}${remote:+/}}" \
 	| sed -e "/^${remote:-[^/]\\+}\/HEAD$/d"
 }
-eval 'remoteBranchQuery "$@"' "${postProcessingAction:+|}$postProcessingAction"
+eval 'remoteBranchQuery "$@"' \
+    "${postProcessingAction:+|}$postProcessingAction"
diff --git a/bin/git-tagage b/bin/git-tagage
--- a/bin/git-tagage
+++ b/bin/git-tagage
@@ -1,11 +1,16 @@
 #!/bin/bash
 set -o pipefail
 
+filterAge()
+{
+    datediff --field-separator $'\t' "$@"
+}
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-r|--resolve] [--bare|-l|--long] [-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]|DATE] [--] [<tag-glob> ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[-r|--resolve] [--bare|-l|--long] [$(filterAge --get-short-usage filter 2>/dev/null)] [--] [<tag-glob> ...] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -29,11 +34,8 @@ HELPDESCRIPTION
 			creation date.
     --bare		Just print the tag names.
     --long|-l		Also print the tag[ged commit]'s author name.
-    -n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]|DATE
-			Only print those tags that match the age comparison.
-SUFFIX may be 's' for seconds (the default), 'm' for minutes, 'h' for hours, 'd'
-for days, 'w' for weeks, 'mo' for months, 'y' for years, 'g' for generations.
 HELPTEXT
+    filterAge --get-long-usage filter 'tags' 2>/dev/null
 }
 
 typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS)
@@ -64,19 +66,31 @@ do
 			additionalLogMassaging=(-e 's/^[^\t]\+\t//' -e 's/, /\n/g')    # Need to remove the ISO date required for sorting, and unjoin multiple "TAG1, TAG2" lists.
 			;;
 	--long|-l)	shift; additionalLogFormat='%aN'; additionalRefFormat='%(authorname)%(*authorname)';;
-	-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt)
-			postAction=(filterAge --field-separator $'\t' "$1" "$2"); shift; shift; prefixLogFormat='%ct'; prefixRefFormat='%(creatordate:unix)';;
 	--)		tagArgs+=("$1"); shift; break;;
+	-*)		if argCount=$(filterAge --understand-for filter --understands "$@"); then
+			    [ ${#postAction[@]} -gt 0 ] || postAction=(filterAge --filter)
+			    while ((argCount-- > 0))
+			    do
+				postAction+=("$1"); shift
+			    done
+			    prefixLogFormat='@%ct'; prefixRefFormat='@%(creatordate:unix)'
+			elif [ $? -eq 2 ]; then
+			    exit 2
+			else
+			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2
+			fi
+			;;
 	*)		tagArgs+=("$1"); shift;;
     esac
 done
 
 ageByCommit()
 {
-    git tag --list --format='%(refname)' "$@" | \
-	xargs --no-run-if-empty --delimiter '\n' -n 1 git log --max-count 1 --pretty=tformat:"${prefixLogFormat}${prefixLogFormat:+\\t}%ci	${isInfo:+(%cr}${additionalLogFormat:+, }${additionalLogFormat}${isInfo:+)	}%D${isInfo:+: %s}" | \
-	sort --numeric-sort | \
-	sed -e 's/\(\t\|, \)tag: /\1/g' "${additionalLogMassaging[@]}"
+    git tag --list --format='%(refname)' "$@" \
+	| xargs --no-run-if-empty --delimiter '\n' -n 1 \
+	    git log --max-count 1 --pretty=tformat:"${prefixLogFormat}${prefixLogFormat:+$'\t'}%ci"$'\t'"${isInfo:+(%cr}${additionalLogFormat:+, }${additionalLogFormat}${isInfo:+)$'\t'}%D${isInfo:+: %s}" \
+	| sort --numeric-sort \
+	| sed -e 's/\(\t\|, \)tag: /\1/g' "${additionalLogMassaging[@]}"
 }
 
 ageByCreation()
@@ -84,4 +98,7 @@ ageByCreation()
     git tag --list --sort=creatordate --format="${prefixRefFormat}${prefixRefFormat:+%09}${isInfo:+%(creatordate:iso)%09(%(creatordate:relative)}${additionalRefFormat:+, }${additionalRefFormat}${isInfo:+)%09}%(refname:short)" "$@"
 }
 
-eval '$action "${tagArgs[@]}" "$@"' "${postAction:+|}" '"${postAction[@]}"' "${formatter:+|}" '"${formatter[@]}"' "${pager:+|}" '"${pager[@]}"'
+eval '$action "${tagArgs[@]}" "$@"' \
+    "${postAction:+|}" '"${postAction[@]}"' \
+    "${formatter:+|}" '"${formatter[@]}"' \
+    "${pager:+|}" '"${pager[@]}"'
