CHG: Renaming: invertstage to swapstage
Though "invert" precisely describes the effect, I'm associating this more with the "swap" action. Also fits better with the other swap* commands.

diff --git a/bin/git-swapstage b/bin/git-swapstage
--- a/bin/git-swapstage
+++ b/bin/git-swapstage
@@ -24,7 +24,7 @@ case "$1" in
 esac
 
 if git-existsbr _invert; then
-    echo >&2 "ERROR: It looks like a git-swaplast is under way. Please finalize that first (via --continue|--quit|--abort|--cleanup)."
+    echo >&2 'ERROR: It looks like a git-swaplast is under way. Please finalize that first (via --continue|--quit|--abort|--cleanup).'
     exit 1
 fi
 
