Cosmetics: FIX: Indent
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.96.0 (2026-07-02), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-mergecheck b/bin/git-mergecheck
--- a/bin/git-mergecheck
+++ b/bin/git-mergecheck
@@ -41,19 +41,19 @@ do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--no-color|--color=*)
-    			shift;;
-	--color)		shift; shift;;
-	--merge-to)		shift
-    			if [ ${#sourceBranches[@]} -gt 0 ]; then
-    			    echo 'ERROR: --merge-to TARGET-BRANCH can be given only once.'
-    			    echo
-    			    printUsage "$0"
-    			    exit 2
-    			fi >&2
-    			sourceBranches=("$(git-brname --real-branch-only 2>/dev/null)")
-    			branches+=("${1:?}"); shift
-    			branchFormat='%s..'
-    			;;
+			shift;;
+	--color)	shift; shift;;
+	--merge-to)	shift
+			if [ ${#sourceBranches[@]} -gt 0 ]; then
+			    echo 'ERROR: --merge-to TARGET-BRANCH can be given only once.'
+			    echo
+			    printUsage "$0"
+			    exit 2
+			fi >&2
+			sourceBranches=("$(git-brname --real-branch-only 2>/dev/null)")
+			branches+=("${1:?}"); shift
+			branchFormat='%s..'
+			;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
