git-brc: Refactoring: Use array for what
To prevent problems with the unquoted use.

diff --git a/bin/git-brc b/bin/git-brc
--- a/bin/git-brc
+++ b/bin/git-brc
@@ -30,12 +30,12 @@ do
 done
 dirBranchGlob="${1//\*/*/**}"    # As we're doing file system lookup, a branch name glob needs to be converted into a directory hierarchy one in case the branch name contains slashes.
 case $locality in
-    local)  what="refs/heads/$1 refs/heads/$dirBranchGlob";;
-    all)    what="refs/heads/$1 refs/heads/$dirBranchGlob refs/remotes/$1 refs/remotes/$dirBranchGlob";;
-    remote) what="refs/remotes/$1 refs/remotes/$dirBranchGlob";;
+    local)  typeset -a what=("refs/heads/$1" "refs/heads/$dirBranchGlob");;
+    all)    typeset -a what=("refs/heads/$1" "refs/heads/$dirBranchGlob" "refs/remotes/$1" "refs/remotes/$dirBranchGlob");;
+    remote) typeset -a what=("refs/remotes/$1" "refs/remotes/$dirBranchGlob");;
 esac
 
-readarray -t branches < <(git for-each-ref --format='%(refname:short)' $what; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+readarray -t branches < <(git for-each-ref --format='%(refname:short)' "${what[@]}"; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
 [ ${branches[-1]} -ne 0 ] && exit ${branches[-1]}
 unset 'branches[-1]'
 [ -z "${branches[-1]}" ] && unset 'branches[-1]'
