git-cobr: Refactoring: Already check for passed <remote-branch>, shift that arg off $@

diff --git a/bin/git-cobr b/bin/git-cobr
--- a/bin/git-cobr
+++ b/bin/git-cobr
@@ -7,20 +7,25 @@ Checkout passed <remote-branch>, tracking it if it doesn't yet exist locally, or
 ensuring that an existing tracked branch doesn't contradict the request.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[<checkout-args> ...] [<remote-branch> [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[<checkout-args> ...] <remote-branch> [-?|-h|--help]'
 }
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 esac
-
-remoteBranch=; [ $# -gt 0 ] && remoteBranch=${!#}
+if [ $# -eq 0 ]; then
+    echo 'ERROR: No <remote-branch> passed!'
+    echo
+    printUsage "$0"
+    exit 2
+fi >&2
+remoteBranch="${!#}"; shift
+set -- "${@:1:$(($#-1))}"
 remote="${remoteBranch%%/*}"
 branch="${remoteBranch#*/}"
-
 if [ -z "$remote" -o -z "$branch" ]; then
-    echo >&2 'ERROR: No <remote-branch> passed!'
+    printf 'ERROR: Not a <remote-branch>: %s\n' "$remoteBranch"
     exit 2
-fi
+fi >&2
 
 if git-existsbr "$branch"; then
     trackedRemoteBranch="$(git-tracks "$branch" 2>/dev/null)"
@@ -38,7 +43,7 @@ if git-existsbr "$branch"; then
 	    printf >&2 'Note: The local branch is already tracking the corresponding branch in %s.\n' "$trackedRemote"
 	fi
     fi
-    git checkout "${@:1:$(($#-1))}" "$branch"
+    git checkout "$@" "$branch"
 else
-    git checkout --track "$@"
+    git checkout --track "$@" "$remoteBranch"
 fi
