git-wcdo-command: Usability: Mention how to abort iteration from interactive subshells

diff --git a/bin/git-wcdo-command b/bin/git-wcdo-command
--- a/bin/git-wcdo-command
+++ b/bin/git-wcdo-command
@@ -127,6 +127,7 @@ elif [ "${1:0:1}" != '-' ]; then
 	    wcdoArgs+=(--no-pager --no-header --no-git-color --abort-on 126 --command)
 	    if [ $# -eq 0 ]; then
 		wcdoArgs+=('git dirty && bash -i')
+		echo "Note: To abort the iteration of ${what:=CONFIGURED SUBJECTS}, use \"exit 126\"."
 	    else
 		printf -v quotedSimpleCommand '%q ' "$@"
 		wcdoArgs+=("git dirty && ${quotedSimpleCommand# }")
@@ -145,6 +146,7 @@ elif [ "${1:0:1}" != '-' ]; then
 	    quotedWipsArgs=; [ ${#wipsArgs[@]} -gt 0 ] && printf -v quotedWipsArgs '%q ' "${wipsArgs[@]}"
 	    if [ $# -eq 0 ]; then
 		wcdoArgs+=("git wips ${quotedWipsArgs}&& bash -i")
+		echo "Note: To abort the iteration of ${what:=CONFIGURED SUBJECTS}, use \"exit 126\"."
 	    else
 		printf -v quotedSimpleCommand '%q ' "$@"
 		wcdoArgs+=("git wips --quiet ${quotedWipsArgs}&& ${quotedSimpleCommand# }")
@@ -166,6 +168,7 @@ elif [ "${1:0:1}" != '-' ]; then
 	    wcdoArgs+=(--no-git-color)
 	    # Enable the user to abort the iteration via a special exit status.
 	    wcdoArgs+=(--abort-on 126)
+	    echo "Note: To abort the iteration of ${what:=CONFIGURED SUBJECTS}, use \"exit 126\"."
 	    ;;
 	browse|ci-status|compare|delete|pull-request|fork|release|sync)
 	    wcdoArgs+=(--single-success)
