git-showselected: ENH: Allow selection of the last commit without query with --last-only

diff --git a/bin/git-showselected b/bin/git-showselected
--- a/bin/git-showselected
+++ b/bin/git-showselected
@@ -1,15 +1,17 @@
 #!/bin/bash
+set -o pipefail
 shopt -qs extglob
 
 printUsage()
 {
     cat <<HELPTEXT
-Log together with diff [for FILE(s)] for the commit interactively chosen from
-the commits [that cover FILE ...] in the passed <range>.
+Log together with diff [for FILE(s)] for the commit interactively chosen / last
+commit from the commits [that cover FILE ...] in the passed <range>.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '--since <date>|--max-count <number>|-n <number>|<range> [<show-args> ...] [--] [FILE ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--last-only] --since <date>|--max-count <number>|-n <number>|<range> [<show-args> ...] [--] [FILE ...] [-?|-h|--help]'
 }
+
 typeset -a gitCommandArgs=()
 typeset -a files=()
 while [ $# -ne 0 ]
@@ -41,6 +43,7 @@ typeset -a rangeModificationArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
+	--last-only)	shift; action=getLast;;
 	--since)	rangeArgs+=("$1" "$2"); shift; shift;;
 	--max-count|-n)	rangeArgs+=("$1" "$2"); shift; shift;;
 	--max-count=*|-+([0-9]))
@@ -82,6 +85,16 @@ getSelected()
     elif [ $status -ne 0 ]; then
 	return $status
     fi
+}
+
+getLast()
+{
+    readarray -t commits < <(commitSource --pretty='tformat:%H')
+    if [ ${#commits[@]} -eq 0 ]; then
+	echo >&2 'ERROR: No commits available.'
+	return 1
+    fi
+    commits=("${commits[$((${#commits[@]}-1))]}")
 }
 
 $action || exit $?
