git-co[ot]: BUG: Rebasing not detected
Need to check both for merging or rebasing; that means that we cannot leverage the command's built-in error message, but need to provide our own.

diff --git a/bin/git-coo b/bin/git-coo
--- a/bin/git-coo
+++ b/bin/git-coo
@@ -23,7 +23,10 @@ do
 	*)		break;;
     esac
 done
-git-ismerging --print-negative-error || exit 1
+if ! git-ismerging && ! git-isrebasing; then
+    echo >&2 'ERROR: Not currently merging or rebasing.'
+    exit 1
+fi
 if [ "$isAll" ]; then
     if [ $# -gt 0 ]; then
 	printUsage "$0"
