git-rcolatest[c]: Documentation: FIX: <branch> is a <branch-glob>, not a pattern

diff --git a/bin/git-rcolatest b/bin/git-rcolatest
--- a/bin/git-rcolatest
+++ b/bin/git-rcolatest
@@ -9,7 +9,7 @@ Checkout local branch from latest (by sort order) passed ${remote:-REMOTE}
 [matching pattern].
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [<branch>] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [<branch-glob>] [-?|-h|--help]"
 }
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
@@ -17,7 +17,7 @@ esac
 
 
 if [ $# -eq 0 -o $# -gt 2 ]; then
-    echo >&2 "ERROR: Must pass remote and optionally branch pattern"
+    echo >&2 "ERROR: Must pass REMOTE and optionally <branch-glob>."
     exit 2
 fi
 
