FIX: Missing $branch argument to error message

diff --git a/bin/git-cobr b/bin/git-cobr
--- a/bin/git-cobr
+++ b/bin/git-cobr
@@ -37,7 +37,7 @@ if git-existsbr "$branch"; then
 	trackedRemote="${trackedRemoteBranch%%/*}"
 	trackedBranch="${trackedRemoteBranch#*/}"
 	if [ "$trackedBranch" != "$branch" ]; then
-	    printf >&2 'ERROR: An existing local branch %s is already tracking a differently named remote branch %s; will not switch to %s.\n' "$trackedRemoteBranch" "$remoteBranch"
+	    printf >&2 'ERROR: An existing local branch %s is already tracking a differently named remote branch %s; will not switch to %s.\n' "$branch" "$trackedRemoteBranch" "$remoteBranch"
 	    exit 1
 	elif [ "$trackedRemote" != "$remote" ]; then
 	    printf >&2 'Note: The local branch is already tracking the corresponding branch in %s.\n' "$trackedRemote"
