git-showselected: Refactoring: Extract getSelected()

diff --git a/bin/git-showselected b/bin/git-showselected
--- a/bin/git-showselected
+++ b/bin/git-showselected
@@ -35,6 +35,7 @@ if [ ${#files[@]} -eq 0 ]; then
 fi
 set -- "${gitCommandArgs[@]}"
 
+action=getSelected
 typeset -a rangeArgs=()
 typeset -a rangeModificationArgs=()
 while [ $# -ne 0 ]
@@ -62,21 +63,26 @@ commitSource()
     git log "$@" "${rangeModificationArgs[@]}" "${rangeArgs[@]}" ${files:+--} "${files[@]}"
 }
 
-readarray -t commits < <(
-    commitSource --pretty='tformat:%H %s' \
-	| truncate-trailing -w \
-	| commandWithHiddenId --stdin -p -c 'commandOnSelected --stdin'
-    printf '\n%d\n' "$?"
-)   # Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
-status=${commits[-1]}
-unset 'commits[-1]'
-[ -z "${commits[-1]}" ] && unset 'commits[-1]'
+typeset -a commits=()
+getSelected()
+{
+    readarray -t commits < <(
+	commitSource --pretty='tformat:%H %s' \
+	    | truncate-trailing -w \
+	    | commandWithHiddenId --stdin -p -c 'commandOnSelected --stdin'
+	printf '\n%d\n' "$?"
+    )   # Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+    local status=${commits[-1]}
+    unset 'commits[-1]'
+    [ -z "${commits[-1]}" ] && unset 'commits[-1]'
 
-if [ $status -eq 124 ]; then
-    echo >&2 'ERROR: No commits available.'
-    exit 1
-elif [ $status -ne 0 ]; then
-    exit $status
-fi
+    if [ $status -eq 124 ]; then
+	echo >&2 'ERROR: No commits available.'
+	return 1
+    elif [ $status -ne 0 ]; then
+	return $status
+    fi
+}
 
+$action || exit $?
 exec git-wrapper ${GIT_SHOWSELECTED_COMMAND:-show} "$@" "${commits[@]}" ${files:+--} "${files[@]}"
