git-cat: ENH: Consistency: Use pager for multiple <pathspec>...
Like git-annotate and git-lcl.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.96.0 (2026-07-02), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-cat b/bin/git-cat
--- a/bin/git-cat
+++ b/bin/git-cat
@@ -1,34 +1,68 @@
 #!/bin/bash
+set -o pipefail
+shopt -qs nullglob
 
 printUsage()
 {
     cat <<HELPTEXT
-Retrieve the contents of <pathspec> as it exists in revision <ref>.
+Retrieve the contents of <pathspec> as it exists in <revision>.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '<ref> [--] <pathspec>... [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '<revision> [--] <pathspec>... [-?|-h|--help]'
 }
 
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
+typeset -a allargs=()
+unset files
+revision=
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-esac
-if [ $# -lt 2 ]; then
+	--color)	shift; shift;;
+	--)		shift; typeset -a files=("$@"); set --; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		if [ -z "$revision" ]; then
+			    revision="${1:?}"; shift
+			else
+			    break
+			fi
+			;;
+    esac
+done
+if [ -z "${files+t}" ]; then
+    # No files after -- captured yet; need to investigate parsed and
+    # remaining args from behind for files.
+    typeset -a files=()
+    allargs+=("$@")
+    while [ ${#allargs[@]} -ne 0 ]
+    do
+	lastArg="${allargs[-1]}"
+	[ -e "$lastArg" ] || break
+
+	if [ -d "$lastArg" ]; then
+	    readarray -t containedFiles < <(git-ls --recursive --only-files -- "$lastArg")
+	    files=("${containedFiles[@]}" "${files[@]}")
+	else
+	    files=("$lastArg" "${files[@]}")
+	fi
+	allargs=("${allargs[@]:0:${#allargs[@]}-1}")
+    done
+fi
+if [ -z "$revision" ]; then
+    echo 'ERROR: No <revision> passed.'
+    echo
     printUsage "$0"
     exit 2
-fi
+fi >&2
 
-
-ref="$1"; shift
-[ "$1" = -- ] && shift
-commitId=$(git-commitid "$ref") || exit $?
+commitId=$(git-commitid "$revision") || exit $?
 readarray -t submodules < <(git-sublist --revision "$commitId")
 
-status=0
-for path
-do
+catFile()
+{
+    local path="${1:?}"; shift
     for submodule in "${submodules[@]}"
     do
 	if [[ "${path}/" =~ ^"${submodule}/"(.*)/$ ]]; then
@@ -36,12 +70,35 @@ do
 	    # inside that submodule and do a single recursive call with all of
 	    # them, but this will likely be used mostly with single files,
 	    # anyway.
-	    submoduleRef="$(git-subhash "$ref" "$submodule")" || { status=$?; continue 2; }
-	    (cd "$submodule" && exec "${BASH_SOURCE[0]}" "$submoduleRef" "${BASH_REMATCH[1]}") || status=$?
-	    continue 2
+	    # Another benefit of this implementation is that the tempfile collection and
+	    # file counting can be managed by the initial invocation, as recursive calls
+	    # only output a single (submodule's) file.
+	    submoduleRef="$(git-subhash "$revision" "$submodule")" || { status=$?; continue 2; }
+	    (cd "$submodule" && exec "${BASH_SOURCE[0]}" "$submoduleRef" "${BASH_REMATCH[1]}")
+	    return $?
 	fi
     done
 
-    git show "${commitId}:$path" || status=$?
-done
+    git show "${commitId}:${path}"
+}
+
+status=0
+case ${#files[@]} in
+    0)	echo >&2 'ERROR: No <pathspec> passed.'
+	exit 2
+	;;
+    1)	typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=()
+	eval 'catFile "${files[0]}"' \
+	    "${pager:+|}" '"${pager[@]}"'
+	;;
+    *)	tempDirspec="$(mktemp --directory --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || { dirspec="${TMPDIR:-/tmp}/$(basename -- "$0").$$$RANDOM"; mkdir --parents -- "$dirspec" && printf %s "$dirspec"; })" || exit 3 [ "${DEBUG:-}" ] || trap 'rm -rf -- "$tempDirspec" 2>/dev/null' EXIT [ "$PAGER" = smartless ] && PAGER=less	# smartless does not page small outputs that fit the terminal, but we explicitly want to page through each file separately.
+	[ "$DEBUG" ] || trap 'rm -rf "$tempDirspec" 2>/dev/null' EXIT
+	let count=0
+	for filespec in "${files[@]}"
+	do
+	    printf -v tempFilespec '%s/%04d-%s' "$tempDirspec" $((++count)) "$(basename -- "$filespec")"
+	    catFile "$filespec" > "$tempFilespec" || status=$?
+	done
+	"${PAGER:-less}" --RAW-CONTROL-CHARS "${tempDirspec}"/* || status=$?
+esac
 exit $status
