CHG: Default to showing a status, add --status and --all to control this
A separate command to show the current status of the submodules would duplicate a lot of the functionality.
Also, the immediate checkout of _all_ submodules if no arguments are given is very dangerous.
Default to showing the status, unless at least one SUBMODULE is given. Status of individual SUBMODULE(s) can still be obtained via --status.

diff --git a/bin/git-subcobr b/bin/git-subcobr
--- a/bin/git-subcobr
+++ b/bin/git-subcobr
@@ -5,7 +5,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--query] [--recursive] [--local|--remote|--update [--gui|--terminal|--none]] [-f|--force] [--] [SUBMODULE ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--status|--query|--all] [--recursive] [--local|--remote|--update [--gui|--terminal|--none]] [-f|--force] [--] [SUBMODULE ...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -26,9 +26,14 @@ HELPDESCRIPTION
     printShortUsage "$1"
     echo
     cat <<HELPTEXT
+    --status		Show the current status of all / the passed submodules
+			without doing any checkouts.
     --query		Confirm for each submodule whether it should be checked
 			out, reset to what the superproject has recorded, or
 			left as-is.
+    --all		Check out all defined submodules without querying.
+			By default, the status will be shown unless at least one
+			SUBMODULE is passed.
     --recursive		Also check out branches in nested submodules.
     --local		Check out the local branch.
     --remote		Update the local branch to the tracked remote (without
@@ -42,9 +47,9 @@ HELPTEXT
 }
 
 typeset -a recursiveArgs=()
-isQuery=
+action=
 isRecursive=
-action=update
+checkoutAction=update
 logArg=
 forceArg=
 prefix=
@@ -53,11 +58,12 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-	--query)	recursiveArgs+=("$1"); shift; isQuery=t;;
+	--@(status|query|all))
+			recursiveArgs+=("$1"); action="${1#--}"; shift;;
 	--recursive)	recursiveArgs+=("$1"); shift; isRecursive=t;;
-	--local)	recursiveArgs+=("$1"); shift; action=checkoutLocal;;
-	--remote)	recursiveArgs+=("$1"); shift; action=update; logArg=--none;;
-	--update)	recursiveArgs+=("$1"); shift; action=update;;
+	--local)	recursiveArgs+=("$1"); shift; checkoutAction=checkoutLocal;;
+	--remote)	recursiveArgs+=("$1"); shift; checkoutAction=update; logArg=--none;;
+	--update)	recursiveArgs+=("$1"); shift; checkoutAction=update;;
 	--@(gui|terminal|none))
 			recursiveArgs+=("$1")
 			logArg="$1"; shift;;
@@ -71,8 +77,10 @@ done
 typeset -A selectedSubmodules=()
 for submodule
 do
+    : ${action:=all}
     selectedSubmodules["${submodule%/}"]=t
 done
+: ${action:=status}
 
 checkoutLocal()
 {
@@ -127,31 +135,61 @@ for submodule in "${!submoduleBranches[@]}"
 do
     [ ${#selectedSubmodules[@]} -eq 0 ] || [ "${selectedSubmodules["$submodule"]}" ] || continue
 
-    if [ "$isQuery" ]; then
-	choice="$(userchoiceFromList --no-cancel --question "${prefix}${submodule}" \
-	    'check out' 'reset to superproject' 'leave as-is')"
-	case "$choice" in
-	    'check out')
-		# This is the default action.
-		;;
-	    'reset to superproject')
-		git checkout $forceArg HEAD -- "$submodule" && : ${status:=0} || status=$?
-		continue
-		;;
-	    'leave as-is')
-		: ${status:=0}
-		continue
-		;;
-	    *)	printf >&2 'ASSERT: Invalid choice: %s\n' "$choice"; exit 3;;
-	esac
-    fi
+    case "$action" in
+	status)
+	    #subhash="$(git-subhash "$submodule")"
+	    subhash="$(git rev-parse --short "HEAD:${submodule}" 2>/dev/null)"
+	    ( set -e
+		if ! cd "$submodule" 2>/dev/null; then
+		    printf '%s\tnot initialized\n' "${prefix}${submodule}"
+		    exit 1
+		fi
+
+		currentBranchName="$(git-brname --real-branch-only 2>/dev/null)"
+		if [ "$currentBranchName" = "${submoduleBranches["$submodule"]}" ]; then
+		    printf '%s\talready on %s\n' "${prefix}${submodule}" "$currentBranchName"
+		elif [ -n "$currentBranchName" ]; then
+		    printf '%s\ton %s; would switch to %s\n' "${prefix}${submodule}" "$currentBranchName" "${submoduleBranches["$submodule"]}"
+		else
+		    currentRev="$(git rev-parse --short HEAD)"
+		    if [ "$subhash" = "$currentRev" ]; then
+			printf '%s\tdetached checkout of %s\n' "${prefix}${submodule}" "$currentRev"
+		    else
+			printf "%s\tdetached checkout of %s != %s\\n" "${prefix}${submodule}" "$currentRev" "$subhash"
+		    fi
+		fi
+	    ) && : ${status:=0} || status=$?
+	    continue
+	    ;;
+	query)
+	    choice="$(userchoiceFromList --no-cancel --question "${prefix}${submodule}" \
+		'check out' 'reset to superproject' 'leave as-is')"
+	    case "$choice" in
+		'check out')
+		    # This is the default action.
+		    ;;
+		'reset to superproject')
+		    git checkout $forceArg HEAD -- "$submodule" && : ${status:=0} || status=$?
+		    continue
+		    ;;
+		'leave as-is')
+		    : ${status:=0}
+		    continue
+		    ;;
+		*)	printf >&2 'ASSERT: Invalid choice: %s\n' "$choice"; exit 3;;
+	    esac
+	    ;;
+	all)
+	    ;;
+	*)  printf >&2 'ASSERT: Invalid action: %s\n' "$action"; exit 3;;
+    esac
 
     ( set -e
 	if ! cd "$submodule" 2>/dev/null; then
 	    printf '%s\tnot initialized\n' "${prefix}${submodule}"
 	    exit 1
 	fi
-	$action "${submoduleBranches["$submodule"]}"
+	$checkoutAction "${submoduleBranches["$submodule"]}"
 
 	if [ "$isRecursive" ]; then
 	    typeset -a selectedNestedSubmodules=()
