git-rewordrebasedcommithashes: Minor: Full command-line argument parsing
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.92.0 (2026-04-28), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-rewordrebasedcommithashes b/bin/git-rewordrebasedcommithashes
--- a/bin/git-rewordrebasedcommithashes
+++ b/bin/git-rewordrebasedcommithashes
@@ -14,11 +14,21 @@ HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" '[--update-commit-hashes] [-?|-h|--help]'
 }
 
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --update-commit-hashes)
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--update-commit-hashes)
 			shift; git-wrapper rebase --generate-rebased-commit-hashes || exit $?;;
-esac
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
+if [ $# -ne 0 ]; then
+    printUsage "$0" >&2
+    exit 2
+fi
 
 gitDir="$(git rev-parse --git-dir 2>/dev/null)" || exit 3
 readonly rebasedCommitHashesFilespec="${gitDir}/rebasedCommitHashes"
