Robustness: Check existence of <target-branch>
Though "git checkout" might complain, it'll happily take a SHA and do a detached checkout, which cannot be merged.

diff --git a/bin/git-mergeto b/bin/git-mergeto
--- a/bin/git-mergeto
+++ b/bin/git-mergeto
@@ -19,7 +19,12 @@ if [ $# -eq 0 ]; then
     exit 2
 fi
 targetBranch="${!#}"; set -- "${@:1:$(($#-1))}"
+if ! git-existsbr "$targetBranch"; then
+    printf >&2 'ERROR: Branch %s does not exist.\n' "$targetBranch"
+    exit 1
+fi
 
 branch="$(git brname --real-branch-only --raw)" || exit $?
 
-git checkout "$targetBranch" && git-wrapper merge "$@" "$branch"
+git checkout "$targetBranch" \
+    && git-wrapper merge "$@" "$branch"
