git-changesetfiles: CHG: Consistency: Take revisionRangeArgs like git-showfiles-command instead of <pathspec>|<commit>
This is more flexible and allows time-, count-, and revision-based commit ranges instead of just individual revisions.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.95.0 (2026-06-17), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-changesetfiles b/bin/git-changesetfiles
--- a/bin/git-changesetfiles
+++ b/bin/git-changesetfiles
@@ -1,11 +1,14 @@
 #!/bin/bash
 set -o pipefail
+shopt -qs extglob
 
 : ${GIT_CHANGESETFILES_PERCENTAGE_THRESHOLD:=10}
 : ${GIT_CHANGESETFILES_ORIGINAL_FILE_PREFIX='[01;37m'}
 : ${GIT_CHANGESETFILES_ORIGINAL_FILE_SUFFIX='[0m'}
+: ${GIT_CHANGESETFILES_REVISIONS_END=;}
 
-readonly allArgs='[-N|--no-percentage] [-%|--percentage-threshold PCT] [-a|--include-original-files|-d|--drop-original-files]'
+readonly revisionRangeArgs="[-n|--count N|-r|--revision REVISION|--revisions REVISION1 [...] $GIT_CHANGESETFILES_REVISIONS_END|--since <date>|--max-count <number>|--range <range> [--range ...]]"
+readonly allArgs="[-N|--no-percentage] [-%|--percentage-threshold PCT] [-a|--include-original-files|-d|--drop-original-files] $revisionRangeArgs"
 readonly filterArgs='[-%|--percentage-threshold PCT] [-d|--drop-original-files]'
 readonly formatArgs='[-N|--no-percentage] [-a|--include-original-files]'
 getShortUsage()
@@ -16,6 +19,8 @@ getShortUsage()
 	    printf %s "$filterArgs";;
 	format)
 	    printf %s "$formatArgs";;
+	revision-range)
+	    printf %s "$revisionRangeArgs";;
 	*)  echo "ERROR: Unknown short usage topic \"$1\"!" >&2; return 2;;
     esac
 }
@@ -42,6 +47,23 @@ HELPTEXT
 HELPTEXT
 	    hadTopic=t
 	    ;;&
+	''|revision-range)
+	    cat <<HELPTEXT
+    --count|-n N	Use files modified in the N'th previous commit.
+    --revision|-r REVISION
+			Use files modified in REVISION.
+    --revisions REVISION1 [...] $GIT_CHANGESETFILES_REVISIONS_END
+			Use files modified in REVISION(s); all following
+			arguments until an argument consisting of '$GIT_CHANGESETFILES_REVISIONS_END' is
+			encountered.
+    --since <date>	Use files modified since <date> (inclusive) instead of
+			the last commit.
+    --max-count <number>
+			Use files modified in the last <number> commits instead
+			of the last commit.
+    --range <range>	Use files modified in the commits in <range>.
+HELPTEXT
+	    ;;&
 	*)  [ "$hadTopic" ] || { echo "ERROR: Unknown long usage topic \"$topic\"!" >&2; return 2; };;
     esac
 }
@@ -49,7 +71,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" "$allArgs [<log-options>] [<revision range>] [--] <pathspec>|<commit> [...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "$allArgs [<log-options>] [<revision range>] [--] [<pathspec>...] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -81,11 +103,13 @@ RELATED COMMANDS:
 HELPTEXT
 }
 
+typeset -a revisionRanges=()
 typeset -a gitLogArgs=()
 isPercentage=t
 filterCommand="s/.*/${GIT_CHANGESETFILES_ORIGINAL_FILE_PREFIX}&${GIT_CHANGESETFILES_ORIGINAL_FILE_SUFFIX}/"
 option() { :; }
 parameter() { :; }
+parameterToSep() { :; }
 endOfOptionsAndParameters() { :; }
 noUnderstand() { :; }
 typeset -A understandsSubtopics=()
@@ -110,6 +134,7 @@ do
 	--understands)	shift
 			option() { isUnderstandSubtopic "$@" || exit 1; printf 1; exit 0; }
 			parameter() { isUnderstandSubtopic "$@" || exit 1; printf 2; exit 0; }
+			parameterToSep() { local argCnt="${1:?}"; shift; isUnderstandSubtopic "$@" || exit 1; printf $argCnt; exit 0; }
 			endOfOptionsAndParameters() { exit 99; }
 			noUnderstand() { exit 1; }
 			;;
@@ -122,6 +147,35 @@ do
 			shift; filterCommand=''; option format;;
 	--drop-original-files|-d)
 			shift; filterCommand='d'; option filter;;
+
+	--count|-n)	shift
+			if ! [[ "$1" =~ ^[0-9]+$ ]]; then
+			    printUsage "$0" >&2
+			    exit 2
+			fi
+			revisionRanges+=("HEAD~$(($1 - 1))")
+			shift
+			parameter revision-range
+			;;
+	--revision|-r)	shift; revisionRanges+=("${1:?}"); shift; parameter revision-range;;
+	--revisions)	shift
+			while [ $# -gt 0 -a "$1" != "$GIT_CHANGESETFILES_REVISIONS_END" ]
+			do
+			    revisionRanges+=("${1:?}"); shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --revisions must be concluded with '${GIT_CHANGESETFILES_REVISIONS_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			parameterToSep ${#revisionRanges[@]} revision-range
+			;;
+	--@(since|max-count)=*)
+			revisionRanges+=("$1"); shift; option revision-range;;
+	--@(since|max-count))
+			revisionRanges+=("$1" "${2?}"); shift; shift; parameter revision-range;;
+	--range=*)	revisionRanges+=("${1#--range=}"); shift;;
+	--range)	shift; revisionRanges+=("${1:?}"); shift;;
 
 	--)		gitLogArgs+=("$1"); shift; endOfOptionsAndParameters; break;;
 	*)		gitLogArgs+=("$1"); shift; endOfOptionsAndParameters;;
@@ -139,11 +193,17 @@ removeStatus()
 	-e 's/^\(.*\)	\(.*\)$/\1\n\2/'
 }
 
+logFiles()
+{
+    local prettyArg="${1:?}"; shift
+    git-logv "$prettyArg" "${revisionRanges[@]}" "${gitLogArgs[@]}" "$@"
+}
 extractChangesetFiles()
 {
     if [ "$isPercentage" ] || [ $GIT_CHANGESETFILES_PERCENTAGE_THRESHOLD -gt 0 ]; then
-	GIT_LOGOFFILES_COMMAND=logv git-logoffiles --pretty=format:--- "${gitLogArgs[@]}" "$@" | \
-	    removeStatus | awk -v "isPercentage=$isPercentage" -v percentageThreshold="$GIT_CHANGESETFILES_PERCENTAGE_THRESHOLD" '
+	logFiles --pretty=format:--- "$@" \
+	    | removeStatus \
+	    | awk -v "isPercentage=$isPercentage" -v percentageThreshold="$GIT_CHANGESETFILES_PERCENTAGE_THRESHOLD" '
 BEGIN {
     PROCINFO["sorted_in"] = "@val_num_desc"
 }
@@ -168,8 +228,9 @@ END {
 }
 '
     else
-	GIT_LOGOFFILES_COMMAND=logv git-logoffiles --pretty= "${gitLogArgs[@]}" "$@" | \
-	    removeStatus | sort -u
+	logFiles --pretty= "$@" \
+	    | removeStatus \
+	    | sort --unique
     fi
 }
 
@@ -188,7 +249,10 @@ if [ -n "$filterCommand" ]; then
 
 	[ ${#filterPipeline[@]} -eq 0 ] && filterPipeline+=(sed)
 	filterPipeline+=(-e "/${originalFilePrefixPattern}${literalOriginalPathspec}${pathspecAnchor}/${filterCommand}")
-    done < <(git-logoffiles --only-list-expanded-paths "${gitLogArgs[@]}" "$@" 2>/dev/null | sed -e 's/[][\$*.^/]/\\&/g')
+    done < <(
+	git-showfiles "${revisionRanges[@]}" "${gitLogArgs[@]}" "$@" 2>/dev/null \
+	    | sed -e 's/[][\$*.^/]/\\&/g'
+	)
 
 fi
 
