Refactoring: Minor: Extract synthesizeDefaultWipMessage.sh (d6787aa5 continued)
(This continues commit d6787aa53a52de1d7ffbbe422c7f66f7fad411c3)

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.96.0 (2026-07-02), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-wipcommit b/bin/git-wipcommit
--- a/bin/git-wipcommit
+++ b/bin/git-wipcommit
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+: ${GIT_WIPCOMMIT_INCOMPLETE_KEYWORD=FIXME:}
+: ${GIT_WIPCOMMIT_QUICK_KEYWORD=WIP:}
+
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+
 printUsage()
 {
     cat <<HELPTEXT
@@ -16,9 +24,6 @@ HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" '[<commit-args> ...] [--] [<pathspec>...] [-?|-h|--help]'
 }
 
-: ${GIT_WIPCOMMIT_INCOMPLETE_KEYWORD=FIXME:}
-: ${GIT_WIPCOMMIT_QUICK_KEYWORD=WIP:}
-
 keyword="$GIT_WIPCOMMIT_INCOMPLETE_KEYWORD"
 message=
 typeset -a commitArgs=()
@@ -33,9 +38,4 @@ do
     esac
 done
 
-synthesizeDefaultMessage()
-{
-    printf 'WIP on %s' "$(git log --max-count 1 --pretty=format:'%h %s')"
-}
-
-exec git-wrapper commit --message "${keyword} ${message:-$(synthesizeDefaultMessage)}" "${commitArgs[@]}" "$@"
+exec git-wrapper commit --message "${keyword} ${message:-$("${libDir}/synthesizeDefaultWipMessage.sh")}" "${commitArgs[@]}" "$@"
diff --git a/bin/git-wipetostash b/bin/git-wipetostash
--- a/bin/git-wipetostash
+++ b/bin/git-wipetostash
@@ -2,6 +2,11 @@
 
 : ${GIT_WIPETOSTASH_TITLE_PREFIX:=Backup:}
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+
 printUsage()
 {
     cat <<HELPTEXT
@@ -27,9 +32,4 @@ do
     esac
 done
 
-synthesizeDefaultMessage()
-{
-    printf 'WIP on %s' "$(git log --max-count 1 --pretty=format:'%h %s')"
-}
-
-exec git-wrapper ${GIT_WIPETOSTASH_STASH_COMMAND:-stash} push --message "${GIT_WIPETOSTASH_TITLE_PREFIX} ${message:-$(synthesizeDefaultMessage)}" "$@"
+exec git-wrapper ${GIT_WIPETOSTASH_STASH_COMMAND:-stash} push --message "${GIT_WIPETOSTASH_TITLE_PREFIX} ${message:-$("${libDir}/synthesizeDefaultWipMessage.sh")}" "$@"
