Refactoring: Extract fixPath()

diff --git a/bin/git-wrapper b/bin/git-wrapper
--- a/bin/git-wrapper
+++ b/bin/git-wrapper
@@ -1,17 +1,20 @@
 #!/bin/bash
 
+fixPath()
+{
+    # XXX: Git puts itself in front of the PATH; need precedence for our
+    # scripts, though. Solve this by putting our dirspec in front again. Take
+    # that, Git!
+    readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && absoluteScriptFile="$(readlink -nf -- "${BASH_SOURCE[0]}")" && dirname -- "$absoluteScriptFile" || exit 3)"
+    [ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }
+    PATH="${scriptDir}:$PATH"
+}
+
 if type -t hub >/dev/null; then
     hubAlias="hub-$1"
     if type -t "$hubAlias" >/dev/null; then
 	shift
-
-	# XXX: Git puts itself in front of the PATH; need precedence for our
-	# scripts, though. Solve this by putting our dirspec in front again. Take
-	# that, Git!
-	readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && absoluteScriptFile="$(readlink -nf -- "${BASH_SOURCE[0]}")" && dirname -- "$absoluteScriptFile" || exit 3)"
-	[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }
-	PATH="${scriptDir}:$PATH"
-
+	fixPath
 	eval exec $hubAlias '"$@"'
     fi
 fi
@@ -19,14 +22,7 @@ fi
 gitAlias="git-$1"
 if type -t "$gitAlias" >/dev/null; then
     shift
-
-    # XXX: Git puts itself in front of the PATH; need precedence for our
-    # scripts, though. Solve this by putting our dirspec in front again. Take
-    # that, Git!
-    readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && absoluteScriptFile="$(readlink -nf -- "${BASH_SOURCE[0]}")" && dirname -- "$absoluteScriptFile" || exit 3)"
-    [ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }
-    PATH="${scriptDir}:$PATH"
-
+    fixPath
     eval exec $gitAlias '"$@"'
 else
     exec "$(which hub || which git)" "$@"
