Cosmetics: Align code, combine two parsing steps

diff --git a/bin/git-rtagtype b/bin/git-rtagtype
--- a/bin/git-rtagtype
+++ b/bin/git-rtagtype
@@ -10,33 +10,30 @@ HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} all|annotated|lightweight [-l|--list <pattern>] [-?|-h|--help]"
 }
 case "$1" in
-    --help|-h|-\?)  shift; printUsage "$0"; exit 0;;
+    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
     --no-color|--color=*)
 			shift;;
     --color)		shift; shift;;
 esac
 remote="${1:?}"; shift
 case "$1" in
-    --help|-h|-\?)  shift; printUsage "$0"; exit 0;;
+    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
     --no-color|--color=*)
 			shift;;
     --color)		shift; shift;;
-    all)	    tagType=all;;
-    annotated)	    tagType=tag;;
-    lightweight)    tagType=commit;;
-    *)		    printf >&2 'ERROR: Invalid tag type %s; must be either all, annotated, or lightweight.\n' "$1"; exit 2;;
+    all)		tagType=all;;
+    annotated)		tagType=tag;;
+    lightweight)	tagType=commit;;
+    *)			printf >&2 'ERROR: Invalid tag type %s; must be either all, annotated, or lightweight.\n' "$1"; exit 2;;
 esac; shift
-case "$1" in
-    --help|-h|-\?)  shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
-			shift;;
-    --color)		shift; shift;;
-esac
-
 filter=
 pattern=
 case "$1" in
-    --list|-l)	    shift; filter='matcher'; pattern="$1"; shift;;
+    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+    --no-color|--color=*)
+			shift;;
+    --color)		shift; shift;;
+    --list|-l)		shift; filter='matcher'; pattern="$1"; shift;;
 esac
 
 matcher()
