git-rcolatest: Style: Add line breaks, long option names

diff --git a/bin/git-rcolatest b/bin/git-rcolatest
--- a/bin/git-rcolatest
+++ b/bin/git-rcolatest
@@ -37,10 +37,15 @@ done
 currentBranch="$(git-remotebr "$remote" 2>/dev/null || echo "(remote branch not found)")"
 masterBranch="$(git-mbr)"
 baseBranch="$(git-nbr 2>/dev/null)"
-remoteBranch="$(${GIT_RCOLATEST_REMOTE_BRANCH_COMMAND:-git-rbr} "$remote" ${GIT_RCOLATEST_REMOTE_BRANCH_ARGUMENT:---sort=committerdate} "$@" | grep -v -F --line-regexp -e "${remote}/${masterBranch}" ${baseBranch:+-e "${remote}/$baseBranch"} -e "$currentBranch" | tail -n 1)" || exit $?
+remoteBranch="$(
+    ${GIT_RCOLATEST_REMOTE_BRANCH_COMMAND:-git-rbr} "$remote" ${GIT_RCOLATEST_REMOTE_BRANCH_ARGUMENT:---sort=committerdate} "$@" \
+	| grep --invert-match --fixed-strings --line-regexp -e "${remote}/${masterBranch}" ${baseBranch:+-e "${remote}/$baseBranch"} -e "$currentBranch" \
+	| tail -n 1
+)" || exit $?
 if [ -z "$remoteBranch" ]; then
     # git branch does not return an error if there are no matches for the passed pattern.
-    printf >&2 'ERROR: No%s branch (excluding the current %s and %s%s) found in %s.\n' "${*:+ matching}" "$currentBranch" "$masterBranch" "${baseBranch:+ and ${baseBranch}}" "$remote"
+    printf >&2 'ERROR: No%s branch (excluding the current %s and %s%s) found in %s.\n' \
+	"${*:+ matching}" "$currentBranch" "$masterBranch" "${baseBranch:+ and ${baseBranch}}" "$remote"
     exit 1
 fi
 exec git-checkout-remote-branch "${checkoutArgs[@]}" "$remoteBranch"
