Renaming: Move scripts into bin/ subdir and documents into etc/ subdir
For cleaner separation of the different files, now that there are so many of them.

diff --git a/bin/git-alias b/bin/git-alias
--- a/bin/git-alias
+++ b/bin/git-alias
@@ -1,7 +1,8 @@
 #!/bin/bash
 
-readonly scriptDir=$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 2)
-[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 2; }
+readonly scriptDir=$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)
+[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }
+readonly gitConfig="${scriptDir}/../gitconfig"
 
 printUsage()
 {
@@ -39,7 +40,7 @@ printAliases()
 		    s/[ \t]=[ \t][^;]*[ \t];[ \t]*/\n\t/;
 		    b
 		}' \
-	    "${scriptDir}/gitconfig" \
+	    "$gitConfig" \
 	    | sed -e '/^\t/!s/[^=]*/[01m&[0m/' -e '/^\t/s/^\t//'
     else
 	sed -n \
@@ -61,7 +62,7 @@ printAliases()
 			p
 		    }
 		}' \
-	    "${scriptDir}/gitconfig"
+	    "$gitConfig"
     fi
 }
 
