git-rev-range-this-branch: Usability: Improve error message when no base commit can be found
Previously, we just showed the error from "git describe", but that doesn't have a connection to the command that the user executed:
> fatal: No tags can describe '0689f5564c11bc4b45779f25d08cc8529985e431'.
> Try --always, or create some tags.

diff --git a/bin/git-rev-range-this-branch b/bin/git-rev-range-this-branch
--- a/bin/git-rev-range-this-branch
+++ b/bin/git-rev-range-this-branch
@@ -57,7 +57,10 @@ do
 	# This will exit eventually with
 	#	"fatal: Not a valid object name REV^" or
 	#	"fatal: No tags can describe REV".
-	previousRev=$(git describe --abbrev=0 --all "${previousRev}^") || exit $?
+	if ! previousRev="$(git describe --abbrev=0 --all "${previousRev}^" 2>/dev/null)"; then
+	    printf >&2 'ERROR: Cannot find base commit for %s\n' "${startRev:-the current branch.}"
+	    exit 1
+	fi
 	[ "$isAny" ] && break
 	contains "${previousRev%%/*}" "${include[@]}" && break
     done
