git-{{author,showfile}s-command,whois}: Refactoring: Consistency: Extract parseShowRangeArgsInto()
And handle any range args provided by "git show", not just --max-count and --since.
I needs this for git-showfiles-command; git-authors-command is converted because it has the same API, and git-whois is the command underlying git-authors-command that gets the arguments forwarded.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.95.0 (2026-06-17), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-authors-command b/bin/git-authors-command
--- a/bin/git-authors-command
+++ b/bin/git-authors-command
@@ -1,14 +1,23 @@
 #!/bin/bash
 shopt -qs extglob
 
+: ${GIT_AUTHORSCOMMAND_REVISIONS_END=;}
+
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+source "${libDir}/logArgParser.sh" || exit 3
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--no-option-name|--option-name NAME] [--literal|--joined-as-pattern [--prefix P] [--suffix S]|--invert-authors] [--since <date>|--max-count <number>|--range <range> [--range ...]] ... [-?|-h|--help]'
+    local revisionRangeArgs="[$(GIT_LOGARGPARSER_REVISIONS_END="$GIT_AUTHORSCOMMAND_REVISIONS_END" getShowRangeArgsShortUsage)]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[--no-option-name|--option-name NAME] [--literal|--joined-as-pattern [--prefix P] [--suffix S]|--invert-authors] $revisionRangeArgs ... GIT-COMMAND $revisionRangeArgs [...] [-?|-h|--help]"
     printf 'Usage: %q %s\n' "$(basename "$1")" '... GIT-COMMAND [...] AUTHOR-PATTERN|(-- [AUTHOR-PATTERN ...])'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... --keep-position GIT-COMMAND [... AUTHORS ...] AUTHOR-PATTERN|(-- [AUTHOR-PATTERN ...])'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '... [-2 GIT-COMMAND ARG1|-3 GIT-COMMAND ARG1 ARG2|...] GIT-COMMAND [...] AUTHOR-PATTERN|(-- [AUTHOR-PATTERN ...])'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '... [-2 GIT-COMMAND ARG1|-3 GIT-COMMAND ARG1 ARG2|...] [...] AUTHOR-PATTERN|(-- [AUTHOR-PATTERN ...])'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... [+1 ARG1|+2 ARG1 ARG2|+3 ARG1 ARG2 ARG3|...] GIT-COMMAND [...] AUTHOR-PATTERN|(-- [AUTHOR-PATTERN ...])'
 }
 printUsage()
@@ -49,12 +58,14 @@ HELPDESCRIPTION
 			the single matched author. Cannot be combined with
 			--joined-as-pattern.
 HELPTEXT
+    GIT_LOGARGPARSER_REVISIONS_END="$GIT_AUTHORSCOMMAND_REVISIONS_END" getShowRangeArgsLongUsage 'Use files'
 }
 
 optionName='--author='
 isJoinedAsPattern=
 joinPrefix='\b'
 joinSuffix='\b'
+typeset -a rangeArgs=()
 typeset -a whoisArgs=()
 typeset -a whoisSelectArg=(--select-many)
 typeset -a escaper=(sed -e 's/[][\$*.^]/\\&/g')
@@ -62,19 +73,28 @@ isInvertAuthors=
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)		shift; printLongUsage "$0"; exit 0;;
-	--no-option-name)	shift; optionName=;;
-	--option-name)		shift; optionName="--${1:?}="; shift;;
-	--literal)		shift; escaper=();;
-	--joined-as-pattern)	shift; isJoinedAsPattern=t;;
-	--prefix)		shift; joinPrefix="$1"; shift;;
-	--suffix)		shift; joinSuffix="$1"; shift;;
-	--invert-authors)	shift; isInvertAuthors=t; whoisSelectArg=(--select) whoisArgs+=(--name);;   # Use only name as the anchored author pattern matches the whole name.
-	--name|--email|-[ne]|--follow|--@(since|max-count|range)=*)
-				whoisArgs+=("$1"); shift;;
-	--@(since|max-count|range))
-				whoisArgs+=("$1" "${2?}"); shift; shift;;
-	*)			break;;
+	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--no-option-name)
+			shift; optionName=;;
+	--option-name)	shift; optionName="--${1:?}="; shift;;
+	--literal)	shift; escaper=();;
+	--joined-as-pattern)
+			shift; isJoinedAsPattern=t;;
+	--prefix)	shift; joinPrefix="$1"; shift;;
+	--suffix)	shift; joinSuffix="$1"; shift;;
+	--invert-authors)
+			shift; isInvertAuthors=t; whoisSelectArg=(--select) whoisArgs+=(--name);;   # Use only name as the anchored author pattern matches the whole name.
+	--name|--email|-[ne]|--follow)
+			whoisArgs+=("$1"); shift;;
+	*)		argCount=0
+			typeset -a parsedRangeArgs=()
+			if GIT_LOGARGPARSER_REVISIONS_END="$GIT_AUTHORSCOMMAND_REVISIONS_END" parseShowRangeArgsInto argCount parsedRangeArgs "$@"; then
+			    rangeArgs+=("${parsedRangeArgs[@]}")
+			    shift $argCount
+			else
+			    break
+			fi
+			;;
     esac
 done
 if [ $# -eq 0 ]; then
@@ -110,7 +130,7 @@ if [ ${#authorArgs[@]} -eq 0 ]; then
 fi
 
 readarray -t authors < <(
-    eval 'git-whois "${whoisSelectArg[@]}" "${whoisArgs[@]}" "${authorArgs[@]}"' \
+    eval 'git-whois "${whoisSelectArg[@]}" "${whoisArgs[@]}" "${rangeArgs[@]}" "${authorArgs[@]}"' \
 	"${escaper:+|}" '"${escaper[@]}"'
 )
 
diff --git a/bin/git-showfiles-command b/bin/git-showfiles-command
--- a/bin/git-showfiles-command
+++ b/bin/git-showfiles-command
@@ -4,11 +4,17 @@ shopt -qs extglob
 
 : ${GIT_SHOWFILESCOMMAND_REVISIONS_END=;}
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+source "${libDir}/logArgParser.sh" || exit 3
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    local revisionRangeArgs="[-n|--count N|-r|--revision REVISION|--revisions REVISION1 [...] $GIT_SHOWFILESCOMMAND_REVISIONS_END|--since <date>|--max-count <number>|--range <range> [--range ...]]"
+    local revisionRangeArgs="[$(GIT_LOGARGPARSER_REVISIONS_END="$GIT_SHOWFILESCOMMAND_REVISIONS_END" getShowRangeArgsShortUsage)]"
     local delegationArgs; [ -n "$GIT_SHOWFILES_USAGE_DELEGATION_COMMAND" ] && delegationArgs="$(${GIT_SHOWFILES_USAGE_DELEGATION_COMMAND/--understands/--get-short-usage} 2>/dev/null)"
     printf 'Usage: %q %s\n' "$(basename "$1")" "[-c ...] GIT-COMMAND ${revisionRangeArgs}${delegationArgs:+ }${delegationArgs} [GIT-COMMAND-ARGS ...] [--] [<pathspec>...] [-?|-h|--help]"
     printf 'Usage: %q %s\n' "$(basename "$1")" "--keep-position GIT-COMMAND ${revisionRangeArgs}${delegationArgs:+ }${delegationArgs} [... FILES ...] [--] [<pathspec>...]"
@@ -38,21 +44,7 @@ HELPDESCRIPTION
     echo
     printShortUsage "$1"
     echo
-    cat <<HELPTEXT
-    --count|-n N	Use files modified in the N'th previous commit.
-    --revision|-r REVISION
-			Use files modified in REVISION.
-    --revisions REVISION1 [...] $GIT_SHOWFILESCOMMAND_REVISIONS_END
-			Use files modified in REVISION(s); all following
-			arguments until an argument consisting of '$GIT_SHOWFILESCOMMAND_REVISIONS_END' is
-			encountered.
-    --since <date>	Use files modified since <date> (inclusive) instead of
-			the last commit.
-    --max-count <number>
-			Use files modified in the last <number> commits instead
-			of the last commit.
-    --range <range>	Use files modified in the commits in <range>.
-HELPTEXT
+    GIT_LOGARGPARSER_REVISIONS_END="$GIT_SHOWFILESCOMMAND_REVISIONS_END" getShowRangeArgsLongUsage 'Use files'
     if [ -n "$GIT_SHOWFILES_USAGE_DELEGATION_COMMAND" ]; then
 	${GIT_SHOWFILES_USAGE_DELEGATION_COMMAND/--understands/--get-long-usage} 2>/dev/null
     fi
@@ -62,46 +54,20 @@ case "$1" in
     --help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 esac
 
-typeset -a revisionRanges=()
+typeset -a rangeArgs=()
 typeset -a args=()
 unset files
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-	--count|-n)	shift
-			if ! [[ "$1" =~ ^[0-9]+$ ]]; then
-			    printUsage "$0" >&2
-			    exit 2
-			fi
-			revisionRanges+=("HEAD~$(($1 - 1))")
-			shift
-			;;
-	--revision|-r)	if [ ${#revisionRanges[@]} -eq 0 ]; then
-			    shift; revisionRanges+=("${1:?}"); shift
-			else
-			    args+=("$1" "${2:?}"); shift; shift
-			fi
-			;;
-	--revisions)	shift
-			while [ $# -gt 0 -a "$1" != "$GIT_SHOWFILESCOMMAND_REVISIONS_END" ]
-			do
-			    revisionRanges+=("${1:?}"); shift
-			done
-			if [ $# -eq 0 ]; then
-			    echo "ERROR: --revisions must be concluded with '${GIT_SHOWFILESCOMMAND_REVISIONS_END}'"; echo; printUsage "$0"
-			    exit 2
-			fi >&2
-			shift
-			;;
-	--@(since|max-count)=*)
-			revisionRanges+=("$1"); shift;;
-	--@(since|max-count))
-			revisionRanges+=("$1" "${2?}"); shift; shift;;
-	--range=*)	revisionRanges+=("${1#--range=}"); shift;;
-	--range)	shift; revisionRanges+=("${1:?}"); shift;;
 	--)		shift; typeset -a files=("$@"); break;;
-	*)		if [ -n "$GIT_SHOWFILES_USAGE_DELEGATION_COMMAND" ] && argCount=$($GIT_SHOWFILES_USAGE_DELEGATION_COMMAND --understands "$@"); then
+	*)		argCnt=0
+			if [ ${#rangeArgs[@]} -eq 0 ] \
+			    && GIT_LOGARGPARSER_REVISIONS_END="$GIT_SHOWFILESCOMMAND_REVISIONS_END" parseShowRangeArgsInto argCnt rangeArgs "$@"
+			then
+			    shift $argCnt
+			elif [ -n "$GIT_SHOWFILES_USAGE_DELEGATION_COMMAND" ] && argCount=$($GIT_SHOWFILES_USAGE_DELEGATION_COMMAND --understands "$@"); then
 			    while ((argCount-- > 0))
 			    do
 				showfilesArgs+=("$1"); shift
@@ -135,7 +101,7 @@ if [ $# -eq 0 ]; then
 fi
 
 readarray -t committedFiles < <(
-    eval "${GIT_SHOWFILES_COMMAND:-git-showfiles}" '"${showfilesArgs[@]}" "${revisionRanges[@]}" -- "${files[@]}"' \
+    eval "${GIT_SHOWFILES_COMMAND:-git-showfiles}" '"${showfilesArgs[@]}" "${rangeArgs[@]}" -- "${files[@]}"' \
 	| { xargs -n 1 --no-run-if-empty sh -c 'test -r "$1" && printf %s\\n "$1"' sh || :; }
     printf '\n%d\n' ${PIPESTATUS[0]}
 )	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
diff --git a/bin/git-whois b/bin/git-whois
--- a/bin/git-whois
+++ b/bin/git-whois
@@ -2,11 +2,20 @@
 set -o pipefail
 shopt -qs extglob
 
+: ${GIT_WHOIS_REVISIONS_END=;}
+
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+source "${libDir}/logArgParser.sh" || exit 3
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-1|--first|-s|--select|-S|--select-many] [-n|--name|-e|--email] [--via-email|-E] [--accept-unknown] [--range-is-last|--since <date>|--max-count <number>|-<number>|--range <range> [--range ...]] AUTHOR-PATTERN [...] [-?|-h|--help]'
+    local revisionRangeArgs="[$(GIT_LOGARGPARSER_REVISIONS_END="$GIT_WHOIS_REVISIONS_END" getShowRangeArgsShortUsage)]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[-1|--first|-s|--select|-S|--select-many] [-n|--name|-e|--email] [--via-email|-E] [--accept-unknown] [--range-is-last|${revisionRangeArgs}] AUTHOR-PATTERN [...] [-?|-h|--help]"
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '... --accept-unknown AUTHOR-PATTERN [...]|NAME EMAIL@HOST|"NAME <EMAIL@HOST>"'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... --accept-unknown --select-many AUTHOR-PATTERN|NAME EMAIL@HOST|"NAME <EMAIL@HOST>" [...]'
@@ -44,6 +53,7 @@ HELPDESCRIPTION
 			arguments) or "NAME <EMAIL@HOST>" (one argument) that
 			are not yet found in the repository.
 HELPTEXT
+    GIT_LOGARGPARSER_REVISIONS_END="$GIT_WHOIS_REVISIONS_END" getShowRangeArgsLongUsage 'Use files'
 }
 
 isAcceptUnknown=
@@ -75,17 +85,19 @@ do
 
 	--range-is-last)
 			shift; isRangeLastArg=t;;
-	--since)	rangeArgs+=("$1" "$2"); shift; shift;;
-	--max-count)	rangeArgs+=("$1" "$2"); shift; shift;;
-	--max-count=*|-+([0-9]))
-			rangeArgs+=("$1"); shift;;
-	--range)	shift; rangeArgs+=("$1"); shift;;
-	--range=*)	rangeArgs+=("${1#--range=}"); shift;;
 	--follow)	rangeModificationArgs+=("$1"); shift;;
 
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)		break;;
+	*)		argCount=0
+			typeset -a parsedRangeArgs=()
+			if GIT_LOGARGPARSER_REVISIONS_END="$GIT_WHOIS_REVISIONS_END" parseShowRangeArgsInto argCount parsedRangeArgs "$@"; then
+			    rangeArgs+=("${parsedRangeArgs[@]}")
+			    shift $argCount
+			else
+			    break
+			fi
+			;;
     esac
 done
 
