git-{co[ot],conflictwipe}: Conflicts resulting from "git stash pop" are not recognized
Even though it says "Auto-merging", git-ismerging is false. We need to check for conflicted files as a fallback.

diff --git a/bin/git-conflictwipe b/bin/git-conflictwipe
--- a/bin/git-conflictwipe
+++ b/bin/git-conflictwipe
@@ -28,6 +28,10 @@ elif gitDir="$(git rev-parse --git-dir 2>/dev/null)" || exit 3
 then
     exec git cherry-pick --abort
 else
-    echo >&2 "ERROR: It appears that you're neither merging nor cherry-picking."
-    exit 1
+    readarray -t files < <(git-conflicts)
+    if [ ${#files[@]} -eq 0 ]; then
+	echo 'ERROR: No conflicts.'
+	exit 99
+    fi
+    exec git checkout HEAD -- "${files[@]}"
 fi
