ENH: Allow graphing of the duration and extend per author via gnuplot
This provides a nice visualization, comparing individual authors.

System-info: Ubuntu 20.04.6 LTS, x86_64
System-info: Armbian 24.11.1 noble, aarch64
Platform-info: git version 2.47.1, hub version 2.14.2, gh version 2.55.0 (2024-08-20), git-lfs/3.6.0 (GitHub; linux amd64; go 1.23.1)
Platform-info: git version 2.47.0, hub version 2.14.2, gh version 2.62.0 (2024-11-14), git-lfs/3.5.1 (GitHub; linux arm64; go 1.21.8)

diff --git a/bin/git-brlifetimesbyeach b/bin/git-brlifetimesbyeach
--- a/bin/git-brlifetimesbyeach
+++ b/bin/git-brlifetimesbyeach
@@ -1,11 +1,21 @@
 #!/bin/bash
 
+: ${GIT_BRLIFETIMESBYEACH_GRAPH_NOGUI:=dumb size ${COLUMNS:-80} $((${LINES:-25} - 3)) ansi}
+: ${GIT_BRLIFETIMESBYEACH_GRAPH_GUI:=qt size 1000,1000}
+
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly etcDir="${projectDir}/etc/brlifetimesbyeach"
+
 printUsage()
 {
     git-brlifetimes --help 2>&1 | sed \
 	-e '1s#^.*$#Show one-line lifetime, number of commits, commit range, author, date, tags and\ncommit summary of merged branches for each user that authored merges separately.#' \
 	-e '2b removeFirstParagraphLoop' \
-	-e '/^Usage:$/N' -e '/\(^\|\n\)Usage: */{ s/\(^\|\n\)\(Usage: *\)\?\([^ |]\+ \)*git-brlifetimes /\1\2'"$(basename "$1")"' /; }' \
+	-e '/^ *--raw/i\
+    --graph		Graph the durations and commit counts per author.' \
+	-e '/^Usage:$/N' -e '/\(^\|\n\)Usage: */{ s/\(^\|\n\)\(Usage: *\)\?\([^ |]\+ \)*git-brlifetimes /\1\2'"$(basename "$1")"' /; s/\[--raw\]/[--graph|--raw]/; }' \
 	-e b -e :removeFirstParagraphLoop -e '{ /\(^\|\n\)$/{ s/^\(.*\n\)\?//; b; }; N; b removeFirstParagraphLoop; }'
 }
 case "$1" in
@@ -14,6 +24,7 @@ esac
 
 isSummary=
 isRaw=
+typeset -a grapher=()
 typeset -a logArgs=()
 while [ $# -ne 0 ]
 do
@@ -21,6 +32,7 @@ do
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--summary|-s|--commits-summary|--duration-summary)
 			logArgs+=("$1"); shift; isSummary=t;;
+	--graph)	shift; logArgs+=(--raw); isRaw=t; grapher=(gnuplotWrapper);;
 	--raw)		logArgs+=("$1"); shift; isRaw=t;;
 	--)		logArgs+=("$1"); shift; break;;
 	*)		logArgs+=("$1"); shift;;
@@ -38,8 +50,27 @@ if [ -n "$GIT_BRLIFETIMESBYEACH_AGGREGATE_COMMAND" ]; then
     set -- "$@" --  # Need a trailing -- to prevent that arguments from the aggregate command are parsed off as FILE(s) if it contains a -- itself. Passing <path>s for a multi-repo iteration likely doesn't make sense, anyway.
 fi
 
-GIT_BRLIFETIMES_EXIT_STATUS_NO_MERGES=0 \
-GIT_SEGREGATEDUSERCOMMAND_PREFIX_SEPARATOR=$'\t' \
-STATISTICS_SEP=$'\t' \
-    exec git-segregated-user-command "${segregatedusercommandHeaderArgs[@]}" --log-args-for-range --keep-position \
-	"${brlifetimesCommand[@]}" USERFILTER "${logArgs[@]}" "$@"
+gnuplotWrapper()
+{
+    [ -n "$DISPLAY" ] \
+	&& local terminalSettings="$GIT_BRLIFETIMESBYEACH_GRAPH_GUI" \
+	|| local terminalSettings="$GIT_BRLIFETIMESBYEACH_GRAPH_NOGUI"
+    {
+	printf '$data << EOD\n'
+	cat
+	printf 'EOD\ndata = "$data"\nset terminal %s\n\n' "$terminalSettings"
+	cat "${etcDir}/graph.gnuplot"
+    } | gnuplot --persist
+}
+
+brlifetimesbyeach()
+{
+    GIT_BRLIFETIMESBYEACH_EXIT_STATUS_NO_MERGES=0 \
+    GIT_SEGREGATEDUSERCOMMAND_PREFIX_SEPARATOR=$'\t' \
+    STATISTICS_SEP=$'\t' \
+	git-segregated-user-command "${segregatedusercommandHeaderArgs[@]}" --log-args-for-range --keep-position \
+	    "${brlifetimesCommand[@]}" USERFILTER "${logArgs[@]}" "$@"
+}
+
+eval 'brlifetimesbyeach "$@"' \
+    "${grapher:+|}" '"${grapher[@]}"'
