git-selectedcommit-command: ENH: Also support -n|--count N like git-showselected
This is useful to pre-select a previous commit, so $ git ssg changed⏎ followed by a selection of "2" is the same as $ git sg -n 2 changed⏎.
Unlike git-showselected, this is a git-*-command, so the -n|--count N can be included in an alias (like *{1-7,x,q,z} ones) but also supplied by the user (to pre-select) and skip the query.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.95.0 (2026-06-17), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-selectedcommit-command b/bin/git-selectedcommit-command
--- a/bin/git-selectedcommit-command
+++ b/bin/git-selectedcommit-command
@@ -5,7 +5,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--all|--last-only] [--accept-single] [--single-only [--with-range-from-end RANGE-SEP|--with-range-to-start RANGE-SEP]] [--range-is-last] [--pass-file-args] [--explicit-file-args|--no-file-args] [--except-last] [--one-more] [--allow-outside-workingcopy] ... --since <date>|--max-count <number>|-<number>|-n <number>|<range>|--range <range> [--range ...] [GIT-COMMAND-ARGS ...] [--] [<pathspec>...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--all|-n|--count N|--last-only] [--accept-single] [--single-only [--with-range-from-end RANGE-SEP|--with-range-to-start RANGE-SEP]] [--range-is-last] [--pass-file-args] [--explicit-file-args|--no-file-args] [--except-last] [--one-more] [--allow-outside-workingcopy] ... -n|--count N|--since <date>|--max-count <number>|-<number>|<range>|--range <range> [--range ...] [GIT-COMMAND-ARGS ...] [--] [<pathspec>...] [-?|-h|--help] ...'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... GIT-COMMAND [GIT-COMMAND-ARGS ...]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... --keep-position GIT-COMMAND [... COMMITS ...]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... [-2 GIT-COMMAND ARG1|-3 GIT-COMMAND ARG1 ARG2|...] [...]'
@@ -37,6 +37,8 @@ HELPDESCRIPTION
     echo
     cat <<HELPTEXT
     --all		Choose all commits in the range without querying.
+    --count|-n N	Choose the N'th commit from the commits in the passed
+			<range> without querying.
     --last-only		Choose the last commit in the range without querying.
     --accept-single	Accept a single commit without querying.
     --single-only	The querying stops when one entry has been selected.
@@ -69,6 +71,7 @@ HELPDESCRIPTION
 HELPTEXT
 }
 
+count=1	# Last commit is the first in the list (which goes backwards in time).
 action=getSelected
 isRangeLastArg=
 isPassFileArgs=
@@ -79,12 +82,16 @@ typeset -a specialLastArg=()
 typeset -a commandOnSelectedArgs=()
 withRange=
 rangeSep=
+typeset -a rangeModificationArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-	--last-only)	shift; action=getLast;;
+
 	--all)		shift; action=getAll;;
+	--last-only)	shift; action=getCounted;;
+	--count|-n)	shift; count=${1:?}; shift; action=getCounted; rangeModificationArgs+=(--max-count $count);;
+
 	--accept-single|--single-only)
 			commandOnSelectedArgs+=("$1"); shift;;
 	--with-range-to-start)
@@ -224,7 +231,6 @@ if [ -z "${files+t}" ] && [ ! "$isExplicitFileArgs" ] && [ "$isFileArgs" ]; then
 fi
 set -- "${gitCommandArgs[@]}"
 
-typeset -a rangeModificationArgs=()
 if [ "$isRangeLastArg" ] && [ $# -gt 0 ]; then
     rangeArgs=("${!#}")
     set -- "${@:1:$(($#-1))}"
@@ -232,8 +238,9 @@ elif [ ${#rangeArgs[@]} -eq 0 ]; then
     while [ $# -ne 0 ]
     do
 	case "$1" in
+	    --count|-n)	    shift; count=${1:?}; shift; action=getCounted; rangeArgs+=(--max-count $count);;
 	    --since)	    rangeArgs+=("$1" "$2"); shift; shift;;
-	    --max-count|-n) rangeArgs+=("$1" "$2"); shift; shift;;
+	    --max-count)    rangeArgs+=("$1" "$2"); shift; shift;;
 	    --max-count=*|-+([0-9]))
 			    rangeArgs+=("$1"); shift;;
 	    --range)	    shift; rangeArgs+=("$1"); shift;;
@@ -338,10 +345,19 @@ getAll()
     fi
 }
 
-getLast()
+getCounted()
 {
     getAll || return $?
-    commits=("${commits[0]}")	# Last commit is the first in the list (which goes backwards in time).
+    if [ ${#commits[@]} -lt $count ]; then
+	if [ ${#commits[@]} -eq 0 ]; then
+	    echo >&2 'ERROR: No commits available.'
+	else
+	    countPlural=s; [ ${#commits[@]} -eq 1 ] && countPlural=
+	    printf >&2 'ERROR: Only %d commit%s available.\n' ${#commits[@]} "$countPlural"
+	fi
+	return 1
+    fi
+    commits=("${commits[$((count - 1))]}")
 }
 
 $action || exit $?
