git-stash-rename: ENH: Also support taking the stash@{<revision>} before the --message
So that a message can be passed to the stashr[1-7] and stashrenameselected aliases, too.

diff --git a/bin/git-stash-rename b/bin/git-stash-rename
--- a/bin/git-stash-rename
+++ b/bin/git-stash-rename
@@ -11,13 +11,20 @@ HELPTEXT
 }
 stash='stash@{0}'
 unset message
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-    --message|-m)	shift; message="$1"; shift;;
-esac
+	--color)	shift; shift;;
+	--message|-m)	shift; message="$1"; shift;;
+	stash@*)	stash="$1"; shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -eq 1 ]; then
     stash="$1"; shift
 elif [ $# -gt 1 ]; then
