WIP: Rework branch parsing

diff --git a/bin/git-whowhen b/bin/git-whowhen
--- a/bin/git-whowhen
+++ b/bin/git-whowhen
@@ -6,7 +6,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-r|--remote REMOTE|-a] [--authored] [-s|--shorter|-l|--longer|-lt|-le|-eq|-ne|-ge|-gt TIMESPAN[SUFFIX]]|[--first|--last [-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]] [--names-only]] [<revision range>] [[--] <path>...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-b|--branch BRANCH [-b ...]|--local|-r|(--remote REMOTE [--remote ...])|-a|--all] [--authored] [-s|--shorter|-l|--longer|-lt|-le|-eq|-ne|-ge|-gt TIMESPAN[SUFFIX]]|[--first|--last [-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]] [--names-only]] [<revision range>] [[--] <path>...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -28,9 +28,11 @@ HELPDESCRIPTION
     echo
     cat <<HELPTEXT
     --authored		Use authored times instead of commit times.
-    -r			List remote-tracking branches.
-    --remote REMOTE	List a particular REMOTE.
-    -a			List both local and remote-tracking branches.
+    --branch|-b BRANCH	Consider BRANCH.
+    --local		Consider all local branches.
+    -r			Consider all remote branches.
+    --remote REMOTE	Consider all branches from a particular REMOTE.
+    --all|-a		Consider both local and remote branches.
     -n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX]
     -s|--shorter|-l|--longer|-lt|-le|-eq|-ne|-ge|-gt TIMESPAN[SUFFIX]
 			Only print those dates and names that match the age /
@@ -41,8 +43,16 @@ for days, 'w' for weeks, 'mo' for months, 'y' for years, 'g' for generations.
 HELPTEXT
 }
 
-# TODO
-typeset branchPrefixes=('refs/heads/')
+typeset branches=()
+addBranches()
+{
+    local isAppend="${1?}"; shift
+    readarray ${isAppend:+-O ${#branches[@]}} -t branches < <("$@")
+    if [ ${#branches[@]} -eq 0 ]; then
+	echo 'ERROR: No branches.'
+	return 1
+    fi
+}
 
 typeset -a logArgs=()
 subjectPlaceholder='%c'
@@ -58,20 +68,27 @@ do
 	--no-color|--color=*)
 			shift;;
 	--color)	shift; shift;;
+
 	--authored)	shift; subjectPlaceholder='%a';;
-	-a)		shift; branchPrefixes=('refs/heads/' 'refs/remotes/');;
-	--remote)	shift; branchPrefixes=("refs/remotes/${1}/"); shift;;
-	-r)		shift; branchPrefixes=('refs/remotes/');;
+
+	--branch|-b)	shift; branches+=("$1"); shift;;
+	--local)	shift; addBranches '' git-localbr --include-all || exit 1;;
+	-r)		shift; addBranches '' git-rbr '' || exit 1;;
+	--remote)	shift; addBranches t git-rbr "${1:?}" || exit 1; shift;;
+	--all|-a)	shift; addBranches '' git-abr || exit 1;;
+
 	--first)	shift; uniqueStableArgs=(); timespanConverter=(); firstColumnType=Age;;
 	--last)		shift; uniqueStableArgs=(--last); timespanConverter=(); firstColumnType=Age;;
+
 	-s|--shorter|-l|--longer|-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt)
 			postAction=(filterFirstColumn --field-separator $'\t' "$1" "$2"); shift; shift;;
-	--names-only)
-			shift; endFilter=(field --field-separator $'\t' --remove 1);;
+
+	--names-only)	shift; endFilter=(field --field-separator $'\t' --remove 1);;
 	--)		break;;
 	*)		logArgs+=("$1"); shift;;
     esac
 done
+[ ${#branches[@]} -gt 0 ] || branches=(HEAD)
 
 filterFirstColumn()
 {
