ENH: Allow graph export to PNG or SVG via GIT_BRLIFETIMESBYEACH_GRAPH_OUTPUT
And influence the canvas size via GIT_BRLIFETIMESBYEACH_GRAPH_SIZE.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.47.1, hub version 2.14.2, gh version 2.55.0 (2024-08-20), git-lfs/3.6.0 (GitHub; linux amd64; go 1.23.1)

diff --git a/bin/git-brlifetimesbyeach b/bin/git-brlifetimesbyeach
--- a/bin/git-brlifetimesbyeach
+++ b/bin/git-brlifetimesbyeach
@@ -1,7 +1,9 @@
 #!/bin/bash
 
+: ${GIT_BRLIFETIMESBYEACH_GRAPH_SIZE:=1000,1000}
 : ${GIT_BRLIFETIMESBYEACH_GRAPH_NOGUI:=dumb size ${COLUMNS:-80} $((${LINES:-25} - 3)) ansi}
-: ${GIT_BRLIFETIMESBYEACH_GRAPH_GUI:=qt size 1000,1000}
+: ${GIT_BRLIFETIMESBYEACH_GRAPH_GUI:=qt size $GIT_BRLIFETIMESBYEACH_GRAPH_SIZE}
+: ${GIT_BRLIFETIMESBYEACH_GRAPH_OUTPUT:=}
 
 readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
 [ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
@@ -16,7 +18,7 @@ printUsage()
 	-e '/^ *--raw/i\
     --graph		Graph the durations and commit counts per author.\
     --graph-stdin	Graph the raw data read from stdin.' \
-	-e '/^Usage:$/N' -e '/\(^\|\n\)Usage: */{ s/\(^\|\n\)\(Usage: *\)\?\([^ |]\+ \)*git-brlifetimes /\1\2'"$(basename "$1")"' /; s/\[--raw\]/[--graph|--graph-stdin|--raw]/; }' \
+	-e '/^Usage:$/N' -e '/\(^\|\n\)Usage: */{ s/\(^\|\n\)\(Usage: *\)\?\([^ |]\+ \)*git-brlifetimes /\1[GIT_BRLIFETIMESBYEACH_GRAPH_SIZE=1000,1000] [GIT_BRLIFETIMESBYEACH_GRAPH_OUTPUT=FILE.(png,svg)] \2'"$(basename "$1")"' /; s/\[--raw\]/[--graph|--graph-stdin|--raw]/; }' \
 	-e b -e :removeFirstParagraphLoop -e '{ /\(^\|\n\)$/{ s/^\(.*\n\)\?//; b; }; N; b removeFirstParagraphLoop; }'
 }
 case "$1" in
@@ -55,9 +57,20 @@ fi
 
 gnuplotWrapper()
 {
-    [ -n "$DISPLAY" ] \
-	&& local terminalSettings="$GIT_BRLIFETIMESBYEACH_GRAPH_GUI" \
-	|| local terminalSettings="$GIT_BRLIFETIMESBYEACH_GRAPH_NOGUI"
+    case "${GIT_BRLIFETIMESBYEACH_GRAPH_OUTPUT##*.}" in
+	png)
+	    local terminalSettings="png size $GIT_BRLIFETIMESBYEACH_GRAPH_SIZE; set output '$GIT_BRLIFETIMESBYEACH_GRAPH_OUTPUT'"
+	    ;;
+	svg)
+	    local terminalSettings="svg size $GIT_BRLIFETIMESBYEACH_GRAPH_SIZE background 'white'; set output '$GIT_BRLIFETIMESBYEACH_GRAPH_OUTPUT'"
+	    ;;
+	'') [ -n "$DISPLAY" ] \
+		&& local terminalSettings="$GIT_BRLIFETIMESBYEACH_GRAPH_GUI" \
+		|| local terminalSettings="$GIT_BRLIFETIMESBYEACH_GRAPH_NOGUI"
+	    ;;
+	*)  printf >&2 "ERROR: Unsupported output format '%s'.\\n" "${GIT_BRLIFETIMESBYEACH_GRAPH_OUTPUT##*.}"; exit 2;;
+    esac
+
     {
 	printf '$data << EOD\n'
 	if [ -t 1 ]; then
