BUG: Refuses to work on non-existing SUBPATH
Although the implementation already uses touch-p to ensure that the move can work, the command-line argument parsing for --target-repo doesn't accept a non-existing path.
Resolve an existing parent if the passed DIR doesn't exist; we just need an existing base directory for the Git repo check (and git-relative handles non-existing paths just fine).

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.96.0 (2026-07-02), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-repofilemove b/bin/git-repofilemove
--- a/bin/git-repofilemove
+++ b/bin/git-repofilemove
@@ -85,17 +85,15 @@ do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--target-repo|--to|-t)
-			shift; dirspec="${1:?}"; shift
-			if [ ! -d "$dirspec" ]; then
-			    printf >&2 'ERROR: Target does not exist: %s\n' "$dirspec"
-			    exit 2
-			fi
+			shift; dirspec="${1:?}"
+			[ -d "$dirspec" ] || dirspec="$(existingParentDir -- "$dirspec")"
 			if ! targetRepo="$(cd "$dirspec" && git root 2>/dev/null)"; then
-			    printf >&2 'ERROR: Target is not a Git working copy: %s\n' "$dirspec"
+			    printf >&2 'ERROR: Target is not a Git working copy: %s\n' "$1"
 			    exit 2
 			fi
-			targetSubPath="$(git-relative -- "$dirspec" 2>/dev/null)"
-			[ -z "$targetSubPath" ] && [[ ! "$dirspec" =~ ./$ ]] && unset targetSubPath
+			targetSubPath="$(git-relative -- "$1" 2>/dev/null)"
+			[ -z "$targetSubPath" ] && [[ ! "$1" =~ ./$ ]] && unset targetSubPath
+			shift
 			;;
 	--copy)		shift; isDelete=; actionName='Copy'; actionAlso='also';;
 	--move)		shift; isCommitRemoval=t;;
