git-bisect-run-wrapper: ENH: Accept default check command in GIT_[BISECT_]CHECK_COMMAND
So projects can predefine a check (build and test) command for themselves.

diff --git a/bin/git-bisect-run-wrapper b/bin/git-bisect-run-wrapper
--- a/bin/git-bisect-run-wrapper
+++ b/bin/git-bisect-run-wrapper
@@ -9,7 +9,16 @@ readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" 
 # ensures that this gets cleared after all iterations are through.
 type -t titleupdate >/dev/null && titleupdate --id git-bisecting --panel "testing $(git-desc 2>/dev/null)"
 
-"$@"
+if [ $# -gt 0 ]; then
+    "$@"
+elif [ -n "$GIT_BISECT_CHECK_COMMAND" ]; then
+    eval "$GIT_BISECT_CHECK_COMMAND"
+elif [ -n "$GIT_CHECK_COMMAND" ]; then
+    eval "$GIT_CHECK_COMMAND"
+else
+    echo >&2 'ERROR: No <cmd> passed to git bisect run (and no default check configured).'
+    exit 255    # Need to exit with > 127 to abort the bisect.
+fi
 status=$?
 
 # XXX: My git-bisect is not accessible through PATH when executed by "git
