BUG: Parsing of fileAgeArgs assumes a trailing REMOTE argument
But that is optional! Would need to check for >= 2 instead of >= 3, but let's actually parse all the age options (like in git-stalebr) instead of assuming it's one.
As there are several different arguments (and these also can be combined), we need to do a full parsing loop, not just consider the first one.

diff --git a/bin/git-fetchdate b/bin/git-fetchdate
--- a/bin/git-fetchdate
+++ b/bin/git-fetchdate
@@ -19,15 +19,17 @@ message=
 isAbsolute=
 isEpoch=
 typeset -a fileAgeArgs=()
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-    --message|-m)	shift; message="$1"; shift;;
-    --epoch)		shift; isEpoch=t;;
-    --absolute|-a)	shift; isAbsolute=t;;
-    --set)		shift
+	--color)	shift; shift;;
+	--message|-m)	shift; message="$1"; shift;;
+	--epoch)	shift; isEpoch=t;;
+	--absolute|-a)	shift; isAbsolute=t;;
+	--set)		shift
 			if [ $# -eq 0 ]; then
 			    echo >&2 'ERROR: No REMOTE(s) passed.'
 			    exit 2
@@ -38,12 +40,13 @@ case "$1" in
 			done
 			exit $?
 			;;
-    -*)			if [ $# -eq 3 ]; then
-			    fileAgeArgs=("$1" "$2")
-			    shift; shift
-			fi
-			;;
-esac
+	-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt)
+			fileAgeArgs=("$1" "$2"); shift; shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -eq 0 ]; then
     readarray -t remotes < <(git remote)
     if [ ${#remotes[@]} -eq 0 ]; then
