Refactoring: Consistency: Move git-do-extensions into lib/ dir
This is a helper script to be sourced, not executed. Now that I have several of those in the lib/ dir, it makes sense to move this one there as well.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.47.1, hub version 2.14.2, gh version 2.55.0 (2024-08-20), git-lfs/3.6.0 (GitHub; linux amd64; go 1.23.1)

diff --git a/bin/git-wc-with-suffix-do b/bin/git-wc-with-suffix-do
--- a/bin/git-wc-with-suffix-do
+++ b/bin/git-wc-with-suffix-do
@@ -1,6 +1,11 @@
 #!/bin/bash
 shopt -qs extglob
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+
 hasProgressNotification=; type -t progressNotification >/dev/null && hasProgressNotification=t
 
 case ",${DEBUG:-}," in
@@ -71,7 +76,7 @@ parseCustomInto()
 GIT_DOEXTENSIONS_WRAPPEE=git-wc-with-suffix-do
 GIT_DOEXTENSIONS_DASHDASH_ARGS_BEFORE_SIMPLECOMMAND=t
 : ${GIT_DOEXTENSIONS_WHAT:=working copies}
-source git-do-extensions || exit 3
+source "${libDir}/git-do-extensions.sh" || exit 3
 
 parseCommand "$@"
 if [ "${wcdoArgs[*]:(-1)}" = -- ]; then
diff --git a/bin/git-wcdo b/bin/git-wcdo
--- a/bin/git-wcdo
+++ b/bin/git-wcdo
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+
 case ",${DEBUG:-}," in
     *,git-wcdo:verbose,*) dump-args -- "$@";;
 esac
@@ -7,7 +12,7 @@ esac
 GIT_DOEXTENSIONS_WRAPPEE=git-wcdo-core
 GIT_DOEXTENSIONS_DASHDASH_ARGS_BEFORE_SIMPLECOMMAND=t
 : ${GIT_DOEXTENSIONS_WHAT:=working copies}
-source git-do-extensions || exit 3
+source "${libDir}/git-do-extensions.sh" || exit 3
 
 parseCommand "$@"
 
diff --git a/bin/git-wcs-in-dir-do b/bin/git-wcs-in-dir-do
--- a/bin/git-wcs-in-dir-do
+++ b/bin/git-wcs-in-dir-do
@@ -1,6 +1,11 @@
 #!/bin/bash
 shopt -qs extglob
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+
 case ",${DEBUG:-}," in
     *,git-wcs-in-dir-do:verbose,*) dump-args -- "$@";;
 esac
@@ -84,7 +89,7 @@ parseCustomInto()
 GIT_DOEXTENSIONS_WRAPPEE=git-wcs-in-dir-do
 GIT_DOEXTENSIONS_DASHDASH_ARGS_BEFORE_SIMPLECOMMAND=t
 : ${GIT_DOEXTENSIONS_WHAT:=working copies}
-source git-do-extensions || exit 3
+source "${libDir}/git-do-extensions.sh" || exit 3
 
 parseCommand "$@"
 parseWcdo "${wcdoArgs[@]}"
