git-addn: Store previous FILE(s) and recall when invoked without arguments

diff --git a/bin/git-addn b/bin/git-addn
--- a/bin/git-addn
+++ b/bin/git-addn
@@ -8,6 +8,13 @@ FILE-GLOB(s). Like addu, but with inverted meaning of the file arguments.
 HELPTEXT
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" "FILE|'FILE-GLOB' [...] [-?|-h|--help]"
+    echo
+    cat <<HELPTEXT
+Add all modified and deleted files except those ignored by previous FILE /
+FILE-GLOB arguments; i.e. keep ignoring the same files.
+HELPTEXT
+    echo
+    printf 'Usage: %q\n' "$(basename "$1")"
 }
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
@@ -31,9 +38,23 @@ noMatchFor()
     exit 1
 }
 
+gitDir="$(git rev-parse --git-dir 2>/dev/null)" || exit $?
+addnConfigFilespec="${gitDir}/addn"
 if [ $# -eq 0 ]; then
-    echo >&2 'ERROR: Must pass at least one FILE / escaped FILE-GLOB to not add!'
-    exit 2
+    if [ -r "$addnConfigFilespec" ]; then
+	readarray -t ignoredFilespecs < "$addnConfigFilespec"
+	if [ ${#ignoredFilespecs[@]} -eq 0 ]; then
+	    echo >&2 'ERROR: No ignored files to recall.'
+	    exit 1
+	fi
+	printf 'Recalling ignored files: %s\n' "$(joinBy --truncate-after 3 -- ', ' "${ignoredFilespecs[@]}")"
+	set -- "${ignoredFilespecs[@]}"
+    else
+	echo >&2 'ERROR: Must pass at least one FILE / escaped FILE-GLOB to not add!'
+	exit 2
+    fi
+else
+    printf '%s\n' "$@" > "$addnConfigFilespec"
 fi
 
 readarray -t reportedAdditions < <(git add --update --dry-run; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
