git-reintegrate: FIX: Cosmetics: "deleted" not negated

diff --git a/bin/git-reintegrate b/bin/git-reintegrate
--- a/bin/git-reintegrate
+++ b/bin/git-reintegrate
@@ -424,7 +424,7 @@ elif [ ${#checkCommands[@]} -gt 0 ]; then
     (eval "${checkCommands[@]}")
 fi || {
     status=$?
-    echo >&2 "Checks failed; $branchesSubjectAuxiliaryVerb been reintegrated, but not ${isPush:+pushed or }deleted yet."
+    echo >&2 "Checks failed; $branchesSubjectAuxiliaryVerb been reintegrated, but not ${isPush:+pushed or }${isKeepBranches:+not }deleted yet."
     echo >&2 'Correct the problem by amending or additional commits, then invoke'
     printContinueCommand
     exit $status
