Robustness: Also parse custom args before the dashdash part
My Unixhome-ingo et al. don't do this, as they provide the DIRSPEC ... and leave the actual SIMPLECOMMAND (and any custom flags like --quiet) to be passed by the user.
But the usage help actually advertises the placement at the beginning.
To handle both positions, rename parseDashdashAndUnknownArgs() into parseCustomInto() and inject the variable that will hold the non-custom args: For dashdashArgs, that'll gather the DIRSPEC(s) in dirspecs, for unknownOptions, it'll complain.

diff --git a/bin/git-wc-with-suffix-do b/bin/git-wc-with-suffix-do
--- a/bin/git-wc-with-suffix-do
+++ b/bin/git-wc-with-suffix-do
@@ -37,11 +37,12 @@ isWorktrees=
 isQuiet=
 isIgnoreNonexisting=
 typeset -a wcs=()
-parseDashdash()
+parseCustomInto()
 {
+    local intoVarName="${1?}"; shift
     # git-do-extensions doesn't understand our custom options, so they are
-    # intermingled with the wcs; we need to separate them on our own.
-    local isDoneWorkingCopies=
+    # intermingled with the wcs (if passed before them) or in the unknown arguments
+    # (if after the dashdash arguments); we need to separate them on our own.
     while [ $# -ne 0 ]
     do
 	case "$1" in
@@ -51,10 +52,12 @@ parseDashdash()
 	    --quiet|-q)	shift; isQuiet=t;;
 	    --ignore-nonexisting)
 			shift; isIgnoreNonexisting=t;;
-	    --)		shift; [ ${#wcs[@]} -eq 0 ] || isDoneWorkingCopies=t;;
-	    *)		[ "$isDoneWorkingCopies" ] \
-			    && args+=("$1") \
-			    || wcs+=("$1")
+	    *)		if [ -n "$intoVarName" ]; then
+			    eval "${intoVarName}+=(\"\$1\")"
+			else
+			    printf >&2 'ERROR: Unknown option: "%s"!\n' "$1"
+			    exit 2
+			fi
 			shift
 			;;
 	esac
@@ -74,7 +77,8 @@ if [ "${wcdoArgs[*]:(-1)}" = -- ]; then
     # Remove a trailing --; we'll separately delimit any SIMPLECOMMAND in "${args[@]}".
     wcdoArgs=("${wcdoArgs[@]:(-1)}")
 fi
-parseDashdash "${dashdashArgs[@]}"
+parseCustomInto wcs "${dashdashArgs[@]}"
+parseCustomInto '' "${unknownOptions[@]}"
 
 case ",${DEBUG:-}," in
     *,git-wc-with-suffix-do,*)
@@ -83,7 +87,6 @@ case ",${DEBUG:-}," in
     *,git-wc-with-suffix-do:verbose,*)
 	    dump-args -a wcdoCommandArgs -- "${wcdoCommandArgs[@]}"
 	    dump-args -a wcdoArgs -- "${wcdoArgs[@]}"
-	    dump-args -a dashdashArgs -- "${dashdashArgs[@]}"
 	    dump-args -a wcs -- "${wcs[@]}"
 	    dump-args -a args -- "${args[@]}"
 	;;
diff --git a/bin/git-wcdo b/bin/git-wcdo
--- a/bin/git-wcdo
+++ b/bin/git-wcdo
@@ -19,8 +19,13 @@ case ",${DEBUG:-}," in
 	    dump-args -a wcdoCommandArgs -- "${wcdoCommandArgs[@]}"
 	    dump-args -a wcdoArgs -- "${wcdoArgs[@]}"
 	    dump-args -a dashdashArgs -- "${dashdashArgs[@]}"
+	    dump-args -a unknownOptions -- "${unknownOptions[@]}"
 	    dump-args -a args -- "${args[@]}"
 	;;
 esac
+if [ ${#unknownOptions[@]} -gt 0 ]; then
+    printf >&2 'ERROR: Unknown option: "%s"!\n' "${unknownOptions[0]}"
+    exit 2
+fi
 
 executeCommand
diff --git a/bin/git-wcs-in-dir-do b/bin/git-wcs-in-dir-do
--- a/bin/git-wcs-in-dir-do
+++ b/bin/git-wcs-in-dir-do
@@ -50,11 +50,13 @@ isQuiet=
 isSkipSymlinks=
 compareOp=-d
 typeset -a dirspecs=()
-parseDashdashAndUnknownArgs()
+parseCustomInto()
 {
+    local intoVarName="${1?}"; shift
     # git-do-extensions doesn't understand our custom options, so they are
-    # intermingled with the dirspecs; we need to separate them on our own.
-    local isDoneDirspecs=
+    # intermingled with the dirspecs (if passed before them) or in the unknown
+    # options (if after the dashdash arguments); we need to separate them on our
+    # own.
     while [ $# -ne 0 ]
     do
 	case "$1" in
@@ -63,10 +65,12 @@ parseDashdashAndUnknownArgs()
 			shift; isSkipSymlinks=t;;
 	    --worktrees)
 			shift; compareOp=-e;;
-	    --)		shift; [ ${#dirspecs[@]} -eq 0 ] || isDoneDirspecs=t;;
-	    *)		[ "$isDoneDirspecs" ] \
-			    && args+=("$1") \
-			    || dirspecs+=("$1")
+	    *)		if [ -n "$intoVarName" ]; then
+			    eval "${intoVarName}+=(\"\$1\")"
+			else
+			    printf >&2 'ERROR: Unknown option: "%s"!\n' "$1"
+			    exit 2
+			fi
 			shift
 			;;
 	esac
@@ -83,7 +87,8 @@ source git-do-extensions || exit 3
 
 parseCommand "$@"
 parseWcdo "${wcdoArgs[@]}"
-parseDashdashAndUnknownArgs "${dashdashArgs[@]}" "${unknownArgs[@]}"
+parseCustomInto dirspecs "${dashdashArgs[@]}"
+parseCustomInto '' "${unknownOptions[@]}"
 
 case ",${DEBUG:-}," in
     *,git-wcs-in-dir-do,*)
@@ -92,7 +97,7 @@ case ",${DEBUG:-}," in
     *,git-wcs-in-dir-do:verbose,*)
 	    dump-args -a wcdoCommandArgs -- "${wcdoCommandArgs[@]}"
 	    dump-args -a wcdoArgs -- "${wcdoArgs[@]}"
-	    dump-args -a dashdashArgs -- "${dashdashArgs[@]}"
+	    dump-args -a unknownOptions -- "${unknownOptions[@]}"
 	    dump-args -a dirspecs -- "${dirspecs[@]}"
 	    dump-args -a args -- "${args[@]}"
 	;;
