BUG: Implementation assumes the original remote also exists in the target repo
Split remote into originalRemote and newRemote, and initialize both separately (if HUB is set).

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.96.0 (2026-07-02), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-repofilemove b/bin/git-repofilemove
--- a/bin/git-repofilemove
+++ b/bin/git-repofilemove
@@ -69,7 +69,8 @@ actionAlso=''
 isDelete=t
 isCommitRemoval=
 isRecordOnly=
-remote=
+originalRemote=
+newRemote=
 gitCommitEditArg=(--edit)
 authorSource=whodid
 isChoose=t
@@ -96,7 +97,7 @@ do
 	--copy)		shift; isDelete=; actionName='Copy'; actionAlso='also';;
 	--move)		shift; isCommitRemoval=t;;
 	--record-only)	shift; isRecordOnly=t;;
-	--remote|-r)	shift; remote="$1"; shift;;
+	--remote|-r)	shift; originalRemote="${1:?}"; newRemote="${1:?}"; shift;;
 	--no-edit)	gitCommitEditArg=("$1"); shift;;
 	--creator)	shift; authorSource=whocreated; isChoose=; isMostOnly=t;;
 	--did)		shift; authorSource=whodid; isChoose=; isMostOnly=t;;
@@ -121,15 +122,27 @@ elif [ $# -eq 0 ]; then
     exit 2
 fi >&2
 
-if [ "$HUB" ] && [ -z "$remote" ]; then
-    readarray -t remotes < <(git remote)
-    case ${#remotes[@]} in
-	0)  ;;
-	1)  remote="${remotes[0]}";;
-	*)  echo >&2 'ERROR: Multiple remotes exist; unable to pick a default. Pass --remote REMOTE to select one.'
-	    exit 2
-	    ;;
-    esac
+if [ "$HUB" ]; then
+    if [ -z "$originalRemote" ]; then
+	readarray -t remotes < <(git remote)
+	case ${#remotes[@]} in
+	    0)  ;;
+	    1)  originalRemote="${remotes[0]}";;
+	    *)  echo >&2 'ERROR: Multiple remotes exist in the current repo; unable to pick a default. Pass --remote REMOTE to select one.'
+		exit 2
+		;;
+	esac
+    fi
+    if [ -z "$newRemote" ]; then
+	readarray -t remotes < <(cd "$targetRepo" && git remote)
+	case ${#remotes[@]} in
+	    0)  ;;
+	    1)  newRemote="${remotes[0]}";;
+	    *)  echo >&2 'ERROR: Multiple remotes exist in the target repo; unable to pick a default. Pass --remote REMOTE to select one.'
+		exit 2
+		;;
+	esac
+    fi
 fi
 
 filemove()
@@ -156,8 +169,8 @@ filemove()
     local originalSubPath; originalSubPath="$(git-relative -- "$filespec")" || return 3
 
     local originalLocation
-    if [ -n "$remote" ]; then
-	originalLocation="$(git lllhurl "$remote" -- "$filespec")" || return 3
+    if [ -n "$originalRemote" ]; then
+	originalLocation="$(git lllhurl "$originalRemote" -- "$filespec")" || return 3
     else
 	originalLocation="$(git-wcname)/${originalSubPath}" || return 3
     fi
@@ -221,8 +234,8 @@ Originally committed at $originalLocation" "${gitCommitEditArg[@]}" -- "$targetF
     ) || return $?
 
     newRepoName="$(cd "$targetRepo" && git-wcname)"
-    if [ -n "$remote" ]; then
-	newLocation="$(cd "$targetRepo" && git lllhurl "$remote" -- "$targetFilepath")"
+    if [ -n "$newRemote" ]; then
+	newLocation="$(cd "$targetRepo" && git lllhurl "$newRemote" -- "$targetFilepath")"
     else
 	printf -v newLocation '%s/%s\n' "${newRepoName:-???}" "$targetFilepath"
     fi
