ENH: Implement --record-only
Useful when the file move has already happened, e.g. through refactoring tools of the IDE, and we just want to do the Git move.

diff --git a/bin/git-repofilemove b/bin/git-repofilemove
--- a/bin/git-repofilemove
+++ b/bin/git-repofilemove
@@ -4,7 +4,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-t|--target-repo OTHER-REPO-PATH[/[SUBPATH]] [--copy|--move] [-r|--remote REMOTE] [--no-edit] [--creator|--did|--owner|--contributor] [--] FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '-t|--target-repo OTHER-REPO-PATH[/[SUBPATH]] [--copy|--move] [--record-only] [-r|--remote REMOTE] [--no-edit] [--creator|--did|--owner|--contributor] [--] FILE [...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -40,6 +40,9 @@ HELPDESCRIPTION
 			each FILE separately). By default, FILE(s) are deleted
 			but that change is not committed; you should do a
 			separate removal commit yourself after the move.
+    --record-only	Accept an existing target file as a copy or move that
+			has already happened and just commit (and delete the
+			original).
     --remote|-r REMOTE	Include links to the GitHub REMOTE in the move commits
 			instead of just referencing the repos by working copy
 			name.
@@ -60,6 +63,7 @@ actionName='Move'
 actionAlso=''
 isDelete=t
 isCommitRemoval=
+isRecordOnly=
 remote=
 gitCommitEditArg=(--edit)
 authorSource=
@@ -83,6 +87,7 @@ do
 			;;
 	--copy)		shift; isDelete=; actionName='Copy'; actionAlso='also';;
 	--move)		shift; isCommitRemoval=t;;
+	--record-only)	shift; isRecordOnly=t;;
 	--remote|-r)	shift; remote="$1"; shift;;
 	--no-edit)	gitCommitEditArg=("$1"); shift;;
 	--creator)	shift; authorSource=whocreated;;
@@ -147,8 +152,13 @@ moveFile()
     local sourceFilespec="${1:?}"; shift
     local targetFilespec="${1:?}"; shift
     if [ -e "$targetFilespec" ]; then
-	printf >&2 'ERROR: Cannot move %s; the target already exists: %s\n' "$sourceFilespec" "$targetFilespec"
-	return 1
+	if [ "$isRecordOnly" ]; then
+	    printf >&2 'Note: Not moving %s; the target already exists: %s\n' "$sourceFilespec" "$targetFilespec"
+	    return 0
+	else
+	    printf >&2 'ERROR: Cannot move %s; the target already exists: %s\n' "$sourceFilespec" "$targetFilespec"
+	    return 1
+	fi
     fi
     touch-p --no-create --verbose -- "$targetFilespec" || return 3
     cp --archive -- "$sourceFilespec" "$targetFilespec" || return 3
