ENH: Handle multiple <branch-glob>s for the *c variants as well
Just requires a different argument handling; the filter-globs are already collected in the what array.

diff --git a/bin/git-rcolatestc b/bin/git-rcolatestc
--- a/bin/git-rcolatestc
+++ b/bin/git-rcolatestc
@@ -10,7 +10,7 @@ was created last (except the current branch and master (and base branch if
 defined)).
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [--gui|--terminal|--none] [--submodule ignore|yes|recurse] [(--submodules|--queried-submodules) [--submodules-recursive]] [<branch-glob>] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [--gui|--terminal|--none] [--submodule ignore|yes|recurse] [(--submodules|--queried-submodules) [--submodules-recursive]] [<branch-glob> ...] [-?|-h|--help]"
 }
 
 case "$1" in
@@ -33,21 +33,19 @@ do
 	*)		break;;
     esac
 done
-case $# in
-    0)	branchPattern='';;
-    1)	branchPattern="$1"; shift;;
-    *)	printUsage "$0" >&2
-	exit 2
-	;;
-esac
+if [ $# -eq 0 ]; then
+    set -- "${remote}/"
+else
+    set -- "${@/#/${remote}/}"
+fi
 
 currentBranch="$(git-remotebr "$remote" 2>/dev/null || echo "(remote branch not found)")"
 masterBranch="$(git-mbr)"
 baseBranch="$(git-nbr 2>/dev/null)"
-remoteBranch="$(git-brc --bare -r "${remote}/${branchPattern}" | grep -v -F --line-regexp -e "${remote}/${masterBranch}" ${baseBranch:+-e "${remote}/$baseBranch"} -e "$currentBranch" | tail -n 1)" || exit $?
+remoteBranch="$(git-brc --bare -r "$@" | grep -v -F --line-regexp -e "${remote}/${masterBranch}" ${baseBranch:+-e "${remote}/$baseBranch"} -e "$currentBranch" | tail -n 1)" || exit $?
 if [ -z "$remoteBranch" ]; then
     # git branch does not return an error if there are no matches for the passed pattern.
-    printf >&2 'ERROR: No branch matching %s/%s (excluding the current %s and %s%s) found.\n' "$remote" "$branchPattern" "$currentBranch" "$masterBranch" "${baseBranch:+ and ${baseBranch}}"
+    printf >&2 'ERROR: No%s branch (excluding the current %s and %s%s) found in %s.\n' "${*:+ matching}" "$currentBranch" "$masterBranch" "${baseBranch:+ and ${baseBranch}}" "$remote"
     exit 1
 fi
 exec git-checkout-remote-branch "${checkoutArgs[@]}" "$remoteBranch"
