UI: Advertise new --record-only

diff --git a/bin/git-repofilemove b/bin/git-repofilemove
--- a/bin/git-repofilemove
+++ b/bin/git-repofilemove
@@ -156,7 +156,7 @@ moveFile()
 	    printf >&2 'Note: Do not %s %s; the target already exists: %s\n' "${actionName,,}" "$sourceFilespec" "$targetFilespec"
 	    return 0
 	else
-	    printf >&2 'ERROR: Cannot %s %s; the target already exists: %s\n' "${actionName,,}" "$sourceFilespec" "$targetFilespec"
+	    printf >&2 'ERROR: Cannot %s %s; the target already exists: %s\nPass --record-only to skip the %s itself.\n' "${actionName,,}" "$sourceFilespec" "$targetFilespec" "${actionName,,}"
 	    return 1
 	fi
     fi
