git-stashi: FIX: Check for staged and unstaged changes
If nothing's in the index, we can fail early - the following stashing of the index would fail, anyway, and we'd have to needlessly undo the stashing of the working copy.
If there are no unstaged changes, a plain stash will do (the --no-keep-index is just for documentation; that's the default stash behavior). We can skip the whole temporary stashing of the working copy (and the existing implementation would fail, anyway).

diff --git a/bin/git-stashi b/bin/git-stashi
--- a/bin/git-stashi
+++ b/bin/git-stashi
@@ -14,12 +14,21 @@ case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 esac
 
+if ! git-staged --quiet; then
+    echo >&2 'ERROR: Nothing staged.'
+    exit 1
+elif ! git-unstaged; then
+    # Every change is in the index already, we can simply stash it.
+    exec git stash push --no-keep-index "$@"
+fi
+
+
 # There's no direct way (a la --keep-working-copy) to ignore unstaged changes,
 # so it has to be done the other way around, by first temporarily stashing the
 # working copy, then the index, then undoing the working copy stashing.
 
 # Stash only unstaged changes not yet in the index temporarily.
-git stash push --keep-index --quiet || exit $?
+git stash push --keep-index --quiet --message 'unstaged changes' || exit $?
 
 # Stash everything that remains (only the staged changes should remain). This is
 # the stash we want to keep, allow to give it a name / influence the stashing
