git-{ff,re}integrate[to]: Robustness: Don't allow reintegration on dirty working copy
Especially with merge conflicts, it's easy to directly invoke "git reintegrate --continue" without commiting the merge. As the index then still contains the merge result, a dirty check successfully prevents that. I can't think of a situation where it's advisable to reintegrate into a dirty working copy.

diff --git a/bin/git-ffintegrateto b/bin/git-ffintegrateto
--- a/bin/git-ffintegrateto
+++ b/bin/git-ffintegrateto
@@ -194,15 +194,6 @@ do
 	*)		break;;
     esac
 done
-sourceBranch="$(git-brname --real-branch-only)" || exit $?
-if [ -z "$targetBranch" ]; then
-    echo 'ERROR: Missing <branch>.'
-    exit 2
-elif [ "$targetBranch" = "$sourceBranch" ]; then
-    printf 'ERROR: Cannot integrate %s onto itself; check out a different branch first.\n' "$targetBranch"
-    exit 2
-fi >&2
-
 if [ "${!#}" = '-' ]; then
     isCheckFromStdin=t
     set -- "${@:1:$(($#-1))}"
@@ -218,6 +209,19 @@ elif [ -n "$GIT_REINTEGRATE_CHECK_COMMAND" -a ${#checkCommands[@]} -eq 0 ]; then
     checkCommands=("$GIT_REINTEGRATE_CHECK_COMMAND")
 fi
 [ "$isDisableChecks" ] && checkCommands=()
+
+sourceBranch="$(git-brname --real-branch-only)" || exit $?
+if [ -z "$targetBranch" ]; then
+    echo 'ERROR: Missing <branch>.'
+    exit 2
+elif [ "$targetBranch" = "$sourceBranch" ]; then
+    printf 'ERROR: Cannot integrate %s onto itself; check out a different branch first.\n' "$targetBranch"
+    exit 2
+elif git-dirty; then
+    echo 'ERROR: working copy is still dirty; please clean up first.'
+    git status
+    exit 1
+fi >&2
 
 typeset -a contextShortener=(headtail --separator $'\t\t\t\t\t[...]')
 confirmFastForwardTarget()
diff --git a/bin/git-reintegrate b/bin/git-reintegrate
--- a/bin/git-reintegrate
+++ b/bin/git-reintegrate
@@ -177,11 +177,15 @@ fi
 
 branches+=("$@")
 if [ ${#branches[@]} -eq 0 ]; then
-    echo >&2 'Need (at least one) <branch> to merge!'
+    echo 'Need (at least one) <branch> to merge!'
     exit 2
 elif ! git-existsbr --verbose "${branches[@]}"; then
     exit 1
-fi
+elif git-dirty; then
+    echo 'ERROR: working copy is still dirty; please clean up first.'
+    git status
+    exit 1
+fi >&2
 
 branchesPlural=es
 branchesSubject=them
diff --git a/bin/git-reintegrateto b/bin/git-reintegrateto
--- a/bin/git-reintegrateto
+++ b/bin/git-reintegrateto
@@ -83,9 +83,13 @@ do
     esac
 done
 if [ -z "$targetBranch" ]; then
-    echo >&2 'ERROR: Missing <branch>.'
+    echo 'ERROR: Missing <branch>.'
     exit 2
-fi
+elif git-dirty; then
+    echo 'ERROR: working copy is still dirty; please clean up first.'
+    git status
+    exit 1
+fi >&2
 
 isOnTargetBranch=; [ "$targetBranch" = "$sourceBranch" ] && isOnTargetBranch=t
 if [ "$isOnTargetBranch" ] && [ ! "$isContinue" ]; then
