git-subhash: ENH: Handle nested submodules and submodules from a subdir that do not use ./
By determining the superproject's parent first and changing into that directory, then using the relative subpath to the submodule in rev-parse.

diff --git a/bin/git-subhash b/bin/git-subhash
--- a/bin/git-subhash
+++ b/bin/git-subhash
@@ -24,5 +24,16 @@ if [ $# -gt 2 ]; then
 elif [ $# -eq 2 ]; then
     ref="$1"; shift
 fi
+absoluteSubmodule="$(realpath --no-symlinks -- "${1:?}")" || exit 3
+if ! absoluteSuperprojectRoot="$(git superproject "$submodule")"; then
+    printf >&2 'ERROR: Not a submodule: %s\n' "$absoluteSubmodule"
+    exit 1
+fi
+relativeSubmodule="${absoluteSubmodule#${absoluteSuperprojectRoot}/}"
+if [ "$relativeSubmodule" = "$absoluteSubmodule" ]; then
+    printf >&2 "ERROR: Submodule '%s' is not inside superproject '%s'.\\n" "$absoluteSubmodule" "$absoluteSuperprojectRoot"
+    exit 3
+fi
 
-exec git rev-parse "${revParseArgs[@]}" "${ref}:${1:?}"
+cd "$absoluteSuperprojectRoot" || exit 3
+exec git rev-parse "${revParseArgs[@]}" "${ref}:${relativeSubmodule}"
