Refactoring: Extract extractCoreCommitSubject.sh and introduce GIT_EXTRACTCORECOMMITSUBJECTCOMMAND
To deduplicate and make the extraction logic customizable.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.92.0 (2026-04-28), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-inout b/bin/git-inout
--- a/bin/git-inout
+++ b/bin/git-inout
@@ -1,12 +1,18 @@
 #!/bin/bash
 set -o pipefail
-shopt -qs extglob
 
 : ${GIT_INOUT_COLOR_TITLE='[1m'}
 : ${GIT_INOUT_COLOR_HEADER=}
 : ${GIT_INOUT_COLOR_IN='[3m'}
 : ${GIT_INOUT_COLOR_OUT='[1m'}
 : ${GIT_INOUT_COLOR_RESET='[0m'}
+: ${GIT_EXTRACTCORECOMMITSUBJECTCOMMAND=extractCoreCommitSubject.sh}
+
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+PATH="${libDir}:${PATH}"
 
 printShortUsage()
 {
@@ -198,16 +204,7 @@ inoutPlain()
 # Duplicated to /getLenientIdentifyingInformation() git-rebase
 getLenientIdentifyingInformation()
 {
-    local information="${1?}"; shift
-    local lenientInformation="$information"
-
-    # Remove all parenthesized information information.
-    lenientInformation="${lenientInformation//(+([^)]))/}"
-    # Remove all leading "scope:" and "keyword:" prefixes.
-    lenientInformation="${lenientInformation/#+(+([^ ]): )/}"
-
-    [ -n "$lenientInformation" -a "$lenientInformation" != "$information" ] \
-	&& printf '%s' "$lenientInformation"
+    ${GIT_EXTRACTCORECOMMITSUBJECTCOMMAND:-false} "$@"
 }
 inout()
 {
diff --git a/bin/git-rebase b/bin/git-rebase
--- a/bin/git-rebase
+++ b/bin/git-rebase
@@ -1,7 +1,13 @@
 #!/bin/bash
-shopt -qs extglob
 
 : ${GIT_REBASE_EXEC_END=;}
+: ${GIT_EXTRACTCORECOMMITSUBJECTCOMMAND=extractCoreCommitSubject.sh}
+
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+PATH="${libDir}:${PATH}"
 
 printUsage()
 {
@@ -58,16 +64,7 @@ recordOriginalPersistentCommits()
 # Duplicated to /getLenientIdentifyingInformation() git-inout
 getLenientIdentifyingInformation()
 {
-    local information="${1?}"; shift
-    local lenientInformation="$information"
-
-    # Remove all parenthesized information information.
-    lenientInformation="${lenientInformation//(+([^)]))/}"
-    # Remove all leading "scope:" and "keyword:" prefixes.
-    lenientInformation="${lenientInformation/#+(+([^ ]): )/}"
-
-    [ -n "$lenientInformation" -a "$lenientInformation" != "$information" ] \
-	&& printf '%s' "$lenientInformation"
+    ${GIT_EXTRACTCORECOMMITSUBJECTCOMMAND:-false} "$@"
 }
 generateRebasedCommitHashes()
 {
