WIP: Implement --push-branch

diff --git a/bin/git-ffintegrateto b/bin/git-ffintegrateto
--- a/bin/git-ffintegrateto
+++ b/bin/git-ffintegrateto
@@ -261,6 +261,20 @@ printContinueCommand()
     [ "$isCheckFromStdin" ] && printf >&2 ' -'
     printf >&2 '\n'
 }
+pushBranch()
+{
+    local sourceTracks="$(git-tracks 2>/dev/null)"
+    if [ -z "$sourceTracks" ]; then
+	printf >&2 "ERROR: Cannot push; no upstream configured for the current branch '%s'\\n" "$sourceBranch"
+	return 1    # Still continue with the branch deletion here, but following push errors will abort.
+    fi
+
+    local sourceTrackedRemote="${sourceTracks%%/*}"
+    local quotedSourceBranch; printf -v quotedSourceBranch %q "$sourceBranch"
+    # Push to the tracked remote (usually origin).
+    git-remote-mutate "$sourceTrackedRemote" --message 'Push' --argument "$sourceBranch" --context-command "git rev-range-outgoing $sourceTrackedRemote --color=always --one-more-command greyonelinelog --one-more-only-to-terminal lg --branch $quotedSourceBranch" "${gitRemoteMutateArgs[@]}" \
+	push "$sourceTrackedRemote" || exit $?
+}
 
 targetTracks="$(git-tracks "$targetBranch" 2>/dev/null)"
 targetTrackedRemote="${targetTracks%%/*}"
@@ -359,3 +373,6 @@ fi || {
     printContinueCommand
     exit $status
 }
+
+status=0
+[ ! "$isPushBranch" ] || pushBranch || status=$?
