git-{exists,remote,rldelete}br: Cosmetics: Correctly document and handle [--]

diff --git a/bin/git-existsbr b/bin/git-existsbr
--- a/bin/git-existsbr
+++ b/bin/git-existsbr
@@ -6,16 +6,22 @@ printUsage()
 Check whether [all of] the passed [<remote>/]<branch> exists.
 With -v|--verbose, print any invalid branches.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-v|--verbose] [<remote>/]<branch> [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-v|--verbose] [--] [<remote>/]<branch> [...] [-?|-h|--help]'
 }
 isVerbose=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-    --verbose|-v)	shift; isVerbose=t;;
-esac
+	--color)	shift; shift;;
+	--verbose|-v)	shift; isVerbose=t;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -eq 0 ]; then
     echo 'ERROR: No <branch> passed.'
     echo
