{td,week,month,year}compare[uo]url: Handle passed --branch, too
The *pred command needs the start revision as well.
Extend git-rbrurl-compare-to-base to only resolve BASE-COMMAND after the command-line argument parsing, and then append the COMMIT there.

diff --git a/bin/git-rbrurl-compare-to-base b/bin/git-rbrurl-compare-to-base
--- a/bin/git-rbrurl-compare-to-base
+++ b/bin/git-rbrurl-compare-to-base
@@ -5,7 +5,8 @@ printUsage()
     cat <<HELPTEXT
 Print the URL of a compare view of HEAD (as branch name (if exists, unless
 --commit-to-rev) / the passed COMMIT to the passed BASE-COMMIT (literal unless
---base-to-rev) / the commit returned by BASE-COMMAND.
+--base-to-rev) / the commit returned by BASE-COMMAND (which gets the COMMIT
+appended).
 HELPTEXT
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '--remote REMOTE --base BASE-COMMIT|--base-command BASE-COMMAND [--base-to-rev] [--short[=length]] [--commit-to-rev] [[--commit] COMMIT] [-?|-h|--help]'
@@ -16,6 +17,7 @@ HELPTEXT
 remote=
 commit=
 base=
+baseCommand=
 isNormalizeBaseRev=
 isNormalizeCommitRev=
 typeset -a revParseArgs=()
@@ -25,7 +27,7 @@ do
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 	--remote)	shift; remote="${1:?}"; shift;;
 	--base)		shift; base="${1:?}"; shift;;
-	--base-command)	shift; base="$(git-wrapper "$1")" || exit $?; shift;;
+	--base-command)	shift; baseCommand="${1:?}"; shift;;
 	--base-to-rev)	shift; isNormalizeBaseRev=t;;
 	--commit)	shift; commit="${1:?}"; shift;;
 	--commit-to-rev)
@@ -60,6 +62,16 @@ case $# in
     *)	printUsage "$0" >&2; exit 2;;
 esac
 : ${commit:=HEAD}
+
+if [ -n "$baseCommand" ]; then
+    if [ -n "$base" ]; then
+	echo 'ERROR: BASE-COMMIT already given.'
+	echo
+	printUsage "$0"
+	exit 2
+    fi >&2
+    base="$(git-wrapper $baseCommand "$commit")" || exit $?
+fi
 
 if [ "$isNormalizeBaseRev" ]; then
     base="$(git rev-parse "${revParseArgs[@]}" "$base")" || exit $?
