git-rcolatest: FIX: REMOTE must be parsed before any log arg
And apply the restructuring in git-rcolatestc to here as well.

diff --git a/bin/git-rcolatest b/bin/git-rcolatest
--- a/bin/git-rcolatest
+++ b/bin/git-rcolatest
@@ -9,25 +9,34 @@ Checkout local branch from latest (by sort order) passed ${remote:-REMOTE}
 [matching pattern].
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [--gui|--terminal|--none] [<branch-glob>] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [--gui|--terminal|--none] [--submodule ignore|yes|recurse] [(--submodules|--queried-submodules) [--submodules-recursive]] [<branch-glob> ...] [-?|-h|--help]"
 }
-logArg=
+
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --@(gui|terminal|none))
-			logArg="$1"; shift;;
 esac
-
-
-if [ $# -eq 0 -o $# -gt 2 ]; then
-    echo >&2 "ERROR: Must pass REMOTE and optionally <branch-glob>."
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: Must pass REMOTE.'
     exit 2
 fi
+remote="${1:?}"; shift
 
-remoteBranch="$(git-rbr "$@" | tail -n 1)" || exit $?
+typeset -a checkoutArgs=()
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--@(gui|terminal|none|submodules|queried-submodules|submodules-recursive))
+			checkoutArgs+=("$1"); shift;;
+	--submodule)	checkoutArgs+=("$1" "$2"); shift; shift;;
+	*)		break;;
+    esac
+done
+
+remoteBranch="$(git-rbr "$remote" "$@" | tail -n 1)" || exit $?
 if [ -z "$remoteBranch" ]; then
     # git branch does not return an error if there are no matches for the passed pattern.
     printf >&2 'ERROR: No branch matching %s/%s found.\n' "$@"
     exit 1
 fi
-exec git-checkout-remote-branch $logArg "${remoteBranch##+( )}"
+exec git-checkout-remote-branch "${checkoutArgs[@]}" "${remoteBranch##+( )}"
