BUG: "git subdo --dirty --untracked" does not work
Because predicates add more conditions, so this will only catch submodules with both untracked and modified files. Making the combination (default: &&) of predicates configurable would be one solution, but cumbersome and complex if it is / can be changed during parsing.
What we actually need is a combined predicate; unfortunately, a good name for "untracked || dirty" is hard to find: "unstaged" definitely excludes files in the index (which "dirty" includes) and (at least in my use) excludes files not under source control. Same for "uncommitted".
I've decided to use "stageable" for untracked or modifications not yet in the index, which makes this not a direct combination (as it excludes the stage).
Add git-stageable variant of git-untracked (i.e. requiring --print to show the files, unlike git-dirty), --stageable and stageable-sh to git-do-extensions.

diff --git a/bin/git-do-extensions b/bin/git-do-extensions
--- a/bin/git-do-extensions
+++ b/bin/git-do-extensions
@@ -22,7 +22,7 @@ printExtendedUsage()
     local splitPattern='/^Note:/'
     "$GIT_DOEXTENSIONS_WRAPPEE" --help 2>&1 | sed \
 	-e "${splitPattern},\$d" \
-	-e '/^Usage:$/N' -e '/\(^\|\n\)Usage: */{ s/\(^\|\n\)\(Usage: *\)\?\([^ ]\+ \)*'"${GIT_DOEXTENSIONS_WRAPPEE} /\\1\\2${wrapper}"' [--untracked|--dirty|--wips [(+|-)CHECK [(+|-)...]]|--same-branch [-b|--branch BRANCH]] /; }'
+	-e '/^Usage:$/N' -e '/\(^\|\n\)Usage: */{ s/\(^\|\n\)\(Usage: *\)\?\([^ ]\+ \)*'"${GIT_DOEXTENSIONS_WRAPPEE} /\\1\\2${wrapper}"' [--untracked|--dirty|--stageable|--wips [(+|-)CHECK [(+|-)...]]|--same-branch [-b|--branch BRANCH]] /; }'
     cat <<HELPTEXT
 Supports the following special commands and options:
     repo-missing	    Show those $GIT_DOEXTENSIONS_WHAT that are not yet
@@ -46,6 +46,17 @@ Supports the following special commands and options:
 			    You can abort the iteration by exiting the shell
 			    with exit status 126.
     --dirty		    Also available as a standalone predicate (to combine
+			    with other COMMAND(s)).
+    stageable-sh [COMMAND ...]
+			    Open an interactive shell / execute COMMAND in those
+			    $GIT_DOEXTENSIONS_WHAT that have new files not yet
+			    added to version control (and not covered by the
+			    ignore patterns) and/or files with an unstaged
+			    modification.
+			    Equivalent to untracked + dirty - staged files.
+			    You can abort the iteration by exiting the shell
+			    with exit status 126.
+    --stageable		    Also available as a standalone predicate (to combine
 			    with other COMMAND(s)).
     wips-sh [(+|-)CHECK [(+|-)...]] [COMMAND ...]
 			    Open an interactive shell / execute COMMAND in those
@@ -111,6 +122,7 @@ parseCommand()
 
 	    --untracked)    shift; wcdoArgs+=(--predicate-command 'git untracked');;
 	    --dirty)	    shift; wcdoArgs+=(--predicate-command 'git-dirty --quiet');;
+	    --stageable)    shift; wcdoArgs+=(--predicate-command 'git-stageable');;
 	    --wips)	    shift
 			    typeset -a wipsArgs=()
 			    while [ $# -gt 0 ] && [[ "$1" =~ ^[+-][[:alpha:]]+$ ]]
@@ -214,6 +226,18 @@ parseCommand()
 		# Synthesized new command.
 		shift
 		wcdoArgs+=(--predicate-command 'git-dirty --quiet')
+		if [ $# -eq 0 ]; then
+		    wcdoArgs+=("${shellInteractiveWcdoArgs[@]}" --command "$quotedShell -i")
+		    echo "Note: To abort the iteration of $GIT_DOEXTENSIONS_WHAT, use \"exit 126\"."
+		else
+		    printf -v quotedSimpleCommand '%q ' "$@"
+		    wcdoArgs+=("${shellCommandWcdoArgs[@]}" --command "${quotedSimpleCommand# }")
+		fi
+		;;
+	    stageable-sh)
+		# Synthesized new command.
+		shift
+		wcdoArgs+=(--predicate-command 'git-stageable')
 		if [ $# -eq 0 ]; then
 		    wcdoArgs+=("${shellInteractiveWcdoArgs[@]}" --command "$quotedShell -i")
 		    echo "Note: To abort the iteration of $GIT_DOEXTENSIONS_WHAT, use \"exit 126\"."
