UI: FIX: Use $actionName

diff --git a/bin/git-repofilemove b/bin/git-repofilemove
--- a/bin/git-repofilemove
+++ b/bin/git-repofilemove
@@ -153,10 +153,10 @@ moveFile()
     local targetFilespec="${1:?}"; shift
     if [ -e "$targetFilespec" ]; then
 	if [ "$isRecordOnly" ]; then
-	    printf >&2 'Note: Not moving %s; the target already exists: %s\n' "$sourceFilespec" "$targetFilespec"
+	    printf >&2 'Note: Do not %s %s; the target already exists: %s\n' "${actionName,,}" "$sourceFilespec" "$targetFilespec"
 	    return 0
 	else
-	    printf >&2 'ERROR: Cannot move %s; the target already exists: %s\n' "$sourceFilespec" "$targetFilespec"
+	    printf >&2 'ERROR: Cannot %s %s; the target already exists: %s\n' "${actionName,,}" "$sourceFilespec" "$targetFilespec"
 	    return 1
 	fi
     fi
