git-{ff,re}integrate[to]: FIX: Default checks via environment variable should also be added to checkCommandArgs
Doesn't matter if those are exported in the invoking shell, but if those have been explicitly passed, they otherwise would be lost on --continue.
Also mention "Checks are disabled." if --no-checks is given (regardless of whether there actually are checks - I'm too lazy to check).

diff --git a/bin/git-reintegrate b/bin/git-reintegrate
--- a/bin/git-reintegrate
+++ b/bin/git-reintegrate
@@ -168,19 +168,27 @@ if [ "${!#}" = '-' ]; then
     isCheckFromStdin=t
     set -- "${@:1:$(($#-1))}"
 fi
-if [ "$isCheckFromStdin" ]; then
-    if [ ${#checkCommands[@]} -gt 0 ]; then
-	echo 'ERROR: Cannot combine CHECK-COMMANDLINE from stdin (-) with -c|--command|--exec.'
-	echo
-	printUsage "$0"
-	exit 2
-    fi >&2
-elif [ -n "$GIT_REINTEGRATE_CHECK_COMMAND" -a ${#checkCommands[@]} -eq 0 ]; then
-    checkCommands=("$GIT_REINTEGRATE_CHECK_COMMAND")
-elif [ -n "$GIT_CHECK_COMMAND" -a ${#checkCommands[@]} -eq 0 ]; then
-    checkCommands=("$GIT_CHECK_COMMAND")
+if [ "$isCheckFromStdin" ] && [ ${#checkCommands[@]} -gt 0 ]; then
+    echo 'ERROR: Cannot combine CHECK-COMMANDLINE from stdin (-) with -c|--command|--exec.'
+    echo
+    printUsage "$0"
+    exit 2
+fi >&2
+if [ "$isDisableChecks" ]; then
+    echo 'Checks are disabled.'
+    checkCommands=()
 else
-    echo 'No checks to run.'
+    if [ "$isCheckFromStdin" ]; then
+	:
+    elif [ -n "$GIT_REINTEGRATE_CHECK_COMMAND" -a ${#checkCommands[@]} -eq 0 ]; then
+	checkCommands=("$GIT_REINTEGRATE_CHECK_COMMAND")
+	checkCommandArgs+=(--command "$GIT_REINTEGRATE_CHECK_COMMAND")
+    elif [ -n "$GIT_CHECK_COMMAND" -a ${#checkCommands[@]} -eq 0 ]; then
+	checkCommands=("$GIT_CHECK_COMMAND")
+	checkCommandArgs+=(--command "$GIT_CHECK_COMMAND")
+    else
+	echo 'No checks to run.'
+    fi
 fi
 if [ -z "${isPush+t}" -a -n "$HUB" ]; then
     # Need to push to remote first so that GitHub recognizes that the branch has
@@ -188,7 +196,6 @@ if [ -z "${isPush+t}" -a -n "$HUB" ]; then
     # pull request as "closed".
     isPush=t
 fi
-[ "$isDisableChecks" ] && checkCommands=()
 
 branches+=("$@")
 if [ ${#branches[@]} -eq 0 ]; then
