ENH: Add git-committemplate --edit and precommit alias
For recording a commit message (for the staged files), without actually commiting yet. This is an alternative to stashing, when one wants to delay the commit without undoing the changes.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.92.0 (2026-04-28), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-committemplate b/bin/git-committemplate
--- a/bin/git-committemplate
+++ b/bin/git-committemplate
@@ -22,6 +22,13 @@ HELPTEXT
     printf 'Usage: echo TEXT | %q %s\n' "$(basename "$1")" '--save|--append'
     echo
     cat <<HELPTEXT
+Open the editor to record the commit template for a commit based on the current
+HEAD [for <pathspec>].
+HELPTEXT
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" '--edit [-m|--message MESSAGE] [-F|--file FILE] [--] [<pathspec>...]'
+    echo
+    cat <<HELPTEXT
 Delete any residual commit template(s).
 HELPTEXT
     echo
@@ -35,10 +42,11 @@ case "$1" in
     --get-filespec)	shift; action=getFilespec;;
     --save)		shift; action=save;;
     --append)		shift; action=save; saveOperator='>>';;
+    --edit)		shift; action=edit;;
     --clean)		shift; action=clean;;
     -*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 esac
-if [ $# -ne 0 ]; then
+if [ $# -ne 0 -a "$action" != 'edit' ]; then
     printUsage "$0" >&2
     exit 2
 fi
@@ -56,6 +64,44 @@ getFilespec()
 save()
 {
     eval "exec cat $saveOperator \"\${commitTemplateFilespec:?}\""
+}
+
+edit()
+{
+    local commitMessageFilespec="${gitDir}/COMMIT_EDITMSG"
+    {
+	local hasMessage
+	while [ $# -ne 0 ]
+	do
+	    case "$1" in
+		--message|-m)	shift; printf '%s\n' "$1"; shift; hasMessage=t;;
+		--file|-F)	shift; cat -- "$1"; shift; hasMessage=t;;
+		--)		break;;
+		-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+		*)		break;;
+	    esac
+	done
+	[ "$hasMessage" ] || printf '\n\n'  # Leave the first two lines blank for the user to fill in.
+	cat <<'EOF'
+# Please enter the pending commit message for your changes. Lines
+# starting with '#' will be ignored, and an empty message aborts the
+# recording of the commit message.
+#
+EOF
+	# Add commit boilerplate information at the bottom, just like a real commit
+	# message. It'll be stripped out before saving.
+	command git commit --dry-run "$@" | prefix \#\ | truncate-whitespace --trailing
+
+	# Automatic commit trailers are not part of the pre-commit message; these will
+	# be added on the commit itself.
+    } > "$commitMessageFilespec"
+
+    "$EDITOR" "$commitMessageFilespec" || { status=$?; echo 2>&1 "Unclean exit of editor; aborting!"; exit $status; }
+
+    git-commitMessageStrip --in-place "$commitMessageFilespec"
+
+    [ -s "$commitMessageFilespec" ] || { echo >&2 'Aborting: Empty commit message.'; exit 1; }
+    saveOperator='< "$commitMessageFilespec" >' save
 }
 
 clean()
