git-editstage: UI: Cosmetics: Improve error message

diff --git a/bin/git-editstage b/bin/git-editstage
--- a/bin/git-editstage
+++ b/bin/git-editstage
@@ -55,7 +55,7 @@ fi
 if [ ! "$isContinue" ] && [ ${#paths[@]} -eq 0 ]; then
     readarray -t paths < <(git-staged)
     if [ ${#paths[@]} -eq 0 ]; then
-	echo >&2 'ERROR: No staged files found.'
+	echo >&2 'ERROR: Nothing staged.'
 	exit 1
     fi
 elif [ "$isContinue" ] && [ ${#paths[@]} -gt 0 ]; then
