Robustness: Check for empty input branches
For git-archivelocalbr, continuing would mean use of _all_ branches, which would be unexpected.

diff --git a/bin/git-archivelocalbr b/bin/git-archivelocalbr
--- a/bin/git-archivelocalbr
+++ b/bin/git-archivelocalbr
@@ -20,6 +20,11 @@ if [ "$1" = '--branches' ]; then
     shift
     inputBranches=($1)
     shift
+
+    if [ ${#inputBranches[@]} -eq 0 ]; then
+	echo >&2 'ERROR: No branches passed to --branches.'
+	exit 2
+    fi
 fi
 isQuiet=
 isYes=
