ENH: Support direct commit via --commit
It's too cumbersome to supply --edit, then quit the stash message editor, and commit manually.

System-info: Armbian 24.11.1 noble, aarch64
Platform-info: git version 2.47.0, hub version 2.14.2, gh version 2.62.0 (2024-11-14), git-lfs/3.5.1 (GitHub; linux arm64; go 1.21.8)

diff --git a/bin/git-stash-join b/bin/git-stash-join
--- a/bin/git-stash-join
+++ b/bin/git-stash-join
@@ -1,30 +1,54 @@
 #!/bin/bash
 
+printShortUsage()
+{
+    # Note: short followed by long option; if the user knows the short one, she can
+    # skim the long one.
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-n|--count N] [--commit] [-e|--edit|--no-edit] [-m|--message=MESSAGE|-F|--file=FILE [...]] [-?|-h|--help]'
+}
 printUsage()
 {
-    cat <<HELPTEXT
+    # This is the short help when launched with no or incorrect arguments.
+    # It is printed to stderr to avoid accidental processing.
+    printShortUsage "$1" >&2
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
+}
+printLongUsage()
+{
+    # This is the long "man page" when launched with the help argument.
+    # It is printed to stdout to allow paging with 'more'.
+    cat <<HELPDESCRIPTION
 Join the last two / N stashes together into a single one.
-HELPTEXT
+HELPDESCRIPTION
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-n|--count N] [-e|--edit|--no-edit] [-m|--message=MESSAGE|-F|--file=FILE [...]] [-?|-h|--help]'
+    printShortUsage "$1"
+    echo
+    cat <<HELPTEXT
+    --count|-n N	Join the last N stashes together.
+    --commit		Commit the joined stashes instead of creating a single
+			new stash.
+HELPTEXT
 }
 
 action=join
+storeAction=git-stash-push
+storeWhat='saved'
 continueIndex=
 count=2
-typeset -a stashPushArgs=()
+typeset -a storeArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--count|-n)	shift; count="${1:?}"; shift;;
+	--commit)	shift; storeAction=git-commit; storeWhat='committed';;
 	--continue)	shift; continueIndex="${1:?}"; shift;;
 	--cleanup)	shift; action=cleanup;;
-	--)		stashPushArgs+=("$1"); shift; break;;
-	*)		stashPushArgs+=("$1"); shift;;
+	--)		storeArgs+=("$1"); shift; break;;
+	*)		storeArgs+=("$1"); shift;;
     esac
 done
-set -- "${stashPushArgs[@]}" "$@"
+set -- "${storeArgs[@]}" "$@"
 
 join()
 {
@@ -59,13 +83,13 @@ join()
 	stashHashes+=("$(git rev-parse "$currentStash")") || return 3
     done
 
-    if git-stash-push --message="$concatenatedStashMessages" "$@"; then
+    if $storeAction --message="$concatenatedStashMessages" "$@"; then
 	:
     else
 	status=$?
 	local quotedStashHashes; printf -v quotedStashHashes ' %q' "${stashHashes[@]}"
-	printf >&2 'ERROR: Joined stashes have not been saved. Wipe the working copy to undo, or\n       "git stash push", or alternatively directly commit the joined stashes.\n       Then, remove the original stashes via\n       $ %q --cleanup%s\n' \
-	    "$(basename "$0")" "$quotedStashHashes"
+	printf >&2 'ERROR: Joined stashes have not been %s. Wipe the working copy to undo, or\n       "git stash push", or alternatively directly commit the joined stashes.\n       Then, remove the original stashes via\n       $ %q --cleanup%s\n' \
+	    "$storeWhat" "$(basename "$0")" "$quotedStashHashes"
 	return $status
     fi
 
