ENH: Add git-onemorelg and use that in git-selectedcommit-command --one-more
A plain A..B range can be extended by appending "^": A^..B, but even that requires parsing. Not all ranges can be extended. It's worse if FILE(s) are involved. A range just selects commits, regardless of which files are affected.
For commands like catselected and cpselected, we'd like to include one more commit _that affects the passed FILEs_.
To obtain that, let's parse off the range (implementation taken from git-selectedcommit-command), and execute once with that range, then without any range, and include the line just beyond the first log's output. This means that it only works with one-line output (and no coloring), but for the internal use this is fine.

diff --git a/bin/git-selectedcommit-command b/bin/git-selectedcommit-command
--- a/bin/git-selectedcommit-command
+++ b/bin/git-selectedcommit-command
@@ -5,7 +5,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--last-only] [--accept-single] [--single-only] [--range-is-last] [--pass-file-args] [--allow-outside-workingcopy] ... --since <date>|--max-count <number>|-n <number>|<range>|--range <range> [--range ...] [GIT-COMMAND-ARGS ...] [--] [FILE ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--last-only] [--accept-single] [--single-only] [--range-is-last] [--pass-file-args] [--one-more] [--allow-outside-workingcopy] ... --since <date>|--max-count <number>|-n <number>|<range>|--range <range> [--range ...] [GIT-COMMAND-ARGS ...] [--] [FILE ...] [-?|-h|--help]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... GIT-COMMAND [GIT-COMMAND-ARGS ...]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... --keep-position GIT-COMMAND [... COMMITS ...]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... [-2 GIT-COMMAND ARG1|-3 GIT-COMMAND ARG1 ARG2|...] [...]'
@@ -43,6 +43,8 @@ HELPDESCRIPTION
     --pass-file-args
 		    Pass FILE arguments also to GIT-COMMAND, and not just use
 		    them to determine the commits.
+    --one-more	    Offer the first commit [affecting FILE(s)] after the range
+		    as well.
     --allow-outside-workingcopy
 		    Use git-inside to also resolve commits from outside the
 		    current working copy. If --pass-file-args is also passed,
@@ -66,6 +68,12 @@ do
 			shift; isRangeLastArg=t;;
 	--pass-file-args)
 			shift; isPassFileArgs=t;;
+	--one-more)	shift;
+			if [ -n "$GIT_SELECTEDCOMMIT_COMMAND" ]; then
+			    echo >&2 'ERROR: --one-more cannot be combined with a custom $GIT_SELECTEDCOMMIT_COMMAND.'
+			    exit 2
+			fi
+			GIT_SELECTEDCOMMIT_COMMAND="onemorelg${isRangeLastArg:+ --range-is-last}";;
 	--allow-outside-workingcopy)
 			shift; isAllowOutsideWorkingCopy=t;;
 	*)		break;;
@@ -201,7 +209,7 @@ fi
 
 commitSource()
 {
-    eval "git${files:+${isAllowOutsideWorkingCopy:+-inside}} ${GIT_SELECTEDCOMMIT_COMMAND:-log}" '"$@" "${rangeModificationArgs[@]}" "${rangeArgs[@]}" ${files:+${isAllowOutsideWorkingCopy:+\$FILE }--} "${files[@]}"'
+    eval "git${files:+${isAllowOutsideWorkingCopy:+-inside}} ${GIT_SELECTEDCOMMIT_COMMAND:-log}" '"${rangeModificationArgs[@]}" "${rangeArgs[@]}" "$@" ${files:+${isAllowOutsideWorkingCopy:+\$FILE }--} "${files[@]}"'
 }
 
 appendMergeIndicator()
