git-up: ENH: Also handle update of detached working copy
For lack of a branch, we cannot pull / rebase then, so only GIT_UP_FETCH=t GIT_UP_NO_UPDATE=t could be used so far.
Treat a detached working copy like a fetch-only, but attempt to do logging against the remote's base or master branch.

diff --git a/bin/git-up b/bin/git-up
--- a/bin/git-up
+++ b/bin/git-up
@@ -23,6 +23,12 @@ HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" "[--gui|--terminal|--none] [-q|--quiet] ${remote:-REMOTE} [PULL/REBASE-ARGS ...] [-?|-h|--help]"
 }
 
+getDetachedBranch()
+{
+    git-nbr 2>/dev/null || \
+	git-mbr 2>/dev/null
+}
+
 getRemoteBranch()
 {
     if [ $# -gt 0 ] && git-existsbr "${!#}"; then
@@ -76,6 +82,14 @@ else
 	    [ "${logDeltaArgs[*]}" = '--none' ] || echo >&2 "Warning: Could not determine corresponding ${remote:-REMOTE} branch, no logging possible."
 	    logDeltaArgs=(--none)
 	fi
+    elif git-isdetached; then
+	# On a detached checkout, fall back to the base / master branch.
+	if branch="$(getDetachedBranch)"; then
+	    logDeltaArgs+=(--branch "${remote}/${branch}")
+	else
+	    [ "${logDeltaArgs[*]}" = '--none' ] || echo >&2 "Warning: Detached working copy, and could not determine base / master ${remote:-REMOTE} branch, no logging possible."
+	    logDeltaArgs=(--none)
+	fi
     fi
 
     exec git-logdelta "${colorArg[@]}" "${logDeltaArgs[@]}" -- "$scriptFilespec" "${remote:?}" --launch "$@"
@@ -112,6 +126,10 @@ if [ "$GIT_UP_NO_UPDATE" ]; then
 elif [ "$GIT_UP_REBASE" ]; then
     remoteBranch="$(getRemoteBranch "$@")" || exit $?
     git "${gitAutoStashGitArg[@]}" rebase "${gitAutoStashPullOrRebaseArg[@]}" "${gitRebaseMergesArg[@]}" "${@:1:$(($#-1))}" "$remoteBranch" || exit $?
+elif git-isdetached; then
+    # Checkout (and keep detached) latest base / master branch.
+    branch="$(getDetachedBranch)" && git-existsbr "${remote}/${branch}" || exit $?
+    git checkout --detach "${remote}/${branch}"
 else
     git "${gitAutoStashGitArg[@]}" pull "${gitAutoStashPullOrRebaseArg[@]}" "${gitPullRebaseMergesArg[@]}" "$remote" "$@" || exit $?
 fi
