git-decorated: ENH: Accept --decorate[-refs[-exclude]] parameters from git-log

diff --git a/bin/git-decorated b/bin/git-decorated
--- a/bin/git-decorated
+++ b/bin/git-decorated
@@ -1,4 +1,5 @@
 #!/bin/bash
+shopt -qs extglob
 
 printUsage()
 {
@@ -6,16 +7,30 @@ printUsage()
 Show the (short) ref names of the current / passed revision(s).
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[<commit-ish> ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--decorate[=short|full|auto|no]] [--decorate-refs=<pattern>] [--decorate-refs-exclude=<pattern>] [--] [<commit-ish> ...] [-?|-h|--help]'
 }
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-esac
+
+typeset -a logDecorateArgs=()
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--decorate|--decorate=*)
+			logDecorateArgs+=("$1"); shift;;
+	--decorate-refs?(-exclude))
+			logDecorateArgs+=("$1" "${2?}"); shift; shift;;
+	--decorate-refs?(-exclude)=*)
+			logDecorateArgs+=("$1"); shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 [ $# -eq 0 ] && set -- HEAD
 
 status=0
 for rev
 do
-    git log --max-count 1 --pretty='format:%D' "$rev" -- || status=$?
+    git log --max-count 1 "${logDecorateArgs[@]}" --pretty='format:%D' "$rev" -- || status=$?
 done
 exit $status
