git-mbr: ENH: Check for actual existence of master or main branches, and use the first that exists
And also persist that information. Without that, the command would continuously print the "Note: ..." if for example no remotes are defined so the above determination would remain inconclusive.
If none of the candidate branches actually exists, print nothing and fail (so clients will notice and not act on wrong information).

diff --git a/bin/git-mbr b/bin/git-mbr
--- a/bin/git-mbr
+++ b/bin/git-mbr
@@ -34,8 +34,19 @@ if [ -z "$masterBranch" ]; then
 	done
     fi
     if [ -z "$masterBranch" ]; then
-	echo >&2 'Note: The name of the master branch could not be determined; defaulting to "master".'
-	masterBranch=master
+	for candidateBranch in master main
+	do
+	    if git-existsbr "$candidateBranch"; then
+		printf >&2 'Note: The name of the master branch could not be determined; defaulting to "%s".\n' "$candidateBranch"
+		masterBranch="$candidateBranch"
+		setMasterBranchConfiguration "$masterBranch"
+		break
+	    fi
+	done
+	if [ -z "$masterBranch" ]; then
+	    echo >&2 'ERROR: The name of the master branch could not be determined.'
+	    exit 1
+	fi
     fi
 fi
 
