ENH: Allow any rev as arguments, translate to more readable form via git-desc
Renaming: Use {base,other}Rev instead of {base,other}Branch

diff --git a/bin/git-inout b/bin/git-inout
--- a/bin/git-inout
+++ b/bin/git-inout
@@ -5,11 +5,11 @@ printUsage()
 {
     cat <<HELPTEXT
 Show incoming and outgoing commit logs between current / passed <branch> and its
-remote tracked branch / passed <other-branch> / corresponding remote branch of
-passed <remote>.
+remote tracked branch / passed <other-branch> / passed <commit> and
+<other-commit> / corresponding remote branch of passed <remote>.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[<remote>|(<branch> [<other-branch>])] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[<remote>|(<branch>|<commit> [<other-branch>|<other-commit>])] [-?|-h|--help]'
 }
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
@@ -17,29 +17,31 @@ esac
 
 ensureValidRef()
 {
-    if ! git-existsbr "$1"; then
-	printf >&2 'ERROR: Branch %s does not exist!\n' "$1"
+    local ref="${1:?}"; shift
+    if ! git rev-parse --verify --quiet "$ref" >/dev/null 2>&1; then
+	printf >&2 'ERROR: %s does not exist!\n' "$ref"
 	exit 1
     fi
 }
 
 case $# in
-    2)	baseBranch="$1"
-	otherBranch="$2"
+    2)	baseRev="$(git-desc "$1")" || exit $?; shift
+	otherRev="$(git-desc "$1")" || exit $?; shift
 	;;
-    1)	baseBranch="$(git-brname --real-branch-only)" || exit $?
+    1)	baseRev="$(git-brname --real-branch-only)" || exit $?
 	case "$1" in
-	    */*)    otherBranch="$1";;
+	    */*)    otherRev="$1";;
 	    *)	    if git-existsremote "$1"; then
-			otherBranch="$(git-remotebr "$1")" || exit $?
+			otherRev="$(git-remotebr "$1")" || exit $?
 		    else
-			otherBranch="$1"
+			otherRev="$(git-desc "$1")" || exit $?
 		    fi
 		    ;;
 	esac
+	shift
 	;;
-    0)	baseBranch="$(git-brname --real-branch-only)" || exit $?
-	otherBranch="$(git tracks)" || exit $?
+    0)	baseRev="$(git-brname --real-branch-only)" || exit $?
+	otherRev="$(git tracks)" || exit $?
 	;;
     *)	printUsage >&2 "$0"
 	exit 2
@@ -53,18 +55,18 @@ if [ -t 1 ]; then
 else
     pager=()
 fi
-ensureValidRef "$baseBranch"
-ensureValidRef "$otherBranch"
+ensureValidRef "$baseRev"
+ensureValidRef "$otherRev"
 
 inout()
 {
     local status=1
     local padding=$'\n'
-    GIT_ONELINELOG_DIRECT_ARG=--no-pager git-onelinelog "${gitColorArg[@]}" "$baseBranch..$otherBranch" | \
-	outputAndPrintf "incoming ${otherBranch} -> ${baseBranch}:\\n" && status=0 || padding=''
+    GIT_ONELINELOG_DIRECT_ARG=--no-pager git-onelinelog "${gitColorArg[@]}" "$baseRev..$otherRev" | \
+	outputAndPrintf "incoming ${otherRev} -> ${baseRev}:\\n" && status=0 || padding=''
 
-    GIT_ONELINELOG_DIRECT_ARG=--no-pager git-onelinelog "${gitColorArg[@]}" "$otherBranch..$baseBranch" | \
-	outputAndPrintf "${padding}outgoing ${baseBranch} -> ${otherBranch}:\\n" && status=0
+    GIT_ONELINELOG_DIRECT_ARG=--no-pager git-onelinelog "${gitColorArg[@]}" "$otherRev..$baseRev" | \
+	outputAndPrintf "${padding}outgoing ${baseRev} -> ${otherRev}:\\n" && status=0
 
     return $status
 }
