git-localbrdo: Remove the obsolete interrupt suppression message, add abort note
Interrupting is now suppressed by omitting the --interrupt-on* options.
As aborting will restore the original branch (and that one prints a message, anyway), let's be explicit about the reason for aborting.

diff --git a/bin/git-localbrdo b/bin/git-localbrdo
--- a/bin/git-localbrdo
+++ b/bin/git-localbrdo
@@ -209,6 +209,7 @@ abortIfDesired()
     local status="${1:?}"; shift
     [ -n "$abortStatus" ] || return
     if [ "$status" $abortComparison $abortStatus ];then
+	[ "$isQuiet" ] || printf >&2 'Note: Aborting iteration because the command failed (with exit status %d).\n' "$status"
 	restoreOriginalBranch
 	exit $status
     fi
@@ -219,8 +220,7 @@ interruptIfDesired()
     local status="${1:?}"; shift
     [ -n "$interruptStatus" ] || return
     if [ "$status" $interruptComparison $interruptStatus ];then
-	printf >&2 'Note: Interrupting iteration because the command failed (with exit status %d). Please check and then continue with --continue.\n' "$status"
-	echo >&2 'You can suppress checking of exit status by appending "|| :" to the COMMANDLINE.'
+	[ "$isQuiet" ] || printf >&2 'Note: Interrupting iteration because the command failed (with exit status %d). Please check and then continue with --continue.\n' "$status"
 	exit $status
     fi
 }
