git-wips: Robustness: Complain about unknown arguments instead of hanging forever

diff --git a/bin/git-wips b/bin/git-wips
--- a/bin/git-wips
+++ b/bin/git-wips
@@ -48,9 +48,12 @@ do
 	    checks["${1:1}"]=t
 	    shift
 	    ;;
-	-*) unset checks["${1:1}"]
+	-[^-]?*)
+	    unset checks["${1:1}"]
 	    shift
 	    ;;
+	-*) { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)  printUsage "$0" >&2; exit 2;;
     esac
     isFirst=
 done
