git-selectedcommit-command: Refactoring: Extract getSelected()

diff --git a/bin/git-selectedcommit-command b/bin/git-selectedcommit-command
--- a/bin/git-selectedcommit-command
+++ b/bin/git-selectedcommit-command
@@ -48,6 +48,8 @@ HELPDESCRIPTION
 		    GIT-COMMAND must be able to deal with those files, too.
 HELPTEXT
 }
+
+action=getSelected
 isRangeLastArg=
 isPassFileArgs=
 isAllowOutsideWorkingCopy=
@@ -206,25 +208,30 @@ appendMergeIndicator()
 
 }
 
-readarray -t commits < <(
-    : ${GIT_SELECTEDCOMMIT_COMMAND_FORMAT:=$'%s\t%p'}
-    mergeIndicatorCommand=; [[ "$GIT_SELECTEDCOMMIT_COMMAND_FORMAT" =~ $'\t'%p$ ]] && mergeIndicatorCommand=appendMergeIndicator
-    commitSource --pretty="tformat:%H $GIT_SELECTEDCOMMIT_COMMAND_FORMAT" \
-	"${mergeIndicatorCommand:+|}$mergeIndicatorCommand" \
-	| truncate-trailing -w \
-	| commandWithHiddenId --stdin -p -c "commandOnSelected --stdin${commandOnSelectedArgs:+ }${commandOnSelectedArgs[*]}"
-    printf '\n%d\n' "$?"
-)   # Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
-status=${commits[-1]}
-unset 'commits[-1]'
-[ -z "${commits[-1]}" ] && unset 'commits[-1]'
+typeset -a commits=()
+getSelected()
+{
+    readarray -t commits < <(
+	: ${GIT_SELECTEDCOMMIT_COMMAND_FORMAT:=$'%s\t%p'}
+	mergeIndicatorCommand=; [[ "$GIT_SELECTEDCOMMIT_COMMAND_FORMAT" =~ $'\t'%p$ ]] && mergeIndicatorCommand=appendMergeIndicator
+	commitSource --pretty="tformat:%H $GIT_SELECTEDCOMMIT_COMMAND_FORMAT" \
+	    "${mergeIndicatorCommand:+|}$mergeIndicatorCommand" \
+	    | truncate-trailing -w \
+	    | commandWithHiddenId --stdin -p -c "commandOnSelected --stdin${commandOnSelectedArgs:+ }${commandOnSelectedArgs[*]}"
+	printf '\n%d\n' "$?"
+    )   # Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+    status=${commits[-1]}
+    unset 'commits[-1]'
+    [ -z "${commits[-1]}" ] && unset 'commits[-1]'
 
-if [ $status -eq 124 ]; then
-    echo >&2 'ERROR: No commits available.'
-    exit 1
-elif [ $status -ne 0 ]; then
-    exit $status
-fi
+    if [ $status -eq 124 ]; then
+	echo >&2 'ERROR: No commits available.'
+	return 1
+    elif [ $status -ne 0 ]; then
+	return $status
+    fi
+}
 
+$action || exit $?
 [ "$isPassFileArgs" ] || files=()
 executor "$@" ${files:+--} "${files[@]}"
