git-super{only,sub}reintegratetom: ENH: Allow configuration of integration in GitHub
I only want the integration in GitHub offered for superproject-only pull requests; for the rest, I prefer to do this locally. The configuration allows me to pre-answer the question.

diff --git a/bin/git-superonlyreintegratetom b/bin/git-superonlyreintegratetom
--- a/bin/git-superonlyreintegratetom
+++ b/bin/git-superonlyreintegratetom
@@ -34,6 +34,10 @@ reintegration is a simple fast-forward.
 Performs additional sanity checks and chooses the right arguments based on
 whether this is a short-lived feature with a single superproject commit or full
 history exists.
+The answers to some questions can be preconfigured via these boolean config
+settings; when not configured (true or false), the user will be prompted every
+time:
+- reintegrate.superonlyproject-in-hub	integrate superproject in and by GitHub
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
@@ -76,7 +80,17 @@ case $(git bomcount) in
 	;;
 esac
 
-[ "$HUB" ] && hub-integrate --offer "${integrateArgs[@]}" "$@" && exit 0
+if [ "$HUB" ]; then
+    if choice="$(git config --type bool --get reintegrate.superonlyproject-in-hub)"; then
+	case "$choice" in
+	    true)   hub-integrate --make-ready "${integrateArgs[@]}" "$@" && exit 0;;
+	    false)  ;;
+	    *)	    printf >&2 'ASSERT: Invalid choice: %s\n' "$choice"; exit 3;;
+	esac
+    else
+	hub-integrate --offer "${integrateArgs[@]}" "$@" && exit 0
+    fi
+fi
 
 git-dirty --print-error --error-message 'ERROR: The superproject working copy is still dirty.' \
     && exit 1
diff --git a/bin/git-supersubreintegratetom b/bin/git-supersubreintegratetom
--- a/bin/git-supersubreintegratetom
+++ b/bin/git-supersubreintegratetom
@@ -33,6 +33,11 @@ fast-forward.
 Performs additional sanity checks and chooses the right arguments based on
 whether this is a short-lived feature with a single superproject commit or full
 history exists.
+The answers to some questions can be preconfigured via these boolean config
+settings; when not configured (true or false), the user will be prompted every
+time:
+- reintegrate.superproject-in-hub   integrate superproject in and by GitHub
+- reintegrate.submodule-in-hub	    integrate submodule(s) in and by GitHub
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
@@ -231,7 +236,17 @@ fetchFirst()
 
 reintegrateSubmodule()
 {
-    [ "$HUB" ] && "${submoduleExecutor[@]:-git-wrapper}" ${submoduleExecutor:+--interactive} integrate --offer "$@" && return
+    if [ "$HUB" ]; then
+	if choice="$(git config --type bool --get reintegrate.submodule-in-hub)"; then
+	    case "$choice" in
+		true)   "${submoduleExecutor[@]:-git-wrapper}" ${submoduleExecutor:+--interactive} integrate --make-ready "$@" && return;;
+		false)  ;;
+		*)	printf >&2 'ASSERT: Invalid choice: %s\n' "$choice"; exit 3;;
+	    esac
+	else
+	    "${submoduleExecutor[@]:-git-wrapper}" ${submoduleExecutor:+--interactive} integrate --offer "$@" && return
+	fi
+    fi
 
     fetchFirst
 
@@ -322,7 +337,15 @@ reintegrateSuperproject()
 	if ! "${submoduleExecutor[@]:-git-wrapper}" ${submoduleExecutor:+--no-pager --separate-errors} outlg \
 	    | outputAndPrintf 'Note: Submodule(s) have outgoing reintegration commits; integration in and by GitHub not possible:\n'
 	then
-	    hub-integrate --offer "${integrateArgs[@]}" "$@" && return
+	    if choice="$(git config --type bool --get reintegrate.superproject-in-hub)"; then
+		case "$choice" in
+		    true)   hub-integrate --make-ready "${integrateArgs[@]}" "$@" && return;;
+		    false)  ;;
+		    *)	    printf >&2 'ASSERT: Invalid choice: %s\n' "$choice"; exit 3;;
+		esac
+	    else
+		hub-integrate --offer "${integrateArgs[@]}" "$@" && return
+	    fi
 	fi
     fi
 
