BUG: Regression: Table alignment (tab rendering) breaks parsing of result (after f1bd690a)
Render the separating tabs into columns turns the (single) separating tabs into runs of spaces.
Because the relative date itself contains (a variable amount of) spaces and we want the following working copy, too (which potentially might include spaces as well), just changing IFS isn't enough.
Moving the working copy column before the date breaks alignment.
Instead, implement color highlighting (as in git-onelinelog) for the different columns, and use that new feature to extract the right fields. As the selection always is interactive, we'll always have coloring.

(This corrects commit f1bd690a23d6d744d0f701ea577f254ec66d067a)

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.86.0 (2026-01-21), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-selectedrecentcommit-command b/bin/git-selectedrecentcommit-command
--- a/bin/git-selectedrecentcommit-command
+++ b/bin/git-selectedrecentcommit-command
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+: ${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_COMMIT='[36m'}
+: ${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_DATE='[32m'}
+: ${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_WORKINGCOPY='[35m'}
+: ${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_SUBJECT='[0m'}
+: ${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_RESET='[0m'}
+
 printUsage()
 {
     cat <<HELPTEXT
@@ -26,6 +32,7 @@ do
 			commandOnSelectedArgs+=("$1"); shift;;
 	--generate)	shift
 			reldate --date-pattern '' -- "${XDG_CACHE_HOME:-${HOME}/.cache}/git-recentcommits" \
+			    | sed -e 's#^\([^\t]\+\)\t\([^\t]\+\)\t\([^\t]\+\)\t\(.*\)$#'"${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_COMMIT}\\1${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_RESET}\\t${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_DATE}\\2${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_RESET}\\t${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_WORKINGCOPY}\\3${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_RESET}\\t${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_SUBJECT}\\4${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_RESET}#" \
 			    | column -s $'\t' -t
 			exit $?
 			;;
@@ -108,13 +115,14 @@ esac
 
 typeset -a commits=()
 exitStatus=
-while IFS=$'\t' read -r commitId commitDate workingCopy subject || { exitStatus="$commitId"; break; }	# Exit status from the process substitution (<()) is lost; return the actual exit status via an incomplete (i.e. missing the newline) last line.
+while IFS=$'\t' read -r commitId workingCopy || { exitStatus="$commitId"; break; }	# Exit status from the process substitution (<()) is lost; return the actual exit status via an incomplete (i.e. missing the newline) last line.
 do
     commits+=("$commitId" "$workingCopy")
 done < <(
     printf -v quotedScriptFilespec %q "${BASH_SOURCE[0]}"
-    commandOnSelected --generator "$quotedScriptFilespec --generate" --filter '' "${commandOnSelectedArgs[@]}" "$@"
-    printf %d "$?"
+    commandOnSelected --generator "$quotedScriptFilespec --generate" --filter '' "${commandOnSelectedArgs[@]}" "$@" \
+	| sed -e "s#^${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_COMMIT//\[/\\[}\\(.\\+\\)${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_RESET//\[/\\[}[[:space:]]\\+${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_DATE//\[/\\[}.\\+${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_RESET//\[/\\[}[[:space:]]\\+${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_WORKINGCOPY//\[/\\[}\\(.\\+\\)${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_RESET//\[/\\[}[[:space:]]\\+${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_SUBJECT//\[/\\[}.*${GIT_SELECTEDRECENTCOMMITCOMMAND_COLOR_RESET//\[/\\[}\$#\1\t\2#"
+    printf %d ${PIPESTATUS[0]}
 )
 
 if [ $exitStatus -eq 124 ]; then
