git-correct: BUG: Regression: Continues with committing when no commit ID found (after d519a54)
The loop then doesn't yield any data, but the commit still continues despite that.
As we cannot easily signal an error from inside the process substitution, add a dedicated check prior to that; it also prevents the unnecessary creation of the temp file.
(This corrects commit d519a548ce7398e8022fc5b0ab2d7c85207c6736)

diff --git a/bin/git-correct b/bin/git-correct
--- a/bin/git-correct
+++ b/bin/git-correct
@@ -71,6 +71,10 @@ do
     set -- "${@:1:$(($#-1))}"
     lastArg="${!#}"
 done
+if [ ! "$isAmend" ] && [ ${#commitIds[@]} -eq 0 ]; then
+    printf >&2 'ERROR: No commit found for %s\n' "$lastArg"
+    exit 1
+fi
 
 commitMessageFilespec="$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || echo "${TMPDIR:-/tmp}/$(basename -- "$0").$$$RANDOM")"
 cleanup()
