Refactoring: Extract countLogArgsInfluencingOutput() from git-lh to logArgParser.sh
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.47.0, hub version 2.14.2, gh version 2.55.0 (2024-08-20), git-lfs/3.6.0 (GitHub; linux amd64; go 1.23.1)

diff --git a/bin/git-lh b/bin/git-lh
--- a/bin/git-lh
+++ b/bin/git-lh
@@ -1,6 +1,12 @@
 #!/bin/bash
 shopt -qs extglob
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
+source "${libDir}/logArgParser.sh" || exit 3
+
 printUsage()
 {
     cat <<HELPTEXT
@@ -23,16 +29,15 @@ do
 	--abbrev-commit|--abbrev|--abbrev=*)
 			logArgs+=("$1"); shift; hashFormat='%h';;
 
-	# Ignore options that influence commit formatting (we need just the
-	# hashes), and diff options.
-	-+([cmtpuz])|-[LUX]?*)	shift;;
-	--@(abbrev-commit|no-abbrev-commit|oneline|no-notes|show-signature|relative-date|parents|children|left-right|graph|cc|dd|patch|no-patch|raw|patch-with-raw|numstat|shortstat|summary|patch-with-stat|binary|name-only|name-status|check|no-color|remerge-diff|no-diff-merges))	shift;;
-	-[L])	shift; shift;;
-	--@(pretty|format|notes|date|unified|stat|dirstat|submodule|color|word-diff|word-diff-regex|color-words|diff-merges|output)=*)	shift;;
-	--@(format|date|unified|word-diff-regex|diff-merges|output))	shift; shift;;
-
 	--)		shift; break;;
-	*)		logArgs+=("$1"); shift;;
+	*)		if countLogArgsInfluencingOutput "$1"; argCount=$?; [ $argCount -gt 0 ]; then
+			    # Ignore options that influence commit formatting (we need just the
+			    # hashes), and diff options.
+			    shift $argCount
+			else
+			    logArgs+=("$1"); shift
+			fi
+			;;
     esac
 done
 
