Refactoring: Delegate parsing of filterTimespan comparison parameters to it
Instead of duplicating the syntax here.

System-info: Ubuntu 24.04.4 LTS, x86_64
Platform-info: git version 2.54.0, hub version 2.14.2, gh version 2.92.0 (2026-04-28), git-lfs/3.7.1 (GitHub; linux amd64; go 1.24.4)

diff --git a/bin/git-whowhen b/bin/git-whowhen
--- a/bin/git-whowhen
+++ b/bin/git-whowhen
@@ -88,9 +88,6 @@ do
 	--first)	shift; uniqueStableArgs=(); timespanConverter=(); firstColumnType=Age;;
 	--last)		shift; uniqueStableArgs=(--last); timespanConverter=(); firstColumnType=Age;;
 
-	-s|--shorter|-l|--longer|-n|--newer|-o|--older|-lt|-le|-eq|-ne|-ge|-gt)
-			postAction=(filterFirstColumn --field-separator $'\t' "$1" "$2"); shift; shift;;
-
 	--names-only)	shift; endFilter=(field --field-separator $'\t' --remove 1);;
 
 	# Ignore options that influence commit formatting (we need just the
@@ -100,7 +97,20 @@ do
 	-[U])	shift; shift;;
 	--@(abbrev|pretty|format|notes|date|unified|stat|dirstat|submodule|color|word-diff|word-diff-regex|color-words)=*)	shift;;
 	--@(pretty|format|notes|date|unified|stat|dirstat|submodule|color|word-diff|word-diff-regex|color-words))	shift; shift;;
+
 	--)		break;;
+	-*)		if argCount=$(filterTimespan --understand-for compare --understands "$@"); then
+			    while ((argCount-- > 0))
+			    do
+				filterFirstColumnArgs+=("$1"); shift
+			    done
+			    postAction=(filterFirstColumn --field-separator $'\t' "${filterFirstColumnArgs[@]}")
+			elif [ $? -eq 2 ]; then
+			    exit 2
+			else
+			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2
+			fi
+			;;
 	*)		logArgs+=("$1"); shift;;
     esac
 done
