git-rcolatest: FIX: Minor: Error message does not handle multiple <branch-glob>s
Don't parrot back the patterns, just mention that matching is involved.

diff --git a/bin/git-rcolatest b/bin/git-rcolatest
--- a/bin/git-rcolatest
+++ b/bin/git-rcolatest
@@ -36,7 +36,7 @@ done
 remoteBranch="$(git-rbr "$remote" "$@" | tail -n 1)" || exit $?
 if [ -z "$remoteBranch" ]; then
     # git branch does not return an error if there are no matches for the passed pattern.
-    printf >&2 'ERROR: No branch matching %s/%s found.\n' "$@"
+    printf >&2 'ERROR: No%s branch found in %s.\n' "${*:+ matching}" "$remote"
     exit 1
 fi
 exec git-checkout-remote-branch "${checkoutArgs[@]}" "${remoteBranch##+( )}"
