Refactoring: Minor: Extract parseUrlsFromLog()

diff --git a/bin/git-logbrowse b/bin/git-logbrowse
--- a/bin/git-logbrowse
+++ b/bin/git-logbrowse
@@ -53,7 +53,13 @@ do
     esac
 done
 
-readarray -t urls < <(git lo "${logArgs[@]}" "$@" | grep -o "${GIT_LOGBROWSE_URL_SCHEMES}${GIT_LOGBROWSE_URL_CHARACTERS}"; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+parseUrlsFromLog()
+{
+    git lo "${logArgs[@]}" "$@" \
+	| grep -o "${GIT_LOGBROWSE_URL_SCHEMES}${GIT_LOGBROWSE_URL_CHARACTERS}"
+}
+
+readarray -t urls < <(parseUrlsFromLog; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
 [ ${urls[-1]} -ne 0 ] && exit ${urls[-1]}
 unset 'urls[-1]'
 [ -z "${urls[-1]}" ] && unset 'urls[-1]'
