git-localbrdo: CHG: Turn --direct-branches into --branches BRANCH [...] ;
Now that the original --branches "<branch1> ..." is gone, we can rename the newly added --direct-branches and make it take several arguments (until ;).

diff --git a/bin/git-localbrdo b/bin/git-localbrdo
--- a/bin/git-localbrdo
+++ b/bin/git-localbrdo
@@ -10,7 +10,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s%s %s\n' "$(basename "$1")" '[-q|--quiet] [--no-pager] [--no-header]' "${hasProgressNotification:+ [--progress SINK]}" '[-i|--interactive] [--separate-errors] [--no-git-color] [--single-success] [--status-99-is-noop] [--abort-on-failure|-X|--abort-on EXIT_STATUS] [--interrupt-on-failure|--interrupt-on EXIT_STATUS] [--continue|--abort|--stashed] [--include-current] [--include-master] [--include-base] [--include-all] [--detach] [(--submodules|--queried-submodules) [--submodules-recursive]] [-B N|--max-branch N] [[--not]-P|--predicate-command "COMMANDLINE" [...]] [-c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...]] [-?|-h|--help]'
+    printf 'Usage: %q %s%s %s\n' "$(basename "$1")" '[-q|--quiet] [--no-pager] [--no-header]' "${hasProgressNotification:+ [--progress SINK]}" '[-i|--interactive] [--separate-errors] [--no-git-color] [--single-success] [--status-99-is-noop] [--abort-on-failure|-X|--abort-on EXIT_STATUS] [--interrupt-on-failure|--interrupt-on EXIT_STATUS] [--continue|--abort|--stashed] [--include-current] [--include-master] [--include-base] [--include-all] [--branches BRANCH [...] ;] [--detach] [(--submodules|--queried-submodules) [--submodules-recursive]] [-B N|--max-branch N] [[--not]-P|--predicate-command "COMMANDLINE" [...]] [-c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...]] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -83,6 +83,10 @@ current Git branch before the command output.
 			    $(basename "$1") [...] [--] SIMPLECOMMAND
 			If omitted, will just return to the shell for each
 			branch.
+    --branches BRANCH [...] ;
+			Only iterate over the following BRANCH(es); i.e. all
+			following arguments until an argument consisting of ';'
+			is encountered.
     --stashed		Don't create a temporary stash in case the working copy
 			is dirty (as an optimization in case you know you're
 			clean.)
@@ -158,7 +162,18 @@ do
 	--color)		colorArg=("$1" "$2"); shift; shift;;
 	--stashed)	    shift; isStashed=t;;
 	--include-*)	    gitLocalbrArgs+=("$1"); shift;;
-	--direct-branches)  shift; IFS=$' \t' read -r -a directBranches <<<"${1//$'\n'/ }"; shift;;	# Internal hook to pass in the branches without further processing except applying --max-branch.
+	--branches)	    shift
+			    while [ $# -gt 0 -a "$1" != ';' ]
+			    do
+				directBranches+=("$1")
+				shift
+			    done
+			    if [ $# -eq 0 ]; then
+				echo 'ERROR: --branches must be concluded with ;!'; echo; printUsage "$0"
+				exit 2
+			    fi >&2
+			    shift
+			    ;;
 	--continue|--abort) iterationAction="${1#--}"; shift;;
 	--detach)	    iteratingCheckoutArgs+=("$1"); shift;;
 	--submodules|--queried-submodules|--submodules-recursive)
