Refactoring: Minor: Define dirspec
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.96.0 (2026-07-02), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-repofilemove b/bin/git-repofilemove
--- a/bin/git-repofilemove
+++ b/bin/git-repofilemove
@@ -85,18 +85,17 @@ do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--target-repo|--to|-t)
-			shift
-			if [ ! -d "$1" ]; then
-			    printf >&2 'ERROR: Target does not exist: %s\n' "$1"
+			shift; dirspec="${1:?}"; shift
+			if [ ! -d "$dirspec" ]; then
+			    printf >&2 'ERROR: Target does not exist: %s\n' "$dirspec"
 			    exit 2
 			fi
-			if ! targetRepo="$(cd "$1" && git root 2>/dev/null)"; then
-			    printf >&2 'ERROR: Target is not a Git working copy: %s\n' "$1"
+			if ! targetRepo="$(cd "$dirspec" && git root 2>/dev/null)"; then
+			    printf >&2 'ERROR: Target is not a Git working copy: %s\n' "$dirspec"
 			    exit 2
 			fi
-			targetSubPath="$(git-relative -- "$1" 2>/dev/null)"
-			[ -z "$targetSubPath" ] && [[ ! "$1" =~ ./$ ]] && unset targetSubPath
-			shift
+			targetSubPath="$(git-relative -- "$dirspec" 2>/dev/null)"
+			[ -z "$targetSubPath" ] && [[ ! "$dirspec" =~ ./$ ]] && unset targetSubPath
 			;;
 	--copy)		shift; isDelete=; actionName='Copy'; actionAlso='also';;
 	--move)		shift; isCommitRemoval=t;;
