Style: Replace ($(...)) with readarray
The removes the need for "set noglob" and often also for IFS=$'\n'.

diff --git a/bin/git-addn b/bin/git-addn
--- a/bin/git-addn
+++ b/bin/git-addn
@@ -1,5 +1,4 @@
 #!/bin/bash
-shopt -qs nullglob
 
 printUsage()
 {
@@ -37,10 +36,11 @@ if [ $# -eq 0 ]; then
     exit 2
 fi
 
-IFS=$'\n'
-set -o noglob
-typeset -a reportedAdditions=($(git add --update --dry-run)) || exit $?
-set +o noglob
+readarray -t reportedAdditions < <(git add --update --dry-run; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+[ ${reportedAdditions[-1]} -ne 0 ] && exit ${reportedAdditions[-1]}
+unset 'reportedAdditions[-1]'
+[ -z "${reportedAdditions[-1]}" ] && unset 'reportedAdditions[-1]'
+
 if [ ${#reportedAdditions[@]} -eq 0 ]; then
     echo >&2 'ERROR: Nothing to add'
     exit 1
@@ -53,7 +53,6 @@ do
     additions["$a"]=1
 done
 
-typeset -a exclusions=()
 for exclusion
 do
     if [ -e "$exclusion" ]; then
diff --git a/bin/git-brc b/bin/git-brc
--- a/bin/git-brc
+++ b/bin/git-brc
@@ -36,7 +36,11 @@ case $locality in
     remote) what="refs/remotes/$1 refs/remotes/$dirBranchGlob";;
 esac
 
-typeset -a branches=($(git for-each-ref --format='%(refname:short)' $what)) || exit $?
+readarray -t branches < <(git for-each-ref --format='%(refname:short)' $what; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+[ ${branches[-1]} -ne 0 ] && exit ${branches[-1]}
+unset 'branches[-1]'
+[ -z "${branches[-1]}" ] && unset 'branches[-1]'
+
 typeset -a firstCommits=()
 for branch in "${branches[@]}"
 do
@@ -55,7 +59,7 @@ do
     fi
     firstCommits+=("$firstCommit $branch")
 done
-IFS=$'\n' sortedFirstCommits=($(sort <<<"${firstCommits[*]}"))
+readarray -t sortedFirstCommits < <(sort <<<"${firstCommits[*]}")
 
 # Print the sorted information without the leading Unix timestamp used as the
 # sort key.
diff --git a/bin/git-selectedcommit-command b/bin/git-selectedcommit-command
--- a/bin/git-selectedcommit-command
+++ b/bin/git-selectedcommit-command
@@ -1,5 +1,4 @@
 #!/bin/bash
-set -o noglob
 shopt -qs extglob
 
 printUsage()
@@ -79,12 +78,15 @@ if [ ${#rangeArgs[@]} -eq 0 ]; then
     exit 2
 fi
 
-IFS=$'\n'
-typeset -a commits; commits=($(
+readarray -t commits < <(
     git log --pretty='tformat:%H %s' "${rangeModificationArgs[@]}" "${rangeArgs[@]}" ${files:+--} "${files[@]}" | \
     truncate-trailing -w | commandWithHiddenId --stdin -p -c "commandOnSelected --stdin${commandOnSelectedArgs:+ }${commandOnSelectedArgs[*]}"
-))
-status=$?
+    printf '\n%d\n' "$?"
+)   # Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+status=${commits[-1]}
+unset 'commits[-1]'
+[ -z "${commits[-1]}" ] && unset 'commits[-1]'
+
 if [ $status -eq 124 ]; then
     echo >&2 'ERROR: No commits available.'
     exit 1
diff --git a/bin/git-whois b/bin/git-whois
--- a/bin/git-whois
+++ b/bin/git-whois
@@ -1,5 +1,4 @@
 #!/bin/bash
-set -o noglob
 
 printUsage()
 {
@@ -75,7 +74,7 @@ else
 			Abort via Ctrl-D.
 EOF
 		else
-		    typeset -a filteredCandidates=($(unset IFS; printf '%s\n' "$@" | grep $REPLY))
+		    typeset -a filteredCandidates=(); readarray -t filteredCandidates < <(unset IFS; printf '%s\n' "$@" | grep $REPLY)
 		    selectCandidates "${filteredCandidates[@]}"
 		    break
 		fi
@@ -91,8 +90,7 @@ printPersons()
     eval 'printf %s\\n "$@"' "${personFilter:+|}" '"${personFilter[@]}"' "${personFilter:+|sort --unique}"
 }
 
-IFS=$'\n'
-typeset -a candidates=($(git log -i ${isShowFirstCandidate:+-1} --pretty='tformat:%aN <%aE>' "${@/#/--author=}" | sort --unique))
+readarray -t candidates < <(git log -i ${isShowFirstCandidate:+-1} --pretty='tformat:%aN <%aE>' "${@/#/--author=}" | sort --unique)
 
 if [ ${#candidates[@]} -eq 0 ]; then
     if [ "$isAcceptUnknown" -a \( $# -eq 1 -o $# -eq 2 \) ]; then
@@ -104,7 +102,7 @@ if [ ${#candidates[@]} -eq 0 ]; then
 	    printPersons "$person"
 	    exit
 	else
-	    printf >&2 "ERROR: Did not pass a valid NAME <EMAIL@HOST>: %s\n" "$person"
+	    printf >&2 'ERROR: Did not pass a valid NAME <EMAIL@HOST>: %s\n' "$person"
 	    exit 2
 	fi
     fi
