git-graphsortrevs: ENH: Usability: Include missing input revisions in the error message if possible
Just stating "ERROR: Did not find 1 revision." isn't super helpful. In the frequent case that full commit hashes have been passed, we can actually obtain the correct discrepancy through comm.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.95.0 (2026-06-17), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-graphsortrevs b/bin/git-graphsortrevs
--- a/bin/git-graphsortrevs
+++ b/bin/git-graphsortrevs
@@ -122,8 +122,18 @@ readarray -t revisionsInOrder < <(git lh "${logArgs[@]}" "$@" | grep "${grepArgs
 typeset -a netRevisionsInOrder=(${revisionsInOrder[@]/#--/})	# Drop the separators; remove the holes by omitting the quoting, which is fine here as it's only hashes.
 revisionDifference=$((${#revisions[@]} - ${#netRevisionsInOrder[@]}))
 if [ $revisionDifference -gt 0 ]; then
+    # This assumes that the input revisions are hashes in the exact format as
+    # produced by "git lh". If some are shorter or tag names, there will be more
+    # discrepancies, and we'd have to compare each one (which is too costly). Just
+    # report the number of missing revisions then.
+    readarray -t discrepancyRevisions < <(comm -23 -- <(printf '%s\n' "${revisions[@]}" | sort) <(printf '%s\n' "${netRevisionsInOrder[@]}" | sort) 2>/dev/null)
+
     revisionDifferencePlural=s; [ $revisionDifference -eq 1 ] && revisionDifferencePlural=
-    printf >&2 'ERROR: Did not find %d revision%s.\n' "$revisionDifference" "$revisionDifferencePlural"
+    if [ ${#discrepancyRevisions[@]} -eq $revisionDifference ]; then
+	printf >&2 'ERROR: Did not find %d revision%s: %s\n' "$revisionDifference" "$revisionDifferencePlural" "$(joinBy ', ' "${discrepancyRevisions[@]}")"
+    else
+	printf >&2 'ERROR: Did not find %d revision%s.\n' "$revisionDifference" "$revisionDifferencePlural"
+    fi
     exit 1
 fi
 
