git-rev-range-to-previous-clone: BUG: Complains about the current branch not being a cloned branch when --branch is passed
Combine currentBranchName with startRev into branchName, and skip the branch lookup when already set.

diff --git a/bin/git-rev-range-to-previous-clone b/bin/git-rev-range-to-previous-clone
--- a/bin/git-rev-range-to-previous-clone
+++ b/bin/git-rev-range-to-previous-clone
@@ -12,13 +12,13 @@ printUsage()
 
 # -b|--branch can also be passed after GIT-COMMAND; need to parse that
 # separately.
-startRev=
+branchName=
 typeset -a args=()
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-	--branch|-b)	shift; startRev="$1"; shift;;
+	--branch|-b)	shift; branchName="${1:?}"; shift;;
 	--)		args+=("$1"); shift; break;;
 	*)		args+=("$1"); shift;;
     esac
@@ -33,17 +33,17 @@ do
     case "$1" in
 	--help|-h|-\?)			shift; printUsage "$0"; exit 0;;
 	--previous-clone-number|-n)	shift; previousCloneNumber="$1"; shift;;
-	--start-rev)			shift; startRev="$1"; shift;;
+	--start-rev)			shift; branchName="${1:?}"; shift;;
 	--no-range)			revRangeArgs+=("$1"); shift; isWithRange=;;
 	--keep-position|[+-][0-9])	revRangeArgs+=("$1"); shift; break;;
 	*)				revRangeArgs+=("$1"); shift;;
     esac
 done
 
-currentBranchName="$(git-brname --real-branch-only)" || exit $?
+[ -n "$branchName" ] || branchName="$(git-brname --real-branch-only)" || exit $?
 
-if [[ ! "$currentBranchName" =~ ^(.+)"${GIT_CLONEBR_SEPARATOR}"([[:digit:]]+)$ ]]; then
-    printf >&2 'ERROR: Current branch is not a cloned branch; the %s1 suffix is missing: %s\n' "$GIT_CLONEBR_SEPARATOR" "$currentBranchName"
+if [[ ! "$branchName" =~ ^(.+)"${GIT_CLONEBR_SEPARATOR}"([[:digit:]]+)$ ]]; then
+    printf >&2 'ERROR: Current branch is not a cloned branch; the %s1 suffix is missing: %s\n' "$GIT_CLONEBR_SEPARATOR" "$branchName"
     exit 1
 fi
 branchBase="${BASH_REMATCH[1]}"
@@ -59,14 +59,14 @@ do
     fi
 done
 if [ $encounteredCloneCnt -eq 0 ]; then
-    printf >&2 'ERROR: No additional clones of %s available.\n' "$currentBranchName"
+    printf >&2 'ERROR: No additional clones of %s available.\n' "$branchName"
     exit 1
 elif [ $encounteredCloneCnt -lt $previousCloneNumber ]; then
     encounteredCloneCntPlural=s; [ $encounteredCloneCnt -eq 1 ] && encounteredCloneCntPlural=
-    printf >&2 'ERROR: Only %d clone%s of %s available.\n' $encounteredCloneCnt "$encounteredCloneCntPlural" "$currentBranchName"
+    printf >&2 'ERROR: Only %d clone%s of %s available.\n' $encounteredCloneCnt "$encounteredCloneCntPlural" "$branchName"
     exit 1
 fi
 
-[ "$isWithRange" ] || startRev=''   # Prevent "ERROR: --end-revision cannot be combined with --no-range!"; we don't need the end revision, as --no-range drops that, anyway.
+[ "$isWithRange" ] || branchName=''   # Prevent "ERROR: --end-revision cannot be combined with --no-range!"; we don't need the end revision, as --no-range drops that, anyway.
 
-exec git-rev-range --revision "$previousClonedBranch" ${startRev:+--end-revision} $startRev "${revRangeArgs[@]}" "$@"
+exec git-rev-range --revision "$previousClonedBranch" ${branchName:+--end-revision} $branchName "${revRangeArgs[@]}" "$@"
