CHG: Renaming: [logof]relatedfiles to [logof]changesetfiles
As there is ambiguity between git-commitrelate / git-logrelated and the idea that files within the same commit are related to each other.
To be more precise, files in a commit belong to the same changeset, so let's use that instead.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.95.0 (2026-06-17), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-logofchangesetfiles b/bin/git-logofchangesetfiles
--- a/bin/git-logofchangesetfiles
+++ b/bin/git-logofchangesetfiles
@@ -21,8 +21,8 @@ printLongUsage()
 Show log of commits that modify files that often get changed in commits that
 modify files in <pathspec> / the files affected by <commit>. So it doesn't just
 show commits that modify the passed files, but also any commits that modify
-files that are often modified together with the passed files, even if those
-commits don't directly modify the passed files.
+files that are often modified together with the passed files (i.e. a changeset),
+even if those commits don't directly modify the passed files.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
@@ -38,7 +38,7 @@ SEE ALSO:
 HELPTEXT
 }
 
-typeset -a relatedfilesArgs=()
+typeset -a changesetsArgs=()
 typeset -a gitLogArgs=()
 typeset -A files=()
 while [ $# -ne 0 ]
@@ -46,7 +46,7 @@ do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--percentage-threshold|-%)
-			relatedfilesArgs+=("$1" "${2:?}"); shift; shift;;
+			changesetsArgs+=("$1" "${2:?}"); shift; shift;;
 	--)		shift; break;;
 	*)		gitLogArgs+=("$1"); shift;;
     esac
@@ -94,10 +94,10 @@ if [ ${#uniqueFiles[@]} -eq 0 ]; then
     exit 1
 fi
 
-readarray -t relatedFiles < <(git-relatedfiles --no-percentage "${relatedfilesArgs[@]}" "${gitLogArgs[@]}" -- "${uniqueFiles[@]}"; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
-[ ${relatedFiles[-1]} -ne 0 ] && exit ${relatedFiles[-1]}
-unset 'relatedFiles[-1]'; [ -n "${relatedFiles[-1]}" ] || unset 'relatedFiles[-1]'
+readarray -t changesetFiles < <(git-changesetfiles --no-percentage "${changesetsArgs[@]}" "${gitLogArgs[@]}" -- "${uniqueFiles[@]}"; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+[ ${changesetFiles[-1]} -ne 0 ] && exit ${changesetFiles[-1]}
+unset 'changesetFiles[-1]'; [ -n "${changesetFiles[-1]}" ] || unset 'changesetFiles[-1]'
 
-[ ${#relatedFiles[@]} -gt 0 ] || exit 1
+[ ${#changesetFiles[@]} -gt 0 ] || exit 1
 
-exec git-wrapper ${GIT_LOGOFRELATEDFILES_COMMAND:-log} "${gitLogArgs[@]}" -- "${relatedFiles[@]}"
+exec git-wrapper ${GIT_LOGOFCHANGESETFILES_COMMAND:-log} "${gitLogArgs[@]}" -- "${changesetFiles[@]}"
