ENH: Allow preconfigured CHECK-COMMANDS via GIT_REINTEGRATE_CHECK_COMMAND
To be able to configure default checks (that can still be overridden / suppressed via "--command :") for certain working copies.

diff --git a/bin/git-reintegrate b/bin/git-reintegrate
--- a/bin/git-reintegrate
+++ b/bin/git-reintegrate
@@ -19,6 +19,8 @@ if the last succeeds) delete the branch from the local repository as well as a
 tracked remote (if it exists there) (unless --no-delete is given).
 HELPTEXTCHECK
     echo
+    printf 'Usage: GIT_REINTEGRATE_CHECK_COMMAND=CMD %q %s\n' "$(basename "$1")" '[...]'
+    echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '[...] -c|--command "CHECK-COMMANDLINE" [-c ...] | --exec SIMPLECOMMAND [...] ; [...]'
     echo
     printf 'Usage: echo CHECK-COMMANDLINES | %q %s\n' "$(basename "$1")" '[...] [--bare|[--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] -'
@@ -103,12 +105,16 @@ if [ "${!#}" = '-' ]; then
     isCheckFromStdin=t
     set -- "${@:1:$(($#-1))}"
 fi
-if [ "$isCheckFromStdin" ] && [ ${#checkCommands[@]} -gt 0 ]; then
-    echo 'ERROR: Cannot combine CHECK-COMMANDLINE from stdin (-) with -c|--command|--exec.'
-    echo
-    printUsage "$0"
-    exit 2
-fi >&2
+if [ "$isCheckFromStdin" ]; then
+    if [ ${#checkCommands[@]} -gt 0 ]; then
+	echo 'ERROR: Cannot combine CHECK-COMMANDLINE from stdin (-) with -c|--command|--exec.'
+	echo
+	printUsage "$0"
+	exit 2
+    fi >&2
+elif [ -n "$GIT_REINTEGRATE_CHECK_COMMAND" -a ${#checkCommands[@]} -eq 0 ]; then
+    checkCommands=("$GIT_REINTEGRATE_CHECK_COMMAND")
+fi
 
 branches+=("$@")
 if [ ${#branches[@]} -eq 0 ]; then
