Documentation: Cosmetics: Use <path> instead of <pathspec>
For consistency. <file> is also in use in a few scripts.

diff --git a/bin/git-editstage b/bin/git-editstage
--- a/bin/git-editstage
+++ b/bin/git-editstage
@@ -7,7 +7,7 @@ Directly edit file(s) in the index (or the HEAD revision if the file hasn't been
 staged yet) without modifying the corresponding files in the working copy.
 You can re-edit the same set of files again with --continue.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[EDITOR-ARGS ... [--]] [<pathspec> ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[EDITOR-ARGS ... [--]] [<path> ...] [-?|-h|--help]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '--continue [EDITOR-ARGS ... [--]] [-?|-h|--help]'
 }
 isContinue=
@@ -59,7 +59,7 @@ if [ ! "$isContinue" ] && [ ${#paths[@]} -eq 0 ]; then
 	exit 1
     fi
 elif [ "$isContinue" ] && [ ${#paths[@]} -gt 0 ]; then
-    echo >&2 "ERROR: --continue uses the original <pathspec>s, don't add new ones."
+    echo >&2 "ERROR: --continue uses the original <path>s, don't add new ones."
     exit 2
 fi
 
@@ -79,10 +79,10 @@ if [ "$isContinue" ]; then
     mapfile -t paths < "$indexEditPathsFilespec"
     mapfile -t editFilespecs < "$indexEditFilesFilespec"
     if [ ${#editFilespecs[@]} -eq 0 ]; then
-	printf >&2 'ERROR: No <pathspec> given but also no edited files found under %s/!\n' "$indexEditDirspec"
+	printf >&2 'ERROR: No <path> given but also no edited files found under %s/!\n' "$indexEditDirspec"
 	exit 2
     elif [ ${#paths[@]} -ne ${#editFilespecs[@]} ]; then
-	echo >&2 "ERROR: Inconsistent numbers of <pathspec> and edited files found. Aborting."
+	echo >&2 "ERROR: Inconsistent numbers of <path> and edited files found. Aborting."
 	exit 2
     fi
 
@@ -92,7 +92,7 @@ else
     for path in "${paths[@]}"
     do
 	if [ ! -r "$path" ]; then
-	    printf "fatal: pathspec '%s' did not match any files\\n" "$path"
+	    printf "FATAL: path '%s' did not match any files\\n" "$path"
 	    exit 2
 	fi
 
