git-conflicts: ENH: Allow suppression of output via -q|--quiet, indicate no conflicts via exit status 1
Like git-dirty; this allows clients to just check for conflicts.

diff --git a/bin/git-conflicts b/bin/git-conflicts
--- a/bin/git-conflicts
+++ b/bin/git-conflicts
@@ -6,13 +6,24 @@ printUsage()
 List files with merge conficts.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--] [<path> ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet] [--] [<path> ...] [-?|-h|--help]'
 }
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
-			shift;;
-    --color)		shift; shift;;
-esac
 
-git ls-files --unmerged "$@" | cut -f2 | uniq
+isQuiet=
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
+			shift;;
+	--color)	shift; shift;;
+	--quiet|-q)	shift; isQuiet=t;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
+
+paths="$(git ls-files --unmerged "$@" | cut -f2 | uniq)"
+[ -n "$paths" ] || exit 1
+[ "$isQuiet" ] || printf '%s\n' "$paths"
