Refactoring: Invert $isDelete to $isKeepBranches so that the messages can be prefixed with "not delete"
This is a bit clumsy, but not important enough to warrant another variable for "keep" vs "delete".

diff --git a/bin/git-ffintegrateto b/bin/git-ffintegrateto
--- a/bin/git-ffintegrateto
+++ b/bin/git-ffintegrateto
@@ -93,7 +93,7 @@ case "$1" in
 esac
 
 isContinue=
-isDelete=t
+isKeepBranches=
 isMerge=t
 isPush=
 isPushBranch=
@@ -128,7 +128,7 @@ do
 			shift;;
 	--color)	shift; shift;;
 	--continue)	shift; isContinue=t;;
-	--no-delete)	continueArgs+=("$1"); shift; isDelete=;;
+	--no-delete)	continueArgs+=("$1"); shift; isKeepBranches=t;;
 	--no-merge)	continueArgs+=("$1"); shift; isMerge=;;
 	--push)		continueArgs+=("$1"); shift; isPush=t;;
 	--push-branch)	continueArgs+=("$1"); shift; isPushBranch=t;;
@@ -345,7 +345,7 @@ else
 	if [ "$isRebase" ]; then
 	    git rebase "$targetIntegrationSourceBranch" || {
 		status=$?
-		echo >&2 "After the branch has been successfully rebased (see above), you can ${isCheckFromStdin:+run checks and }${isPushBranch:+push and }${isMerge:+fast-forward to $targetBranch integrate and }${isPush:+push and }delete it via"
+		echo >&2 "After the branch has been successfully rebased (see above), you can ${isCheckFromStdin:+run checks and }${isPushBranch:+push and }${isMerge:+fast-forward to $targetBranch integrate and }${isPush:+push and }${isKeepBranches:+not }delete it via"
 		printContinueCommand
 		exit $status
 	    }
@@ -353,7 +353,7 @@ else
 	    # TODO: We want a merge with the two parents swapped here.
 	    git-wrapper merge "${fastForwardArgs[@]:---no-ff}" "${mergeArgs[@]}" "$targetBranch" || {
 		status=$?
-		echo >&2 "After the branch has been merged, you can ${isCheckFromStdin:+run checks and }${isPushBranch:+push and }${isMerge:+fast-forward integrate to $targetBranch and }${isPush:+push and }delete it via"
+		echo >&2 "After the branch has been merged, you can ${isCheckFromStdin:+run checks and }${isPushBranch:+push and }${isMerge:+fast-forward integrate to $targetBranch and }${isPush:+push and }${isKeepBranches:+not }delete it via"
 		printContinueCommand
 		exit $status
 	    }
@@ -372,7 +372,7 @@ elif [ ${#checkCommands[@]} -gt 0 ]; then
     (eval "${checkCommands[@]}")
 fi || {
     status=$?
-    echo >&2 "Checks failed; $targetIntegrationSourceBranch has been integrated into the current branch, but the current branch has not been ${isPushBranch:+pushed and }${isMerge:+fast-forward integrated to $targetBranch and }${isPush:+pushed or }deleted yet."
+    echo >&2 "Checks failed; $targetIntegrationSourceBranch has been integrated into the current branch, but the current branch has not been ${isPushBranch:+pushed and }${isMerge:+fast-forward integrated to $targetBranch and }${isPush:+pushed or }${isKeepBranches:+not }deleted yet."
     echo >&2 'Correct the problem by amending or additional commits, then invoke'
     printRestartCommand	# If the current branch has been modified, the reintegration need to be restarted to be able to fast-forward. We cannot simply continue after the original integration commit has been left behind.
     echo >&2 'to restart the fast-forwarding integration. If the checks just failed due to an external issue and you would like to try again, invoke'
