UI: Print decision based on the config via new choiceEvaluate()

diff --git a/bin/git-reintegrate b/bin/git-reintegrate
--- a/bin/git-reintegrate
+++ b/bin/git-reintegrate
@@ -292,6 +292,20 @@ printContinueCommand()
     printf >&2 '\n'
 }
 
+choiceEvaluate()
+{
+    local configKey="${1:?}"; shift
+    local choice="${1:?}"; shift
+    local messagePrefix="${1:?}"; shift
+    local positiveMessage="${1:?}"; shift
+    local negativeMessage="${1:?}"; shift
+    case "$choice" in
+	true)	printf '%s %s (based on the %s config)."\n' "$messagePrefix" "$positiveMessage" "$configKey"; return 0;;
+	false)	printf '%s %s (based on the %s config).\n' "$messagePrefix" "$negativeMessage" "$configKey"; return 1;;
+	*)	printf >&2 'ASSERT: Invalid choice: %s\n' "$choice"; exit 3;;
+    esac
+}
+
 targetBranch="$(git-brname --real-branch-only)" || exit $?
 targetTracks="$(git-tracks 2>/dev/null)"
 targetTrackedRemote="${targetTracks%%/*}"
@@ -348,8 +362,10 @@ else
 		commitNum=$(git log --pretty=tformat:%H "HEAD..${branches[-1]}" | wc -l)
 		commitNumPlural=s; [ $commitNum -eq 1 ] && commitNumPlural=
 		branchNum=${#branches[@]}; [ $branchNum -eq 1 ] && branchNum=
-		if choice="$(git config --type bool --get "$([ $commitNum -eq 1 ] && echo 'reintegrate.fastforward-single' || printf 'reintegrate.fastforward')")"; then
-		    [ "$choice" = true ]
+
+		fastForwardInsteadOfMergeConfigKey='reintegrate.fastforward'; [ $commitNum -eq 1 ] && fastForwardInsteadOfMergeConfigKey='reintegrate.fastforward-single'
+		if choice="$(git config --type bool --get "$fastForwardInsteadOfMergeConfigKey")"; then
+		    choiceEvaluate "$fastForwardInsteadOfMergeConfigKey" "$choice" "The $commitNum commit$commitNumPlural on the ${branchNum}${branchNum:+ }branch$branchesPlural will be" "fast-forwarded instead of merged" "merged, not fast-forwarded"
 		else
 		    userBinaryChoice --keep-prompt --console --question "The $commitNum commit$commitNumPlural on the ${branchNum}${branchNum:+ }branch$branchesPlural can be fast-forwarded instead of merged. Fast-forward?" --yes-no
 		fi && fastForwardArgs=(--ff-only)
@@ -360,8 +376,11 @@ else
 			hubNote+=" (But be aware that the CHECK-COMMAND(s) won't be executed then.)"
 		    fi
 		fi
-		choice="$(git config --type bool --get reintegrate.rebase-single)" \
-		    || choice="$(userchoiceFromList --keep-prompt --question "The branch$branchesPlural only consist$verbPlural of a single commit. Rebase $branchesSubject instead of creating a separate merge commit?${hubNote:+$'\n'}${hubNote}" --no-cancel --ignore-case -- '[Y]es' '[N]o' '[Q]uit')" || exit $?
+		if choice="$(git config --type bool --get reintegrate.rebase-single)"; then
+		    choiceEvaluate reintegrate.rebase-single "The single commit on the ${branchNum}${branchNum:+ }branch$branchesPlural will be" "rebased instead of merged" "merged, not rebased"
+		else
+		    choice="$(userchoiceFromList --keep-prompt --question "The branch$branchesPlural only consist$verbPlural of a single commit. Rebase $branchesSubject instead of creating a separate merge commit?${hubNote:+$'\n'}${hubNote}" --no-cancel --ignore-case -- '[Y]es' '[N]o' '[Q]uit')" || exit $?
+		fi
 		case "$choice" in
 		    true|Yes)
 			isRebase=t;;
