Refactoring: Extract getLogDates(), add remaining args to gitArgs

diff --git a/bin/git-logdistribution b/bin/git-logdistribution
--- a/bin/git-logdistribution
+++ b/bin/git-logdistribution
@@ -79,12 +79,18 @@ do
 	*)		gitArgs+=("$1"); shift;;
     esac
 done
+gitArgs+=("$@")
+
+getLogDates()
+{
+    git log --pretty=tformat:'%ai' "${gitArgs[@]}"
+}
 
 # The logged dates still need to be sorted, because sorting happens by commit
 # date, but we'd like to show the author date distribution. The
 # --split-graph-field would be disturbed by an earlier date reappeared after a
 # later date again.
-readarray -t dates < <(git log --pretty=tformat:'%ai' "${gitArgs[@]}" "$@" | sort --numeric-sort; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
+readarray -t dates < <(getLogDates | sort --numeric-sort; printf '\n%d\n' "$?")	# Exit status from the process substitution is lost; return the actual exit status via an appended additional line.
 [ ${dates[-1]} -ne 0 ] && exit ${dates[-1]}
 unset 'dates[-1]'
 [ -z "${dates[-1]}" ] && unset 'dates[-1]'
