CHG: Renaming: git-swaplast to git-swap
The "last" is implied in stack operations.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.92.0 (2026-04-28), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-swap b/bin/git-swap
--- a/bin/git-swap
+++ b/bin/git-swap
@@ -83,7 +83,7 @@ do
     esac
 done
 if git-existstag _invert; then
-    echo >&2 'ERROR: It looks like another git-swaplast is under way. Please finalize that first (via --continue|--quit|--abort|--cleanup).'
+    echo >&2 'ERROR: It looks like another git-swap is under way. Please finalize that first (via --continue|--quit|--abort|--cleanup).'
     exit 1
 elif git-dirty --print-error "$@"; then
     exit 1
diff --git a/bin/git-swapstage b/bin/git-swapstage
--- a/bin/git-swapstage
+++ b/bin/git-swapstage
@@ -36,11 +36,11 @@ do
 	--continue-command)
 			shift; continueCommand="${1:?}"; shift;;
 	--continue-[12])
-			git-swaplast --continue-command "$(basename "$0")" "$@" \
+			git-swap --continue-command "$(basename "$0")" "$@" \
 			    && uncommit
 			exit $?
 			;;
-	--abort)	git-swaplast --abort "$@" \
+	--abort)	git-swap --abort "$@" \
 			    && uncommit
 			exit $?
 			;;
@@ -51,7 +51,7 @@ do
     esac
 done
 if git-existstag _invert; then
-    echo >&2 'ERROR: It looks like a git-swaplast is under way. Please finalize that first (via --continue|--quit|--abort|--cleanup).'
+    echo >&2 'ERROR: It looks like a git-swap is under way. Please finalize that first (via --continue|--quit|--abort|--cleanup).'
     exit 1
 fi
 
@@ -81,5 +81,5 @@ else
     git commit -m futureStage -- "${unstagedFiles[@]}"
 fi || exit $?
 
-git-swaplast --continue-command "$continueCommand" "$@" || exit $?
+git-swap --continue-command "$continueCommand" "$@" || exit $?
 uncommit "$@"
