git-subhash: ENH: Allow decoration of the commit ID via --decorate[-refs[-exclude]]

diff --git a/bin/git-subhash b/bin/git-subhash
--- a/bin/git-subhash
+++ b/bin/git-subhash
@@ -1,5 +1,6 @@
 #!/bin/bash
 # Source: https://stackoverflow.com/a/32327200/813602
+shopt -qs extglob
 
 printUsage()
 {
@@ -7,16 +8,30 @@ printUsage()
 Show the commit ID recorded in the superproject [in <ref>] for passed <submodule>.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--short[=length]] [<ref>] <submodule> [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--short[=length]] [--decorate[=short|full|auto|no]] [--decorate-refs=<pattern>] [--decorate-refs-exclude=<pattern>] [<ref>] <submodule> [-?|-h|--help]'
 }
 typeset -a revParseArgs=()
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
+typeset -a logDecorateArgs=()
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-    --short|--short=*)	revParseArgs+=("$1"); shift
-esac
+	--color)	shift; shift;;
+	--short|--short=*)
+			revParseArgs+=("$1"); shift;;
+	--decorate|--decorate=*)
+			logDecorateArgs+=("$1"); shift;;
+	--decorate-refs?(-exclude))
+			logDecorateArgs+=("$1" "${2?}"); shift; shift;;
+	--decorate-refs?(-exclude)=*)
+			logDecorateArgs+=("$1"); shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 ref='HEAD'
 if [ $# -gt 2 ]; then
     printUsage "$0" >&2
@@ -37,4 +52,10 @@ if [ "$relativeSubmodule" = "$absoluteSubmodule" ]; then
 fi
 
 cd "$absoluteSuperprojectRoot" || exit 3
-exec git rev-parse "${revParseArgs[@]}" "${ref}:${relativeSubmodule}"
+rev="$(git rev-parse "${revParseArgs[@]}" "${ref}:${relativeSubmodule}")" || exit $?
+
+if [ ${#logDecorateArgs[@]} -eq 0 ]; then
+    printf '%s\n' "$rev"
+else
+    printf '%s\t%s\n' "$rev" "$(cd "$absoluteSubmodule" && git-decorated "${logDecorateArgs[@]}" "$rev")"
+fi
