git-changesetfiles: CHG: Just take <pathspec>s instead of revisionRangeArgs (cp. ff098888)
This is all so confusing; I hope I finally understand now. We definitely need <pathspec>(s) to determine other commits that modify the same files. That the command also took <commit>s was just syntaxtic sugar; git-showfiles-command can easily provide those externally. And, like other aliases, we'd like to have git-changesetfiles{st,i,I,g,changed,touched} variants as well.
So do this via embellishments, and keep the API to mandatory <pathspec>s.

The second dimension is the <revision-range>. That's for how far back the command looks for commits. Looking back as much as possible is a great default. This could be expanded to look at all branches in the repo, or limit via br-variants, but it's doubtful that this is important. The conflict between <revision-range> and the <commit> arguments really got me here, and it took so many attempts to figure this out!

The third dimension is git-logofchangesetfiles, which also takes a <revision-range>, but here it's much more important to limit the scope, and we'd probably want br-variants for those.

(This relates to commit ff098888a99bb2eb3d1aa07d0ee840be620f1f91)

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.95.0 (2026-06-17), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-changesetfiles b/bin/git-changesetfiles
--- a/bin/git-changesetfiles
+++ b/bin/git-changesetfiles
@@ -5,10 +5,8 @@ shopt -qs extglob
 : ${GIT_CHANGESETFILES_PERCENTAGE_THRESHOLD:=10}
 : ${GIT_CHANGESETFILES_ORIGINAL_FILE_PREFIX='[01;37m'}
 : ${GIT_CHANGESETFILES_ORIGINAL_FILE_SUFFIX='[0m'}
-: ${GIT_CHANGESETFILES_REVISIONS_END=;}
 
-readonly revisionRangeArgs="[-n|--count N|-r|--revision REVISION|--revisions REVISION1 [...] $GIT_CHANGESETFILES_REVISIONS_END|--since <date>|--max-count <number>|--range <range> [--range ...]]"
-readonly allArgs="[-N|--no-percentage] [-%|--percentage-threshold PCT] [-a|--include-original-files|-d|--drop-original-files] $revisionRangeArgs"
+readonly allArgs="[-N|--no-percentage] [-%|--percentage-threshold PCT] [-a|--include-original-files|-d|--drop-original-files]"
 readonly filterArgs='[-%|--percentage-threshold PCT] [-d|--drop-original-files]'
 readonly formatArgs='[-N|--no-percentage] [-a|--include-original-files]'
 getShortUsage()
@@ -19,8 +17,6 @@ getShortUsage()
 	    printf %s "$filterArgs";;
 	format)
 	    printf %s "$formatArgs";;
-	revision-range)
-	    printf %s "$revisionRangeArgs";;
 	*)  echo "ERROR: Unknown short usage topic \"$1\"!" >&2; return 2;;
     esac
 }
@@ -47,23 +43,6 @@ HELPTEXT
 HELPTEXT
 	    hadTopic=t
 	    ;;&
-	''|revision-range)
-	    cat <<HELPTEXT
-    --count|-n N	Use files modified in the N'th previous commit.
-    --revision|-r REVISION
-			Use files modified in REVISION.
-    --revisions REVISION1 [...] $GIT_CHANGESETFILES_REVISIONS_END
-			Use files modified in REVISION(s); all following
-			arguments until an argument consisting of '$GIT_CHANGESETFILES_REVISIONS_END' is
-			encountered.
-    --since <date>	Use files modified since <date> (inclusive) instead of
-			the last commit.
-    --max-count <number>
-			Use files modified in the last <number> commits instead
-			of the last commit.
-    --range <range>	Use files modified in the commits in <range>.
-HELPTEXT
-	    ;;&
 	*)  [ "$hadTopic" ] || { echo "ERROR: Unknown long usage topic \"$topic\"!" >&2; return 2; };;
     esac
 }
@@ -71,7 +50,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" "$allArgs [<log-options>] [<revision range>] [--] [<pathspec>...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "$allArgs [<log-options>] [<revision range>] [--] <pathspec>... [-?|-h|--help]"
 }
 printUsage()
 {
@@ -85,10 +64,11 @@ printLongUsage()
     # This is the long "man page" when launched with the help argument.
     # It is printed to stdout to allow paging with 'more'.
     cat <<HELPDESCRIPTION
-Show files that often get changed in commits that modify files in <pathspec> /
-the files affected by <commit>, and the correlation between the commits; 100%
-means an affected file is included in every commit that touches a passed file;
-0% means it's included in less than one commit out of hundred.
+Show files that often get changed in commits that modify files in <pathspec>
+[within <revision range>] [while applying <log-options>] and the correlation
+between the commits; 100% means an affected file is included in every commit
+that touches a passed file; 0% means it's included in less than one commit out
+of hundred.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
@@ -103,13 +83,12 @@ RELATED COMMANDS:
 HELPTEXT
 }
 
-typeset -a revisionRanges=()
-typeset -a gitLogArgs=()
+typeset -a args=()
 isPercentage=t
 filterCommand="s/.*/${GIT_CHANGESETFILES_ORIGINAL_FILE_PREFIX}&${GIT_CHANGESETFILES_ORIGINAL_FILE_SUFFIX}/"
+unset files
 option() { :; }
 parameter() { :; }
-parameterToSep() { :; }
 endOfOptionsAndParameters() { :; }
 noUnderstand() { :; }
 typeset -A understandsSubtopics=()
@@ -134,7 +113,6 @@ do
 	--understands)	shift
 			option() { isUnderstandSubtopic "$@" || exit 1; printf 1; exit 0; }
 			parameter() { isUnderstandSubtopic "$@" || exit 1; printf 2; exit 0; }
-			parameterToSep() { local argCnt="${1:?}"; shift; isUnderstandSubtopic "$@" || exit 1; printf $argCnt; exit 0; }
 			endOfOptionsAndParameters() { exit 99; }
 			noUnderstand() { exit 1; }
 			;;
@@ -148,39 +126,29 @@ do
 	--drop-original-files|-d)
 			shift; filterCommand='d'; option filter;;
 
-	--count|-n)	shift
-			if ! [[ "$1" =~ ^[0-9]+$ ]]; then
-			    printUsage "$0" >&2
-			    exit 2
-			fi
-			revisionRanges+=("HEAD~$(($1 - 1))")
-			shift
-			parameter revision-range
-			;;
-	--revision|-r)	shift; revisionRanges+=("${1:?}"); shift; parameter revision-range;;
-	--revisions)	shift
-			while [ $# -gt 0 -a "$1" != "$GIT_CHANGESETFILES_REVISIONS_END" ]
-			do
-			    revisionRanges+=("${1:?}"); shift
-			done
-			if [ $# -eq 0 ]; then
-			    echo "ERROR: --revisions must be concluded with '${GIT_CHANGESETFILES_REVISIONS_END}'"; echo; printUsage "$0"
-			    exit 2
-			fi >&2
-			shift
-			parameterToSep ${#revisionRanges[@]} revision-range
-			;;
-	--@(since|max-count)=*)
-			revisionRanges+=("$1"); shift; option revision-range;;
-	--@(since|max-count))
-			revisionRanges+=("$1" "${2?}"); shift; shift; parameter revision-range;;
-	--range=*)	revisionRanges+=("${1#--range=}"); shift;;
-	--range)	shift; revisionRanges+=("${1:?}"); shift;;
-
-	--)		gitLogArgs+=("$1"); shift; endOfOptionsAndParameters; break;;
-	*)		gitLogArgs+=("$1"); shift; endOfOptionsAndParameters;;
+	--)		args+=("$1"); shift; typeset -a files=("$@"); set --; endOfOptionsAndParameters; break;;
+	*)		args+=("$1"); shift; endOfOptionsAndParameters;;
     esac
 done
+if [ -z "${files+t}" ]; then
+    # No files after -- captured yet; need to investigate parsed and
+    # remaining args from behind for files.
+    typeset -a files=()
+    args+=("$@")
+    while [ ${#args[@]} -ne 0 ]
+    do
+	lastArg="${args[-1]}"
+	[ -e "$lastArg" ] || break
+
+	files=("$lastArg" "${files[@]}")
+	args=("${args[@]:0:${#args[@]}-1}")
+    done
+fi
+set -- "${args[@]}" "$@"
+if [ ${#files[@]} -eq 0 ]; then
+    echo >&2 'ERROR: No <pathspec> passed.'
+    exit 2
+fi
 
 removeStatus()
 {
@@ -196,7 +164,7 @@ removeStatus()
 logFiles()
 {
     local prettyArg="${1:?}"; shift
-    git-logv "$prettyArg" "${revisionRanges[@]}" "${gitLogArgs[@]}" "$@"
+    git-logv "$prettyArg" "$@" -- "${files[@]}"
 }
 extractChangesetFiles()
 {
@@ -250,7 +218,7 @@ if [ -n "$filterCommand" ]; then
 	[ ${#filterPipeline[@]} -eq 0 ] && filterPipeline+=(sed)
 	filterPipeline+=(-e "/${originalFilePrefixPattern}${literalOriginalPathspec}${pathspecAnchor}/${filterCommand}")
     done < <(
-	git-showfiles "${revisionRanges[@]}" "${gitLogArgs[@]}" "$@" 2>/dev/null \
+	printf '%s\n' "${files[@]}" \
 	    | sed -e 's/[][\$*.^/]/\\&/g'
 	)
 
