ENH: Also support passing -r|--revision <commit>
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.96.0 (2026-07-02), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-cp b/bin/git-cp
--- a/bin/git-cp
+++ b/bin/git-cp
@@ -3,30 +3,42 @@
 printUsage()
 {
     cat <<HELPTEXT
-Retrieve the contents of <pathspec> as it exists in revision <revision> and save
+Retrieve the contents of <pathspec> as it exists in revision <commit> and save
 it as <pathspec>.<revision> (or override with -O|--override, or <target> if
 given).
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-O|--override] <revision> [--] (<pathspec> [to <target>]) [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-O|--override] [-r|--revision] <commit> [--] (<pathspec> [to <target>]) [...] [-?|-h|--help]'
 }
 
+revision=
 isOverride=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-    --override|-O)	shift; isOverride=t;;
-esac
-if [ $# -lt 2 ]; then
+	--color)	shift; shift;;
+	--revision|-r)	shift; revision="${1:?}"; shift;;
+	--override|-O)	shift; isOverride=t;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		if [ -z "$revision" ]; then
+			    revision="${1:?}"; shift
+			else
+			    break
+			fi
+			;;
+    esac
+done
+if [ -z "$revision" ]; then
+    echo 'ERROR: No <revision> passed.'
+    echo
     printUsage "$0"
     exit 2
-fi
+fi >&2
 
-
-revision="$1"; shift
-[ "$1" = -- ] && shift
 commitId=$(git-commitid "$revision") || exit $?
 
 status=0
