git-dirty: CHG: Print status unless new -q|--quiet is given
Many clients already run "git status" after a positive dirty check. As the status output may already be used by git-dirty itself to determine the state, let's simply print it by default. (A color flag can be ignored as the pure status doesn't have any coloring.) This also make the git-dirty more consistent with git-staged et al.

diff --git a/bin/git-archivelast b/bin/git-archivelast
--- a/bin/git-archivelast
+++ b/bin/git-archivelast
@@ -65,13 +65,12 @@ if [ $# -gt 0 ]; then
     fi
 fi
 if [ $# -gt 0 ]; then
-    printUsage "$0" >&2
+    printUsage "$0"
     exit 2
 elif git-dirty; then
-    echo >&2 'ERROR: working copy is still dirty; please clean up first.'
-    git status
+    echo 'ERROR: working copy is still dirty; please clean up first.'
     exit 1
-fi
+fi >&2
 
 tagCommit="$(git rev-parse HEAD)" || exit $?
 if [ -z "$tagName" ] && [ ! "$isYes" ]; then
diff --git a/bin/git-checkoutpreviousselected b/bin/git-checkoutpreviousselected
--- a/bin/git-checkoutpreviousselected
+++ b/bin/git-checkoutpreviousselected
@@ -17,8 +17,7 @@ case "$1" in
 esac
 
 if git-dirty; then
-    echo >&2 "ERROR: working copy is still dirty; please clean up first."
-    git status
+    echo >&2 'ERROR: working copy is still dirty; please clean up first.'
     exit 1
 fi
 
diff --git a/bin/git-dirty b/bin/git-dirty
--- a/bin/git-dirty
+++ b/bin/git-dirty
@@ -3,21 +3,33 @@
 printUsage()
 {
     cat <<HELPTEXT
-Test whether there are uncommitted changes, either in the working copy or the
-index.
+Test whether there are / list uncommitted changes, either in the working copy or
+the index.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--] [<path> ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet] [--] [<path> ...] [-?|-h|--help]'
 }
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
+isQuiet=
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-    --)			shift;;
-esac
+	--color)	shift; shift;;
+	--quiet|-q)	shift; isQuiet=t;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 
-if [ $# -eq 0 ]; then
+runStatus()
+{
+    git status --short --untracked-files=no -- "$@" 2>/dev/null
+}
+
+if [ "$isQuiet" ] && [ $# -eq 0 ]; then
     # An empty repository causes "git diff-index" to complain about "fatal: bad
     # revision 'HEAD'", so it would be considered dirty if we didn't check for
     # that here.
@@ -25,5 +37,13 @@ if [ $# -eq 0 ]; then
 
     ! { git update-index --refresh >/dev/null  && git diff-index --cached --quiet HEAD --; } # Note: Could use "! git-staged --quiet" here as well, but let's avoid the indirection here.
 else
-    [ "$(git status --short --untracked-files=no -- "$@" 2>/dev/null)" ]
+    paths="$(runStatus "$@")"
+    if [ "$isQuiet" ]; then
+	[ -n "$paths" ]
+    else
+	# Note: Re-execute the status command because it does not (Git version
+	# 2.39.0) support any --color=always and the captured output has no
+	# coloring.
+	[ -n "$paths" ] && runStatus "$@"
+    fi
 fi
