git-segregatecommits: Robustness: Use -- as the rebaseArgs may contain a flag (like --interactive) that causes parsing error in git-commitid
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.89.0 (2026-03-26), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-segregatecommits b/bin/git-segregatecommits
--- a/bin/git-segregatecommits
+++ b/bin/git-segregatecommits
@@ -52,7 +52,7 @@ git-isrebasing --print-positive-error && exit 2
 git-dirty --print-error && exit 2
 
 branch=HEAD
-if [ ${#rebaseArgs[@]} -ge 2 ] && git-commitid --quiet --no-error "${rebaseArgs[-1]}" && git-commitid --quiet --no-error "${rebaseArgs[-2]}"; then
+if [ ${#rebaseArgs[@]} -ge 2 ] && git-commitid --quiet --no-error -- "${rebaseArgs[-1]}" && git-commitid --quiet --no-error -- "${rebaseArgs[-2]}"; then
     # <upstream> <branch> variant: Move <branch> off rebaseArgs onto $@, so that it
     # doesn't get reapplied to git-bifurcate.
     branch="${rebaseArgs[-1]}"
@@ -60,7 +60,7 @@ if [ ${#rebaseArgs[@]} -ge 2 ] && git-commitid --quiet --no-error "${rebaseArgs[
     rebaseArgs=("${rebaseArgs[@]:0:$((${#rebaseArgs[@]}-1))}")
 fi
 
-originalCommit="$(git-commitid "$branch")" || exit 3
+originalCommit="$(git-commitid -- "$branch")" || exit 3
 export GIT_SEGREGATECOMMIT_FINAL_MESSAGE=''
 git-wrapper rebase --exec git-segregatecommit "${segregateCommitArgs[@]}" \; "${rebaseArgs[@]}" "$@" || exit $?
 if [ "$isBifurcate" ]; then
