git-submodule-uninitialized: ENH: Support --recursive

diff --git a/bin/git-submodule-uninitialized b/bin/git-submodule-uninitialized
--- a/bin/git-submodule-uninitialized
+++ b/bin/git-submodule-uninitialized
@@ -7,13 +7,25 @@ Test whether there are uninitialized submodules.
 With -p|--print, also prints the names of those submodules.
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-p|--print] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-p|--print] [--recursive] [-?|-h|--help]'
 }
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --print|-p)		shift; isPrint=t;;
-esac
+typeset -a submoduleArgs=()
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--print|-p)	shift; isPrint=t;;
+	--recursive)	submoduleArgs+=("$1"); shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
+if [ $# -ne 0 ]; then
+    printUsage "$0" >&2
+    exit 2
+fi
 
-uninitializedSubmodules="$(git submodule status | sed -n -e 's/^-[[:xdigit:]]\+[[:space:]]\+\(.*\)$/\1/p')" || exit 3
+uninitializedSubmodules="$(git submodule status "${submoduleArgs[@]}" | sed -n -e 's/^-[[:xdigit:]]\+[[:space:]]\+\(.*\)$/\1/p')" || exit 3
 [ -n "$uninitializedSubmodules" ] || exit 1
 [ ! "$isPrint" ] || printf '%s\n' "$uninitializedSubmodules"
