git-ls: ENH: Implement (one-level, recursive) listing of submodules

diff --git a/bin/git-ls b/bin/git-ls
--- a/bin/git-ls
+++ b/bin/git-ls
@@ -5,15 +5,17 @@ printUsage()
     cat <<HELPTEXT
 List files under version control; skip unversioned files.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-l|--long [--date FORMAT|--relative-date]] [-r|--recursive|-d|--directory] [-f|--only-files] [--no-classify] [FILE, ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-l|--long [--date FORMAT|--relative-date]] [-r|--recursive|-d|--directory] [-f|--only-files] [--no-classify] [--submodule name|ignore|recurse] [--] [FILE ...] [-?|-h|--help]'
 }
 
+typeset -a allSelfArgs=("$@")
 isNeedLog=
 formatPrefix=
 formatSuffix=
 maxDepth=1
 isOnlyFiles=
 classifyDirectories=/
+submodule=name
 typeset -a gitLogArgs=()
 while [ $# -ne 0 ]
 do
@@ -28,23 +30,49 @@ do
 	--date=*)		isNeedLog=t; gitLogArgs+=("$1"); shift;;
 	--relative-date)	isNeedLog=t; gitLogArgs+=("$1"); shift;;
 	--no-classify)		shift; classifyDirectories=;;
+	--submodule)	shift; submodule="${1:?}"; shift;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
+typeset -a allSelfOptions=("${allSelfArgs[@]:0:$((${#allSelfArgs[@]} - $#))}")
 
 listFiles()
 {
     find "${@#${PWD}/}" ${maxDepth:+-maxdepth} $maxDepth -name .git -prune -o -print | sort
 }
 
+typeset -A submodules=()
+case "$submodule" in
+    name) ;;
+    ignore|recurse)
+	while IFS=$'\n' read -r name
+	do
+	    submodules["$name"]=t
+	done < <(git sublist)
+	;;
+    *)	echo >&2 'ERROR: Invalid value for --submodule, must be one of name|ignore|recurse'
+	echo >&2
+	printUsage "$0" >&2
+	exit 2
+	;;
+esac
+
 IFS=$'\n'
 for filespec in $(listFiles "$@")
 do
     [ "$filespec" = . ] && continue
-
     filespec=${filespec#./}
+
+    [ "${submodules["$filespec"]}" ] && case "$submodule" in
+	ignore)
+	    continue;;
+	recurse)
+	    (cd "$filespec" && git-ls "${allSelfOptions[@]}" | prefix "$filespec/");;
+    esac
+
+
     if [ "$isNeedLog" ]; then
 	# Optimization: git ls-files can sort out untracked files much faster
 	# than git log.
