ENH: Minor: Make the -l|--list optional
Simply passing the <pattern> is more natural, as there's already "list" in the command name itself. But keep the option as well, as that's convenient for wrappers.

diff --git a/bin/git-tagtype b/bin/git-tagtype
--- a/bin/git-tagtype
+++ b/bin/git-tagtype
@@ -6,23 +6,32 @@ printUsage()
     cat <<HELPTEXT
 List only those tags of the passed (annotated or lightweight) type.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" 'annotated|lightweight [-l|--list <pattern>] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" 'annotated|lightweight [[-l|--list] <pattern>] [-?|-h|--help]'
 }
 
 case "$1" in
-    --help|-h|-\?)  shift; printUsage "$0"; exit 0;;
+    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
     --no-color|--color=*)
 			shift;;
     --color)		shift; shift;;
-    annotated)	    tagType=tag;;
-    lightweight)    tagType=commit;;
-    *)		    printf >&2 'ERROR: Invalid tag type %s; must be either annotated or lightweight.\n' "$1"; exit 2;;
+    annotated)		tagType=tag;;
+    lightweight)	tagType=commit;;
+    *)			printf >&2 'ERROR: Invalid tag type %s; must be either annotated or lightweight.\n' "$1"; exit 2;;
 esac; shift
 
 filter=
 pattern=
 case "$1" in
-    --list|-l)	    shift; filter='matcher'; pattern="$1"; shift;;
+    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+    --no-color|--color=*)
+			shift;;
+    --color)		shift; shift;;
+    --list|-l)		shift; filter='matcher'; pattern="$1"; shift;;
+esac
+case $# in
+    0)	;;
+    1)	filter='matcher'; pattern="$1"; shift;;
+    *)	printUsage "$0" >&2; exit 2;;
 esac
 
 matcher()
