Refactoring: Minor: Long command-line argument parsing
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.95.0 (2026-06-17), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/git-alias b/bin/git-alias
--- a/bin/git-alias
+++ b/bin/git-alias
@@ -25,16 +25,22 @@ printUsage()
 List all Git aliases [starting with <pattern>].
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[<pattern>] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--] [<pattern>] [-?|-h|--help]'
 }
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
-			shift;;
-    --color)		shift; shift;;
-    --translate)	shift; translateUppercaseAlias "${1?}"; exit 0;;
-    --un-translate)	shift; unTranslateUppercaseAlias; exit 0;;
-esac
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
+    			shift;;
+	--color)	shift; shift;;
+	--translate)	shift; translateUppercaseAlias "${1?}"; exit 0;;
+	--un-translate)	shift; unTranslateUppercaseAlias; exit 0;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=()
 
 printAliases()
