git-logrange-command:CHG: Make --revision REVISION the start revision for a search for the first matching commit (cp. 4f5bcf95)
Instead of complaining that the first revision already doesn't match. That isn't so useful. I want to point the search to the beginning of e.g. a merged branch and have it find the consecutive matching commits there.

(This relates to commit 4f5bcf95a5cbeabccb20fe7a49242bbb757d6b41)

diff --git a/bin/git-logrange-command b/bin/git-logrange-command
--- a/bin/git-logrange-command
+++ b/bin/git-logrange-command
@@ -30,8 +30,8 @@ printLongUsage()
     # This is the long "man page" when launched with the help argument.
     # It is printed to stdout to allow paging with 'more'.
     cat <<HELPDESCRIPTION
-Print / execute GIT-COMMAND with a revision range starting from the passed
-REVISION / the most recent revision where ${GIT_LOGRANGE_RANGE_WHAT:?} and including all such following commits where ${GIT_LOGRANGE_RANGE_WHAT:?}
+Print / execute GIT-COMMAND with a revision range starting with the most recent
+revision from HEAD / passed REVISION where ${GIT_LOGRANGE_RANGE_WHAT:?} and including all consecutive commits where ${GIT_LOGRANGE_RANGE_WHAT:?}
 - appended
 - replacing RANGE argument(s) anywhere
 - replacing RANGE in the following GIT-COMMAND and -(N-1) arguments
@@ -159,30 +159,19 @@ if [ -z "${files+t}" ]; then
 	set -- "${@:1:$(($#-1))}"
     done
 fi
+: ${revision:=HEAD}
 
+revision="$(git ${GIT_LOGRANGE_RANGE_COMMAND:?} --max-count 1 --pretty=tformat:%H "${grepModificationArgs[@]}" "${grepArgs[@]}" ${isLogArgsForRange:+"${logArgs[@]}"} "$revision" ${isFilesForRange:+-- "${files[@]}"} "${finalGrepArg[@]}")"
 if [ -z "$revision" ]; then
-    revision="$(git ${GIT_LOGRANGE_RANGE_COMMAND:?} --max-count 1 --pretty=tformat:%H "${grepModificationArgs[@]}" "${grepArgs[@]}" ${isLogArgsForRange:+"${logArgs[@]}"} ${isFilesForRange:+-- "${files[@]}"} "${finalGrepArg[@]}")"
-    if [ -z "$revision" ]; then
-	echo >&2 'Could not find a matching commit.'
-	exit 1
-    fi
+    echo >&2 'Could not find a matching commit.'
+    exit 1
 fi
 
-startRevision=
-< <(diff --unchanged-line-format= --old-line-format='%dn %L' --new-line-format= -- \
+< <(diff --unchanged-line-format= --old-line-format='%L' --new-line-format= -- \
     <(git log --first-parent --pretty=tformat:%H "$revision" ${isLogArgsForRange:+"${logArgs[@]}"} ${isFilesForRange:+-- "${files[@]}"}) \
     <(git ${GIT_LOGRANGE_RANGE_COMMAND:?} --first-parent --pretty=tformat:%H "${grepModificationArgs[@]}" "${grepArgs[@]}" "$revision" ${isLogArgsForRange:+"${logArgs[@]}"} ${isFilesForRange:+-- "${files[@]}"} "${finalGrepArg[@]}") # Fortunately, "git log <revision> --follow -- <path>" also works; else, we would have to split logArgs into options and path arguments.
-) IFS=' ' read -r firstDifferentCount firstDifferentRevision
-
-if [ -n "$firstDifferentRevision" ]; then
-    if [ $firstDifferentCount -eq 1 ]; then
-	printf >&2 'The %s revision already does not match.\n' "$revision"
-	exit 1
-    else
-	startRevision="$firstDifferentRevision"
-    fi
-fi
+) IFS=$'\n' read -r firstDifferentRevision
 
 [ "$isWithRange" ] || revision=''   # Prevent "ERROR: --end-revision cannot be combined with --no-range!"; we don't need the end revision, as --no-range drops that, anyway.
 
-exec git-rev-range --revision "$startRevision" ${revision:+--end-revision "$revision"} ${isLogArgsForCommand:+"${logArgs[@]}"} "$@" ${isFilesForCommand:+${files:+--} "${files[@]}"} "${specialLastArg[@]}"
+exec git-rev-range --revision "$firstDifferentRevision" ${revision:+--end-revision "$revision"} ${isLogArgsForCommand:+"${logArgs[@]}"} "$@" ${isFilesForCommand:+${files:+--} "${files[@]}"} "${specialLastArg[@]}"
