git-files-command: ENH: Also support --source-exec COMMAND [...] ; in addition to --source-command COMMANDLINE
This allow us to pass the git-rev-range RANGE as a separate argument. The alternative would have been to make git-rev-range expand RANGE anywhere, or add a QRANGE symbol.

diff --git a/bin/git-files-command b/bin/git-files-command
--- a/bin/git-files-command
+++ b/bin/git-files-command
@@ -11,15 +11,30 @@ Execute GIT-COMMAND with a list of files that is obtained from SOURCE-COMMAND
 - replacing FILES in the following +(N) arguments and appending those
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '--source-command SOURCE-COMMAND GIT-COMMAND [GIT-COMMAND-ARGS ...] [-?|-h|--help]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '--source-command SOURCE-COMMAND --keep-position GIT-COMMAND SOURCE-COMMAND [GIT-COMMAND-ARGS ... FILES ...]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '--source-command SOURCE-COMMAND [-2 GIT-COMMAND ARG1|-3 GIT-COMMAND ARG1 ARG2|...] [...]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '--source-command SOURCE-COMMAND [+1 ARG1|+2 ARG1 ARG2|+3 ARG1 ARG2 ARG3|...] GIT-COMMAND [...]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '--source-command SOURCE-COMMANDLINE|--source-exec COMMAND [...] ; GIT-COMMAND [GIT-COMMAND-ARGS ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '--source-command SOURCE-COMMANDLINE|--source-exec COMMAND [...] ; --keep-position GIT-COMMAND SOURCE-COMMAND [GIT-COMMAND-ARGS ... FILES ...]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '--source-command SOURCE-COMMANDLINE|--source-exec COMMAND [...] ; [-2 GIT-COMMAND ARG1|-3 GIT-COMMAND ARG1 ARG2|...] [...]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '--source-command SOURCE-COMMANDLINE|--source-exec COMMAND [...] ; [+1 ARG1|+2 ARG1 ARG2|+3 ARG1 ARG2 ARG3|...] GIT-COMMAND [...]'
 }
 sourceCommand=
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --source-command)	shift; sourceCommand="${1:?}"; shift;;
+    --source-command)	shift; sourceCommand+="${sourceCommand:+; }${1:?}"; shift;;
+    --source-exec)	shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != ';' ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    cmd="${cmd}${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo 'ERROR: --source-exec command must be concluded with ;!'; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			sourceCommand+="${sourceCommand:+; }$cmd"
+			;;
 esac
 if [ -z "$sourceCommand" -o $# -lt 1 ]; then
     echo >&2 'ERROR: Need to pass GIT-COMMAND and SOURCE-COMMAND'
