git-reintegrate: Also print continuation when pre-push command fails
So that the user knows how to restart.

diff --git a/bin/git-reintegrate b/bin/git-reintegrate
--- a/bin/git-reintegrate
+++ b/bin/git-reintegrate
@@ -433,7 +433,14 @@ fi || {
 status=0
 if [ "$isPush" ]; then
     if [ -n "$GIT_REINTEGRATE_PRE_PUSH_COMMAND" ]; then
-	eval "$GIT_REINTEGRATE_PRE_PUSH_COMMAND" || exit $?
+	eval "$GIT_REINTEGRATE_PRE_PUSH_COMMAND" || {
+	    status=$?
+	    echo >&2 "Push preparation failed; $branchesSubjectAuxiliaryVerb been reintegrated, but not pushed or ${isKeepBranches:+not }deleted yet."
+	    echo >&2 'Correct the problem, then invoke'
+	    isCheckFromStdin=; checkCommandArgs=()  # No need to re-run checks.
+	    printContinueCommand --no-checks
+	    exit $status
+	}
     fi
 
     printf '\nPushing merged branch%s:\n' "$branchesPlural"
