Renaming: pickaxe to changed-command, which now takes GIT-COMMAND as a first argument
The pickaxe verb still isn't very intuitive for me, the legacy workaround with the shell command syntax has been ugly, and prevented me from doing the right thing; i.e. defining rnlog variants instead of directly shoving in GIT_RNLOG_COMMAND overrides in addition to the GIT_PICKAXE_COMMAND ones.
Cleanup: The show[files]{changed,touched} variants are duplicates and poorly documented; get rid of them.
Sketch new changedfiles variants that will now only cover the last found commit (making wherelastfiles truly different from changedfiles), but still requires some work, as these aren't consecutive commits that can simply be passed to showfiles, but need to be individually tallied and then deduplicated (via a new --uniq flag).

diff --git a/bin/git-changed-command b/bin/git-changed-command
--- a/bin/git-changed-command
+++ b/bin/git-changed-command
@@ -3,14 +3,25 @@
 printUsage()
 {
     cat <<HELPTEXT
-Pickaxe: Log where text or /regexp/ was added or removed (i.e. those filepairs
-whose preimage and postimage have different number of occurrences of the text).
+${gitCommand:-Execute GIT-COMMAND} where text or /regexp/ was added or removed (i.e. those
+filepairs whose preimage and postimage have different number of occurrences of
+the text).
 With --more also log where lines were modified where text or /regexp/ just
 appears (without necessarily modifying text or /regexp/ itself).
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--more] [<log-options>] [<since>..<until>] [[--] <path>...] text|/regexp/ [-?|-h|--help]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--more] [<log-options>] [<since>..<until>] --grep=<pattern> [[--] <path>...]'
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" "${gitCommand:-GIT-COMMAND} [--more] [<log-options>] [<since>..<until>] [[--] <path>...] text|/regexp/ [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "${gitCommand:-GIT-COMMAND} [--more] [<log-options>] [<since>..<until>] --grep=<pattern> [[--] <path>...]"
 }
+
+case "$1" in
+    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+esac
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    exit 2
+fi
+gitCommand="$1"; shift
 
 isMore=
 typeset -a args=()
@@ -65,4 +76,4 @@ else
     fi
 fi
 
-exec git-wrapper ${GIT_PICKAXE_COMMAND:-log} "${pickaxeArgs[@]}" "$@"
+exec git-wrapper $gitCommand "${pickaxeArgs[@]}" "$@"
