FIX: REMOTE must be parsed before any log arg

diff --git a/bin/git-rcolatestc b/bin/git-rcolatestc
--- a/bin/git-rcolatestc
+++ b/bin/git-rcolatestc
@@ -12,14 +12,21 @@ HELPTEXT
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" "${remote:-REMOTE} [--gui|--terminal|--none] [<branch-glob>] [-?|-h|--help]"
 }
+case "$1" in
+    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+esac
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: Must pass REMOTE.'
+    exit 2
+fi
+remote="${1:?}"; shift
+
 logArg=
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
     --@(gui|terminal|none))
 			logArg="$1"; shift;;
 esac
-
-
 if [ $# -eq 0 -o $# -gt 2 ]; then
     echo >&2 "ERROR: Must pass REMOTE and optionally <branch-glob>."
     exit 2
