ENH: Highlight approval state with colorful background

diff --git a/bin/hub-prapproval b/bin/hub-prapproval
--- a/bin/hub-prapproval
+++ b/bin/hub-prapproval
@@ -5,6 +5,10 @@ set -o pipefail
 
 : ${HUB_PRAPPROVAL_OWNER:='{owner}'}
 : ${HUB_PRAPPROVAL_REPO:='{repo}'}
+: ${HUB_PRAPPROVAL_COLOR_APPROVED=[37;42m}
+: ${HUB_PRAPPROVAL_COLOR_COMMENTED=[37;44m}
+: ${HUB_PRAPPROVAL_COLOR_CHANGES_REQUESTED=[37;41m}
+: ${HUB_PRAPPROVAL_COLOR_RESET=[0m}
 
 printUsage()
 {
@@ -15,15 +19,34 @@ HELPTEXT
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '[#ID|<commit> [...]] [-?|-h|--help]'
 }
+
+isColor=; [ -t 1 ] && isColor=t
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+    --no-color|--color=never)
+			isColor=; shift;;
+    --color=always)	isColor=t; shift;;
+    --color=auto)	shift;;
+    --color)		case "$2" in
+			    always) isColor=t;;
+			    never)  isColor=;;
+			    auto)   ;;
+			    *)	    echo >&2 "ERROR: Invalid --color arg: $2"
+				    echo >&2
+				    printUsage "$0" >&2
+				    exit 2
+				    ;;
+			esac
+			shift; shift
+			;;
 esac
+[ "$isColor" ] || unset "${!HUB_PRAPPROVAL_COLOR_@}"
 
 apiCall()
 {
     local prId="${1:?}"; shift
     hub api "$@" "repos/${HUB_PRAPPROVAL_OWNER}/${HUB_PRAPPROVAL_REPO}/pulls/${prId:?}/reviews" \
-	| jq --raw-output '.[] | .user.login + "\t" + .state + "\t" + .submitted_at + if .body == "" then "" else "\n" + .body | gsub("(\r?\n)+$"; "") end' \
+	| jq --raw-output '.[] | .user.login + "\t" + '"if .state == \"APPROVED\" then \"${HUB_PRAPPROVAL_COLOR_APPROVED}APPROVED${HUB_PRAPPROVAL_COLOR_RESET}\" elif .state == \"COMMENTED\" then \"${HUB_PRAPPROVAL_COLOR_COMMENTED}COMMENTED${HUB_PRAPPROVAL_COLOR_RESET}\" elif .state == \"CHANGES_REQUESTED\" then \"${HUB_PRAPPROVAL_COLOR_CHANGES_REQUESTED}CHANGES_REQUESTED${HUB_PRAPPROVAL_COLOR_RESET}\" else .state end"' + "\t" + .submitted_at + if .body == "" then "" else "\n" + .body | gsub("(\r?\n)+$"; "") end' \
 	| reldate --delta-each --within all
 }
 
