ENH: Also capture existing colors and descriptions and skip update if identical
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.47.1, hub version 2.14.2, gh version 2.55.0 (2024-08-20), git-lfs/3.6.0 (GitHub; linux amd64; go 1.23.1)

diff --git a/bin/hub-labels b/bin/hub-labels
--- a/bin/hub-labels
+++ b/bin/hub-labels
@@ -80,14 +80,16 @@ listLabels()
 
 setDefaultLabels()
 {
-    typeset -A existingLabels=() unprocessedLabels=()
-    local name; while IFS=$'\n' read -r name
+    typeset -A existingLabels=() existingColors=() existingDescriptions=() unprocessedLabels=()
+    local name; while IFS=$'\t' read -r name color description
     do
 	existingLabels["$name"]=t
+	existingColors["$name"]="$color"
+	existingDescriptions["$name"]="$description"
 	unprocessedLabels["$name"]=t
     done < <(
 	apiCall \
-	    | jq --raw-output '.[] | .name'
+	    | jq --raw-output '.[] | .name + "\t" + "#" + .color + "\t" + .description'
     )
 
     if [ -r "$1" ]; then
@@ -114,16 +116,21 @@ setDefaultLabels()
     do
 	[ ! "$hasPassedLabels" ] || [ "${passedLabels["$label"]}" ] || continue
 
-	local labelJson; labelJson="$(jo -- name="$label" -s color="${color#\#}" description="$description")" || exit 3
-	if [ "${existingLabels["$label"]}" ]; then
-	    apiCall --method PATCH --input <(printf "%s\n" "$labelJson") >/dev/null <&3 \
-		&& printf 'Updated label "%s"\n' "$label" \
-		|| { status=$?; printf >&2 'ERROR: Failed to update label "%s"\n' "$label"; }
-	else
-	    label='' apiCall --method POST --input <(printf '%s\n' "$labelJson") >/dev/null <&3 \
-		&& printf 'Added label "%s"\n' "$label" \
-		|| { status=$?; printf >&2 'ERROR: Failed to add label "%s"\n' "$label"; }
+	if [ "${existingColors["$label"]}" != "${color,,}" ] \
+	    || [ "${existingDescriptions["$label"]}" != "$description" ]
+	then
+	    local labelJson; labelJson="$(jo -- name="$label" -s color="${color#\#}" description="$description")" || exit 3
+	    if [ "${existingLabels["$label"]}" ]; then
+		apiCall --method PATCH --input <(printf "%s\n" "$labelJson") >/dev/null <&3 \
+		    && printf 'Updated label "%s"\n' "$label" \
+		    || { status=$?; printf >&2 'ERROR: Failed to update label "%s"\n' "$label"; }
+	    else
+		label='' apiCall --method POST --input <(printf '%s\n' "$labelJson") >/dev/null <&3 \
+		    && printf 'Added label "%s"\n' "$label" \
+		    || { status=$?; printf >&2 'ERROR: Failed to add label "%s"\n' "$label"; }
+	    fi
 	fi
+
 	unset "unprocessedLabels[$label]"
 	unset "passedLabels[$label]"
     done < "$defaultLabelsFilespec"
