Refactoring: Extract format

diff --git a/bin/hub-pr b/bin/hub-pr
--- a/bin/hub-pr
+++ b/bin/hub-pr
@@ -6,6 +6,7 @@ if [ $# -eq 0 -o "${1:0:1}" = '-' ]; then
 	--assignee=*|--creator=*|--mentioned=*)
 	    # XXX: hub pr (in version 2.10.0) cannot filter yet, but we can
 	    # misuse hub issue for it (with filtering).
+	    format='%sC%>(8)%i%Creset  %t%  l'
 	    typeset -a args=()
 	    typeset -a colorArg=()
 	    while [ $# -ne 0 ]
@@ -14,14 +15,15 @@ if [ $# -eq 0 -o "${1:0:1}" = '-' ]; then
 		    --help|-h|-\?)		shift; printUsage "$0"; exit 0;;
 		    --no-color|--color=*)	colorArg=("$1"); shift;;
 		    --color)			colorArg=("$1" "$2"); shift; shift;;
-		    --format|-f)		echo >&2 "ERROR: Cannot use -f|--format here."; exit 2;;
+		    --format|-f)		echo >&2 'ERROR: Cannot use -f|--format here.'; exit 2;;
 		    --)				args+=("$1"); shift; break;;
 		    *)				args+=("$1"); shift;;
 		esac
 	    done
 	    isNeedColorArgumentWhenPiping "${colorArg[@]}" && colorArg=(--color=always) || colorArg=()
 
-	    hub issue --include-pulls --format '%U	%sC%>(8)%i%Creset  %t%  l%n' "${colorArg[@]}" "${args[@]}" "$@" | sed -e 's#^[^\t]\+/pull/[^\t]\+\t\(.*\)$#\1#' -e t -e 'd'
+	    hub issue --include-pulls --format "%U	${format}%n" "${colorArg[@]}" "${args[@]}" "$@" \
+		| sed -e 's#^[^\t]\+/pull/[^\t]\+\t\(.*\)$#\1#' -e t -e 'd'
 	    exit $?
 	    ;;
     esac
