ENH: Minor: Return 99 if all labels are already up-to-date
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.47.1, hub version 2.14.2, gh version 2.55.0 (2024-08-20), git-lfs/3.6.0 (GitHub; linux amd64; go 1.23.1)

diff --git a/bin/hub-labels b/bin/hub-labels
--- a/bin/hub-labels
+++ b/bin/hub-labels
@@ -110,7 +110,7 @@ setDefaultLabels()
 	passedLabels["$label"]=t
     done
 
-    local color description status=0
+    local color description status=
     exec 3<&0
     while IFS=$'\t' read -r color label description
     do
@@ -121,13 +121,21 @@ setDefaultLabels()
 	then
 	    local labelJson; labelJson="$(jo -- name="$label" -s color="${color#\#}" description="$description")" || exit 3
 	    if [ "${existingLabels["$label"]}" ]; then
-		apiCall --method PATCH --input <(printf "%s\n" "$labelJson") >/dev/null <&3 \
-		    && printf 'Updated label "%s"\n' "$label" \
-		    || { status=$?; printf >&2 'ERROR: Failed to update label "%s"\n' "$label"; }
+		if apiCall --method PATCH --input <(printf "%s\n" "$labelJson") >/dev/null <&3; then
+		    : ${status:=0}
+		    printf 'Updated label "%s"\n' "$label"
+		else
+		    status=$?
+		    printf >&2 'ERROR: Failed to update label "%s"\n' "$label"
+		fi
 	    else
-		label='' apiCall --method POST --input <(printf '%s\n' "$labelJson") >/dev/null <&3 \
-		    && printf 'Added label "%s"\n' "$label" \
-		    || { status=$?; printf >&2 'ERROR: Failed to add label "%s"\n' "$label"; }
+		if label='' apiCall --method POST --input <(printf '%s\n' "$labelJson") >/dev/null <&3; then
+		    : ${status:=0}
+		    printf 'Added label "%s"\n' "$label"
+		else
+		    status=$?
+		    printf >&2 'ERROR: Failed to add label "%s"\n' "$label"
+		fi
 	    fi
 	fi
 
@@ -149,7 +157,7 @@ setDefaultLabels()
     elif [ ${#unprocessedLabels[@]} -gt 0 ]; then
 	printf 'Note: Additional label in GitHub: "%s"\n' "${!unprocessedLabels[@]}"
     fi
-    return $status
+    return ${status:-99}
 }
 
 deleteLabels()
