hub-pr{approval,comments}: Robustness: Split apiCall from rendering and handle unknown PR ID
If the supplied PR ID does not exist, a different response is returned:
> {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/pulls#list-reviews-for-a-pull-request"}

jq's parsing barfs on that, which isn't nice:
> jq: error (at <stdin>:0): Cannot index string with string "body"

Apply the error handling from hub-branch-protection by splitting the API call and the parsing via jq into two separate functions, and only go this route if the API call was successful. In case of an error, extract the error message (via a separate jq call), print that, and fail.

diff --git a/bin/hub-prcomments b/bin/hub-prcomments
--- a/bin/hub-prcomments
+++ b/bin/hub-prcomments
@@ -101,8 +101,12 @@ query FetchReviewComments($owner: String!, $repo: String!, $pr: Int!) {
 	    }
 	}
     }
-}' \
-    | jq --raw-output "
+}'
+}
+
+renderComments()
+{
+    jq --raw-output "
 	.data.repository.pullRequest.reviewThreads.edges
 	    ${isResolvedFilter:+| map(select(.node.isResolved == false))}
 	    | .[]
@@ -141,7 +145,13 @@ status=0
 prComments=''
 for id in "${identifiers[@]}"
 do
-    prComments+="$(apiCall "$id")" || status=3
+    if response="$(apiCall "$id")"; then
+	prComments+="$(printf '%s\n' "$response" | renderComments)" || status=3
+    else
+	status=1
+	# Note: "gh api graphql" already extracts and prints the error message.
+	#printf '%s\n' "$response" | jq --raw-output '.errors | .[] | .message' >&2
+    fi
 done
 
 if [ $status -ne 0 ]; then
