Refactoring: Minor: Long command-line argument parsing
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.100.0 (2026-09-03), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/bin/hub-pr-isready b/bin/hub-pr-isready
--- a/bin/hub-pr-isready
+++ b/bin/hub-pr-isready
@@ -39,12 +39,18 @@ EXIT STATUS:
 HELPTEXT
 }
 
-case "$1" in
-    --help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-    --no-color|--color=*)
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-esac
+	--color)	shift; shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 case $# in
     0)	set -- 'HEAD';;
     1)	;;
diff --git a/bin/hub-prapproval b/bin/hub-prapproval
--- a/bin/hub-prapproval
+++ b/bin/hub-prapproval
@@ -46,13 +46,15 @@ HELPTEXT
 }
 
 isColor=; [ -t 1 ] && isColor=t
-case "$1" in
-    --help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-    --no-color|--color=never)
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--no-color|--color=never)
 			isColor=; shift;;
-    --color=always)	isColor=t; shift;;
-    --color=auto)	shift;;
-    --color)		case "$2" in
+	--color=always)	isColor=t; shift;;
+	--color=auto)	shift;;
+	--color)	case "$2" in
 			    always) isColor=t;;
 			    never)  isColor=;;
 			    auto)   ;;
@@ -64,7 +66,11 @@ case "$1" in
 			esac
 			shift; shift
 			;;
-esac
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 [ "$isColor" ] || unset "${!HUB_PRAPPROVAL_COLOR_@}"
 
 apiCall()
diff --git a/bin/hub-prcomments b/bin/hub-prcomments
--- a/bin/hub-prcomments
+++ b/bin/hub-prcomments
@@ -47,13 +47,15 @@ HELPTEXT
 
 isColor=; [ -t 1 ] && isColor=t
 isResolvedFilter=t
-case "$1" in
-    --help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-    --no-color|--color=never)
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--no-color|--color=never)
 			isColor=; shift;;
-    --color=always)	isColor=t; shift;;
-    --color=auto)	shift;;
-    --color)		case "$2" in
+	--color=always)	isColor=t; shift;;
+	--color=auto)	shift;;
+	--color)	case "$2" in
 			    always) isColor=t;;
 			    never)  isColor=;;
 			    auto)   ;;
@@ -65,8 +67,12 @@ case "$1" in
 			esac
 			shift; shift
 			;;
-    --all|-a)		shift; isResolvedFilter=;;
-esac
+	--all|-a)	shift; isResolvedFilter=;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 [ "$isColor" ] || unset "${!HUB_PRCOMMENTS_COLOR_@}"
 
 apiCall()
