Typo: Missing space in error message

diff --git a/bin/hub-workflow-status b/bin/hub-workflow-status
--- a/bin/hub-workflow-status
+++ b/bin/hub-workflow-status
@@ -96,7 +96,7 @@ if [ -z "$workflowId" ]; then
     workflowId="$(git config --get "$WORKFLOW_ID_CONFIG_KEY")"
     if [ -z "$workflowId" ]; then
 	[ "$isWorkflowCheck" ] && exit 1
-	echo >&2 "ERROR: No workflow specified (via --idWORKFLOW_ID|WORKFLOW_FILENAME, \$HUB_WORKFLOWSTATUS_WORKFLOW_ID, or the $WORKFLOW_ID_CONFIG_KEY configuration)."
+	echo >&2 "ERROR: No workflow specified (via --id WORKFLOW_ID|WORKFLOW_FILENAME, \$HUB_WORKFLOWSTATUS_WORKFLOW_ID, or the $WORKFLOW_ID_CONFIG_KEY configuration)."
 	exit 2
     elif [ "$isWorkflowCheck" ]; then
 	exit 0
