Robustness: Print unknown URL

diff --git a/bin/hub-userrepo b/bin/hub-userrepo
--- a/bin/hub-userrepo
+++ b/bin/hub-userrepo
@@ -29,5 +29,6 @@ elif [[ "$url" =~ ^[[:alnum:]]+://[^/]+/([^/]+/[^/]+).*$ ]]; then
 elif [[ "$url" =~ ^git@[^:]+:([^/]+/[^/]+)\.git.*$ ]]; then
     printf '%s\n' "${BASH_REMATCH[1]}"
 else
+    printf >&2 'ERROR: Unknown URL: %s\n' "$url"
     exit 3
 fi
