Robustness: --wait requires --is STATE

diff --git a/bin/hub-workflow-status b/bin/hub-workflow-status
--- a/bin/hub-workflow-status
+++ b/bin/hub-workflow-status
@@ -122,6 +122,13 @@ if [ -z "$workflowId" ]; then
 fi
 
 if [ "$isWait" ]; then
+    if [ ${#acceptedStates[@]} -eq 0 ]; then
+	echo 'ERROR: Need --is STATE to wait for.'
+	echo
+	printUsage "$0"
+	exit 2
+    fi >&2
+
     verb="$(joinBy ' or ' "${acceptedStates[@]}")"
     RETRY_SUCCEED_VERB="got $verb" RETRY_FAIL_VERB="still is not ${verb}${action:+: %OUTPUT%}" RETRY_ABORT_VERB="did not become ${verb}${action:+: %OUTPUT%}" \
 	retry --silent-command --command-name "${waitWhat:-The workflow action}" ${action:+--verbose-or-none --verbose-output} --interval "$HUB_WORKFLOWSTATUS_WAIT_INTERVAL" --abort-timeout "$HUB_WORKFLOWSTATUS_WAIT_TIMEOUT" \
