TODOFIX: Support -y|--yes in hub-{delete-merged-branches,push-this-branch} and pass from all clients
When the user decides to perform remote operations without confirmation, this should also include the branch pushes and deletions.

diff --git a/bin/hub-push-this-branch b/bin/hub-push-this-branch
--- a/bin/hub-push-this-branch
+++ b/bin/hub-push-this-branch
@@ -7,14 +7,22 @@ Push the current branch to all of: upstream (if writeable) / tracked remote /
 origin (in an order that makes sense).
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-y|--yes] [-?|-h|--help]'
 }
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --no-color|--color=*)
+typeset -a gitRemoteMutateArgs=()
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--no-color|--color=*)
 			shift;;
-    --color)		shift; shift;;
-esac
+	--color)	shift; shift;;
+	--yes|-y)	gitRemoteMutateArgs+=("$1"); shift;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -ne 0 ]; then
     printUsage "$0" >&2
     exit 2
