git-reintegrateto: Make passing of <branch> mandatory
Defaulting to master is not so useful, as the command reads strangely without a target branch and there is already the reintegratetom alias.

diff --git a/git-reintegrateto b/git-reintegrateto
--- a/git-reintegrateto
+++ b/git-reintegrateto
@@ -3,10 +3,11 @@
 printUsage()
 {
     cat <<HELPTEXT
-Merge the current branch to master / the passed <branch>, then delete it from
-the local repository as well as a tracked remote (if it exists there).
+Merge the current branch to the passed <branch>, then delete it from the local
+repository as well as a tracked remote (if it exists there).
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[<branch>] [--ff|--ff-only|--no-ff|<merge-args> ...] [-b|--branch <branch>]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '<branch> [--ff|--ff-only|--no-ff|<merge-args> ...]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--ff|--ff-only|--no-ff|<merge-args> ...] -b|--branch <branch>'
 }
 
 case "$1" in
@@ -39,7 +40,10 @@ do
 	*)		reintegrateArgs+=("$1"); shift;;
     esac
 done
-: ${target:=master}
+if [ -z "$target" ]; then
+    echo >&2 'ERROR: Missing <branch>.'
+    exit 2
+fi
 
 if [ "$target" = "$sourceBranch" ]; then
     printf >&2 'ERROR: Cannot reintegrate %s onto itself; check out a different branch first!\n' "$target"
