git-wcs-in-dir-do: Complain when a passed base directory does not exist
This could have prevented missed directories in my Unixhome-ingo script when it wasn't adapted to a changed directory layout.

diff --git a/git-wcs-in-dir-do b/git-wcs-in-dir-do
--- a/git-wcs-in-dir-do
+++ b/git-wcs-in-dir-do
@@ -49,6 +49,11 @@ fi
 typeset -a wcs=()
 for baseDir in "${dirspecs[@]}"
 do
+    if [ ! -d "$baseDir" ]; then
+	printf >&2 'ERROR: Not a directory: %s\n' "$baseDir"
+	continue
+    fi
+
     for dir in "${baseDir}"/*
     do
 	[ -d "$dir" ] || continue
