ENH: Handle git -c name=value arguments preceding the Git command in *-command wrappers
These arguments must be passed before the Git subcommand (so git -c merge.defaultToUpstream=true merge instead of git merge -c merge.defaultToUpstream=true). We need to add them to the gitCommand array so that proper ordering is maintained. (Most wrappers insert additional arguments in between, or invoke Git with a subset.)

diff --git a/git-contained-command b/git-contained-command
--- a/git-contained-command
+++ b/git-contained-command
@@ -1,14 +1,25 @@
 #!/bin/bash
 set -o pipefail
 
-command="${1:?}"; shift
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: Need to pass GIT-COMMAND.'
+    exit 2
+fi
+typeset -a gitCommand=()
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	-c) gitCommand+=("$1" "$2"); shift; shift;;
+	*)  gitCommand+=("$1"); shift; break;;
+    esac
+done
 
 printUsage()
 {
     cat <<HELPTEXT
 Show first tag [that matches GREP-ARGS] that the passed <commit> is based on.
 HELPTEXT
-    printf 'Usage: %q %s %s\n' "$(basename "$1")" "$command" '[GREP-ARGS] <commit> [-?|-h|--help]'
+    printf 'Usage: %q %s %s\n' "$(basename "$1")" "${gitCommand[-1]}" '[GREP-ARGS] <commit> [-?|-h|--help]'
 }
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
@@ -18,8 +29,8 @@ if [ $# -eq 0 ]; then
     echo >&2 'ERROR: Must pass <commit>'
     exit 2
 fi
-revision=${!#}
+revision="${!#}"
 typeset -a grepArgs=("${@:1:$(($#-1))}")
 
-eval 'git "$command" --contains "$revision" | ' ${grepArgs:+grep} '"${grepArgs[@]}"' ${grepArgs:+|} 'head -n 1' 2>/dev/null || \
+eval 'git "${gitCommand[@]}" --contains "$revision" | ' ${grepArgs:+grep} '"${grepArgs[@]}"' ${grepArgs:+|} 'head -n 1' 2>/dev/null || \
     git name-rev --name-only "$revision"
diff --git a/git-selected-command b/git-selected-command
--- a/git-selected-command
+++ b/git-selected-command
@@ -1,11 +1,23 @@
 #!/bin/bash
 
-gitCommand=${1:?}; shift
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: Need to pass GIT-COMMAND.'
+    exit 2
+fi
+typeset -a gitCommand=()
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	-c) gitCommand+=("$1" "$2"); shift; shift;;
+	*)  gitCommand+=("$1"); shift; break;;
+    esac
+done
 generator="${GIT_SELECTED_COMMAND_DEFAULT_FILES:-git ls-files --modified --}"
 
+printf -v quotedGitCommand '%q ' "${gitCommand[@]}"; quotedGitCommand=${quotedGitCommand% }
 type -t commandOnSelected >/dev/null && exec commandOnSelected \
     --generator "$generator" \
-    --command "git-wrapper $gitCommand" \
+    --command "git-wrapper $quotedGitCommand" \
     -- "$@"
 
 
@@ -25,7 +37,7 @@ do
 done
 set -- $(eval "$generator" '"$@"')
 if [ $# -eq 0 ]; then
-    echo >&2 "No files to ${gitCommand}."
+    echo >&2 "No files to ${gitCommand[-1]}."
     exit 124
 fi
 
@@ -60,7 +72,7 @@ selectByCounts()
     do
 	if [ $count -gt $# ]; then
 	    filePlural=s; [ $# -eq 1 ] && filePlural=
-	    printf >&2 'Only %d file%s to %s.\n' "$#" "$filePlural" "$gitCommand"
+	    printf >&2 'Only %d file%s to %s.\n' "$#" "$filePlural" "${gitCommand[-1]}"
 	    exit 2
 	fi
 
@@ -76,4 +88,4 @@ fi
 
 [ ${#selectedPaths[@]} -gt 0 ] || exit 125
 
-exec git-wrapper "$gitCommand" "${args[@]}" "${selectedPaths[@]}"
+exec git-wrapper "${gitCommand[@]}" "${args[@]}" "${selectedPaths[@]}"
