Minor: Consistently use printUsage(), add newline before bottom hint, do block-wide redirection

diff --git a/git-autostash b/git-autostash
--- a/git-autostash
+++ b/git-autostash
@@ -38,9 +38,11 @@ if [ $# -ne 0 ]; then
     fi
 fi
 if [ ${#commands[@]} -eq 0 ]; then
-    echo >&2 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 isDirty=; git-dirty && isDirty=t
 
diff --git a/git-autoworktree b/git-autoworktree
--- a/git-autoworktree
+++ b/git-autoworktree
@@ -11,7 +11,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -77,11 +77,11 @@ do
     esac
 done
 if [ ! "$path" ]; then
-    echo >&2 'ERROR: No -n|--name NAME|<path> passed.'
-    echo >&2
-    printUsage "$0" >&2
+    echo 'ERROR: No -n|--name NAME|<path> passed.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 if [ $# -ne 0 ]; then
     if [ "$isNeedEval" ]; then
 	# Combine --command and SIMPLECOMMAND; need to quote SIMPLECOMMAND to
@@ -92,9 +92,11 @@ if [ $# -ne 0 ]; then
     fi
 fi
 if [ ${#commands[@]} -eq 0 ]; then
-    echo >&2 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 if [ -d "$path" ]; then
     cd "$path" || exit $?
diff --git a/git-byuserrange-command b/git-byuserrange-command
--- a/git-byuserrange-command
+++ b/git-byuserrange-command
@@ -6,6 +6,7 @@ printShortUsage()
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" '-a|--auto-revision|-r|--revision REVISION [--author=<pattern>|--committer=<pattern> ...] [--no-range|--with-range ...|--last-only] [+1|--one-more] [GIT-COMMAND ...] [-?|-h|--help]'
+    echo
     printf 'Usage: %q %s\n' "$(basename "$1")" 'GIT-COMMAND -a|--auto-revision|-r|--revision REVISION [...] [-?|-h|--help]'
 }
 printUsage()
@@ -13,7 +14,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -80,11 +81,11 @@ if [ ${#userFilterArgs[@]} -eq 0 ]; then
 fi
 if [ "$isAutoRevision" ]; then
     if [ "$revision" != 'HEAD' ]; then
-	echo >&2 'ERROR: Cannot combine --auto-revision with --revision.'
-	echo >&2
-	printShortUsage "$0" >&2
+	echo 'ERROR: Cannot combine --auto-revision with --revision.'
+	echo
+	printUsage "$0"
 	exit 2
-    fi
+    fi >&2
 
     revision="$(git log --max-count 1 --pretty=tformat:%H "${userFilterArgs[@]}")"
     if [ -z "$revision" ]; then
diff --git a/git-contained-command b/git-contained-command
--- a/git-contained-command
+++ b/git-contained-command
@@ -25,10 +25,12 @@ case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 esac
 if [ $# -eq 0 ]; then
-    printUsage "$0" 2>&1
-    echo >&2 'ERROR: Must pass <commit>'
+    echo 'ERROR: Must pass <commit>'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
+
 revision="${!#}"
 typeset -a grepArgs=("${@:1:$(($#-1))}")
 
diff --git a/git-dashdash-default-command b/git-dashdash-default-command
--- a/git-dashdash-default-command
+++ b/git-dashdash-default-command
@@ -17,11 +17,11 @@ typeset -a gitCommand=()
 while [ "$1" != "$sep" ]
 do
     if [ $# -eq 0 ]; then
-	printf >&2 'ERROR: GIT-COMMAND not concluded by %s\n' "$sep"
-	echo >&2
-	printUsage "$0" >&2
+	printf 'ERROR: GIT-COMMAND not concluded by %s\n' "$sep"
+	echo >
+	printUsage "$0"
 	exit 2
-    fi
+    fi >&2
 
     gitCommand+=("$1"); shift
 done
diff --git a/git-discrepancylog b/git-discrepancylog
--- a/git-discrepancylog
+++ b/git-discrepancylog
@@ -23,10 +23,11 @@ do
     esac
 done
 if [ -z "$field1" -o -z "$field2" ]; then
-    echo >&2 'ERROR: Must pass both fields.'
-    printUsage "$0" >&2
+    echo 'ERROR: Must pass both fields.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 contains()
 {
diff --git a/git-email-command b/git-email-command
--- a/git-email-command
+++ b/git-email-command
@@ -12,7 +12,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -36,19 +36,20 @@ HELPTEXT
 case "$1" in
     --help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 esac
+
 typeset -a gitLookupCommand=(log)
 gitLogCommand="$1"; shift
 if [ -z "$gitLogCommand" ]; then
-    echo >&2 'ERROR: No GIT-COMMAND passed.'
-    echo >&2
-    printShortUsage "$0" >&2
+    echo 'ERROR: No GIT-COMMAND passed.'
+    echo
+    printShortUsage "$0"
     exit 2
 elif [ "$gitLogCommand" = show ]; then
     # git log would follow all passed revisions; --max-count 1 would only handle
     # a single passed revision. Therefore, use git show for the lookup as well,
     # but omit the diff.
     gitLookupCommand=(show --no-patch)
-fi
+fi >&2
 
 isDryRun=
 emailFormats='%aE%n%cE'
diff --git a/git-existsbr b/git-existsbr
--- a/git-existsbr
+++ b/git-existsbr
@@ -14,9 +14,11 @@ case "$1" in
     --verbose|-v)	shift; isVerbose=t;;
 esac
 if [ $# -eq 0 ]; then
-    echo >&2 'ERROR: No <branch> passed.'
+    echo 'ERROR: No <branch> passed.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 existsBranch()
 {
diff --git a/git-inside b/git-inside
--- a/git-inside
+++ b/git-inside
@@ -5,6 +5,7 @@ printShortUsage()
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-r|--from-root] [-s|--skip-foreign|--foreign-command "COMMANDLINE"] -c|--command "COMMANDLINE" [-c ...] | SIMPLECOMMAND [...] -- FILE [...] [-?|-h|--help]'
+    echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-r|--from-root] [-s|--skip-foreign|--foreign-command "COMMANDLINE"] -c|--command "COMMANDLINE" [-c ...] | SIMPLECOMMAND [...] [--] FILE [-?|-h|--help]'
 }
 printUsage()
@@ -12,7 +13,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -83,14 +84,14 @@ fi
 fileArgs+=("$@")
 
 if [ ${#commands[@]} -eq 0 ]; then
-    echo >&2 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
-    printUsage "$0" >&2
+    echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    printUsage "$0"
     exit 2
 elif [ ${#fileArgs[@]} -eq 0 ] || [ $# -eq 1 -a "$1" = '--' ]; then
-    echo >&2 'ERROR: No FILE(s) specified; need a file for the working copy location.'
-    printUsage "$0" >&2
+    echo 'ERROR: No FILE(s) specified; need a file for the working copy location.'
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 # If we're launched from within a Git operation (e.g. the external editor opened
 # by git commit), the environment variable GIT_DIR may have been set, and this
diff --git a/git-lghighlight b/git-lghighlight
--- a/git-lghighlight
+++ b/git-lghighlight
@@ -12,11 +12,11 @@ case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 esac
 if [ $# -eq 0 ]; then
-    echo >&2 'ERROR: No PATTERN passed.'
-    echo >&2
-    printUsage "$0" >&2
+    echo 'ERROR: No PATTERN passed.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 
 lghighlight()
diff --git a/git-others-command b/git-others-command
--- a/git-others-command
+++ b/git-others-command
@@ -30,11 +30,11 @@ do
     esac
 done
 if [ $# -eq 0 ]; then
-    echo >&2 'ERROR: No GIT-COMMAND passed.'
-    echo >&2
-    printUsage "$0" >&2
+    echo 'ERROR: No GIT-COMMAND passed.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 lastArg=${!#}
 typeset -a authorArgs=()
diff --git a/git-pasttimes-command b/git-pasttimes-command
--- a/git-pasttimes-command
+++ b/git-pasttimes-command
@@ -12,7 +12,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -89,11 +89,11 @@ else
 fi
 set -- "${args[@]}" "$@"
 if [ $# -eq 0 ]; then
-    echo >&2 'ERROR: No GIT-COMMAND passed.'
-    echo >&2
-    printShortUsage "$0" >&2
+    echo 'ERROR: No GIT-COMMAND passed.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 typeset -a gitCommand=()
 case "$1" in
diff --git a/git-reintegrate b/git-reintegrate
--- a/git-reintegrate
+++ b/git-reintegrate
@@ -75,11 +75,11 @@ if [ "${!#}" = '-' ]; then
     set -- "${@:1:$(($#-1))}"
 fi
 if [ "$isCheckFromStdin" ] && [ ${#checkCommands[@]} -gt 0 ]; then
-    echo >&2 'ERROR: Cannot combine CHECK-COMMANDLINE from stdin (-) with -c|--command.'
-    echo >&2
-    printUsage "$0" >&2
+    echo 'ERROR: Cannot combine CHECK-COMMANDLINE from stdin (-) with -c|--command.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 branches+=("$@")
 if [ ${#branches[@]} -eq 0 ]; then
diff --git a/git-rev-range b/git-rev-range
--- a/git-rev-range
+++ b/git-rev-range
@@ -53,12 +53,16 @@ do
     esac
 done
 if [ ! "$revision" ]; then
-    echo >&2 "ERROR: Missing REVISION!"
+    echo "ERROR: Missing REVISION!"
+    echo
+    printUsage "$0"
     exit 2
 elif [ ! "$range" ] && [ "$endRevision" ]; then
-    echo >&2 "ERROR: --end-revision cannot be combined with --no-range!"
+    echo "ERROR: --end-revision cannot be combined with --no-range!"
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 contains()
 {
diff --git a/git-stashselected b/git-stashselected
--- a/git-stashselected
+++ b/git-stashselected
@@ -16,7 +16,7 @@ case "$1" in
 esac
 
 if ! git diff-index --cached --quiet HEAD --; then
-    echo 'ERROR: Index must be clean.'
+    echo 'ERROR: Index must be clean.' >&2
     exit 1
 fi
 
diff --git a/git-wc-with-suffix-do b/git-wc-with-suffix-do
--- a/git-wc-with-suffix-do
+++ b/git-wc-with-suffix-do
@@ -34,10 +34,11 @@ do
 done
 if [ "$isWorktrees" ]; then
     if [ "$suffix" ]; then
-	echo >&2 "ERROR: Cannot combine --suffix and --worktrees."
-	printUsage "$0" >&2
+	echo "ERROR: Cannot combine --suffix and --worktrees."
+	echo
+	printUsage "$0"
 	exit 2
-    fi
+    fi >&2
 
     typeset -a collectDirnames=()
     for d in "${wcs[@]}"
@@ -47,10 +48,11 @@ if [ "$isWorktrees" ]; then
     wcs=("${collectDirnames[@]}")
 fi
 if [ ${#wcs[@]} -eq 0 ]; then
-    echo >&2 "ERROR: No WORKING-COPYs."
-    printUsage "$0" >&2
+    echo "ERROR: No WORKING-COPYs."
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 typeset -a wcWithSuffixes=()
 for dir in "${wcs[@]}"
diff --git a/git-wcs-in-dir-do b/git-wcs-in-dir-do
--- a/git-wcs-in-dir-do
+++ b/git-wcs-in-dir-do
@@ -45,10 +45,11 @@ do
     esac
 done
 if [ ${#dirspecs[@]} -eq 0 ]; then
-    echo >&2 "ERROR: No DIRSPECs."
-    printUsage "$0" >&2
+    echo "ERROR: No DIRSPECs."
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 typeset -a wcs=()
 for baseDir in "${dirspecs[@]}"
diff --git a/git-writebackup-import b/git-writebackup-import
--- a/git-writebackup-import
+++ b/git-writebackup-import
@@ -29,7 +29,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -216,7 +216,7 @@ do
 	--edit-message)		    shift; commitEditMessage='--edit';;
 	--edit-plugin-message)	    shift; commitEditMessage='plugin';;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
