git-whois: Cosmetics: Print command's understanding of invalid person argument
To make troubleshooting easier.

diff --git a/git-whois b/git-whois
--- a/git-whois
+++ b/git-whois
@@ -70,7 +70,7 @@ if [ ${#candidates[@]} -eq 0 ]; then
 	    printf '%s\n' "$person"
 	    exit
 	else
-	    echo >&2 "ERROR: Did not pass a valid NAME <EMAIL@HOST>!"
+	    printf >&2 "ERROR: Did not pass a valid NAME <EMAIL@HOST>: %s\n" "$person"
 	    exit 2
 	fi
     fi
