git-byuserrange-command: ENH: Add --auto-revision that selects the first commit of one of the passed authors / committers
With this the command can be used to obtain the last consecutive commit range of a user.

diff --git a/git-byuserrange-command b/git-byuserrange-command
--- a/git-byuserrange-command
+++ b/git-byuserrange-command
@@ -4,26 +4,29 @@ printUsage()
 {
     cat <<HELPTEXT
 Print / execute GIT-COMMAND with a revision range starting from HEAD / the
-passed REVISION and including all commits done by the passed --author(s) /
---committer(s) (or the author (+ committer if different) from the start
+passed REVISION / (with -a|--auto-revision:) the first found revision from the
+passed author / committer(s) and including all commits done by the passed author
+/ committer(s) (or the author (+ committer if different) from the start
 revision).
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-r|--revision REVISION --author=<pattern>|--committer=<pattern> [...] [GIT-COMMAND ...] [-?|-h|--help]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" 'GIT-COMMAND -r|--revision REVISION --author=<pattern>|--committer=<pattern> [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '-a|--auto-revision|-r|--revision REVISION [--author=<pattern>|--committer=<pattern> ...] [GIT-COMMAND ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" 'GIT-COMMAND -a|--auto-revision|-r|--revision REVISION [--author=<pattern>|--committer=<pattern> ...] [-?|-h|--help]'
 }
 typeset -a gitCommand=()
 isFirstArg=t
+isAutoRevision=
 revision='HEAD'
 range=..
 typeset userFilterArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-	--revision|-r)	shift; revision="$1"; shift;;
+	--help|-h|-\?)		    shift; printUsage "$0"; exit 0;;
+	--auto-revision|-a)	    shift; isAutoRevision=t;;
+	--revision|-r)		    shift; revision="$1"; shift;;
 	--author|--committer)	    userFilterArgs+=("$1" "$2"); shift; shift;;
 	--author=*|--committer=*)   userFilterArgs+=("$1"); shift;;
-	--with-range)	shift; range="$1"; shift;;
+	--with-range)		    shift; range="$1"; shift;;
 	*)  if [ "$isFirstArg" ]; then
 		case "$1" in
 		    -c) gitCommand+=("$1" "$2"); shift; shift;;
@@ -43,6 +46,20 @@ if [ ${#userFilterArgs[@]} -eq 0 ]; then
     committer="$(git show --no-patch --pretty=format:'%cN <%cE>' "$revision")" || exit $?
     userFilterArgs+=(--author "$author")
     [ "$author" = "$committer" ] || userFilterArgs+=(--committer "$committer")
+fi
+if [ "$isAutoRevision" ]; then
+    if [ "$revision" != 'HEAD' ]; then
+	echo >&2 'ERROR: Cannot combine --auto-revision with --revision.'
+	echo >&2
+	printUsage "$0" >&2
+	exit 2
+    fi
+
+    revision="$(git log --max-count 1 --pretty=tformat:%H "${userFilterArgs[@]}")"
+    if [ -z "$revision" ]; then
+	echo >&2 'Could not find a commit from those user(s).'
+	exit 1
+    fi
 fi
 
 startRevision=
