git-reintegrate: Refactoring: Collect branchesPlural definitions at top

diff --git a/git-reintegrate b/git-reintegrate
--- a/git-reintegrate
+++ b/git-reintegrate
@@ -75,6 +75,18 @@ if [ ${#branches[@]} -eq 0 ]; then
     exit 2
 fi
 
+branchesPlural=es
+branchesSubject=them
+branchesSubjectAuxiliaryVerb='branches have'
+verbPlural=
+if [ ${#branches[@]} -eq 1 ]; then
+    branchesPlural=
+    branchesSubject=it
+    branchesSubjectAuxiliaryVerb='the branch has'
+    verbPlural=s
+fi
+
+
 
 canFastForward()
 {
@@ -103,15 +115,6 @@ canRebase()
 
 if [ ! "$isContinue" ]; then
     if [ ! "$hasMergeResolutionArg" ]; then
-	branchesPlural=es
-	branchesSubject=them
-	verbPlural=
-	if [ ${#branches[@]} -eq 1 ]; then
-	    branchesPlural=
-	    branchesSubject=it
-	    verbPlural=s
-	fi
-
 	if canFastForward; then
 	    < /dev/tty read -r -N 1 -p "The branch$branchesPlural can be fast-forwarded instead of merged. Fast-forward? (y/n) " choice; echo >/dev/tty
 	    [ "$choice" = 'y' ] && fastForwardArgs=(--ff-only)
@@ -146,8 +149,7 @@ elif [ ${#checkCommands[@]} -gt 0 ]; then
     eval "${checkCommands[@]}"
 fi || {
     status=$?
-    branchSubject='branches have'; [ ${#branches[@]} -eq 1 ] && branchSubject='the branch has'
-    echo >&2 "Checks failed; $branchSubject been merged, but not ${isPush:+pushed or }deleted yet."
+    echo >&2 "Checks failed; $branchesSubjectAuxiliaryVerb been merged, but not ${isPush:+pushed or }deleted yet."
     echo >&2 'Correct the problem by amending or additional commits, then invoke'
 
     [ "$isCheckFromStdin" ] && printf >&2 'echo CHECK-COMMANDLINES | '
