git-*-command: Usability: Minor: Consistently check for empty GIT-COMMAND
This must be passed; else, strange errors are reported (mostly because augmented arguments like --author= are interpreted as a Git command). Better check this explicitly.

diff --git a/git-base-command b/git-base-command
--- a/git-base-command
+++ b/git-base-command
@@ -3,6 +3,9 @@
 if [ -z "$GIT_BASE_BRANCH" ]; then
     echo >&2 'ERROR: GIT_BASE_BRANCH not defined!'
     exit 2
+elif [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    exit 2
 fi
 
 typeset -a baseArgs=()
diff --git a/git-contained-command b/git-contained-command
--- a/git-contained-command
+++ b/git-contained-command
@@ -2,7 +2,7 @@
 set -o pipefail
 
 if [ $# -eq 0 ]; then
-    echo >&2 'ERROR: Need to pass GIT-COMMAND.'
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
     exit 2
 fi
 typeset -a gitCommand=()
diff --git a/git-me-in-github-command b/git-me-in-github-command
--- a/git-me-in-github-command
+++ b/git-me-in-github-command
@@ -2,6 +2,10 @@
 
 meOptionName="${1:?}"; shift
 me="$(git me-in-github)" || exit $?
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    exit 2
+fi
 
 typeset -a hubCommand=()
 case "$1" in
diff --git a/git-mine-command b/git-mine-command
--- a/git-mine-command
+++ b/git-mine-command
@@ -6,6 +6,10 @@ optionName='--author='
 if [ "$1" = '--no-option-name' ]; then
     shift; optionName=
 fi
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    exit 2
+fi
 
 typeset -a gitCommand=()
 case "$1" in
diff --git a/git-rev-branch-remotebr-command b/git-rev-branch-remotebr-command
--- a/git-rev-branch-remotebr-command
+++ b/git-rev-branch-remotebr-command
@@ -2,5 +2,9 @@
 
 remote=${1:?}; shift
 branch=${1:?}; shift
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    exit 2
+fi
 
 exec git-wrapper "$@" "${branch}..${remote}/${branch}"
diff --git a/git-rev-fetch-command b/git-rev-fetch-command
--- a/git-rev-fetch-command
+++ b/git-rev-fetch-command
@@ -1,3 +1,8 @@
 #!/bin/sh
 
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    exit 2
+fi
+
 exec git-wrapper "$@" ..FETCH_HEAD
diff --git a/git-rev-remote-command b/git-rev-remote-command
--- a/git-rev-remote-command
+++ b/git-rev-remote-command
@@ -1,5 +1,10 @@
 #!/bin/bash
 
 remote=${1:?}; shift
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    exit 2
+fi
+
 set -- $(git-parse-last-remotebr-argument "$remote" "$@")
 exec git-wrapper "$@"
diff --git a/git-rev-tracked-command b/git-rev-tracked-command
--- a/git-rev-tracked-command
+++ b/git-rev-tracked-command
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    exit 2
+fi
+
 trackedBranch=$(git tracks) || exit $?
 
 exec git-wrapper "$@" "$trackedBranch"
diff --git a/git-stfiles-command b/git-stfiles-command
--- a/git-stfiles-command
+++ b/git-stfiles-command
@@ -1,6 +1,11 @@
 #!/bin/bash
 set -o noglob
 
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    exit 2
+fi
+
 IFS=$'\n'
 typeset -a stfiles=($(${GIT_STFILES_COMMAND:-git-stfiles}))
 [ ${#stfiles[@]} -eq 0 ] && exit 1
diff --git a/git-team-command b/git-team-command
--- a/git-team-command
+++ b/git-team-command
@@ -15,6 +15,11 @@ else
     typeset -a teamArgs=("${team[@]/#/--author=}")
 fi
 
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    exit 2
+fi
+
 typeset -a gitCommand=()
 case "$1" in
     [^-]*-command)  gitCommand+=("$1"); shift
diff --git a/git-today-command b/git-today-command
--- a/git-today-command
+++ b/git-today-command
@@ -13,6 +13,11 @@ else
     rangeArgs=('--since' "$yesterdayTimestamp")
 fi
 
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    exit 2
+fi
+
 typeset -a gitCommand=()
 case "$1" in
     [^-]*-command)  gitCommand+=("$1"); shift
