git-alias: Adapt to new location of gitconfig

diff --git a/git-alias b/git-alias
--- a/git-alias
+++ b/git-alias
@@ -1,4 +1,7 @@
-#!/bin/sh
+#!/bin/bash
+
+readonly scriptDir=$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 2)
+[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 2; }
 
 printUsage()
 {
@@ -33,7 +36,7 @@ sed \
 	    s/[ \t]=[ \t][^;]*[ \t];[ \t]*/\n\t/;
 	    b
 	}' \
-    ~/.gitconfig \
+    "${scriptDir}/gitconfig" \
     | sed -e '/^\t/!s/[^=]*/[01m&[0m/' -e '/^\t/s/^\t//' | less --RAW-CONTROL-CHARS
 else
 sed -n \
@@ -55,6 +58,6 @@ sed -n \
 		p
 	    }
 	}' \
-    ~/.gitconfig \
+    "${scriptDir}/gitconfig" \
     | less --RAW-CONTROL-CHARS
 fi
