Minor: ENH: Check for empty GIT-COMMAND

diff --git a/git-pasttimes-command b/git-pasttimes-command
--- a/git-pasttimes-command
+++ b/git-pasttimes-command
@@ -78,6 +78,12 @@ else
     gitColorArg=()
 fi
 set -- "${args[@]}" "$@"
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No GIT-COMMAND passed.'
+    echo >&2
+    printShortUsage "$0" >&2
+    exit 2
+fi
 
 typeset -a dates=("$(date "+%F 03:00" 2>/dev/null || printf yesterday)" '7 days ago' '30 days ago' '365 days ago' '')
 
