git-inside: Add --skip-foreign to suppress "not inside Git wc" error
It may be simplest to just pass a file glob that accidentially picks up files not under Git source control; with the new option, these can be silently ignored.

diff --git a/git-inside b/git-inside
--- a/git-inside
+++ b/git-inside
@@ -10,11 +10,14 @@ copy.)
 			command, it can also be passed as such. Within CMD, you
 			can refer to the corresponding FILE via \$FILE, and to
 			the root directory of the Git working copy as \$ROOT.
+--skip-foreign|-s	Silently skip FILEs that are not inside a Git working
+			copy (instead of printing an error message).
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-c|--command "COMMANDLINE" [-c ...] | SIMPLECOMMAND [...] [--] FILE [-?|-h|--help]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-c|--command "COMMANDLINE" [-c ...] | SIMPLECOMMAND [...] -- FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '-s|--skip-foreign -c|--command "COMMANDLINE" [-c ...] | SIMPLECOMMAND [...] [--] FILE [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '-s|--skip-foreign -c|--command "COMMANDLINE" [-c ...] | SIMPLECOMMAND [...] -- FILE [...] [-?|-h|--help]'
 }
 
+isSkipForeign=
 isNeedEval=
 typeset -a commands=()
 typeset -a files=()
@@ -22,6 +25,7 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--skip-foreign|-s)	shift; isSkipForeign=t;;
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
 	--)		shift; files=("$@"); set --; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
@@ -71,8 +75,11 @@ do
 	# FILE may directly refer to the root of the working copy; try that,
 	# too.
 	if [ ! -d "$FILE" ] || ! cd "$FILE" || ! ROOT=$(git root 2>/dev/null); then
-	    printf >&2 'ERROR: %s is not inside a Git working copy!\n' "$FILE"
-	    status=1; continue
+	    if [ ! "$isSkipForeign" ]; then
+		printf >&2 'ERROR: %s is not inside a Git working copy!\n' "$FILE"
+		status=1
+	    fi
+	    continue
 	fi
     fi
     if [ "$isNeedEval" ]; then
