git-reintegrate: Usability: Minor: Use singluar / plural form for branch(es)

diff --git a/git-reintegrate b/git-reintegrate
--- a/git-reintegrate
+++ b/git-reintegrate
@@ -99,7 +99,8 @@ elif [ ${#checkCommands[@]} -gt 0 ]; then
     eval "${checkCommands[@]}"
 fi || {
     status=$?
-    echo >&2 "Checks failed; branch(es) have been merged, but not ${isPush:+pushed or }deleted yet."
+    branchSubject='branches have'; [ ${#branches[@]} -eq 1 ] && branchSubject='the branch has'
+    echo >&2 "Checks failed; $branchSubject been merged, but not ${isPush:+pushed or }deleted yet."
     echo >&2 'Correct the problem by amending or additional commits, then invoke'
 
     [ "$isCheckFromStdin" ] && printf >&2 'echo CHECK-COMMANDLINES | '
