git-up: FIX: Missing &&

diff --git a/git-up b/git-up
--- a/git-up
+++ b/git-up
@@ -35,7 +35,7 @@ git -c rebase.autoStash=true pull --rebase=preserve "$remote" "$@" || exit $?
 #git pull --rebase=preserve --autostash "$remote" "$@" || exit $?
 
 if [ ! "$path" ]; then
-    [ "$log" ] echo >&2 "Warning: Could not determine updated path, no logging possible."
+    [ "$log" ] && echo >&2 "Warning: Could not determine updated path, no logging possible."
 elif [ "$(git rev-parse "$path" 2>/dev/null)" == "$originalRevision" ]; then
     printf 'No changes in %s.\n' "$path"
 else
