git-localbrdo: Complain about invalid command-line options
Now that COMMANDs are introduced via -c (and there's -- for SIMPLECOMMAND), there's no need to accept anything. This prevents typos like "git-localbrdo --contineu".

diff --git a/git-localbrdo b/git-localbrdo
--- a/git-localbrdo
+++ b/git-localbrdo
@@ -39,6 +39,7 @@ do
 	+([0-9]))	    branchNum=$1; shift;;
 	--command|-c)	    shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
 	--)		    shift; break;;
+	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		    break;;
     esac
 done
