Re-implement git-ll as git-ls --long
To avoid duplicating the (now fixed and extended git-ls) functionality, and to be able to use git ls -l, too.

diff --git a/git-ls b/git-ls
--- a/git-ls
+++ b/git-ls
@@ -1,8 +1,20 @@
 #!/bin/bash
 
+formatPrefix=
+formatSuffix=
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--)		shift; break;;
+	--long|-l)	shift; formatPrefix='%h %<(12,trunc)%aN %ad '; formatSuffix=;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
+
 IFS=$'\n'
 for filespec in $(find "$@" -mindepth 1 -maxdepth 1 -type f -print | sort)
 do
     file=${filespec#./}
-    git log --pretty=format:"${file//%/%%}" --max-count 2 -- "$filespec"
+    git log --pretty=format:"${formatPrefix}${file//%/%%}${formatSuffix}" --max-count 2 -- "$filespec"
 done
