git-ident-update: Robustness: Complain about additional arguments instead of going into endless loop

diff --git a/git-ident-update b/git-ident-update
--- a/git-ident-update
+++ b/git-ident-update
@@ -85,6 +85,8 @@ INSTRUCTIONS
 			    fi
 			    didAction=t
 			    ;;
+	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		    printUsage "$0" >&2; exit 2;;
     esac
 done
 [ "$didAction" ] && exit 0
