git-lghighlight: Add usage help, use pager only when output is to terminal

diff --git a/git-lghighlight b/git-lghighlight
--- a/git-lghighlight
+++ b/git-lghighlight
@@ -1,5 +1,29 @@
 #!/bin/bash
+set -o pipefail
 
-pattern=${1:?}; shift
+printUsage()
+{
+    cat <<HELPTEXT
+git lg, with lines that match passed PATTERN highlighted
+HELPTEXT
+    printf 'Usage: %q %s\n' "$(basename "$1")" 'PATTERN [GIT-LOG-ARGUMENTS ...] [<revision range>] [[--] <path>...] [-?|-h|--help]'
+}
+case "$1" in
+    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+esac
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No PATTERN passed.'
+    echo >&2
+    printUsage "$0" >&2
+    exit 2
+fi
 
-git lg "$@" | sed -e "/${pattern//\//\/}/"'{ s#\[0*m#&[07m#g; s#.*#[07m&[0m# }' | "${PAGER:-less}" --RAW-CONTROL-CHARS
+
+lghighlight()
+{
+    pattern=${1:?}; shift
+    git lg "$@" | sed -e "/${pattern//\//\/}/"'{ s#\[0*m#&[07m#g; s#.*#[07m&[0m# }'
+}
+
+typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=()
+eval 'lghighlight "$@"' "${pager:+|}" '"${pager[@]}"'
