git-existsbr: Robustness: Ensure that exactly one <branch> is passed

diff --git a/git-existsbr b/git-existsbr
--- a/git-existsbr
+++ b/git-existsbr
@@ -1,5 +1,13 @@
 #!/bin/sh
 
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: No <branch> passed.'
+    exit 2
+elif [ $# -gt 1 ]; then
+    echo >&2 'ERROR: Must pass only one <branch>.'
+    exit 2
+fi
+
 # First check whether any valid ref is passed.
 git rev-parse --verify --quiet "$@" >/dev/null || exit 1
 
