git-localbrdo: Change command-line argument handling for COMMAND
The syntax for accepting certain pipe and list operators inline had weaknesses and did not offer a consistent model. Rather, adopt a different model that either handles simple commands, or requires the quoting of an entire command-line, without exceptions.
The storing / recalling of COMMAND needs rework, as it could be either a SIMPLECOMMAND or COMMANDLINE(s). Because the reading of $commandLineStore is easiest to do into a single argument (without word splitting), we need eval() to execute in any case. It's then just a matter of writing $commands in the proper format.

diff --git a/git-localbrdo b/git-localbrdo
--- a/git-localbrdo
+++ b/git-localbrdo
@@ -3,20 +3,26 @@
 shopt -qs extglob
 
 readonly scriptFilespec="${BASH_SOURCE[0]}"
+
 printUsage()
 {
     cat <<HELPTEXT
-Check out all / the last committed N local branches (except for the current branch
-and master) one by one and execute COMMANDLINE on each branch. If no COMMANDLINE
+Check out all / the last committed N local branches (except for the current
+branch and master) one by one and execute COMMAND on each branch. If no COMMAND
 is given, just performs the checkout and returns to the shell; the next
 iteration is then triggered by re-executing with --continue, which can also be
-used to continue with COMMANDLINE execution in case an unclean exit or a
-left-behind dirty working copy made the command to fall out of the iteration.
+used to continue with COMMAND execution in case an unclean exit or a left-behind
+dirty working copy made the command to fall out of the iteration.
+--command|-c CMD	The command line to be executed. When this is a simple
+			command, it can also be passed as such. If omitted, will
+			just return to the shell for each branch.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-y|--yes] [--continue|--abort] [--branches "<branch1> ..."] [N] COMMANDLINE'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-y|--yes] [--continue|--abort] [--branches "<branch1> ..."] [N] [-c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...]]'
 }
 
 typeset -a args=("$@")
+isNeedEval=
+typeset -a commands=()
 isStashed=
 isYes=
 branchNum=9999
@@ -25,40 +31,39 @@ iterationAction=
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)		    shift; printUsage "$0"; exit 0;;
-	--stashed)		    shift; isStashed=t;;
-	--yes|-y)		    shift; isYes=t;;
-	--branches)		    shift; inputBranches=$1; shift;;	# Internal hook to pass in the branches.
-	--continue|--abort)	    iterationAction=${1#--}; shift; break;;
-	+([0-9]))		    branchNum=$1; shift;;
-	*)			    break;;
+	--help|-h|-\?)	    shift; printUsage "$0"; exit 0;;
+	--stashed)	    shift; isStashed=t;;
+	--yes|-y)	    shift; isYes=t;;
+	--branches)	    shift; inputBranches=$1; shift;;	# Internal hook to pass in the branches.
+	--continue|--abort) iterationAction=${1#--}; shift;;
+	+([0-9]))	    branchNum=$1; shift;;
+	--command|-c)	    shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
+	--)		    shift; break;;
+	*)		    break;;
     esac
 done
-[ $# -eq 0 ] && isYes=t	# No need to confirm when no command-line is passed; user can abort via --abort interactively.
 if [ ! "$isStashed" -a ! "$iterationAction" ]; then
     exec git-autostash "$scriptFilespec" --stashed "${args[@]}"
 fi
+if [ $# -ne 0 ]; then
+    if [ "$isNeedEval" ]; then
+	# Combine --command and SIMPLECOMMAND; need to quote SIMPLECOMMAND to
+	# undo the effects of eval.
+	commands+=(${commands:+;} $(printf '%q ' "$@"))
+    else
+	commands=("$@")
+    fi
+fi
+[ ${#commands[@]} -eq 0 ] && isYes=t	# No need to confirm when no command-line is passed; user can abort via --abort interactively.
 
 gitDir=$(git rev-parse --git-dir 2>/dev/null) || exit $?
 origBranchStore="${gitDir}/localbrOrig"
 branchStore="${gitDir}/localbr" || exit $?
 commandLineStore="${gitDir}/localbrCommandLine"
 
-commandLineEscape()
-{
-    eval "typeset -a result=(\"\${${1:?}[@]}\")"
-    typeset escapeChars="\\${IFS-$' \t\n'}"
-    typeset escapeCharIdx
-    for ((escapeCharIdx = 0; escapeCharIdx < ${#escapeChars}; escapeCharIdx++))
-    do
-	result=("${result[@]//"${escapeChars:$escapeCharIdx:1}"/\\"${escapeChars:$escapeCharIdx:1}"}")
-    done
-    eval "${1}Escaped=(\"\${result[@]}\")"
-}
-if [ $# -gt 0 ]; then
-    typeset -a commandLine=("$@")
-    commandLineEscape commandLine
-    printf '%s ' "${commandLineEscaped[@]}" > "$commandLineStore" || exit $?
+if [ ${#commands[@]} -gt 0 ]; then
+    storeQuoting=%q; [ "$isNeedEval" ] && storeQuoting=%s   # Already quoted for eval, but a SIMPLECOMMAND needs quoting because after recalling it from $commandLineStore, it's in one single argument and needs eval() to execute.
+    printf "$storeQuoting " "${commands[@]}" > "$commandLineStore" || exit $?
 fi
 
 getNextBranch()
@@ -82,7 +87,7 @@ interrupt()
 {
     local status=${1:?}
     printf >&2 'Note: Interrupting iteration because the command failed (with exit status %d). Please check and then continue with --continue.\n' "$status"
-    echo >&2 'You can suppress checking of exit status by appending "\|\| :" to the COMMANDLINE.'
+    echo >&2 'You can suppress checking of exit status by appending "|| :" to the COMMANDLINE.'
     exit $status
 }
 
@@ -102,10 +107,13 @@ case "$iterationAction" in
     continue)
 	dirtyCheck
 
-	if [ $# -eq 0 -a -e "$commandLineStore" ]; then
+	if [ ${#commands[@]} -eq 0 -a -e "$commandLineStore" ]; then
 	    # Recall command-line from original / previous call, unless it is
 	    # overridden by updated arguments provided to this invocation.
-	    commandLineEscaped=$(<"$commandLineStore")
+	    commands=$(<"$commandLineStore")
+	    # The command-line is read as one (escaped) argument, and therefore
+	    # needs eval to execute.
+	    isNeedEval=t
 	fi
 	;;
     '')
@@ -126,7 +134,7 @@ ${localBranches[*]}"
 
 	printf '%s\n' "${localBranches[*]}" > "$branchStore" || exit $?
 	git-orig-ref > "$origBranchStore"
-	if [ $# -eq 0 -a -e "$commandLineStore" ]; then
+	if [ ${#commands[@]} -eq 0 -a -e "$commandLineStore" ]; then
 	    rm -- "$commandLineStore" || exit $?
 	fi
 	;;
@@ -147,10 +155,15 @@ do
 
     git checkout --quiet "${branch}" || exit $?	# Suppress Git's checkout information with --quiet. We're probably not interested in stuff like "Your branch is up-to-date with ...", and we emulate the switch message itself:
     printf "\\nSwitched to branch '%s'\\n" "$branch"
-    if [ ${#commandLineEscaped[@]} -eq 0 ]; then
+    if [ ${#commands[@]} -eq 0 ]; then
 	exit 0
     else
-	if (eval "${commandLineEscaped[@]}"); then
+	if (
+	    if [ "$isNeedEval" ]; then
+		eval "${commands[@]}"
+	    else
+		"${commands[@]}"
+	    fi); then
 	    dirtyCheck
 	else
 	    interrupt "$?"
