git-localbr: Cosmetics: Align indent

diff --git a/git-localbr b/git-localbr
--- a/git-localbr
+++ b/git-localbr
@@ -26,14 +26,14 @@ isIncludeBase=
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--help|-h|-\?)	    shift; printUsage "$0"; exit 0;;
 	--include-current)  shift; isIncludeCurrent=t;;
 	--include-master)   shift; isIncludeMaster=t;;
 	--include-base)	    shift; isIncludeBase=t;;
 	--include-all)	    shift; isIncludeCurrent=t; isIncludeMaster=t; isIncludeBase=t;;
-	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)		break;;
+	--)		    shift; break;;
+	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		    break;;
     esac
 done
 
