git-reintegrate: Robustness: Ensure that all passed branch(es) are valid

diff --git a/git-reintegrate b/git-reintegrate
--- a/git-reintegrate
+++ b/git-reintegrate
@@ -80,6 +80,13 @@ if [ ${#branches[@]} -eq 0 ]; then
     echo >&2 'Need (at least one) <branch> to merge!'
     exit 2
 fi
+for branch in "${branches[@]}"
+do
+    if ! git-existsbr "$branch"; then
+	printf >&2 'ERROR: Not a valid branch: %s\n' "$branch"
+	exit 1
+    fi
+done
 
 branchesPlural=es
 branchesSubject=them
