git-wrapper: Also handle hub aliases (if hub is installed) and use for delegation instead of hub || git
When custom git-* / hub-* commands are passed to e.g. git-wcdo, the alias needs to be resolved there as well. Make git-wrapper also handle hub aliases (if hub is installed); keep the dedicated hub-wrapper for pure hub wrapping. (As hub falls back to Git built-in commands, hub-wrapper therefore handles hub-aliases, and built-in hub and git commands, but not git-aliases.)

diff --git a/git-wrapper b/git-wrapper
--- a/git-wrapper
+++ b/git-wrapper
@@ -1,4 +1,21 @@
 #!/bin/bash
+
+if type -t hub >/dev/null; then
+    hubAlias="hub-$1"
+    if type -t "$hubAlias" >/dev/null; then
+	shift
+
+	# XXX: Git puts itself in front of the PATH; need precedence for our
+	# scripts, though. Solve this by putting our dirspec in front again. Take
+	# that, Git!
+	readonly scriptDir=$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)
+	[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }
+	PATH="${scriptDir}:$PATH"
+
+	eval exec $hubAlias '"$@"'
+    fi
+fi
+
 gitAlias="git-$1"
 if type -t "$gitAlias" >/dev/null; then
     shift
