git-existsremote: ENH: Check for existence of any configured remote if no arguments are passed
And do proper error handling if more than one argument is passed.

diff --git a/git-existsremote b/git-existsremote
--- a/git-existsremote
+++ b/git-existsremote
@@ -1,3 +1,7 @@
-#!/bin/sh
+#!/bin/bash
 
-git config "remote.${1:?}.url" >/dev/null
+case $# in
+    0)	[ -n "$(git remote show 2>/dev/null)" ];;
+    1)	git config "remote.${1:?}.url" >/dev/null;;
+    *)	echo >&2 "ERROR: Pass one <remote> or nothing to check whether any remote is defined."; exit 2;;
+esac
