Refactoring: Reuse git-existsbr instead of git show-ref
Shorter and shows the intention better.

diff --git a/git-inout b/git-inout
--- a/git-inout
+++ b/git-inout
@@ -2,8 +2,8 @@
 
 ensureValidRef()
 {
-    if ! git show-ref "$1" > /dev/null; then
-	echo >&2 "bad ref: $1"
+    if ! git-existsbr "$1"; then
+	printf >&2 'ERROR: Branch %s does not exist!\n' "$1"
 	exit 1
     fi
 }
