Documentation: Split usage into long (for --help) and short (for command-line argument parsing errors) variants for commands with many arguments and long help texts
Getting a wall of text in case of a wrong invocation isn't nice, so just show the error and usage, and leave the full documentation for -h|--help.

diff --git a/git-inside b/git-inside
--- a/git-inside
+++ b/git-inside
@@ -1,25 +1,44 @@
 #!/bin/bash
 
+printShortUsage()
+{
+    # Note: short followed by long option; if the user knows the short one, she can
+    # skim the long one.
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-s|--skip-foreign|--foreign-command "COMMANDLINE"] -c|--command "COMMANDLINE" [-c ...] | SIMPLECOMMAND [...] -- FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-s|--skip-foreign|--foreign-command "COMMANDLINE"] -c|--command "COMMANDLINE" [-c ...] | SIMPLECOMMAND [...] [--] FILE [-?|-h|--help]'
+}
 printUsage()
 {
-    cat <<HELPTEXT
+    # This is the short help when launched with no or incorrect arguments.
+    # It is printed to stderr to avoid accidental processing.
+    printShortUsage "$1" >&2
+    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+}
+printLongUsage()
+{
+    # This is the long "man page" when launched with the help argument.
+    # It is printed to stdout to allow paging with 'more'.
+    cat <<HELPDESCRIPTION
 Execute "git SIMPLECOMMAND" and/or COMMANDLINE (which probably contains Git
 command(s)) inside the working copy that FILE resides in. (Most Git commands
 only work from within the working copy.)
---command|-c CMD	The command line to be executed. When this is a simple
-			command, it can also be passed as such. Within CMD, you
-			can refer to the corresponding FILE via \$FILE, and to
-			the root directory of the Git working copy as \$ROOT
-			(both with absolute paths, also in SIMPLECOMMAND when
-			it's a separate argument).
---skip-foreign|-s	Silently skip FILEs that are not inside a Git working
-			copy (instead of printing an error message).
---foreign-command CMD	Execute CMD in (accessible) directories that are not
-			inside a Git working copy (e.g. to initialize a Git
-			repo).
+HELPDESCRIPTION
+    echo
+    printShortUsage "$1"
+    cat <<HELPTEXT
+    --command|-c CMD	    The command line to be executed. When this is a
+			    simple command, it can also be passed as such.
+			    Within CMD, you can refer to the corresponding FILE
+			    via \$FILE, and to the root directory of the Git
+			    working copy as \$ROOT (both with absolute paths,
+			    also in SIMPLECOMMAND when it's a separate
+			    argument).
+    --skip-foreign|-s	    Silently skip FILEs that are not inside a Git
+			    working copy (instead of printing an error message).
+    --foreign-command CMD   Execute CMD in (accessible) directories that are not
+			    inside a Git working copy (e.g. to initialize a Git
+			    repo).
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-s|--skip-foreign|--foreign-command "COMMANDLINE"] -c|--command "COMMANDLINE" [-c ...] | SIMPLECOMMAND [...] [--] FILE [-?|-h|--help]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-s|--skip-foreign|--foreign-command "COMMANDLINE"] -c|--command "COMMANDLINE" [-c ...] | SIMPLECOMMAND [...] -- FILE [...] [-?|-h|--help]'
 }
 
 isSkipForeign=
@@ -30,13 +49,13 @@ typeset -a fileArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-	--skip-foreign|-s)	shift; isSkipForeign=t;;
-	--foreign-command)	shift; foreignCommands+=(${foreignCommands:+;} "$1"); shift;;
-	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
-	--)		shift; fileArgs=("$@"); set --; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)  break;;
+	--help|-h|-\?)	    shift; printLongUsage "$0"; exit 0;;
+	--skip-foreign|-s)  shift; isSkipForeign=t;;
+	--foreign-command)  shift; foreignCommands+=(${foreignCommands:+;} "$1"); shift;;
+	--command|-c)	    shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
+	--)		    shift; fileArgs=("$@"); set --; break;;
+	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		    break;;
     esac
 done
 readonly gitCommand="$(which hub || which git)"
@@ -61,9 +80,11 @@ fileArgs+=("$@")
 
 if [ ${#commands[@]} -eq 0 ]; then
     echo >&2 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    printUsage "$0" >&2
     exit 2
 elif [ ${#fileArgs[@]} -eq 0 ] || [ $# -eq 1 -a "$1" = '--' ]; then
     echo >&2 'ERROR: No FILE(s) specified; need a file for the working copy location.'
+    printUsage "$0" >&2
     exit 2
 fi
 
diff --git a/git-wcdo b/git-wcdo
--- a/git-wcdo
+++ b/git-wcdo
@@ -1,30 +1,52 @@
 #!/bin/bash
 
+printShortUsage()
+{
+    # Note: short followed by long option; if the user knows the short one, she can
+    # skim the long one.
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--no-pager] [--no-header|--branch-name] [--no-git-color] [--single-success] [--skip-files] [-s|--skip-foreign|--foreign-command "COMMANDLINE" [...]] [--predicate-command "COMMANDLINE" [...]] [-c|--command "COMMANDLINE" [-c ...]] WORKING-COPY [...] [-- SIMPLECOMMAND ...] [-?|-h|--help]'
+}
 printUsage()
 {
-    cat <<HELPTEXT
+    # This is the short help when launched with no or incorrect arguments.
+    # It is printed to stderr to avoid accidental processing.
+    printShortUsage "$1" >&2
+    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+}
+printLongUsage()
+{
+    # This is the long "man page" when launched with the help argument.
+    # It is printed to stdout to allow paging with 'more'.
+    cat <<HELPDESCRIPTION
 Execute "git SIMPLECOMMAND" and/or COMMANDLINE on each passed WORKING-COPY.
+HELPDESCRIPTION
+    echo
+    printShortUsage "$1"
+    cat <<HELPTEXT
+
 Puts a header line (unless --no-header) that contains the WORKING-COPY name
 (with --branch-name: also the current Git branch) before the command output.
---skip-files		Silently skip files that are passed as WORKING-COPY
-			(e.g. resulting from a file glob).
---skip-foreign|-s	Silently skip directories that are not a Git working
-			copy (instead of printing an error message).
---foreign-command CMD	Execute CMD in (accessible) directories that are not
-			a Git working copy (e.g. to initialize a Git repo).
---predicate-command CMD	Skip working copies where CMD fails. This is an
-			alternative to --command "if CMD; then COMMANDLINE; fi"
-			that lets you still use SIMPLECOMMAND.
+    --skip-files	    Silently skip files that are passed as WORKING-COPY
+			    (e.g. resulting from a file glob).
+    --skip-foreign|-s	    Silently skip directories that are not a Git working
+			    copy (instead of printing an error message).
+    --foreign-command CMD   Execute CMD in (accessible) directories that are not
+			    a Git working copy (e.g. to initialize a Git repo).
+    --predicate-command CMD Skip working copies where CMD fails. This is an
+			    alternative to
+				--command "if CMD; then COMMANDLINE; fi"
+			    that lets you still use SIMPLECOMMAND.
 Note: For paging and headers, this command has to control Git's color output.
 Pass --no-git-color if "git SIMPLECOMMAND" does not support the --color=...
 arguments. (For COMMANDLINE you have to insert "\${gitColorArg[@]}" yourself.)
 You can still pass --color=always if you pipe this command's output yet still
 want coloring of headers.
+
+EXIT STATUS
 Returns the last non-successful exit status. With --single-success,
 non-successful executions are ignored unless all of them fail. In other words,
 exit status is 0 if at least command in one WORKING-COPY succeeded.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--no-pager] [--no-header|--branch-name] [--no-git-color] [--single-success] [--skip-files] [-s|--skip-foreign|--foreign-command "COMMANDLINE" [...]] [--predicate-command "COMMANDLINE" [...]] [-c|--command "COMMANDLINE" [-c ...]] WORKING-COPY [...] [-- SIMPLECOMMAND ...] [-?|-h|--help]'
 }
 
 typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=()
@@ -44,22 +66,22 @@ typeset -a args=()
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--help|-h|-\?)		shift; printLongUsage "$0"; exit 0;;
 	--single-success)	shift; isSingleSuccess=t;;
 	--skip-files)		shift; isSkipFiles=t;;
 	--skip-foreign|-s)	shift; isSkipForeign=t;;
 	--foreign-command)	shift; foreignCommands+=(${foreignCommands:+;} "$1"); shift;;
 	--predicate-command)	shift; predicateCommands+=(${predicateCommands:+&&} "$1"); shift;;
-	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
-	--no-pager)	shift; pager=();;
-	--no-header)	shift; isHeader=; emptyHeaderFilterCommand=;;
-	--branch-name)	shift; isBranchName=t;;
-	--no-git-color)	shift; isGitColor=;;
+	--command|-c)		shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
+	--no-pager)		shift; pager=();;
+	--no-header)		shift; isHeader=; emptyHeaderFilterCommand=;;
+	--branch-name)		shift; isBranchName=t;;
+	--no-git-color)		shift; isGitColor=;;
 	--no-color|--color=*)	colorArg=("$1"); shift;;
 	--color)		colorArg=("$1" "$2"); shift; shift;;
-	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)		args+=("$1"); shift;;
+	--)			shift; break;;
+	-*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)			args+=("$1"); shift;;
     esac
 done
 if [ ${#args[@]} -eq 0 ]; then
