git-autostash: Complain when no COMMANDs are given

diff --git a/git-autostash b/git-autostash
--- a/git-autostash
+++ b/git-autostash
@@ -27,7 +27,10 @@ do
 	*)  break;;
     esac
 done
-if [ $# -ne 0 ]; then
+if [ $# -eq 0 ]; then
+    echo >&2 'ERROR: Need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    exit 2
+else
     if [ "$isNeedEval" ]; then
 	# Combine --command and SIMPLECOMMAND; need to quote SIMPLECOMMAND to
 	# undo the effects of eval.
