check-switch-completeness: Tests: FIX: Minor: Wrong variable (after d60f2623)
That was GitHub Copilot's suggestion, I swear!

(This corrects commit d60f262317c66fde182d13bb0a8aafd49385d98a)

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.96.0 (2026-07-02), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)

diff --git a/tests/check-switch-completeness b/tests/check-switch-completeness
--- a/tests/check-switch-completeness
+++ b/tests/check-switch-completeness
@@ -45,7 +45,7 @@ readarray -t gitSupportedCommands < "${etcDir}/$COMMANDS_SUPPORTED_FILENAME"
 do
     duplicateCheck "$COMMANDS_SUPPORTED_FILENAME"
     if ! git-aliases --quiet "${gitCommand}\$"; then
-	printf >&2 'ERROR: Supported Git command "%s" is not defined as an alias. Add it to gitconfig, or move to %s\n' "$gitCommand" "$GIT_NEW_COMMANDS_FILENAME"
+	printf >&2 'ERROR: Supported Git command "%s" is not defined as an alias. Add it to gitconfig, or move to %s\n' "$gitCommand" "$COMMANDS_NEW_FILENAME"
 	exit 1
     fi
 done
